### ISSUE TITLE
Hardware Acceleration is not enabled on AMD system.

### ISSUE THREAD

**Issue by pilcherd** [dotnet/docs-maui#1000]
This page indicates that "After Hyper-V is enabled, you'll be able to run your accelerated Android emulator."

This is when using "Microsoft's Hyper-V and the Windows Hypervisor Platform (WHPX)."

The top table shows AMD processors X.

It even says "For the best experience on Windows, it's recommended you use WHPX to accelerate the Android emulator."  I.e. it's better than HAXM... and the WHPX shows it supports AMD processors.

And yet when I have this setup, the emulator is not accelerated.  Using [troubleshooting](https://learn.microsoft.com/en-us/dotnet/maui/android/emulator/troubleshooting#hardware-acceleration-issues), indicates:

"C:\Users\DavidP>"C:\Program Files (x86)\Android\android-sdk\emulator\emulator-check.exe" accel
accel:
3
Android Emulator requires an Intel processor with VT-x and NX support.  Your CPU: 'AuthenticAMD'
accel"

So, the current emulator appears to require an Intel processor, but this document indicates it doesn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9627ff9-5d98-7114-f57c-2ef9feba2f51
* Version Independent ID: d9627ff9-5d98-7114-f57c-2ef9feba2f51
* Content: [Enable hardware acceleration for the Android emulator (Hyper-V & HAXM) - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/emulator/hardware-acceleration)
* Content Source: [docs/android/emulator/hardware-acceleration.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/emulator/hardware-acceleration.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Reading through the article and also looking at [Androids emulation setup articles](https://developer.android.com/studio/run/emulator-acceleration#vm-windows-whpx) it seems that those tools check for HAXM or for Android's AMD hypervisor, but not for Window's hypervisor. If you follow the instructions for enabling hyper-v and enabling the virtualization modes in the BIOS, your emulator should be accelerated.

The fact that you got that error message (saying you're using an AMD machine) would indicate you don't have hyper-v installed. When I run it (I'm using AMD) I get this, meaning, hyper-v is blocking android's check tool:

```
C:\Windows\system32>"C:\Program Files (x86)\Android\android-sdk\emulator\emulator-check.exe" accel
accel:
0
Please disable Hyper-V before using the Android Emulator.  Start a command prompt as Administrator, run 'bcdedit /set hypervisorlaunchtype off', reboot.WHPX (10.0.22000) is installed and usable.
accel
```

> **EDIT**
> I just noticed at the end of that message I do see `WHPX (10.0.22000) is installed and usable.` but it seems to be missing a new line so it looks like it's part of the message indicating you MUST disable Hyper-V. Yes you must disable Hyper-V if you want to use HAXM/Android AMD... but if WHPX is installed and usable then it should be fine, you don't need to go the HAXM/Android AMD route...
>
> It also looks like you can use `emulator-check.exe hyper-v` to detect if hyper-v is working with the emulator.

I do think that troubleshooting article needs an update though, showing the output you should expect.

**Comment by pilcherd** [comment]
> Reading through the article and also looking at [Androids emulation setup articles](https://developer.android.com/studio/run/emulator-acceleration#vm-windows-whpx) it seems that those tools check for HAXM or for Android's AMD hypervisor, but not for Window's hypervisor. If you follow the instructions for enabling hyper-v and enabling the virtualization modes in the BIOS, your emulator should be accelerated.
> 
> The fact that you got that error message (saying you're using an AMD machine) would indicate you don't have hyper-v installed. When I run it (I'm using AMD) I get this, meaning, hyper-v is blocking android's check tool:
> 
> ```
> C:\Windows\system32>"C:\Program Files (x86)\Android\android-sdk\emulator\emulator-check.exe" accel
> accel:
> 0
> Please disable Hyper-V before using the Android Emulator.  Start a command prompt as Administrator, run 'bcdedit /set hypervisorlaunchtype off', reboot.WHPX (10.0.22000) is installed and usable.
> accel
> ```
> 
> > **EDIT**
> > I just noticed at the end of that message I do see `WHPX (10.0.22000) is installed and usable.` but it seems to be missing a new line so it looks like it's part of the message indicating you MUST disable Hyper-V. Yes you must disable Hyper-V if you want to use HAXM/Android AMD... but if WHPX is installed and usable then it should be fine, you don't need to go the HAXM/Android AMD route...
> > It also looks like you can use `emulator-check.exe hyper-v` to detect if hyper-v is working with the emulator.
> 
> I do think that troubleshooting article needs an update though, showing the output you should expect.

Hyper-V is very alive and in use on this development PC:

![image](https://user-images.githubusercontent.com/25464172/195919283-d19d5eab-270c-48c4-b0d1-86602e09a085.png)

That command returns:

C:\Users\DavidP>"C:\Program Files (x86)\Android\android-sdk\emulator\emulator-check.exe" hyper-v
hyper-v:
2
Hyper-V is enabled
hyper-v

**Comment by pilcherd** [comment]
Deployment shows this:

![image](https://user-images.githubusercontent.com/25464172/195919892-4ec00c96-844c-4972-9689-b257c6b2764f.png)

But when I run, I see this warning and the output showing not accelerated:

![image](https://user-images.githubusercontent.com/25464172/195920161-1fac09ca-980d-4544-a6ca-ab20d40a39db.png)

See running non-accelerated:

![image](https://user-images.githubusercontent.com/25464172/195920273-ef99a5c2-57db-427a-99d4-fd269cac0ae9.png)

**Comment by Thraka** [comment]
Hrmmm.. Do you have the Windows Hypervisor Platform enabled too? I don't see that in your screenshot.

**Comment by adegeo** [comment]
Hrmmm.. Do you have the Windows Hypervisor Platform enabled too? I don't see that in your screenshot.

**Comment by adegeo** [comment]
Also, what's the exact CPU model are you using?

**Comment by pilcherd** [comment]
> Also, what's the exact CPU model are you using?

5950x

**Comment by pilcherd** [comment]
> Hrmmm.. Do you have the Windows Hypervisor Platform enabled too? I don't see that in your screenshot.

I have tried it with and without that. It made no difference.

**Comment by adegeo** [comment]
You must have Windows Hypervisor Platform enabled, that is what WHPX stands for 😁 The fact that Android tries to run HAXM makes me think something is wrong with WHPX. I'm assuming you've also enabled the BIOS settings too for virtualization.

Can you try running the emulator command directly with acceleration on to see if it works? Maybe it will give you some different output:

```
C:\Program Files (x86)\Android\android-sdk\emulator\emulator.EXE -netfast -accel on -avd Android_accelerated_x86_Oreo -prop monodroid.avdname=Android_accelerated_x86_Oreo
```

What edition of Windows 11 are you using?

**Comment by pilcherd** [comment]
> 



> You must have Windows Hypervisor Platform enabled, that is what WHPX stands for 😁 The fact that Android tries to run HAXM makes me think something is wrong with WHPX. I'm assuming you've also enabled the BIOS settings too for virtualization.
> 
> Can you try running the emulator command directly with acceleration on to see if it works? Maybe it will give you some different output:
> 
> ```
> C:\Program Files (x86)\Android\android-sdk\emulator\emulator.EXE -netfast -accel on -avd Android_accelerated_x86_Oreo -prop monodroid.avdname=Android_accelerated_x86_Oreo
> ```
> 
> What edition of Windows 11 are you using?

Windows 11 Enterprise 22H2 (22621.675)

I have re-enabled Windows Hypervisor Platform again and rebooted.  

![image](https://user-images.githubusercontent.com/25464172/195950354-857c416a-fc0d-4b44-93b8-3fe832c08926.png)


I then ran the command you requested:

C:\Users\DavidP>"C:\Program Files (x86)\Android\android-sdk\emulator\emulator.EXE" -netfast -accel on -avd Android_accelerated_x86_Oreo -prop monodroid.avdname=Android_accelerated_x86_Oreo
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure Windows Hypervisor Platform (WHPX) is properly installed and usable.
CPU acceleration status: Android Emulator requires an Intel processor with VT-x and NX support.  Your CPU: 'AuthenticAMD'

**Comment by pilcherd** [comment]
From within Visual Studio in the Tools/Android SDK Manager, is an updater.

The Emulator had an upgrade available:

![image](https://user-images.githubusercontent.com/25464172/195952069-b455e8b8-0c34-4a09-80a3-5e9a0cb4f2c1.png)


After upgrading it, it now appear to run instantly without error, so I guess a version newer than 27 is required.

Note that my Visual Studio is 2022 Enterprise, version 17.3.6 - the latest.  These tools were only added yesterday so will be the latest Android components installed by Visual Studio.

It appears the documentation needs to say check for updates as part of troubleshooting.

Also the VS2022 installer should really install newer components.

@adegeo , Thank you for your suggestions.

**Comment by adegeo** [comment]
Glad this is working! Honestly, you should just use the preview releases of Visual Studio 2022, all the latest MAUI code gets shipped in there, For .NET MAUI I don't use the non-preview releases anymore unless I have a specific reason to do so.

Anyway. Question on your situation. Did you happen to have the Android Emulator stuff already installed before? I bet VS installs the latest but perhaps you already had it installed from previous work and so it decided not to update?

**Comment by pilcherd** [comment]
No android tooling was installed before yesterday. It was installed from the latest release Visual Studio installer.
