### ISSUE TITLE
Scaling on Mac Catalyst

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1001]
MAUI uses the iPad idiom in Xcode which causes an app on Mac Catalyst to display at 77% size so that designs made for iPad display more like Mac apps. This results in scaling problems in that what's sized correctly on Windows looks small on Mac.

You can set the scaling yourself by updating your info.plist and setting the UIDeviceFamily to 6, which sets Mac Catalyst to use the Desktop controls.

This needs doc'ing.

https://github.com/dotnet/maui/issues/10622

**Comment by pvoelker** [comment]
I'm very new to Macs.  Not to be dense, but is this what needs to be done?

```
	<key>UIDeviceFamily</key>
	<array>
		<integer>6</integer>
	</array>
```

**Comment by davidbritch** [comment]
Fixed by https://github.com/dotnet/docs-maui/pull/1368
