### ISSUE TITLE
Terrible page

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#1002]
So I get a search result sending me here because I'm looking for Expander.  There is mention of it in this page but no where to say where it comes from.  So basically the page is useless.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 830ef2e9-c1f3-e231-21b3-2534cea6e2b0
* Version Independent ID: 830ef2e9-c1f3-e231-21b3-2534cea6e2b0
* Content: [Multi-bindings - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/multibinding)
* Content Source: [docs/fundamentals/data-binding/multibinding.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/multibinding.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
The point of the article isn't to explain expander, but multi-binding.

At the top of the article there is a BROWSE SAMPLE link which will bring you to the code used in the article. In there, the Expander control source code says that it doesn't really exist until the .NET MAUI Community Toolkit adds it. So for now, it's just a hack of a grid control supporting the property required for bindings. You'll need to ask there in the community toolkit repo. I did a quick search and found this issue tracking it: https://github.com/CommunityToolkit/Maui/issues/109
