### ISSUE TITLE
Migrating a Xamarin.Forms app: the compatibility layer

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1015]
There are two pathways users can take for compatibility with Xamarin.Forms:

1. Compatibility handlers - base classes that are API equivalent to renderers but they work via `IViewHandler`.
2. Compatibility renderers - use the legacy renderer structure, so have to be registered through the shim system.

`Microsoft.Maui.Controls.Compatibility.Platform.Android.FastRenderers.VisualElementRenderer` is a compatibility renderer
whereas `Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer` is a compatibility handler.

The theory behind the compatibility handlers is a way to completely remove the shim layer and provide a set of handlers that are API equivalent to Xamarin.Forms renderers but are able to work with the handlers. This makes it a lot easier to make things work with MAUI while providing an easier migration path. Currently, MAUI's using the compatibility handlers successfully to bring over ListView, TableView, Frame, and Shell (ios/android). They should also provide an easy way for anyone to migrate a renderer based on `VisualElementRenderer`.

https://github.com/dotnet/maui/pull/10567

---
[Associated WorkItem - 61813](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61813)

**Comment by BillWagner** [comment]
Adding to December sprint, while @davidbritch is out this week.
