### ISSUE TITLE
[Maui][Android] Keyboard Entry.ImeOption

### ISSUE THREAD

**Issue by CorentinSwiss4** [dotnet/docs-maui#1030]
Hello i have an issue with the android entry ImeOption when i want to set to "search" keyboard icon doesn't change.

Do you reproduce this issue ?

**Comment by davidbritch** [comment]
Hi @CorentinSwiss4 

If you think the control isn't working correctly you should log an issue in the [engineering repo](https://github.com/dotnet/maui). Thanks!
