### ISSUE TITLE
The sample code for creating a pan container is wrong

### ISSUE THREAD

**Issue by ClaudioFriederich** [dotnet/docs-maui#1036]
The sample code for creating a pan container is confusing because it is mathematically not correct and will not have the intended results.

Content.TranslationX = Math.Max(Math.Min(0, x + e.TotalX), -Math.Abs(Content.Width - DeviceDisplay.MainDisplayInfo.Width));
Content.TranslationY = Math.Max(Math.Min(0, y + e.TotalY), -Math.Abs(Content.Height - DeviceDisplay.MainDisplayInfo.Height));

will not work if the content is not larger than the pan container (and doesn't need panning).  When that is the case, the sample code as written will allow panning the content off of the pan container in one direction.  For example, if the pan container is twice as large as the content, the content could be panned all the way off the left or top of the container.  The correct formulae are:

Content.TranslationX = Math.Min(0, Math.Max(x + e.TotalX, DeviceDisplay.MainDisplayInfo.Width - Content.Width));
Content.TranslationY = Math.Min(0, Math.Max(y + e.TotalY, DeviceDisplay.MainDisplayInfo.Height - Content.Height));

which are both simpler and will give the same result as the sample code when the content is larger than the pan container, but will constrain the translation to 0 if the content fits.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6790172b-c85e-0b9a-575f-c8c40fc284c8
* Version Independent ID: 6790172b-c85e-0b9a-575f-c8c40fc284c8
* Content: [Recognize a pan gesture - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/pan)
* Content Source: [docs/fundamentals/gestures/pan.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/gestures/pan.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 57844](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57844)

**Comment by davidbritch** [comment]
Fixed by #1545
