### ISSUE TITLE
XCode path

### ISSUE THREAD

**Issue by dbullen-uk** [dotnet/docs-maui#1037]
Is there a way to set the XCode path if it's not in the Applications folder? 
The error message tells me how to set it in Visual Studio but I don't have VS installed and don't have enough space for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da0a1dce-0ab0-7d18-8dc9-e37854995ace
* Version Independent ID: da0a1dce-0ab0-7d18-8dc9-e37854995ace
* Content: [Build an iOS app on macOS with .NET CLI - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/ios/cli)
* Content Source: [docs/ios/cli.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/cli.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dbullen-uk 

It might be that the drop-down at Xcode > Preferences > Locations > Command Line Tools is blank. If so, select the drop-down and then the command line tools that are installed.

If that doesn't help, afraid you'll have to install Visual Studio.
