### ISSUE TITLE
Migrating a Xamarin Forms app:   HybridWebView

### ISSUE THREAD

**Issue by mtanml** [dotnet/docs-maui#1041]
Is anyone able to translate this Xamarin Forms document to MAUI for the creation of a HybridWebView?

https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview

Thank you!

**Comment by davidbritch** [comment]
Hi @mtanml 

@eilon has produced a `HybridWebView`. Check it out at https://github.com/Eilon/MauiCSharpInteropWebView

**Comment by mtanml** [comment]
@davidbritch @Eilon nice, thank you!
