### ISSUE TITLE
Note to 'Position and size child views' in VerticalStackLayout/HorizontalStackLayout

### ISSUE THREAD

**Issue by anonisnap** [dotnet/docs-maui#1043]
_This is a request that would be added to both the [VerticalStackLayout](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/verticalstacklayout) page and [HorizontalStackLayout](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/horizontalstacklayout) page. Difference being `VerticalStackLayout` should refer to `VerticalOptions` instead_

### Issue

One difference I've found after trial-and-error with the new `HorizontalStackLayout` is how it behaves when using `HorizontalOptions`

When using a `HorizontalStackLayout` it would not be uncommon to assume, that the behaviour would be similar to a [StackLayout](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/stacklayout) with the `Orientation` set to `Horizontal`

With a `StackLayout` we find that `HorizontalOptions` affect the child views, allowing for 2 `Label` views to be in either end with a large gap in the middle. However, when using the `HorizontalStackLayout` the child views are unaffected by `HorizontalOptions`

### Example

I've made an Example Application, _[GitHub Repository here](https://github.com/anonisnap/MAUI-StackLayout-Behaviour-Differences)_, to test the `HorizontalOptions` behaviour

![StackLayoutExample](https://user-images.githubusercontent.com/42655737/198266828-998a42cf-fd02-40d8-8a3e-d960b2a0603f.png)

![HorizontalStackLayoutExample](https://user-images.githubusercontent.com/42655737/198266889-c4cab52b-cdd5-4052-928f-4fe04624e49e.png)

### Suggestion

What I would like to request is a Note in the documentation, informing people of this difference in behaviour, something along the lines of; "`HorizontalOptions` will not affect the layout of child views"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 406ac2c1-07ed-ba39-a2ea-1a1077cc6c04
* Version Independent ID: 406ac2c1-07ed-ba39-a2ea-1a1077cc6c04
* Content: [.NET MAUI HorizontalStackLayout - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/horizontalstacklayout)
* Content Source: [docs/user-interface/layouts/horizontalstacklayout.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/layouts/horizontalstacklayout.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @anonisnap 

Looking at your repo the issue is that you are using the *AndExpand layout options. Those are supported in `StackLayout` but not in `HorizontalStackLayout` or `VerticalStackLayout`. The doc specifically calls out that you can only use `Start`, `Center`, `End`, and `Fill` in VSL/HSL.
