### ISSUE TITLE
TapGestureRecognizer no longer working after a Translate animation

### ISSUE THREAD

**Issue by eli191** [dotnet/docs-maui#1044]
Hi,

The tap event of the TapGestureRecognizer is no longer fired after the view element has been translated somewhere else (still on the screen).

I rescale and move a view on the screen, but then the tap no longer works.
If I rescale only, the tap still works.

Thanks.

```
private void OnImageTapped(object sender, EventArgs e)
{
        image.ScaleXTo(60 / image.Width, 500);
        image.ScaleYTo(80 / image.Height, 500);
        image.TranslateTo(-image.X, -image.Y - mainGrid.Y, 500); 
}
```

If I comment the `TranslateTo` line, then tap still works, but with the translation of the view, tap no longer works.

I tried to reattach the tap gesture programmatically but with no success.

**Comment by davidbritch** [comment]
Hi @eli191 

This sounds like a product bug - I'd guess that the `TapGestureRecognizer` is still expecting the view to be in its original location on screen. I'd recommend logging a bug in the [engineering repo](https://github.com/dotnet/maui). Thanks!

**Comment by AntoninLolivier** [comment]
Hi,
I have the same problem as described in this issue. I translate an element and the Tapped event cannot be raised after that.
Do you have more information on this? Is this really a bug?
