### ISSUE TITLE
BoxView should be mentioned for migration

### ISSUE THREAD

**Issue by BioTurboNick** [dotnet/docs-maui#1045]
BoxView was an important part of Xamarin.Forms, but it's not mentioned at all that I can see in MAUI. Knowing how to migrate it is important.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68990f2c-45ae-8d81-24cc-4004a2fa994c
* Version Independent ID: 68990f2c-45ae-8d81-24cc-4004a2fa994c
* Content: [.NET MAUI handlers - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/)
* Content Source: [docs/user-interface/handlers/index.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/index.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 57847](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57847)

**Comment by davidbritch** [comment]
I've added BoxView to the handlers list. Migrating a BoxView is a topic for the migration docs, which are being tracked in other issues.
