### ISSUE TITLE
Insufficient to achieve a MAC connection

### ISSUE THREAD

**Issue by tradegear** [dotnet/docs-maui#1052]
This documentation fails to mention that there are several steps to perform on a MAC in order for it to be connectable and be a build host.
1. You must actually have a Mac.
2. Have an Apple Developer Account.  Pay your $99.
3. Download/install XCode (close to latest version, but sometimes not absolutely latest version cause VS may choke on it).
4. Install Mono framework.
5. Set Xcode default location on the Mac.
6. Set "Remote Access" on Mac.
7. Sign into Mac.
8. Make sure your Mac and your Windows PC are on the same network.
9. Make note of the IP address of your Mac, since it doesn't seem that the broadcast search for "available" Macs will find a mac.
10. Now Mac might accept your connection.  Try connecting to the Mac via IP.

However even after this, I have yet to succeed in actually getting the IOS emulator to launch with even the "cute bot" application.  I reported this on the Visual Studio feedback channel a few days ago and have been supplying info today after my delay working on other issues.
https://developercommunity.visualstudio.com/t/iOS-app-fails-to-appear---dotnet-MAUI-c/10181157

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3e5ccb-ecdd-c174-6e36-ce3e74a68e4e
* Version Independent ID: 9a3e5ccb-ecdd-c174-6e36-ce3e74a68e4e
* Content: [Remote iOS Simulator for Windows - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/ios/remote-simulator)
* Content Source: [docs/ios/remote-simulator.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/remote-simulator.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@tradegear See step 2 in the doc, which links to https://learn.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac
