### ISSUE TITLE
How to determine correct assembly for a namespace?

### ISSUE THREAD

**Issue by rccnw** [dotnet/docs-maui#1056]
[Enter feedback here]
This article is representative of much of documentation for all products.  A namespace is mentioned, but no clue what assembly should in included via package manager.  This is super frustrating and causes lots of internet searching sometimes. 

Please also state what assembly contains a namespace whenever that namespace is is mentioned..

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c35bd633-398f-ed9f-888d-a72d457a5745
* Version Independent ID: c35bd633-398f-ed9f-888d-a72d457a5745
* Content: [Device information - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/information?tabs=ios)
* Content Source: [docs/platform-integration/device/information.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device/information.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rccnw 

In .NET MAUI in .NET 6 there's no need to install any additional assemblies/packages into your .NET MAUI project. Once you create a .NET MAUI project you automatically have access to all the functionality that MAUI provides. On top of that, you often don't even need to know what namespace a type is in, because there are included by .NET MAUI as implicit using statements. For example, you can use `DeviceInfo` without having to add a `using` statement for `Microsoft.Maui.Devices`.

**Comment by rccnw** [comment]
Hi @davidbritch

Ah, thanks so much.  I was somewhat aware of that automatic references feature in general, but since it 'just works' I never thought about it much or realized the wider implications.  

Thanks to your explanation, I just realized I am trying to use the Location type from Microsoft.Maui.Devices.Sensors in a WebApi project, and I was using a MAUI app as a reference (where it resolves just fine), I want to send that Location back from the app to an endpoint.  Can I even use this Location type in a non-MAUI project? Maybe because this type is so strongly coupled with the device abstraction it isn't appropriate for use elsewhere?  In that case, I need to wonder what form I should use over the wire and in storage.  Any thoughts?  In any case, you've clarified the mystery why one project resolved the type but another did not. I can now search for solutions with at least one set of blinders removed :)

**Comment by davidbritch** [comment]
@rccnw 

So the `Location` type is in the Microsoft.Maui.Essentials assembly. But this isn't actually a NuGet package. To use the `Location` type in a WebApi project you'd be best just copying the type from https://github.com/dotnet/maui/blob/18ed02b41a35edad98aef79ec677c42ebff52890/src/Essentials/src/Types/Location.shared.cs.

As far as I can see, there's nothing MAUI-specific in the type definition so you should be able to use it in your WebAPI project.

**Comment by rccnw** [comment]
@davidbritch

Thank you for suggesting that idea, and for clarifying the existing general mechanism of automatically including typical references, that really is a good feature.    Loving this whole fun playground!
