### ISSUE TITLE
How to close the device dialer?

### ISSUE THREAD

**Issue by Fn-M** [dotnet/docs-maui#1060]
Hi,

Using the PhoneDialer class to open the dialer on the device, what's the procedure to hide or close the dial?

For example, say that the dialer is visible, but the user clicks in a button of the UI page and the behavior for that button is to hide/close the dial, because the operation to dial is to be cancelled.

Same way there is a _PhoneDialer.Open(string number)_, shouldn't be a _PhoneDialer.Close()_ or a boolean property of _PhoneDialer.Current_ that tells if the dialer is open?

Basically if there is more flexibilty to manipulate the dialer..

Best regards!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 434134e2-02dc-840a-1a72-b784165254cd
* Version Independent ID: 434134e2-02dc-840a-1a72-b784165254cd
* Content: [Phone dialer - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/phone-dialer?tabs=android)
* Content Source: [docs/platform-integration/communication/phone-dialer.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/communication/phone-dialer.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
I don't believe so. Any app I've ever used that opens the dialer lets the user choose when to close the dialer by navigating back. You've essentially opened another app when you invoke the dialer, so it's up to the user to close it.
