### ISSUE TITLE
Reference tables are inconsistent

### ISSUE THREAD

**Issue by ClaudioFriederich** [dotnet/docs-maui#1061]
The reference tables are full of inconsistencies.  For example, all the -maui... properties are identified as -xf... properties in their examples.  So is it -maui or -xf?  width, height properties examples show min-width and min-height instead.

Either a column of or a general explanation of the naming convention between the object properties names in C#/XAML and the corresponding CSS property names would be helpful, if not essential.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7897e970-6807-a516-d029-d5d0c27e15de
* Version Independent ID: 7897e970-6807-a516-d029-d5d0c27e15de
* Content: [Style apps using Cascading Style Sheets - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/styles/css)
* Content Source: [docs/user-interface/styles/css.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/styles/css.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 33069](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33069)

**Comment by davidbritch** [comment]
Hi @ClaudioFriederich 

Thanks for pointing this out. It should all be `-maui`, not `-xf`. The easy way to see the mapping from CSS property to .NET properties is to take a look at https://github.com/dotnet/maui/blob/6dc3d240b434b379b03cdd2c788e26e374c07705/src/Controls/src/Core/Properties/AssemblyInfo.cs#L78
