### ISSUE TITLE
Opening Multi-window on Windows raises TargetInvocationException when calling DisplayActionSheet()

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/docs-maui#1064]
[After opening multiple window on Windows as instructed in the documentation, call DisplayActionSheet() raises Excepion:
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.']

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7dc34b7-8355-cff9-6754-c9fdefade29a
* Version Independent ID: c7dc34b7-8355-cff9-6754-c9fdefade29a
* Content: [.NET MAUI windows - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/windows?view=net-maui-7.0)
* Content Source: [docs/fundamentals/windows.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/windows.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SunshineSpring666 

Afraid that this is an issue best raised in the [engineering repo](https://github.com/dotnet/maui). Thanks!

**Comment by SunshineSpring666** [comment]
Sorry, I didn't notice that. I'll post this issue in MAUI repo.
Best Regards
