### ISSUE TITLE
ótima aplicação

### ISSUE THREAD

**Issue by pedrohendp** [dotnet/docs-maui#1072]
[Aplicação muito bem documetada, conseguindo extrair bons frutos somente com as documentações.]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação de problema do learn.microsoft.com ➟ GitHub.*

* ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Version Independent ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Content: [Tutorial: Criar um aplicativo .NET MAUI - .NET MAUI](https://learn.microsoft.com/pt-br/dotnet/maui/tutorials/notes-app/?view=net-maui-7.0&source=docs&tutorial-step=5)
* Content Source: [docs/tutorials/notes-app/index.yml](https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thanks!
