### ISSUE TITLE
MAUI Migration Link to Version 6 Preview

### ISSUE THREAD

**Issue by TonyLugg** [dotnet/docs-maui#1073]
The link to the Migration page (https://github.com/dotnet/maui/wiki/Migrating-from-Xamarin.Forms-(Preview)) points to MAUI version 6 preview and states that things could change once it is released.  Please update the migration docs so we can move from Xamarin Forms.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e223-a9cc-1efb-07ec-01c8501d7a46
* Version Independent ID: 538673ca-22c5-2a5c-97c0-1552ae9f7b79
* Content: [Migrate your app from Xamarin.Forms to .NET MAUI - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/get-started/migrate?view=net-maui-7.0&source=docs)
* Content Source: [docs/get-started/migrate.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/migrate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @TonyLugg 

Afraid I have no control over what's published on the Wiki in the engineering repo. But I can say that the migration doc in the wiki is generally correct. There will be official docs on migrating from Xamarin.Forms once the engineering work to enable this has been finished.
