### ISSUE TITLE
RuntimeIdentifier or RuntimeIdentifiers?

### ISSUE THREAD

**Issue by dbullen-uk** [dotnet/docs-maui#1074]
This does not work for me unless I use RuntimeIdentifiers in the PropertyGroup node, rather than RuntimeIdentifier  (note the s).  Please could you check?

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44286466-fb54-f175-d197-7deee0db1e30
* Version Independent ID: 44286466-fb54-f175-d197-7deee0db1e30
* Content: [Publish a .NET MAUI app for iOS - .NET MAUI](https://learn.microsoft.com/en-gb/dotnet/maui/ios/deployment/overview?view=net-maui-7.0)
* Content Source: [docs/ios/deployment/overview.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/deployment/overview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @dbullen-uk Sorry for the delay in getting back to you, how exactly are you setting this? `<RuntimeIdentifier>` should be correct. Can you share your project xml?
