### ISSUE TITLE
HelloMaui app won't run; access errors

### ISSUE THREAD

**Issue by jbh630** [dotnet/docs-maui#108]
When trying to build or run the HelloMaui app with the Android simulator selected 4 errors occur:
Unable to create directory "obj\Debug\net6.0-androind" Access to path denied.
Same error for ios and mascata
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app in Visual Studio - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jbh630 

This looks like product feedback and should be directed at https://github.com/dotnet/maui. Please open an issue there. Thanks and sorry we can't help with this.
