### ISSUE TITLE
Not able to use a referenced iOS binding project

### ISSUE THREAD

**Issue by realst3v3** [dotnet/docs-maui#1083]
We created an iOS binding project containing a .framework native reference.
Our .NET MAUI app now references the iOS binding project, but the namespaces used in the ApiDefinitions.cs and StructsAndEnums.cs (created with ObjectiveSharpie) will not get resolved in our MAUI app.
We tried a lot of things, but it seems not to work at all. Are there one or two positive examples of binding iOS native frameworks?
Thanks...

**Comment by davidbritch** [comment]
Replaced by #1514
