### ISSUE TITLE
Property Subject

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/docs-maui#1092]
At the end of platform differences (https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/data/share?view=net-maui-7.0&tabs=android) there is the subject property but this is not in code nor anywhere else mentioned on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d340ffe1-24b6-ff95-39a5-057bf10826c9
* Version Independent ID: d340ffe1-24b6-ff95-39a5-057bf10826c9
* Content: [Share - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/data/share?view=net-maui-7.0&tabs=android)
* Content Source: [docs/platform-integration/data/share.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/data/share.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Correct. The subject is only used by android and the examples in the page are built to work across multiple platforms. Without testing, I imagine this is used when you share via an email on android, filling in the subject of the email with the value you provided.
