### ISSUE TITLE
Wireless deployment for iOS apps

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1093]
VS and VSMac support deploying .NET MAUI iOS apps to a device over WiFi (as well as USB). This requires pairing your iOS device with Xcode on your paired Mac. Once paired, it can be selected as a debug target in VS/VSMac.

This needs doc'ing using both VS and VSMac.

https://learn.microsoft.com/en-us/xamarin/ios/deploy-test/wireless-deployment?tabs=macos

---
[Associated WorkItem - 43571](https://dev.azure.com/msft-skilling/Content/_workitems/edit/43571)

**Comment by Rinppn9999** [comment]
😄How do you know?  []()
