### ISSUE TITLE
The app does not behave according to the documentation

### ISSUE THREAD

**Issue by DavidShochet** [dotnet/docs-maui#1095]
I have the following code to send emails (based on an example from https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/email?view=net-maui-7.0&tabs=windows):

```csharp
       try
        {
            if (Microsoft.Maui.ApplicationModel.Communication.Email.Default.IsComposeSupported)
            {
                var message = new EmailMessage
                {
                    Subject = string.Empty,
                    Body = string.Empty,
                    BodyFormat = EmailBodyFormat.PlainText,
                    To = new List<string>() { _emailTechService },
                };

                await Email.Default.ComposeAsync(message);
            }
            else
            {
                await Shell.Current.DisplayAlert("Email Failure", $"Sending emails feature is not supported on this device", "OK");
            }
        }
        catch (Exception ex)
        {
            App.HandleException(ex, true);
        }
```

On iOS and Android it works correctly, but when I run it on Windows Machine in Visual Studio, IsComposeSupported is true, but Email.Default.ComposeAsync(message) throws a System.Runtime.InteropServices.COMException "The request is not supported."

How can I check if the feature is supported correctly to avoid the exception?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb883e1b-a1ef-6684-d501-e9be8a57852b
* Version Independent ID: fb883e1b-a1ef-6684-d501-e9be8a57852b
* Content: [Email - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/email?view=net-maui-7.0&tabs=windows)
* Content Source: [docs/platform-integration/communication/email.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/communication/email.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
I just tested this on windows and it works for me. Is it possible that you don't have a default email app configured or something? Otherwise, I'm unsure, you'll need to file a bug with the product team and probably provide a lot more information, such as the windows version, maui version, what default apps you have configured for email, etc.

I can't transfer your issue, unfortunately, but you can open a new one at https://github.com/dotnet/maui/issues
