### ISSUE TITLE
Platform specific requirements (text-to-speech)

### ISSUE THREAD

**Issue by clough360** [dotnet/docs-maui#1098]
I couldn't find it documented anywhere (may have missed it), but there are platform specific requirements for this to work.
For example, for android, the following intent needs adding to the AndroidManifest.xml file
```
		<intent>
			<action android:name="android.intent.action.TTS_SERVICE" />
		</intent>

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80172681-b0f2-26ea-9062-b23c15699ed4
* Version Independent ID: 80172681-b0f2-26ea-9062-b23c15699ed4
* Content: [Text-to-Speech - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device-media/text-to-speech?view=net-maui-7.0)
* Content Source: [docs/platform-integration/device-media/text-to-speech.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device-media/text-to-speech.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 45532](https://dev.azure.com/msft-skilling/Content/_workitems/edit/45532)

**Comment by adegeo** [comment]
Looks like this was missed. Thank you for letting us know. AFAIK there aren't any other requirements besides the one you posted.
