### ISSUE TITLE
Still don't understand the 'Basis' concept

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/docs-maui#1107]
I don't know you guys. But after reading the `Basis` section many times, I still don't understand what it means and how to use it. The sample doesn't help either, and it doesn't work on Windows platform, i.e. the label2 doesn't change at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b597471-8e79-032f-e023-f14ad564405d
* Version Independent ID: 1b597471-8e79-032f-e023-f14ad564405d
* Content: [FlexLayout - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/flexlayout?view=net-maui-7.0#examples)
* Content Source: [docs/user-interface/layouts/flexlayout.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/layouts/flexlayout.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 56010](https://dev.azure.com/msft-skilling/Content/_workitems/edit/56010)

**Comment by davidbritch** [comment]
Hi @nicholasyin 

I'll give the doc a small update. The basis is the initial size of the item before the free space is distributed according to other property values. 

`FlexLayout` doesn't work so well on Windows. All I can recommend there is logging issues against it in the [engineering repo](https://github.com/dotnet/maui).
