### ISSUE TITLE
ViewCell inside TableView and TableSection is now working

### ISSUE THREAD

**Issue by cicciolinamiranda** [dotnet/docs-maui#1108]
Example code below

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:xct="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             Title="Settings"
             x:Class="MauiApp1.MainPage">

    <TableView Intent="Settings">
        <TableRoot>
            <TableSection Title="Settings">
                <ViewCell>
                    <Grid RowDefinitions="Auto,Auto"
                      ColumnDefinitions="0.5*,0.5*">
                        <Label Text="Vibrate"
                           Margin="10,10,0,0"/>
                        <Switch Grid.Column="1"
                            HorizontalOptions="End" />
                        <Slider Grid.Row="1"
                            Grid.ColumnSpan="2"
                            Margin="10"
                            Minimum="0"
                            Maximum="10"
                            Value="3" />
                    </Grid>
                </ViewCell>
            </TableSection>
        </TableRoot>
    </TableView>

</ContentPage>
`

Result: Items inside ViewCell are not showing
![Screenshot_1670049271](https://user-images.githubusercontent.com/17084421/205428188-3560cddc-bc71-4281-9d10-90247143c4e6.png)

**Comment by adegeo** [comment]
Hello. It looks like you're trying to report a bug with the product and not with a specific article in the documentation. You'll need to create your issue in the product repository: https://github.com/dotnet/maui/issues
