### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by Mar181-arc** [dotnet/docs-maui#1111]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42400eea-3839-ac76-bac9-02e1473bcd87
* Version Independent ID: 42400eea-3839-ac76-bac9-02e1473bcd87
* Content: [Battery - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/battery?source=recommendations&view=net-maui-7.0&tabs=android)
* Content Source: [docs/platform-integration/device/battery.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device/battery.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello! It looks like you opened this issue in error as you didn't provide any details. I'll close it.
