### ISSUE TITLE
iOS image size - Doc

### ISSUE THREAD

**Issue by tuliocll** [dotnet/docs-maui#1115]
Maybe it's a good idea to add [this issue](https://github.com/dotnet/maui/issues/8609) as a tip on the tutorial to help those who are running iOS device and getting this result on Tabbar:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/22357579/206298079-4da0c6a3-eef0-4ab8-a0fe-707f22d99021.png">

Or just resize the `PNG` icons to 30x30 (works well on the android and iOS):
<img width="371" alt="image" src="https://user-images.githubusercontent.com/22357579/206298377-a1839e6b-95e4-4f26-9f5d-9c1b50e68095.png">

Android:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/22357579/206301557-de281642-6432-47fa-84f1-8c5d11a1b86a.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Version Independent ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Content: [Tutorial: Create a .NET MAUI app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?source=recommendations&view=net-maui-7.0&tutorial-step=2#feedback)
* Content Source: [docs/tutorials/notes-app/index.yml](https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 55278](https://dev.azure.com/msft-skilling/Content/_workitems/edit/55278)

**Comment by adegeo** [comment]
@tuliocll This sounds like a bug with .NET MAUI. It shouldn't be allowing an image to bleed through like that. Can you file a bug on https://github.com/dotnet/maui/issues

If you look at the picture, it seems to have sized the image really low, then stretched it to an area too big. It's almost related to https://github.com/dotnet/maui/issues/6043

**Comment by adegeo** [comment]
I'm reopening this. I'm running into more problems with this for iOS/Mac. It doesn't seem like this will be fixed anytime soon in the product so the solution is to set a base size on the icon or use `OnPlatform` extensions.

**Comment by adegeo** [comment]
https://github.com/dotnet/maui/issues/11099
