### ISSUE TITLE
Pick an existing image

### ISSUE THREAD

**Issue by rogersm-uwosh** [dotnet/docs-maui#1117]
There is an example on this page that uses https://aka.ms/campus.jpg

However, that link is defunct, and since people are coming to this page for help, it would be great if when you paste in the code and run it it doesn't fail because of this.

I recommend something from xkcd.com 😀 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb4d16da-8c0f-5b7e-54ee-1fe36c549837
* Version Independent ID: cb4d16da-8c0f-5b7e-54ee-1fe36c549837
* Content: [Image - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/image?view=net-maui-7.0)
* Content Source: [docs/user-interface/controls/image.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/image.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 56011](https://dev.azure.com/msft-skilling/Content/_workitems/edit/56011)

**Comment by adegeo** [comment]
LOL

Thanks for reporting this!

**Comment by davidbritch** [comment]
Hi @rogersm-uwosh 

Fixed!
