### ISSUE TITLE
OMG how terrible.

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#1118]
So I find this and copy the code (you have a copy button).  And ..... compile errors.  So add using Microsoft.Maui.Controls;.  

And the result ..... error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0120	An object reference is required for the non-static field, method, or property 'Page.DisplayAlert(string, string, string)'	NHLMauiApp (net6.0-android)	C:\Visual Studio Stuff\Maui App The Latest\NHLMauiApp ListView HighLights\Views\NHLLeagueView.xaml.cs	235	Active

So this page is useless like most of Maui.

LLoyd Sheen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 144c1b04-ddfc-e59b-773f-94124fbbce7a
* Version Independent ID: 144c1b04-ddfc-e59b-773f-94124fbbce7a
* Content: [Display pop-ups - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pop-ups?view=net-maui-7.0)
* Content Source: [docs/user-interface/pop-ups.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pop-ups.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
I tried the first one and it worked fine for me.

Perhaps you're not running this in the context of a page? Like if you add a button to a page and then in the clicked handler of the page you use `DisplayAlert`.
