### ISSUE TITLE
Location within the overall documentation website

### ISSUE THREAD

**Issue by mprogers** [dotnet/docs-maui#1119]
This may not be practical, but I feel that Layout is such a vital topic that it needs something closer to star billing. Right now in the docs it is buried in User Interface >> Controls >> Layouts, and I had to scrounge a bit to find it. It is a type of Control, but could you consider raising it up one tier, so that it appears under User Interface >> Animation?

Thanks for considering this,

Michael
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdcef51d-4863-b416-c6c3-6b9d7095bef5
* Version Independent ID: fdcef51d-4863-b416-c6c3-6b9d7095bef5
* Content: [Layouts - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/?view=net-maui-7.0)
* Content Source: [docs/user-interface/layouts/index.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/layouts/index.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mprogers 

Thanks for the suggestion, but afraid it's got to stay where it is for now. Thanks anyway!

**Comment by rogersm-uwosh** [comment]
No worries, and thanks for considering it.
