### ISSUE TITLE
Problem with resource specification

### ISSUE THREAD

**Issue by mprogers** [dotnet/docs-maui#1120]
When talking about loading local resources here -- https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/image?view=net-maui-7.0#load-a-local-image -- the example just shows the name of the file. In my testing, with a default app that created Resources/Images, I had to specify Images/Name_Of_Image.png.

So I think there's a mistake in the docs. Can you please check this out?

Yours for better .NET MAUI documentation,

Michael
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb4d16da-8c0f-5b7e-54ee-1fe36c549837
* Version Independent ID: cb4d16da-8c0f-5b7e-54ee-1fe36c549837
* Content: [Image - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/image?view=net-maui-7.0)
* Content Source: [docs/user-interface/controls/image.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/image.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
I think the documentation is correct. I created a new app from the template and the dotnet bot icon that shows up is simply referenced via:

```xml
<Image
    Source="dotnet_bot.png"
    SemanticProperties.Description="Cute dot net bot waving hi to you!"
    HeightRequest="200"
    HorizontalOptions="Center" />
```

I then tried to load images from code. I added a `Loaded` event handler to the page and named the `VerticalStackLayout` in the xaml `verts`. This code works to load the image again by code:

```csharp
private void ContentPage_Loaded(object sender, EventArgs e)
{
	verts.Children.Add(new Image { Source = "dotnet_bot.png", HeightRequest=50 });
	verts.Children.Add(new Image { Source = ImageSource.FromFile("dotnet_bot.png"), HeightRequest=50 });
}
```
What platform are you using? I was testing on windows.
