### ISSUE TITLE
menu item on Android/IOS

### ISSUE THREAD

**Issue by yewtechnologiesuk** [dotnet/docs-maui#1124]
[Enter feedback here]
I tried the Menu Item feature it is working fine for Windows Desktop how could achieve similar in Android/IOS?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 184c91af-4cb0-10a6-bf4b-14b5469f4318
* Version Independent ID: 184c91af-4cb0-10a6-bf4b-14b5469f4318
* Content: [Display a menu bar in a .NET MAUI desktop app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/menu-bar?view=net-maui-7.0)
* Content Source: [docs/user-interface/menu-bar.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/menu-bar.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @yewtechnologiesuk 

You can't. Menu bars are only a concept in desktop apps.
