### ISSUE TITLE
dotnet publish switches - Question

### ISSUE THREAD

**Issue by jonmikeli** [dotnet/docs-maui#1130]
Hi,

Is there any kind of documentation describing all the CLI switches (not only the common ones) to compile and publish MAUI solutions (Android, iOS and Windows)?
The idea is to configure as many things as possible with pipelines and avoid using content at csproj level for specific information (ex: versions, etc).

Kr,

[Enter feedback here]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6c3b8a-6109-5ad5-ca05-fdaae8a9d66e
* Version Independent ID: 6b6c3b8a-6109-5ad5-ca05-fdaae8a9d66e
* Content: [Use the CLI to publish for Android - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-cli?view=net-maui-7.0)
* Content Source: [docs/android/deployment/publish-cli.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/publish-cli.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jonmikeli 

Apologies for the delayed response. For generic `dotnet publish` switches you want https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish. 

For iOS specific build properties, you want https://github.com/xamarin/xamarin-macios/wiki/Project-file-properties

For Android specific build properties, you want https://learn.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-properties, with some additional changes at https://learn.microsoft.com/dotnet/maui/migration/android-projects?view=net-maui-7.0#changes-to-msbuild-properties.

I get that this isn't currently ideal, but it'll take some time to consolidate all this info into a single location.

**Comment by jonmikeli** [comment]
No worries @davidbritch. I understand.
Thank you for your answer.
