### ISSUE TITLE
HelloWorld MAUI on Windows does not start

### ISSUE THREAD

**Issue by proficad** [dotnet/docs-maui#114]
I followed the instruction from this page:
https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=windows

When I try to run the app (Ctrl+F5), a dialog box appears that requires I install iTunes. But I do not plan to develop for iOS !!! Why is installing iTunes mandatory ???
How can I get rid of that dialog window?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @proficad 

iTunes is only necessary for using hot restart to push an app onto an iPhone. My guess is VS thinks you are trying to deploy to iOS, not Windows, so it'd be worth looking at which platform you're deploying to.

**Comment by proficad** [comment]
Thank you for your response!
I am unable to change the target OS of the project.
Please see this video:
https://www.screencast.com/t/cE2TuaSV

Thanks
Vaclav

**Comment by davidbritch** [comment]
@proficad To run on Windows set the .WinUI project as the startup project, and then run it.

Hint: this is actually broken in Preview 7!

**Comment by proficad** [comment]
I set the .WinUI project as the startup project and hit Ctrl+F5, nothing
happened.
