### ISSUE TITLE
iOS crashes when navigating back and forth with Shell animated presentation

### ISSUE THREAD

**Issue by eli191** [dotnet/docs-maui#1142]
Hi,

I get a crash the second time I try to navigate to a page that I have already navigated to once.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '<Microsoft_Maui_Controls_Platform_Compatibility_ShellSectionRenderer: 0x111029c00> is pushing the same view controller instance (<Microsoft_Maui_Platform_PageViewController: 0x11c438f60>) more than once which is not supported and is most likely an error in the application
```

Scenario is :
Page A > go to Page B > back to A > go to B = crash

Page B is set up with
```
Shell.SetPresentationMode(this, PresentationMode.Animated);
```

Navigation is performed  in page A :
``` 
Shell.Current.GoToAsync("pageB");
```
And in page B
``` 
Shell.Current.GoToAsync("..");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97825438-0df2-dbc2-8f1e-fb1490697a2c
* Version Independent ID: 97825438-0df2-dbc2-8f1e-fb1490697a2c
* Content: [.NET MAUI Shell navigation - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation?view=net-maui-7.0)
* Content Source: [docs/fundamentals/shell/navigation.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/navigation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eli191 

It's possible that this is a product bug, or it could also be as the error suggests - an unsupported scenario. It's impossible to know without a full repro case. Either way, this needs to go to the [engineering repo](https://github.com/dotnet/maui). Thanks!
