### ISSUE TITLE
Not clear what the difference is between normal selection and pre-selection

### ISSUE THREAD

**Issue by AdamBebko** [dotnet/docs-maui#1150]
It isn't clear on this page what the distinction between normal selection and pre-selection is. When would you use one over the other?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c12f52df-38dd-8dbd-bd9f-c10ad2831243
* Version Independent ID: c12f52df-38dd-8dbd-bd9f-c10ad2831243
* Content: [Configure CollectionView item selection - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/selection?view=net-maui-7.0)
* Content Source: [docs/user-interface/controls/collectionview/selection.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/collectionview/selection.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @AdamBebko 

It's as simple as using pre-selection when there's a need to (e.g. maybe a CollectionView shows a list of photos, with the last photo taken being pre-selected). I don't mean that to sound as facetious as it does. It's just an item of functionality that was added in response to user requests when `CollectionView` was designed. A quick search on "ListView preselection" and "CollectionView preselection" shows it's a common scenario.

**Comment by AdamBebko** [comment]
Thanks. Perhaps a quick sentence might help at the beginning under preselection just to clarify that it means loading a collection with items already selected. For me, at least, seeing it out of context was very confusing. And I thought it was something completely different. Once you explained it it makes perfect sense now.
