### ISSUE TITLE
Absolute layout code behind example not working

### ISSUE THREAD

**Issue by DimitriVanhaecke** [dotnet/docs-maui#1151]
AbsoluteLayout absoluteLayout = new AbsoluteLayout
        {
            Margin = new Thickness(20)
        };

        absoluteLayout.Add(new BoxView
        {
            Color = Colors.Silver
        }, new Rect(0, 10, 200, 5));
        absoluteLayout.Add(new BoxView
        {
            Color = Colors.Silver
        }, new Rect(0, 20, 200, 5));
        absoluteLayout.Add(new BoxView
        {
            Color = Colors.Silver
        }, new Rect(10, 0, 5, 65));
        absoluteLayout.Add(new BoxView
        {
            Color = Colors.Silver
        }, new Rect(20, 0, 5, 65));

        absoluteLayout.Add(new Label
        {
            Text = "Stylish Header",
            FontSize = 24
        }, new Point(30,25));                     

        Title = "Stylish header demo";
        Content = absoluteLayout;[Enter feedback here]

Not working in .net Maui

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8aac004-9823-8211-3e9d-aefe7d9c4d95
* Version Independent ID: d8aac004-9823-8211-3e9d-aefe7d9c4d95
* Content: [AbsoluteLayout - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/absolutelayout?view=net-maui-7.0)
* Content Source: [docs/user-interface/layouts/absolutelayout.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/layouts/absolutelayout.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 57790](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57790)

**Comment by DimitriVanhaecke** [comment]
AbsoluteLayout absoluteLayout = new AbsoluteLayout
        {
            Margin = new Thickness(20)
        };

        absoluteLayout.Add(new BoxView
        {
            Color = Colors.Silver
        }, new Rect(0, 10, 200, 5));
        absoluteLayout.Add(new BoxView
        {
            Color = Colors.Silver
        }, new Rect(0, 20, 200, 5));
        absoluteLayout.Add(new BoxView
        {
            Color = Colors.Silver
        }, new Rect(10, 0, 5, 65));
        absoluteLayout.Add(new BoxView
        {
            Color = Colors.Silver
        }, new Rect(20, 0, 5, 65));

        absoluteLayout.Add(new Label
        {
            Text = "Stylish Header",
            FontSize = 24
        }, new Point(30,25));                     

        Title = "Stylish header demo";
        Content = absoluteLayout;

This example is not working.

**Comment by davidbritch** [comment]
Hi @DimitriVanhaecke 

Add this file to your solution and it should work: https://github.com/dotnet/maui-samples/blob/main/6.0/UserInterface/Layouts/AbsoluteLayoutDemos/AbsoluteLayoutDemos/AbsoluteLayoutExtensions.cs

I'll get the doc updated with this code.
