### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by GerhardThummerer** [dotnet/docs-maui#1152]
During the tutorial, you're using an inconsistant naming in the German version. With the 'views' everything's fine but with Models appear errors since you use for the folder the German translation 'Modelle' but in the code you're using the English word 'Models'.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Version Independent ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Content: [Tutorial: Erstellen einer .NET MAUI-App - .NET MAUI](https://learn.microsoft.com/de-de/dotnet/maui/tutorials/notes-app/?view=net-maui-7.0&tutorial-step=2)
* Content Source: [docs/tutorials/notes-app/index.yml](https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 57911](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57911)

**Comment by adegeo** [comment]
I'll add some settings to keep Models Views ViewModels all from being localized, so that it remains consistent with the screenshots and actual code.
