### ISSUE TITLE
"Opacity" is no longer recognized.

### ISSUE THREAD

**Issue by pashaUSA** [dotnet/docs-maui#1153]
Property="Opacity" is no longer recognizable or is not accessible when creating a template for radio "check" visibility. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4d9b4fe-c357-031e-3fc4-9c22ffee81db
* Version Independent ID: a4d9b4fe-c357-031e-3fc4-9c22ffee81db
* Content: [RadioButton - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?view=net-maui-7.0)
* Content Source: [docs/user-interface/controls/radiobutton.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/radiobutton.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pashaUSA 

I just tried the code on iOS and `Opacity` was settable, and respected, from a VisualState:

![image](https://user-images.githubusercontent.com/8092460/210335366-6a041828-5090-4be5-ae11-4a4d47d9c55e.png)

```
        <Style TargetType="RadioButton">
            <Setter Property="VisualStateManager.VisualStateGroups">
                <VisualStateGroupList>
                    <VisualStateGroup x:Name="CheckedStates">
                        <VisualState x:Name="Checked">
                            <VisualState.Setters>
                                <Setter Property="TextColor"
                                        Value="Green" />
                                <Setter Property="Opacity"
                                        Value="1" />
                            </VisualState.Setters>
                        </VisualState>
                        <VisualState x:Name="Unchecked">
                            <VisualState.Setters>
                                <Setter Property="TextColor"
                                        Value="Red" />
                                <Setter Property="Opacity"
                                        Value="0.5" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateGroupList>
            </Setter>
        </Style>
``` 

With that said, while `TextColor` was settable it wasn't respected (displayed text was always black).

What platform and version (.NET 6 or 7) were you experiencing this issue o

**Comment by alexvinola** [comment]
Hi @davidbritch, I'm experiencing the same issue with Opacity, I am on dotnet maui 7 and the error only appears when the app is running on debug (I have not tried on release yet) the error that apears for me is this, but it does not stop the execution, it just appears:

XHR0012 Member 'Opacity' is not recognized or cannot be accessed.
