### ISSUE TITLE
Publish (create msix) for .NET MAUI Blazor App

### ISSUE THREAD

**Issue by iwhp** [dotnet/docs-maui#1170]
I try to publish (create a msix) for a .NET MAUI Blazor App.

In Visual Studio (latest preview version) the **Publish** command is not enabled when right clicking on the project file.

Using the cli **dotnet publish** command does not generate a msix file either. The command runs through without error messages. The last statement from the command is Created the package:

Any ideas if this should work and if yes, what am I missing?

**Comment by davidbritch** [comment]
Hi @iwhp 

I just tried to publish a .NET MAUI Blazor Hybrid app in the latest VS preview (17.5 P2) on Windows. For both .NET 6 and .NET 7 apps the Publish option was enabled when right-clicking on the project file. So yes, this should work. 

Similarly, the CLI command should work. It sounds like you might have an installation problem.
