### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cambob1** [dotnet/docs-maui#1181]
Broken link: [How to Use the Intel Hardware Accelerated Execution Manager](https://software.intel.com/android/articles/how-to-use-the-intel-hardware-accelerated-execution-manager-intel-haxm-android-emulator)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b808a184-7b95-fd8e-4ced-36f1deb8cc0b
* Version Independent ID: b808a184-7b95-fd8e-4ced-36f1deb8cc0b
* Content: [Android Emulator Troubleshooting - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/emulator/troubleshooting?view=net-maui-7.0#disabling-device-guard)
* Content Source: [docs/android/emulator/troubleshooting.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/emulator/troubleshooting.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @cambob1 

Afraid that Intel have pulled their HAXM docs, so the best I can do is replace the link with a generic HAXM troubleshooting link.
