### ISSUE TITLE
WooHoo great explanation!

### ISSUE THREAD

**Issue by Sugafar** [dotnet/docs-maui#1185]
This is a refreshingly great page that communicates the info in a clear, concise manner. Thank you so much for this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7dc547-5ff1-416d-450b-e39e56cb1e71
* Version Independent ID: 7d7dc547-5ff1-416d-450b-e39e56cb1e71
* Content: [Add images to a .NET MAUI app project - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/images?view=net-maui-7.0)
* Content Source: [docs/user-interface/images/images.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/images.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thanks, @davidbritch did a great job!
