### ISSUE TITLE
Helpful tip on debugging MAUI on device

### ISSUE THREAD

**Issue by shadowfoxish** [dotnet/docs-maui#1189]
[Enter feedback here]
I spent a fair bit of time figuring this out, so maybe it makes sense to include in the documentation as a troubleshooting hint. After I upgraded from Xamarin.Forms, debugging was broken. To enable it I had to

1. Switch to Debug|Any CPU mode
2. Right-Click the _solution_, and choose "Properties". Then click "Configuration Properties". Locate the MAUI project, and check the corresponding "Deploy" box.
3. Ensure `<OutputType>` is set to EXE in the csproj
4. Remove platforms I wasn't using or didnt have installed such as iOS or Windows
5. Ensure `MainLauncher=true` in the `[Activity]` attribute in MainActivity.cs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 479ebe15-bfd2-d049-7213-8f87c1887b92
* Version Independent ID: 479ebe15-bfd2-d049-7213-8f87c1887b92
* Content: [Set up a device for development - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/device/setup?view=net-maui-7.0)
* Content Source: [docs/android/device/setup.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/device/setup.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 61809](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61809)

**Comment by davidbritch** [comment]
Hi @shadowfoxish 

Good tips, and I'll make sure they make it into migration docs (once they're written).

**Comment by shadowfoxish** [comment]
Thanks, I love this platform. I remember doing cordova/phonegap and javascript years ago, and this is lightyears ahead.
