### ISSUE TITLE
maui progressbar double 0.000000000000 value how it would be

### ISSUE THREAD

**Issue by HFAsif** [dotnet/docs-maui#1193]
here i can not set Minimum="0" Maximum="100" ; there is no progressbar Value option , how to set progress bar maximum lenth and minimum lenth also here when i use percent change my app get hanged

**Comment by davidbritch** [comment]
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/progressbar?view=net-maui-7.0

**Comment by HFAsif** [comment]
i have already completly read this =>
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/progressbar?view=net-maui-7.0
and then i have posted here , there nothing clear , just posted the property

**Comment by OnlyIslam** [comment]
how u closed it unless u didnt gave any sugession about setting value , u closed with a google search result

**Comment by HFAsif** [comment]
thread ""closed as completed""" => false statement nothing completed ,

how u closed it unless u didnt gave any sugession about setting progress value how it would be, 

u closed with a google search result

**Comment by davidbritch** [comment]
The page lists the properties you can set on `ProgressBar`, and gives examples of how to use it. There's no `Minimum`, `Maximum`, or `Value` property. If there were, the doc would mention them.

**Comment by HFAsif** [comment]
when i invoke , progressbar.percent = e.progresspercent ; maui app get hang

**Comment by davidbritch** [comment]
It has to be set to a value between 0 and 1.
