### ISSUE TITLE
The Enterprise Architecture link on the MAUI MVVM Tutorial Next Steps is 404

### ISSUE THREAD

**Issue by Cawifre** [dotnet/docs-maui#1194]
[This link](https://learn.microsoft.com/en-us/architecture/maui/mvvm) found on the final page of the tutorial has gone stale; I get a (rather polished) 404 page when I follow it. That's a shame because I was interested in reading it and the Internet Archive's Wayback Machine never crawled it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 112517e9-4e69-a13d-61d0-9ae41818ca27
* Version Independent ID: 112517e9-4e69-a13d-61d0-9ae41818ca27
* Content: [Tutorial: Use the MVVM toolkit to update the Notes app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-mvvm/?view=net-maui-7.0&tutorial-step=8)
* Content Source: [docs/tutorials/notes-mvvm/index.yml](https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-mvvm/index.yml)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 59515](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59515)

**Comment by davidbritch** [comment]
Hi @Cawifre 

Thanks for letting us know. It needs /dotnet/ inserting in the link - https://learn.microsoft.com/en-us/dotnet/architecture/maui/mvvm

I'll get this updated today.

**Comment by Cawifre** [comment]
Thanks for the quick fix! I'm thrilled that the content is actually available.
