### ISSUE TITLE
Error with example

### ISSUE THREAD

**Issue by grantvine-sc** [dotnet/docs-maui#1204]
It appears the example should change to Rect and not Rectangle

public static Rectangle -> public static Rect

return new Rectangle( -> return new Rect(
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18807604-a4a8-7fa5-b675-5be77277e158
* Version Independent ID: 18807604-a4a8-7fa5-b675-5be77277e158
* Content: [Launcher - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/launcher?view=net-maui-7.0&tabs=ios)
* Content Source: [docs/platform-integration/appmodel/launcher.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/appmodel/launcher.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 65330](https://dev.azure.com/msft-skilling/Content/_workitems/edit/65330)

**Comment by adegeo** [comment]
@grantvine-sc Thank you for spotting this. I'll get it fixed up!

Note to self: check all articles that use the same presentation bounds include file.
