### ISSUE TITLE
Workload troubleshooting

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1206]
Add content on troubleshooting .NET MAUI workloads: https://gist.github.com/jonathanpeppers/63beb491a9185ac06710261536cc35c9

This is probably a good candidate to add to the [Troubleshooting](https://learn.microsoft.com/dotnet/maui/troubleshooting?view=net-maui-7.0) doc.

---
[Associated WorkItem - 66537](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66537)

**Comment by Redth** [comment]
@joeloff @marcpopMSFT Could you perhaps add some information here for how to collect relevant logs and any other information as well as _where_ that should be filed as a bug, so that we can start collecting some useful issues to diagnose these cases better?

**Comment by Redth** [comment]
Related to: https://github.com/dotnet/sdk/issues/22388
