### ISSUE TITLE
and where is the documentation of the model, with its flags

### ISSUE THREAD

**Issue by xdaveRQ** [dotnet/docs-maui#1208]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73164f27-28e1-7bf6-64ec-277ade9ac973
* Version Independent ID: 73164f27-28e1-7bf6-64ec-277ade9ac973
* Content: [.NET MAUI local databases - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/database-sqlite?view=net-maui-7.0)
* Content Source: [docs/data-cloud/database-sqlite.md](https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/database-sqlite.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @xdaveRQ 

Often the docs don't present full code because it would make the content too long. When that happens there's a link to a sample at the top of the doc, that contains full code. Hence you'll find the model code there. Hope this helps!
