### ISSUE TITLE
Why no info on disable?

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#1211]
If I disable Hot Reload the app will not execute as I get a resource (Gray950) not found.  This page does not warn about this.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31cbef98-89fe-fb8a-c1a5-3119c1f0c207
* Version Independent ID: 31cbef98-89fe-fb8a-c1a5-3119c1f0c207
* Content: [XAML Hot Reload for .NET MAUI - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/xaml/hot-reload?view=net-maui-7.0&tabs=vswin)
* Content Source: [docs/xaml/hot-reload.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/hot-reload.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sqlguy6212 

This doesn't sound like a hot reload issue - more likely an issue with bin/obj and resources not rebuilding when hot reload is disabled. The best thing you can do is log an issue in the [engineering repo](https://github.com/dotnet/maui). Thanks!
