### ISSUE TITLE
Is this still current?

### ISSUE THREAD

**Issue by samuelwine** [dotnet/docs-maui#1220]
Thanks for this super-helpful article!
Just wondering if [this section](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?view=net-maui-7.0#configure-the-native-webview-on-ios-and-mac-catalyst) is still current. 
I can't find a constructor on MauiWkWebView that takes in a configuration object, nor a static CreateConfiguration method.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ace91785-d304-f161-408e-34511fb75ce3
* Version Independent ID: ace91785-d304-f161-408e-34511fb75ce3
* Content: [WebView - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?view=net-maui-7.0)
* Content Source: [docs/user-interface/controls/webview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/webview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @samuelwine 

Thanks for the feedback. Yes, that section is still current - it's something that's only present in the .NET 7 version of MAUI (you can switch the docs between .NET 6 and 7). See https://github.com/dotnet/maui/blob/f9d3e3fa4ac0bf7abfa98aae6cbfaa5d24d42f63/src/Core/src/Platform/iOS/MauiWKWebView.cs#L30 for the overload.

**Comment by samuelwine** [comment]
Thanks @davidbritch - appreciate the quick response!
