### ISSUE TITLE
Reference to .Net 6 on a page of .Net 7

### ISSUE THREAD

**Issue by uhfath** [dotnet/docs-maui#1221]
The whole page references .Net 6 on images and through text while the page is for .Net 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2be98396-dc5f-1a99-f96a-a346c3098e2c
* Version Independent ID: e5c64f3c-1ca2-a0d8-b16a-e189918eedb7
* Content: [What is .NET MAUI? - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/what-is-maui?view=net-maui-7.0)
* Content Source: [docs/what-is-maui.md](https://github.com/dotnet/docs-maui/blob/main/docs/what-is-maui.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 61300](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61300)

**Comment by davidbritch** [comment]
Hi @uhfath 

Interesting. Thanks for letting me know. I remember updating this image to just say .NET so I'll go and track down what's gone wrong.

**Comment by davidbritch** [comment]
So I did change this image last November (https://github.com/dotnet/docs-maui/blob/main/docs/media/what-is-maui/maui.png) but the build system isn't picking it up. I'll get that fixed.
