### ISSUE TITLE
This is all very 1980s but how do I use the GUI to design the interface? 

### ISSUE THREAD

**Issue by tmcmi** [dotnet/docs-maui#1235]
Please tell me you haven't regressed to before the WinCE days.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Version Independent ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Content: [Tutorial: Create a .NET MAUI app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?view=net-maui-7.0&tutorial-step=5)
* Content Source: [docs/tutorials/notes-app/index.yml](https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by davidbritch** [comment]
Hi @tmcmi

Afraid there isn't a designer at all. The idea is you write your UI using XAML (or C#) and then rely on hot reload to see the UI changes on your chosen platform, without having to rebuild the app.
