### ISSUE TITLE
Documentation - add advanced sample for every control and also screenshots for this sample

### ISSUE THREAD

**Issue by jfversluis** [dotnet/docs-maui#1238]
---
**Issue moved from dotnet/maui#6011**
- Please respond to @janseris.

---

_From @janseris on Tuesday, April 12, 2022 8:48:17 PM_

### Description

This platform is awesome and it needs much more visual samples in the documentation not only for the main controls but for all controls.
Also, some official videos - like 5 minutes about every of the 40 controls would be awesome.
DevExpress does this very well with their documentation, you should learn from them. For Windows Forms controls, especially.
Not just basic sample but also some advanced using all features of the control and put into context of a real-world app with some tips and tricks and all visible from a screenshot and code on the docs page for quick learning. This might increase the spread of MAUI significantly.
Images are very fast showoff for people browsing the docs. And GIFs and videos and all!

What is great about the docs is that there is always C# equivalent code. That is very welcome to see! It helps understanding XAML constructs how they work behind the scenes.

### Public API Changes

none

### Intended Use-Case

new MAUI learners quick learn

**Comment by davidbritch** [comment]
Hi @janseris

Unfortunately this just isn't on the cards right now, due to resource constraints and the internal guidelines on how docs are to be constructed. Thanks for the suggestion though!

**Comment by janseris** [comment]
@davidbritch btw The point of this was especially so that the docs creators and MAUI developers discover bugs in the controls.

**Comment by davidbritch** [comment]
@janseris 

Yeah, I get it. Right now the focus for the docs is just filing in all the gaps that exist in the content. It'll be that way for a while yet. But there are other things going on behind the scenes that should help with control bugs.
