### ISSUE TITLE
This documentation page is GOOD

### ISSUE THREAD

**Issue by balintn22** [dotnet/docs-maui#1241]
I struggeld a lot with Maui navigation recently. Then I found this page and found it very informative, concise, listing the possible alternatives. It is GOOD.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97825438-0df2-dbc2-8f1e-fb1490697a2c
* Version Independent ID: 97825438-0df2-dbc2-8f1e-fb1490697a2c
* Content: [.NET MAUI Shell navigation - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation?view=net-maui-7.0)
* Content Source: [docs/fundamentals/shell/navigation.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/navigation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thanks! @davidbritch did a great job writing this content!
