### ISSUE TITLE
Where is GraphicsService class mentioned in the docs?

### ISSUE THREAD

**Issue by andriysavin** [dotnet/docs-maui#1242]
In the [Load an image](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/images?view=net-maui-7.0#load-an-image) section I read:

> Image loading functionality is provided by the **GraphicsService** class

However, this class is not used in the provided code snippet and is not mentioned on the page any more. I also can't find it in the Maui and Maui.Graphics repositories. So is this a mistake in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdb45230-f4a3-e5fe-62d7-1009d50e9e4f
* Version Independent ID: fdb45230-f4a3-e5fe-62d7-1009d50e9e4f
* Content: [Images - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/images?view=net-maui-7.0)
* Content Source: [docs/user-interface/graphics/images.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/images.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 63261](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63261)

**Comment by davidbritch** [comment]
Hi @andriysavin 

Yes, it's a mistake in the docs. Originally you'd load an image with `GraphicsService.LoadImageFromStream`, but it was refactored at some point during the previews. The code in the docs was updated but not the surrounding text. Thanks for pointing this out. I'll get it fixed.

**Comment by andriysavin** [comment]
Thanks @davidbritch! 
Btw, I have another wish regarding this page. At least to a person who is trying to quickly find a solution or to one who is new to MAUI, it's unclear what should one do for Windows platform for every scenario on this page. After each code sample there is a warning saying "The PlatformImage type isn't supported on Windows.", making the code sample useless for Windows, and giving no clue about the path on this platform.

**Comment by davidbritch** [comment]
Hi @andriysavin 

Afraid there isn't really a path for Windows when it comes to using `PlatformImage`. The bottom line is that the type that provides the platform image functionality on Windows is internal and incorrectly named (IIRC it's called `W2DImage`).

It's been brought up by several people:

- https://github.com/dotnet/Microsoft.Maui.Graphics/issues/402
- https://github.com/dotnet/Microsoft.Maui.Graphics/issues/422
- https://github.com/dotnet/docs-maui/issues/669
- https://github.com/dotnet/docs-maui/issues/722
- https://github.com/dotnet/docs-maui/issues/820
- https://github.com/dotnet/docs-maui/issues/1122

Numerous PRs have been opened to fix this issue:

- https://github.com/dotnet/Microsoft.Maui.Graphics/pull/464
- https://github.com/dotnet/maui/pull/9948
- https://github.com/dotnet/maui/pull/12104
- https://github.com/dotnet/maui/pull/12578

But none of them have been merged. This is the latest PR that's still open, and should be watched for when the fix gets merged: https://github.com/dotnet/maui/pull/12818

Sorry I don't have something more positive to say here.

**Comment by andriysavin** [comment]
@davidbritch thanks anyway!
