### ISSUE TITLE
Please keep installation instructions up to date

### ISSUE THREAD

**Issue by lavrentius-dev** [dotnet/docs-maui#126]
I know that VS2022/.NET 6/MAUI are previews but it would be nice if someone checked on a daily basis if these installation instructions are actually/still valid? Because right now, they don't seem to be.

```
PS C:\Users\<me>\source\repos> dotnet workload install maui

Failed to update the advertising manifest microsoft.net.sdk.macos: Failed to fetch results from V2 feed at 'https://go.microsoft.com/fwlink/FindPackagesById()?id='microsoft.net.sdk.macos.manifest-6.0.100'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found)..
Failed to update the advertising manifest microsoft.net.sdk.android: Failed to fetch results from V2 feed at 'https://go.microsoft.com/fwlink/FindPackagesById()?id='microsoft.net.sdk.android.manifest-6.0.100'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found)..
Failed to update the advertising manifest microsoft.net.sdk.ios: Failed to fetch results from V2 feed at 'https://go.microsoft.com/fwlink/FindPackagesById()?id='microsoft.net.sdk.ios.manifest-6.0.100'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found)..
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: Failed to fetch results from V2 feed at 'https://go.microsoft.com/fwlink/FindPackagesById()?id='microsoft.net.sdk.maccatalyst.manifest-6.0.100'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found)..
Failed to update the advertising manifest microsoft.net.sdk.maui: Failed to fetch results from V2 feed at 'https://go.microsoft.com/fwlink/FindPackagesById()?id='microsoft.net.sdk.maui.manifest-6.0.100'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found)..
Failed to update the advertising manifest microsoft.net.sdk.tvos: Failed to fetch results from V2 feed at 'https://go.microsoft.com/fwlink/FindPackagesById()?id='microsoft.net.sdk.tvos.manifest-6.0.100'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found)..
Failed to update the advertising manifest microsoft.net.workload.emscripten: Failed to fetch results from V2 feed at 'https://go.microsoft.com/fwlink/FindPackagesById()?id='microsoft.net.workload.emscripten.manifest-6.0.100'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found)..
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: Failed to fetch results from V2 feed at 'https://go.microsoft.com/fwlink/FindPackagesById()?id='microsoft.net.workload.mono.toolchain.manifest-6.0.100'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found)..
Installing pack Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1063+sha.f5acc965e-azdo.5006556...
Workload installation failed, rolling back installed packs...
Rolling back pack Microsoft.Maui.Core.Ref.android installation...
Workload installation failed: Failed to fetch results from V2 feed at 'https://go.microsoft.com/fwlink/FindPackagesById()?id='microsoft.maui.core.ref.android'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found).
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello! Yes, things are changing a lot! However, this is still the way to install things. Those errors are backend errors by the tool and should be reported to the tool's repo. But they sound more temporary with some server disappearing due to a connection problem somewhere. It's probably be resolved by now or you just need to update to the latest preview of either product, something like that. If there is something out of date in the docs though, please let us know.

The instructions were updated for .NET Preview 7, which was released 10 days ago. 

But an error such as this would be reported to the product team at: https://github.com/dotnet/maui/issues

Hopefully your error is gone or the workload installer has been fixed by now. I'll create a new virtual machine and try the install instructions to see if they're broken.

**Comment by davidbritch** [comment]
Hi @lcocea 

I've just created a VM, installed VS2022 Preview 3, and .NET 6 Preview 7 (using maui-check) and I get MAUI templates in VS2022, and the created project builds and runs. I'm updating the instructions to that effect.

**Comment by lavrentius-dev** [comment]
Thanks, now it does on my side as well.
