### ISSUE TITLE
HyperlinkSpan does not work, even in the demo project 

### ISSUE THREAD

**Issue by stephenhauck** [dotnet/docs-maui#1268]
Thanks for the documentation, I was hoping it was going to work .. the Label does but the HyperlinkSpan does not.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 243e6d1d-a276-814f-7943-ff0fa7ba017e
* Version Independent ID: 243e6d1d-a276-814f-7943-ff0fa7ba017e
* Content: [Label - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label?view=net-maui-7.0#create-a-hyperlink)
* Content Source: [docs/user-interface/controls/label.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/label.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @stephenhauck 

Yes, afraid this is a known issue (see https://github.com/dotnet/maui/issues/8004) that's awaiting the engineers to fix it.
