### ISSUE TITLE
iOS safe area layout

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1270]
[This doc](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-safe-area-layout) needs bringing over to .NET MAUI, with updates to specify the scenarios in which it now applies.

By default, .NET MAUI apps will take the safe area into account (unlike Forms, where you had to opt into it). So the use of the platform-specific in .NET MAUI is to disable safe areas. Currently, setting `UseSafeArea` to `false` doesn't change the behaviour (although it should), which is a bug.

There's also a `IgnoreSafeArea` property you can set to achieve the same thing. PR that added it: https://github.com/dotnet/maui/pull/2001. However, it https://github.com/dotnet/maui/issues/12823 like it's no longer working in .NET 7.

---
[Associated WorkItem - 64262](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64262)

**Comment by project-x51** [comment]
This feature is not working for me in .NET 8.0, although IgnoreSafeArea="True" does.
