### ISSUE TITLE
Mobile Development with C++ workload needed?

### ISSUE THREAD

**Issue by adamkimsft** [dotnet/docs-maui#128]
[Enter feedback here]
I added those workloads shown in the list and picture but still didn't see the MAUI project type option.  Installed the MSIX, ran maui-check, ran dotnet workload install maui.  Still nothing.  Then decided that it would make sense to have Mobile Development with C++ workload added even though it's not listed.  That worked and I can see the MAUI project type now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @adamkimsft 

I've just created a VM, installed VS2022 Preview 3, and .NET 6 Preview 7 (using maui-check) and I get MAUI templates in VS2022, and the created project builds and runs. All without installing the Mobile Dev with C++ workload. As everything is only a preview right now, you most likely encountered installer bugs.

**Comment by olicooper** [comment]
I can confirm, uninstalling `.NET desktop development` workload and reinstalling it cured the problem for me. No need for C++ workload
