### ISSUE TITLE
Update RadioButton content to use Border instead of Frame

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1280]
MAUI has a bug whereby when the visual structure of a `RadioButton` is redefined using a `ControlTemplate`, the click event isn't recognised correctly on Android. This occurs when a `Frame` in the `ControlTemplate` prevents the `GestureRecognizer` from firing. See https://github.com/dotnet/maui/issues/6938 for more info.

When the `Frame` is replaced with a `Border`, the `RadioButton` works as expected. Therefore, update the RadioButton sample and doc so that it uses a `Border` rather than a `Frame`.

---
[Associated WorkItem - 66540](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66540)

**Comment by dustin-wojciechowski** [comment]
I have a PR open for this currently, was not sure how to link it to this issue: https://github.com/dotnet/maui/pull/13407
