### ISSUE TITLE
Copy from windows machine to windows machine is not working

### ISSUE THREAD

**Issue by vassiliospallis** [dotnet/docs-maui#1281]
To copy a certificate from a Windows machine to a Windows machine, copy the certificate from the C:\Users{User}\AppData\Local\Xamarin\iOS\Provisioning\Certificates folder and then on the other Windows machine import it into Visual Studio with the Import Certificate button.

This is not working because Visual Studio asks for password and it's not known.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 136ca791-32b6-dc5b-7baa-771283e4ae55
* Version Independent ID: 136ca791-32b6-dc5b-7baa-771283e4ae55
* Content: [Automatic provisioning for .NET MAUI iOS apps - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/ios/device-provisioning/automatic-provisioning?view=net-maui-7.0&tabs=vs)
* Content Source: [docs/ios/device-provisioning/automatic-provisioning.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/device-provisioning/automatic-provisioning.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 66535](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66535)

**Comment by davidbritch** [comment]
Hi @vassiliospallis 

You're right. When I wrote that I was thinking about copying a cert from Windows machine 1 to Windows machine 2, that had previously been copied from a Mac. But in retrospect that's not the main scenario, so I'll get the doc updated.

Thanks for reporting this.

**Comment by NousPratITPC** [comment]
> Hi @vassiliospallis
> 
> You're right. When I wrote that I was thinking about copying a cert from Windows machine 1 to Windows machine 2, that had previously been copied from a Mac. But in retrospect that's not the main scenario, so I'll get the doc updated.
> 
> Thanks for reporting this.

You are welcome!
