### ISSUE TITLE
Geolocation foreground listening

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1288]
In .NET 8, the `Gelocation` class gains foreground listening functionality.

https://github.com/dotnet/maui/pull/9572

https://jamesmontemagno.github.io/GeolocatorPlugin/

---
[Associated WorkItem - 164958](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164958)

**Comment by janseris** [comment]
Is "foreground" background or foreground?
Why am I asking: background service is called "foreground service" on Android.

**Comment by davidbritch** [comment]
This is definitely only for when apps are in the foreground. It adds the ability to start/stop listening for location updates while the app is in the foreground.
