### ISSUE TITLE
TargetIdiom removed in .NET 8

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1289]
`TargetIdiom` has been removed in .NET 8. Sweep the docs/samples to check it isn't being used.

https://github.com/dotnet/maui/pull/13090

---
[Associated WorkItem - 164959](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164959)

**Comment by davidbritch** [comment]
This is being reverted.

**Comment by mattleibow** [comment]
Reverted: https://github.com/dotnet/maui/pull/16982

**Comment by davidbritch** [comment]
No action required. `TargetIdiom` is still present in .NET 8, and isn't used in the docs/samples anyway.
