### ISSUE TITLE
VS 2022 doesn't recognize the WinUI project as a startup project

### ISSUE THREAD

**Issue by kalpanibhagya** [dotnet/docs-maui#129]
When I try to run the WinUI project, VS says it doesn't recognize the project as a startup project. But I have set it up as a startup project. Is there a fix for this issue? 

![image](https://user-images.githubusercontent.com/23649993/130206176-1e830f25-8a11-4a14-be77-8e72026ee726.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @kalpanibhagya 

I'm afraid that this is bug in preview 7. The engineers are aware of the problem and are working on fixing it. A workaround that sometimes works is to build and deploy the WinUI project, launch the app from the Start menu, and then attach the debugger to it (if required).

**Comment by kalpanibhagya** [comment]
@davidbritch Hi, I was able to publish the project but how can I attach the debugger?

**Comment by davidbritch** [comment]
https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2019
