### ISSUE TITLE
OpenGLView removed in .NET 8

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1296]
`OpenGLView` has always been deprecated in .NET MAUI, but has been removed in .NET 8. It shouldn't be present in docs/samples, but it's worth sweeping for it (in samples particularly).

---
[Associated WorkItem - 164950](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164950)

**Comment by ToolmakerSteve** [comment]
Does net 8 support any cross-platform 3D? Is there any plan for 3D in Maui? Maybe use Silk.net?

**Comment by davidbritch** [comment]
AFAIK there are no plans for 3D support in .NET MAUI 8. The options are third-party choices like Veldrid, WaveEngine, Silk.net, and Stride.

**Comment by davidbritch** [comment]
No action required. `OpenGLView` not present in docs/samples.
