### ISSUE TITLE
MessagingCenter internalized

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1302]
`MessagingCenter` was deprecated in .NET 7. In .NET 8 it's been made internal so won't be available to users. Hence the doc should be removed for .NET 8.

https://github.com/dotnet/maui/pull/12582

---
[Associated WorkItem - 164946](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164946)

**Comment by ChristopherStephan** [comment]
And should it be documented in https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0?

**Comment by davidbritch** [comment]
@ChristopherStephan  

Yes (it should be doc'd in the .NET 7 and 8 breaking changes docs). The engineers are responsible for doing that.

**Comment by davidbritch** [comment]
Delayed until .NET 9 - https://github.com/dotnet/maui/issues/16813, https://github.com/dotnet/maui/pull/16798

**Comment by davidbritch** [comment]
No action required. `MessagingCenter` is still present in .NET 8, although it's obsolete. The doc stays for another year.
