### ISSUE TITLE
FilePicker returns wrong path when picking a file from cloud drive

### ISSUE THREAD

**Issue by Jagu01** [dotnet/docs-maui#1312]
Hi everyone,

I'm currently trying to build a file sync for my app via cloud drives. I test my use cases with google and one drive. On Windows the path returned by the FilePicker picking from the cloud storage is correct. If I try to do the same thing on Android I get the following path: `/storage/emulated/0/Android/data/<myapp>/cache/<myfile>` where `<myapp>` is the app identifier (for example com.company.app) and `<myfile>` the filename. I know that I probably can't write directly to my cloud files (even if they are marked for offline access) and I will try to implement a solution using the respective APIs. But I wonder if it is possible to return another path if I pick a cloud file to detect if I can use the regular File API or have to use for example Google Drive API?

I want the users to be able to store the application file on their custom cloud drives without any extra login required. Think of KeePass2Android where you can sync your KDBX-files on cloud drives.

Any ideas on this topic? Am I heading in the wrong direction here?

**Comment by davidbritch** [comment]
Hi @Jagu01 

Afraid that this question is best asked as a discussion in the [engineering repo](https://github.com/dotnet/maui) or on [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/247/dotnet-maui). Thanks!
