### ISSUE TITLE
dotnet command line instructions don't work on a mac

### ISSUE THREAD

**Issue by breynolds** [dotnet/docs-maui#132]
With .net 6 Preview 7, the instructions for using the dotnet CLI fail on a Mac when trying to build a Maui app for iOS. Would like to use VS Code and dotnet CLI on a mac as a baseline build environment and eventually Visual Studio for Mac. Here is the outcome of running the Maui dotnet CLI instructions on a Mac. 

```
breynolds@*** GitHub % dotnet new maui -n MyApp

The template ".NET MAUI App" was created successfully.


breynolds@*** GitHub % cd MyApp 


breynolds@*** MyApp % ls

MyApp		MyApp.WinUI	MyApp.sln


breynolds@*** MyApp % dotnet restore

  Determining projects to restore...
**/usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: Windows is required to build Windows desktop applications.** [/Users/breynolds/GitHub/MyApp/MyApp.WinUI/MyApp.WinUI.csproj]


breynolds@*** MyApp % dotnet build -t:Run net6.0-ios

Microsoft (R) Build Engine version 17.0.0-preview-21378-03+d592862ed for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: net6.0-ios
```

**Comment by davidbritch** [comment]
Hi @breynolds 

The key instruction is: "In the .NET CLI, change directory to the single project and restore its dependencies:"

Your cd into MyApp brings you into the solution level folder. Do another cd MyApp to bring you into the single project. Then restore/build.
