### ISSUE TITLE
Modeless takes to modal navigation

### ISSUE THREAD

**Issue by stormbreakermerika** [dotnet/docs-maui#1337]
This bug is back in

_Originally posted by @stormbreakermerika in https://github.com/dotnet/docs-maui/issues/569#issuecomment-1459045550_
           I wasn't sure how to address this but clicking on the "For more information, see [Perform modeless navigation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/navigationpage?view=net-maui-6.0#perform-modal-navigation)."
           Link as pasted here it clearly points to the anchor tag for modal.  One of the two verbiages is wrong either the link or the verbiage. Thanks!

---
[Associated WorkItem - 69163](https://dev.azure.com/msft-skilling/Content/_workitems/edit/69163)

**Comment by davidbritch** [comment]
@stormbreakermerika Thanks for letting me know. I'll get it fixed today.

**Comment by stormbreakermerika** [comment]
No problem thanks!
