### ISSUE TITLE
Code of "Create a hyperlink" is not working

### ISSUE THREAD

**Issue by scegg** [dotnet/docs-maui#1342]
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label?view=net-maui-7.0#create-a-hyperlink

The command is never executed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 243e6d1d-a276-814f-7943-ff0fa7ba017e
* Version Independent ID: 243e6d1d-a276-814f-7943-ff0fa7ba017e
* Content: [Label - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label?view=net-maui-7.0#create-a-hyperlink)
* Content Source: [docs/user-interface/controls/label.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/label.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @scegg 

Afraid that this is due to product issues: https://github.com/dotnet/maui/issues/4734 and https://github.com/dotnet/maui/issues/8004

When those issues are fixed it'll work as per the docs.
