### ISSUE TITLE
iOS service extensions

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1343]
Add content on how to add an iOS service extension to a MAUI project. This is supported, but there's no project template for it. Instead, it'll require re-using the project file created by the Xamarin.iOS template and porting it to MAUI.

https://github.com/dotnet/maui/issues/8299

https://learn.microsoft.com/en-us/xamarin/ios/platform/extensions
https://learn.microsoft.com/en-us/xamarin/ios/platform/extensions-with-xamarinforms

---
[Associated WorkItem - 82661](https://dev.azure.com/msft-skilling/Content/_workitems/edit/82661)

**Comment by mattleibow** [comment]
This seems to be very nice too: https://github.com/dotnet/maui/discussions/3289

**Comment by davidbritch** [comment]
While it's possible to get this working, iOS extensions have so many rough edges in .NET 6/7 that I'll hold off doc'ing this until some work's been performed in this area.

Because this has been imported into QUEST, I'm going to close this issue and create a new one.

Replaced by https://github.com/dotnet/docs-maui/issues/1434

**Comment by ssbssb-cmd** [comment]
hi did anyone get this working? I need to create a Notification Service extension for iOS in a single project MAUI app

**Comment by skuzminov-softheme** [comment]
@ssbssb-cmd try this example https://github.com/exponea/bloomreach-maui-sdk/tree/master/ExamplePushServiceExtension 

Worked for me almost from the first try.
