### ISSUE TITLE
Not happy about this doc

### ISSUE THREAD

**Issue by balintn22** [dotnet/docs-maui#1348]
There's a disconnect between parts of the examples.
Get Started first one shows how to use (register DI services) for version tracking.
Check the Version uses a variable called VersionTracking, but it doesn't show how that was acquired. Assume it was constructor DI'ed.
That much about the doc itself.

There's another problem: when I implement the use based on the DI assumption above, I get the error "System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.Maui.ApplicationModel.IVersionTracking' while attempting to activate 'Waiter.Maui.Pages.About.AboutViewModel'.'"

My code
    public class AboutViewModel : BaseViewModel
    {
        public string AppVersion { get; private set; }
        
        public AboutViewModel(IVersionTracking versionTracking)
        {
            AppVersion = versionTracking.CurrentVersion;
        }
    }

    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseSharpnadoTabs(loggerEnable: true, debugLogEnable: true)
                .UseMauiCommunityToolkit()
                .ConfigureFonts(fonts =>
                {
                   ...
                })
                .ConfigureEssentials(essentials =>
                {
                    essentials.UseVersionTracking();
                });

            return builder.Build();
        }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b885023-7be3-04ef-36ac-57d57578b7cb
* Version Independent ID: 1b885023-7be3-04ef-36ac-57d57578b7cb
* Content: [Version tracking - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/version-tracking?view=net-maui-7.0)
* Content Source: [docs/platform-integration/appmodel/version-tracking.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/appmodel/version-tracking.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by balintn22** [comment]
Trying to fix my code I just found that VersionTracking is a static object, so no DI resolution needed,  but then there1s another problem with the doc:
"Check the version
The [IVersionTracking](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.applicationmodel.iversiontracking) interface provides many properties ..."
VersionTracking is actually a static object, maybe behind the documentation aiming for a more modern implementation?

**Comment by balintn22** [comment]
Fixing my code I found that no DI constructor injection is needed, VersionTracking is a static object, which means the doc is wrong here:

"Check the version
The [IVersionTracking](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.applicationmodel.iversiontracking) interface provides many properties ..."

which should read the VersionTracking static object.
Ofc it might be the case that the implementation will soon change to a more DI friendly version.

**Comment by davidbritch** [comment]
Hi @balintn22 

There's a bit of a story here.

In Xamarin.Essentials all functionality was accessed via static objects. There were no interfaces. In .NET MAUI, the static objects have been kept (for users migrating from Xamarin.Essentials and for those who prefer the simplicity of using them), and interfaces have been added to support DI. So it's a case of use one approach or the other.

As to the doc not making that clear, it's a fair point. The entire MAUI docset has so far not really touched upon DI, but it will be coming this year.

Hope this helps.

**Comment by davidbritch** [comment]
We now have a doc on DI in .NET MAUI: https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/dependency-injection?view=net-maui-8.0
