### ISSUE TITLE
Splash screen for UWP in MAUI

### ISSUE THREAD

**Issue by Sofiya2696** [dotnet/docs-maui#1351]
Currently, MAUI supports android and ios. But we need support for UWP. 

Can you please provide some solution for this ASAP?

 
    <MauiSplashScreen Include="Resources\Splash\splash_screen.svg"  Resize="false" Color="#C8C8C8" />

**Comment by davidbritch** [comment]
Hi @Sofiya2696 

This is because WinUI doesn't provide any support for splash screens. Once WinUI does, it can be added to .NET MAUI.
