### ISSUE TITLE
How can I handle the case when the website tries to open a new browser tab?

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/docs-maui#1355]
Currently my MAUI app simply does nothing when I click a button which opens a new tab using a browser.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ace91785-d304-f161-408e-34511fb75ce3
* Version Independent ID: ace91785-d304-f161-408e-34511fb75ce3
* Content: [WebView - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?view=net-maui-7.0&pivots=devices-ios)
* Content Source: [docs/user-interface/controls/webview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/webview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nicholasyin 

I'm not entirely sure what you're trying to do here. Can you elaborate?

**Comment by nicholasyin** [comment]
> Hi @nicholasyin
> 
> I'm not entirely sure what you're trying to do here. Can you elaborate?

Sorry about missing the details. I'm using a WebView control to display a remote website, where there's a button whose behavior on a web browser is to open a new tab to display an image. When using the WebView to view the website, clicking the button does nothing on an Android emulator. When running on Windows, clicking the button launches the web browser and displays the image correctly, though.

**Comment by davidbritch** [comment]
Hi @nicholasyin 

`WebView` on Android doesn't support tabs. That's not a .NET MAUI limitation - it's a limitation of Android's `WebView` control. So there's only really two solutions that spring to mind:

1. Add a bit of code that opens what you want to open in a new tab in the system browser instead.
1. Add a bit of code that replaces the content displayed in the WebView with the content that should be opening in a new tab.

Both are possible. (2) is less code than (1).

**Comment by nicholasyin** [comment]
> Hi @nicholasyin
> 
> `WebView` on Android doesn't support tabs. That's not a .NET MAUI limitation - it's a limitation of Android's `WebView` control. So there's only really two solutions that spring to mind:
> 
> 1. Add a bit of code that opens what you want to open in a new tab in the system browser instead.
> 2. Add a bit of code that replaces the content displayed in the WebView with the content that should be opening in a new tab.
> 
> Both are possible. (2) is less code than (1).

Thanks for the reply David.
I actually thought about solution 1. The problem is that I need to be able to capture the event when users click the link from inside the WebView control so that I can kind of cancel it and replace with the action to open the system browser, passing the URL.
I don't quite understand your solution 2 though.

**Comment by davidbritch** [comment]
Re: 1 - if I understand you correctly, it's something I was able to do. I wrote Android code to capture that a new tab needs to be opened, and opened it in the system browser instead.

Re: 2 - I wrote code that captured that a new tab needed to be opened, and just opened it in the current WebView. So effectively the existing page is replaced by the new page.

**Comment by nicholasyin** [comment]
Actually I think the bottleneck for both 1 & 2 solutions is the same, i.e. handling the 'new tab' event. Did you mean to write code using native Android, i.e. Java, or using C# in MAUI? Mind sharing if it's C#? I've no idea how to get notified of the action to open a new tab inside WebView.

**Comment by davidbritch** [comment]
It's native Android code in C#. I'll share a zip.

@nicholasyin 

[MyWebViewApp1.zip](https://github.com/dotnet/docs-maui/files/11060515/MyWebViewApp1.zip) - look at MauiProgram.cs. and Platforms/Android/MyWebChromeClient.

[MyWebViewApp2.zip](https://github.com/dotnet/docs-maui/files/11060517/MyWebViewApp2.zip) - look at MauiProgram.cs

**Comment by nicholasyin** [comment]
> It's native Android code in C#. I'll share a zip.
> 
> @nicholasyin
> 
> [MyWebViewApp1.zip](https://github.com/dotnet/docs-maui/files/11060515/MyWebViewApp1.zip) - look at MauiProgram.cs. and Platforms/Android/MyWebChromeClient.
> 
> [MyWebViewApp2.zip](https://github.com/dotnet/docs-maui/files/11060517/MyWebViewApp2.zip) - look at MauiProgram.cs

Thanks for sharing. Sorry about no update.
After trying both solutions, the second one indeed looks simpler. However, I can't navigate back to the previous page on the Android emulator.
