### ISSUE TITLE
Not enough information

### ISSUE THREAD

**Issue by Ramttid** [dotnet/docs-maui#1356]
I am trying to update/migrate my custom LabelRenderers/EntryRenderers etc and there is no real clear information to be found, in this example it is using View, not a Xamarin.Forms EntryRenderer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c787fde2-1c9c-62d4-2cdd-93681e0c1ff5
* Version Independent ID: c787fde2-1c9c-62d4-2cdd-93681e0c1ff5
* Content: [Use custom renderers in .NET MAUI - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/migration/custom-renderers?view=net-maui-7.0)
* Content Source: [docs/migration/custom-renderers.md](https://github.com/dotnet/docs-maui/blob/main/docs/migration/custom-renderers.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Ramttid 

You don't have a custom control (e.g. `MyEntry`) that your custom entry renderer uses?

**Comment by Ramttid** [comment]
Hello @davidbritch 

this is what my renderer does, I think this is easy to convert but not sure how to.

`
public class NumericEntryRenderer : EntryRenderer
    {
        public NumericEntryRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            if (Control != null)
            {
                Control.InputType = InputTypes.ClassNumber | InputTypes.NumberFlagDecimal;
            }
        }
    }
`

**Comment by davidbritch** [comment]
How do you consume that renderer in Xamarin.Forms?

**Comment by Ramttid** [comment]
I am not sure how to answer that, I think it works the way it works, this is a project I am working on, which I have to update to Maui but I have fixed my problem, thank you for your time.
` Microsoft.Maui.Handlers.EntryHandler.Mapper.AppendToMapping(nameof(NumericEntry), (handler, view) =>
            {
#if ANDROID
                handler.PlatformView.InputType = InputTypes.ClassNumber | InputTypes.NumberFlagDecimal;
#elif IOS
#endif`
