### ISSUE TITLE
Compatibility workload removed in .NET 8

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1357]
In .NET 8, the compatibility workload has been removed. It's still available as a separate NuGet that users will have to install.

Any docs that use the Compatibility namespace (Microsoft.Maui.Controls.Compatibility) will need a note adding to specify the above.

---
[Associated WorkItem - 164941](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164941)

**Comment by MartyIX** [comment]
It would be very helpful to know whether one needs to specify both:

```xml
  <!-- Dotnet MAUI -->
  <PackageVersion Include="Microsoft.Maui.Controls" Version="..." />
  <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="..." />
```

in a new .NET 8 project or whether it is recommended to include only the first one:

```xml
  <!-- Dotnet MAUI -->
  <PackageVersion Include="Microsoft.Maui.Controls" Version="..." />
```

**Comment by davidbritch** [comment]
Hi @MartyIX 

Not sure if I'm missing your point here, but you'd only need to specify `Microsoft.Maui.Controls.Compatibility` in .NET 8 if your code uses anything from that namespace.

**Comment by davidbritch** [comment]
I'd guess you're asking because of: https://github.com/dotnet/maui/pull/14567

I'm investigating internally.

**Comment by MartyIX** [comment]
@davidbritch I'm asking mostly because the two lines are in the template: https://github.com/dotnet/maui/blob/dec8b249fb8d135605dc71bebb4382b9aa63ecd5/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L59-L60 and then I was not too sure what the compatibility package was about. 

Now I understand that it's a sort of optional package I might or might not use, right?

**Comment by davidbritch** [comment]
Correct. It's been present since MAUI's first release. Essentially, if you aren't writing code that uses the `Microsoft.Maui.Controls.Compatibility` namespace, then you aren't using it. It includes `RelativeLayout` (https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/LegacyLayouts/RelativeLayout.cs), and versions of the layouts that behave as they did in Forms. But generally it's use is discouraged, hence it's meant to be becoming an optional package in .NET 8.

**Comment by davidbritch** [comment]
Despite original intentions, the Compatibility NuGet will be implicitly referenced in .NET 8, because VS depends on the assembly being loaded for Live Visual Tree. For more info see https://github.com/dotnet/maui/pull/13427

Eventually, the NuGet won't be implicitly referenced, but for now it is.

I'll leave this issue open until .NET 8 ships, so I can double check before doc'ing this.

**Comment by davidbritch** [comment]
No action required. The project template references this NuGet package.
