### ISSUE TITLE
Running MAUI on Windows?

### ISSUE THREAD

**Issue by mevanecek** [dotnet/docs-maui#136]
I don't need instructions on starting MAUI in an Android Emulator. I need to know how to start it on my Windows 10 desktop, from the Visual Studio debugger. There doesn't seem to be a way in VS 2022, so y'all need to provide some instructions here. I don't seen anything on the Run dropdown, and when I try to run the project, I get a Setup Hot Restart dialog. What's that about?

![image](https://user-images.githubusercontent.com/17767725/130493973-e6ff5934-7dbc-4a2e-8d3b-b3131d24709e.png)

![image](https://user-images.githubusercontent.com/17767725/130494006-27e02e9b-ec7b-4d8d-9915-117ac4f7af5c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mevanecek 

To run on WinUI you need to set the WinUI project as the startup project (right-click on the project and select the correct menu option). Then hit the run button as normal.

However, deployment to Windows is broken in Preview 7 so it won't run your app. The workaround right now is to build/deploy your WinUI app. Then run it from the Start menu. Then attach the debugger in VS if you want to debug your code.
