### ISSUE TITLE
The program cannot save New note because the filename is not generated yet.

### ISSUE THREAD

**Issue by ghkamfung** [dotnet/docs-maui#1366]
[Enter feedback here]
Throw null object reference exception when save a new note.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 112517e9-4e69-a13d-61d0-9ae41818ca27
* Version Independent ID: 112517e9-4e69-a13d-61d0-9ae41818ca27
* Content: [Tutorial: Use the MVVM toolkit to update the Notes app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-mvvm/?view=net-maui-7.0&tutorial-step=8&source=docs)
* Content Source: [docs/tutorials/notes-mvvm/index.yml](https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-mvvm/index.yml)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 82658](https://dev.azure.com/msft-skilling/Content/_workitems/edit/82658)

**Comment by davidbritch** [comment]
At what point in the tutorial does this happen?

**Comment by ghkamfung** [comment]
Click +
And click "Save".

In earlier tutorial, it call a function that generates random file name.

在 2023年4月4日週二 22:52，David Britch ***@***.***> 寫道：

**Comment by davidbritch** [comment]
I tried the solution from the end of the tutorial, and no exception was thrown.

**Comment by ghkamfung** [comment]
I added in Models\Note.cs line 13 in order to work.
        if (Filename==null)
        {
            //New note
            Filename = $"{Path.GetRandomFileName()}.notes.txt";
        }

![image](https://user-images.githubusercontent.com/3148377/230044040-bbee6c23-bc3e-44c6-9c17-8eb7b2e4f6b8.png)

**Comment by davidbritch** [comment]
Hi @ghkamfung 

What I'm trying to establish is at what point in the tutorial do you hit this issue? I can't repro it in the solutions the tutorial links to.
