### ISSUE TITLE
DisplayPromptAsync

### ISSUE THREAD

**Issue by rpalik** [dotnet/docs-maui#1367]
Note: DisplayPromptAsync does not work if the keyboard is set to numeric and the phone uses a localization other than English.

Please add this note to the page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 144c1b04-ddfc-e59b-773f-94124fbbce7a
* Version Independent ID: 144c1b04-ddfc-e59b-773f-94124fbbce7a
* Content: [Display pop-ups - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pop-ups?view=net-maui-7.0)
* Content Source: [docs/user-interface/pop-ups.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pop-ups.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Afraid this is a bug (https://github.com/dotnet/maui/issues/11865), rather than a feature by design, that's waiting for the product team to fix.
