### ISSUE TITLE
XA5301 when building

### ISSUE THREAD

**Issue by WinBase** [dotnet/docs-maui#137]
Hi

i created a new MAUI project to have a look, understand some things are broken in preview 7, but thought it try use the advice on deploying to test, but when i compile i get the following - i have not made any changes to the default project and running Maui-check from the command line says all is ok.

also anything that is to do with android, i,e options, device manager gives errors like xamarinshellpackage package did not load correctly.

regards

Bob

Failed to generate Java type for class: AndroidX.Core.View.Accessibility.AccessibilityManagerCompat/IAccessibilityStateChangeListenerImplementor due to MAX_PATH: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\info\AppData\Local\Microsoft\VisualStudio\17.0_7ac5513b\Settings\PCS\Apps\MauiApp1\MauiApp1\MauiApp1\obj\Debug\net6.0-android\android\src\mono\androidx\core\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)   at Microsoft.Android.Build.Tasks.Files.CopyIfStreamChanged(Stream stream, String destination) in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 170   at Xamarin.Android.Tasks.GenerateJavaStubs.CreateJavaSources(IEnumerable`1 javaTypes, TypeDefinitionCache cache)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=windows)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @WinBase 

Looking at the exception, it looks like you've hit a path length issue due to creating your app in C:\Users\info\AppData\Local\Microsoft\VisualStudio\17.0_7ac5513b\Settings\PCS\Apps. I'd recommend creating your app (MauiApp1) in this case nearer to the root of your drive.

**Comment by WinBase** [comment]
Yes thanks David for the quick reply

i just took the defaults and got this error, but when i change to create it under my data drive D:\evaluation folder it compiles but i still have a plethora of other issues that mean i cant test android emulator for example, i have found things where the 'no impact on existing versions' (such as vs2019) just isnt true, i know about testing winui being broken on preview 7 without deploying, Ive reported a few issues ive found on the developer feedback this morning, but am shelving looking at maui & vs2022 atm, it's just too buggy im afraid and looks like the developers do little testing before releases & want us to do their job for them, which i dont have time to do, and im afraid a live working release that i can use for production or even evaluating the simplest Maui app seems a long way off atm. i know it's pre-release and evaluation, but still...

GL and thanks anyway

Bob
