### ISSUE TITLE
Great Instructions!

### ISSUE THREAD

**Issue by oducille** [dotnet/docs-maui#138]
[Enter feedback here]

These instructions were clear, concise, to the point and effective! In other words, spot on!  Believe it or not, that's rare in this industry of constant change that breaks instructions intended to install, update or fix an issue.

I only wish that the instructions for fixing the HTML 403.1 error were that effective!

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
See https://github.com/dotnet/docs-maui/issues/138
