### ISSUE TITLE
Publish command needs additional information

### ISSUE THREAD

**Issue by RodBarnes** [dotnet/docs-maui#1384]
As shown, the publish command:
`dotnet publish -f:net7.0-android -c:Release /p:AndroidSigningKeyPass=mypassword /p:AndroidSigningStorePass=mypassword`

While only an example, still leaves the user confused because this command will fail with the error of not being able to fine the `net7.0-android` release.  The docs need to inform the user that the actual format is something like `net7.0-androidNN.N` where the `NN.N` is the API version and subversion, and the actual name will be the folder of that found under `./bin/Release` for the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6c3b8a-6109-5ad5-ca05-fdaae8a9d66e
* Version Independent ID: 6b6c3b8a-6109-5ad5-ca05-fdaae8a9d66e
* Content: [Use the CLI to publish for Android - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-cli?view=net-maui-7.0)
* Content Source: [docs/android/deployment/publish-cli.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/publish-cli.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 89018](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89018)

**Comment by davidbritch** [comment]
> While only an example, still leaves the user confused because this command will fail with the error of not being able to fine the `net7.0-android` release. The docs need to inform the user that the actual format is something like `net7.0-androidNN.N` where the `NN.N` is the API version and subversion, and the actual name will be the folder of that found under `./bin/Release` for the project.

Afraid that's not the case. I've published many Android apps using `net7.0-android`, which is the recommendation. Using `net7.0-android` automatically picks the default for you, which is currently `net7.0-android33.0`.

**Comment by RodBarnes** [comment]
> > While only an example, still leaves the user confused because this command will fail with the error of not being able to fine the `net7.0-android` release. The docs need to inform the user that the actual format is something like `net7.0-androidNN.N` where the `NN.N` is the API version and subversion, and the actual name will be the folder of that found under `./bin/Release` for the project.
> 
> Afraid that's not the case. I've published many Android apps using `net7.0-android`, which is the recommendation. Using `net7.0-android` automatically picks the default for you, which is currently `net7.0-android33.0`.

Interesting.  I'll try again; maybe things have changed.  All I can tell you is this is the error I get if I do NOT explicitly use the 33.0

![image](https://github.com/dotnet/docs-maui/assets/3944607/0d49e0be-e68f-4f01-b7ae-49cdad8f8914)
