### ISSUE TITLE
Missing .NET MAUI templates in VS 2022 preview

### ISSUE THREAD

**Issue by oducille** [dotnet/docs-maui#139]
After following instructions that were clear, concise, to the point and supposedly effective!

The DotNet Maui templates do not show up after loading Visual Studio 2022 and attempting to create a new project! 
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @oducille 

I've just created a VM, installed VS2022 Preview 3, and .NET 6 Preview 7 (using maui-check) and I get MAUI templates in VS2022, and the created project builds and runs. Afraid you most likely have an installation issue.

**Comment by oducille** [comment]
Thank you David,

I don't know how long you've been at this. But, there's one thing I've
learned
over the 40 years that I've been in this business: Just because you can't
reproduce the problem on your end doesn't preclude its existence on my end.
Knowing that will serve you very well in the troubleshooting world.

I will update to preview 4.1 and try again.

Thanks for all you do

Oliver

**Comment by davidbritch** [comment]
Hi @oducille 

Hopefully you'll have better luck with VS 2022 Preview 4.1. If you don't have any luck, you'll need to log an issue with the [product](https://developercommunity.visualstudio.com).

**Comment by oducille** [comment]
Good! Thank you much!
