### ISSUE TITLE
Make common markup extensions more easy to find

### ISSUE THREAD

**Issue by Foda** [dotnet/docs-maui#1398]
Hello!

I'd like to make a suggestion/propose that we modify our docs to increase the visibility of the [built-in markup extensions](https://learn.microsoft.com/en-us/dotnet/maui/xaml/markup-extensions/consume?view=net-maui-7.0)

One of the difficulties I faced when making a MAUI app was: "how do I modify my XAML to respond to different platforms or form factors?" Unfortunately, our docs make this answer difficult to find as it's under a page titled "Consume Markup Extensions" rather than something like "Use platform idioms in XAML" or "[Responsive design techniques](https://learn.microsoft.com/en-us/windows/apps/design/layout/responsive-design)" (this is a really great example of a documentation page BTW, +10 points for the animations). You'd have to first know what a markup extension is, and then know that's the way to modify your XAML to respond to different platforms.

Maybe we add the page under "Platforms" that contains the docs for `OnPlatform` and `OnIdiom`?

Another example of how we could make these easier to find would be to move the `FontImage` extension to the `Image` control page.

---
[Associated WorkItem - 85565](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85565)

**Comment by davidbritch** [comment]
Hi @Foda 

Thanks for the suggestion. Moving it to under Platforms seems like a good idea.
