### ISSUE TITLE
Edit for RuntimeIdentifier in MacCatalyst Publishing to App Store

### ISSUE THREAD

**Issue by dustin-wojciechowski** [dotnet/docs-maui#1399]
Where RuntimeIdentifier is specified int a table, the following is described:

"The runtime identifier (RID) for the project. Release builds of .NET MAUI Mac Catalyst apps default to using maccatalyst-x64 and maccatalyst-arm64 as runtime identifiers, to support universal apps. To support only a single architecture, specify maccatalyst-x64 or maccatalyst-arm64."

This is incorrect, as Apple will return the error upon publishing:
`Invalid bundle. The bundle supports arm64 but not Intel-based Mac computers. Your build must include the x86_64 architecture to support Intel-based Mac computers.`

Targeting x64 by itself will work, but selecting arm64 by itself will not. Therefore, this entry will be the ideal when addressing both:
`<RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers>`

For reference, we made this change within Xamarin-macios: [here.](https://github.com/xamarin/xamarin-macios/issues/15620)

---
[Associated WorkItem - 83780](https://dev.azure.com/msft-skilling/Content/_workitems/edit/83780)

**Comment by davidbritch** [comment]
Hey @dustin-wojciechowski 

Thanks for the issue. I get that there's an update to be made. To clarify though, AFAIK `<RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers>` isn't required as this is the default for release builds. So the doc update is probably to say that you can target x64 by itself, but not arm64 by itself.

**Comment by dustin-wojciechowski** [comment]
@davidbritch I would normally agree, but it looks like a user said this was necessary to add for a MAUI Blazor when uploading via transporter:

"rejected when trying to upload with Transporter: `Invalid bundle. The bundle supports arm64 but not Intel-based Mac computers. Your build must include the x86_64 architecture to support Intel-based Mac computers.` A commented section in `csproj` that the developer could un-comment would be helpful here: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers>"

This was from a list of issues with MacCatalyst found [here.](https://github.com/dotnet/maui/issues/12293) I have not tried uploading an app with transporter but looks like a couple people have approached this. We've added a comment to our Xamarin-ios templates for MacCatalyst as well: [here](https://github.com/xamarin/xamarin-macios/blob/4621cf219e166655d80d65cda939c662b56335c0/dotnet/Templates/Microsoft.MacCatalyst.Templates/maccatalyst/csharp/MacCatalystApp1.csproj#L4)

**Comment by davidbritch** [comment]
@dustin-wojciechowski I uploaded to the Mac App Store last month, via Transporter, without specifying RuntimeIdentifiers, and it was a universal binary. So I guess it's been fixed since last year.

**Comment by dustin-wojciechowski** [comment]
@davidbritch Ah good to know, thank you! I'll make an update to the main issue about that.
