### ISSUE TITLE
Workload installation failed for  `dotnet workload install maui`

### ISSUE THREAD

**Issue by tohidazizi** [dotnet/docs-maui#140]
Executing `dotnet workload install maui` (in Powershell, admin mode) exits with the error 'Workload installation failed, rolling back installed packs...'.

**Details:**
`dotnet workload install maui`

> Updated advertising manifest microsoft.net.sdk.android.
> Updated advertising manifest microsoft.net.sdk.maui.
> Updated advertising manifest microsoft.net.sdk.macos.
> Updated advertising manifest microsoft.net.sdk.maccatalyst.
> Updated advertising manifest microsoft.net.sdk.ios.
> Updated advertising manifest microsoft.net.workload.emscripten.
> Updated advertising manifest microsoft.net.sdk.tvos.
> Updated advertising manifest microsoft.net.workload.mono.toolchain.
> Installing pack Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Core.Runtime.android version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.Maui.Core.Runtime.android version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Controls.Ref.android version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.Maui.Controls.Ref.android version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.Maui.Controls.Runtime.android version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Essentials.Ref.android version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.Maui.Essentials.Ref.android version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Essentials.Runtime.android version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.Maui.Essentials.Runtime.android version 6.0.100-preview.7.1345...
> Installing pack Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Dependencies version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.Maui.Dependencies version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Controls.Sdk version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.Maui.Controls.Sdk version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Extensions version 6.0.100-preview.7.1345...
> Writing workload pack installation record for Microsoft.Maui.Extensions version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Resizetizer.Sdk version 6.0.100-preview.7.1345...
> _Workload installation failed, rolling back installed packs..._
> Uninstalling workload pack Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1345.
> Uninstalling workload pack Microsoft.Maui.Core.Runtime.android version 6.0.100-preview.7.1345.
> Uninstalling workload pack Microsoft.Maui.Controls.Ref.android version 6.0.100-preview.7.1345.
> Uninstalling workload pack Microsoft.Maui.Controls.Runtime.android version 6.0.100-preview.7.1345.
> Uninstalling workload pack Microsoft.Maui.Essentials.Ref.android version 6.0.100-preview.7.1345.
> Uninstalling workload pack Microsoft.Maui.Essentials.Runtime.android version 6.0.100-preview.7.1345.
> Uninstalling workload pack Microsoft.AspNetCore.Components.WebView.Maui version 6.0.100-preview.7.1345.
> Uninstalling workload pack Microsoft.Maui.Dependencies version 6.0.100-preview.7.1345.
> Uninstalling workload pack Microsoft.Maui.Controls.Sdk version 6.0.100-preview.7.1345.
> Uninstalling workload pack Microsoft.Maui.Extensions version 6.0.100-preview.7.1345.
> Rolling back pack Microsoft.Maui.Core.Ref.android installation...
> Rolling back pack Microsoft.Maui.Core.Runtime.android installation...
> Rolling back pack Microsoft.Maui.Controls.Ref.android installation...
> Rolling back pack Microsoft.Maui.Controls.Runtime.android installation...
> Rolling back pack Microsoft.Maui.Essentials.Ref.android installation...
> Rolling back pack Microsoft.Maui.Essentials.Runtime.android installation...
> Rolling back pack Microsoft.AspNetCore.Components.WebView.Maui installation...
> Rolling back pack Microsoft.Maui.Dependencies installation...
> Rolling back pack Microsoft.Maui.Controls.Sdk installation...
> Rolling back pack Microsoft.Maui.Extensions installation...
> Rolling back pack Microsoft.Maui.Resizetizer.Sdk installation...
> Writing workload pack installation record for Microsoft.Maui.Resizetizer.Sdk version 6.0.100-preview.7.1345...
> Installing pack Microsoft.Maui.Templates version 6.0.100-preview.7.1345...
> _Workload installation failed: The transaction has aborted._
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tohidazizi 

I'm just updating the installation instructions. `dotnet workload install maui` is no longer required. Instead, `maui-check` installs everything you need.
