### ISSUE TITLE
[Customize Controls] Remove Android Entry example does not work

### ISSUE THREAD

**Issue by juansturla** [dotnet/docs-maui#141]
The "Remove Android Entry underline" is a great example, but it's not working

I wish I could correct it, but I can't find the working class.

Error: "The type 'Entry' does not exist in the namespace 'Android.Views' "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6
* Version Independent ID: 70227b04-808f-1370-186b-10cfef525959
* Content: [.NET MAUI control customization with handlers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize)
* Content Source: [docs/user-interface/handlers/customize.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @juansturla 

It worked in Preview 4, but doesn't any longer. I'll update the doc today, but the solution is:

```
handler.NativeView.SetBackgroundColor(Colors.Transparent.ToNative());
```

This works because the underline is something called an Android drawable, that's set as the background of the control.

**Comment by davidbritch** [comment]
Forgot to add that you'll need to add:

```
using Microsoft.Maui.Graphics;
```
