### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by losh99** [dotnet/docs-maui#1411]
Only app package examples are given for Android and iOS, why not Windows? I came here trying to understand an error I'm getting for Windows:

DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(34,27): error 0x80070002: Cannot install or update package cefe1a18-fa2b-4550-8cae-4060b375dc07_9zz4h110yvjzm because the splash screen image [splashSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found.

This article is yet another example of MAUI dropping support for the Windows platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc
* Version Independent ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc
* Content: [Add a splash screen to a .NET MAUI app project - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?view=net-maui-7.0&tabs=android)
* Content Source: [docs/user-interface/images/splashscreen.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/splashscreen.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @losh99 

Afraid there's no concept of a splash screen in WinUI.
