### ISSUE TITLE
Step 2 of Creating a distribution ticket appears wrong for VS

### ISSUE THREAD

**Issue by DanTravison** [dotnet/docs-maui#1412]
I'm using VS 2022 17.4.4 and 17.6.0 Preview 2.0 and in neither version is there a 'View Details' option.

There is an Add and Remove button to add or remove an account, but once the account is added, selecting it shows the Apple Id, Issuer, and Key.  There is no option to view details.

I'm referring to the Visual Studio under 'To create a distribution certificate' 

2: In the Apple Developer Accounts dialog, select a team and click the View Details... button.

I see the same issue with both versions of Visual Studio, 17.4.4 and 17.6.0 Preview 2.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7ee5865-403a-3d47-ce50-69f42c5d012b
* Version Independent ID: d7ee5865-403a-3d47-ce50-69f42c5d012b
* Content: [Publish a .NET MAUI iOS app for App Store distribution - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-app-store?view=net-maui-7.0&tabs=vs)
* Content Source: [docs/ios/deployment/publish-app-store.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/deployment/publish-app-store.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @DanTravison 

I guess you'll be using an individual account, due to the presence of issuer and key data.

What you should see is a Team box below the issuer/key data that lists your Team and role. When you select the Team the View Details button enables.

![Capture](https://user-images.githubusercontent.com/8092460/231413860-68678662-5716-4170-9ed6-a9b265d3deca.PNG)

You may need to resize your dialog to see all this.

**Comment by DanTravison** [comment]
I do not have a 'View Details' button when selecting the team.

I've see the same problem with the following Visual Studio versions:

* Preview 2, Preview 3
* 17.5.4 (Community) and the previous version.
* 17.5.4 (Enterprise) and the previous version.

Yes, I am using an individual account.

**Comment by davidbritch** [comment]
Hi @DanTravison 

It'll either be an account setup problem with your Apple Developer Account, or a product bug. If it's a product bug, it needs logging in [Developer Community]()https://developercommunity.visualstudio.com/home.
