### ISSUE TITLE
Picker text color not working for windows

### ISSUE THREAD

**Issue by dzuris** [dotnet/docs-maui#1423]
I am creating C# .net maui 7.0 app.

When I change TextColor of Picker to something like Red it is changing back to default color when I hover over the element with mouse on windows 11. 

I am starting the app using visual studio enterprise 2022 in debug.

**Comment by davidbritch** [comment]
Hi @dzuris 

Afraid that this needs reporting in the [engineering repo](https://github.com/dotnet/maui) so that the engineers can investigate. Thanks!
