### ISSUE TITLE
No explanation if "Publish" is grayed out

### ISSUE THREAD

**Issue by SuschNL** [dotnet/docs-maui#1437]
On all the systems our developers have here, the "Publish" option in VS2022 is grayed out for a .NET Maui app, so all of this documentation is useless. Attempting to build an installer via the command line just created unending issues with "certificates".

The installation process for a .NET Maui app is impossible to get working. No one will adopt this technology if it is this hard to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9a8421b-ca5d-96e3-35ab-60118e356017
* Version Independent ID: a9a8421b-ca5d-96e3-35ab-60118e356017
* Content: [Publish a .NET MAUI app to a folder for Windows - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-visual-studio-folder?view=net-maui-7.0)
* Content Source: [docs/windows/deployment/publish-visual-studio-folder.md](https://github.com/dotnet/docs-maui/blob/main/docs/windows/deployment/publish-visual-studio-folder.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SuschNL 

Afraid all I can do is recommend you log an issue at [Visual Studio Developer Community](https://developercommunity.visualstudio.com/home), where it'll be picked up by the product team for investigation. Thanks!
