### ISSUE TITLE
Copy-paste error

### ISSUE THREAD

**Issue by DanielMuhlig** [dotnet/docs-maui#1441]
1. Under the "Launch the app on a device" step 5 says "In Terminal, build the app and run it on your chosen simulator...". This should probably say "physical device" instead of "chosen simulator"

2. Is the command in step 5 correct? The -p options "insert_UDID_here" is that the device Identifier?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da0a1dce-0ab0-7d18-8dc9-e37854995ace
* Version Independent ID: da0a1dce-0ab0-7d18-8dc9-e37854995ace
* Content: [Build an iOS app on macOS with .NET CLI - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/ios/cli?view=net-maui-7.0)
* Content Source: [docs/ios/cli.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/cli.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 86025](https://dev.azure.com/msft-skilling/Content/_workitems/edit/86025)

**Comment by davidbritch** [comment]
Hi @DanielMuhlig 

Thanks for pointing out the mistake. I'll get it fixed, and yes, "insert_UDID_here" means the device identifier you copied to the clipboard. I'll also clarify that.
