### ISSUE TITLE
DataBinding: Mention BindingList in addition to ObservableCollection

### ISSUE THREAD

**Issue by shadowfoxish** [dotnet/docs-maui#1445]
[Enter feedback here]

Would be useful to include instruction or at least a mention of BindingList<T> type as an alternative to ObservableCollection<T>. 

This block of text is mentioned after ObservableCollection<T>, however, OC does not propagate individual property changed events, only collection related events:

> If properties of the items themselves change during runtime, then the items in the collection should implement the INotifyPropertyChanged interface and signal changes to property values using the PropertyChanged event.

A more expanded example of why you might want to use BindingList<T> is below; I'm binding a list of objects that themselves change, and the container for that list needs to update some sort of summary state:

```cs
public class MyViewModel : INotifyPropertyChanged
{
	/*INotifyPropertyChangedImlementation here*/
	
	//Note; FancyItem implements INotifyPropertyChanged and the view binds to properties in it.
	private BindingList<FancyItem> items;

	public BindingList<FancyItem> Items
	{
		get
		{
			return items;
		}
		set
		{
			items = value;
			PropertyChanged(nameof(Items));
		}
	}

	private async Task Initialize()
	{
		try
		{
			if (this.Items != null)
			{
				this.Items.ListChanged -= Items_ListChanged;
			}
			this.Items = new BindingList<FancyItem>(/*Get FancyItems somehow*/);
			this.Items.ListChanged += Items_ListChanged;
		}
		catch (Exception ex)
		{
			/* Exception Handling*/
		}
		finally
		{
			/* Additional Init cleanup */
		}
	}

	private void Items_ListChanged(object sender, ListChangedEventArgs e)
	{
		PropertyChanged(nameof(AllGood));
	}

	//This determines if all the things in the list satisfy some condition 
	public bool AllGood
	{
		get
		{
			return this.Items?.All(f => /*some accessor to check if good*/) ?? false;
		}
	}
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67eff20e-d00f-c29c-c025-eb12f523acd1
* Version Independent ID: 67eff20e-d00f-c29c-c025-eb12f523acd1
* Content: [Data binding basics - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/data-binding-basics?view=net-maui-7.0)
* Content Source: [docs/xaml/fundamentals/data-binding-basics.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/fundamentals/data-binding-basics.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 92646](https://dev.azure.com/msft-skilling/Content/_workitems/edit/92646)

**Comment by davidbritch** [comment]
Hi @shadowfoxish 

Thanks for the suggestion. I'll take a proper look at this next sprint (May).

**Comment by davidbritch** [comment]
Hi @shadowfoxish 

After chatting to the product team, we've decided not to go ahead with mentioning `BindingList`. While it offers more functionality than `ObservableCollection`, and is ok in small lists, it just doesn't scale well and so doesn't offer good performance - particularly on mobile. This is why it isn't mentioned in conceptual docs for any .NET products.
