### ISSUE TITLE
How to participate in translating?

### ISSUE THREAD

**Issue by ryuujo1573** [dotnet/docs-maui#145]
May I commit a new file named {origin}.zh-CN.md as translation?
I am looking forward in helping things out.
If it is convenient for you, to add a button like "Contribute a translation" would help~
thanks!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f62c6f63-7e33-d81d-28db-b9ba40919408
* Version Independent ID: e3bf5b48-ed62-c664-1c33-294c0e762e57
* Content: [.NET MAUI app startup - .NET MAUI](https://docs.microsoft.com/zh-cn/dotnet/maui/fundamentals/app-startup)
* Content Source: [docs/fundamentals/app-startup.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/app-startup.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ryuujo1573 

Unfortunately, not yet. Localization isn't enabled on this repo yet. It's a process I've set in motion last week.

**Comment by ryuujo1573** [comment]
Thank you for your reply.
I am keen on contributing CN&JP localization, so.. if it is acceptable please `@ryuujo1573` at ease.
have a nice day :)

**Comment by juansturla** [comment]
I would love to contribute on localization too
In my case it would be translation to Spanish :)

**Comment by davidbritch** [comment]
Localization is now enabled on the docset.

**Comment by F-Unction** [comment]
But how to participate in it? There's no "Edit" button in localized document page.

**Comment by davidbritch** [comment]
Hi @F-Unction 

It used to be possible in the past, but the localization workflow has changed over the last few years and apparently it's no longer possible. I've been told that "we don't accept external translation" for all kinds of reasons that include "we cant' maintain the localised content when the English content is updated".

Apologies to be the bearer of bad news, but this is out of my hands.

**Comment by F-Unction** [comment]
OK, thank you.
