### ISSUE TITLE
MacCatalyst Publishing Provisioning

### ISSUE THREAD

**Issue by dustin-wojciechowski** [dotnet/docs-maui#1454]
We believe that users are having their MacCatalyst apps crash because of an issue with their provisioning profiles.
We noticed that users were getting this error when they had selected MacCatalyst in the tutorial steps [here](https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/deployment/publish-outside-app-store?view=net-maui-7.0#create-a-provisioning-profile)

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/../MonoBundle/libSystem.IO.Compression.Native.dylib
Referenced from: <DDE3A74F-055E-3EE1-94C5-8E5120BB0680> /Applications/ididit.today.app/Contents/MacOS/ididit.today
Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@executable_path/../MonoBundle/libSystem.IO.Compression.Native.dylib' (no such file), '/usr/lib/libSystem.IO.Compression.Native.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)
```

We had initially recommended a workaround in code for this but it only worked for a couple users and not all of them. But I could confirm this issue when submitting my own application through TestFlight. When I created a new Provisioning Profile, and changed the Platform Type to MacOS, that worked successfully.

We have an issue currently open for this in the Xamarin-ios repo, but a solution isn't immediately clear.

In the meanwhile, I propose a note/warning blurb that recommends using the MacOS PlatformType, and adjusting the screen captures to select the correct os.

---
[Associated WorkItem - 91423](https://dev.azure.com/msft-skilling/Content/_workitems/edit/91423)

**Comment by davidbritch** [comment]
Hi @dustin-wojciechowski 

I'm a bit confused. The doc you've linked to is about publishing outside the Mac App Store, but I'm wondering if you're referring to publishing to the Mac App Store?

**Comment by davidbritch** [comment]
Action: update https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/deployment/?view=net-maui-7.0 to specify the use of a Mac profile, or add the following to the .csproj:

```
<_LibMonoLinkMode>Static</_LibMonoLinkMode>
<_LibXamarinLinkMode>Static</_LibXamarinLinkMode>
```

More info: https://github.com/dotnet/maui/issues/12293#issuecomment-1542645567
