### ISSUE TITLE
FlyoutPage code example missing from the maui-samples project

### ISSUE THREAD

**Issue by dmanning23** [dotnet/docs-maui#1455]
The code example from the FlyoutPage documentation is not included in the maui-samples repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86a77021-9359-304a-5d49-a4feadf2f8fb
* Version Independent ID: 86a77021-9359-304a-5d49-a4feadf2f8fb
* Content: [FlyoutPage - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage?view=net-maui-7.0)
* Content Source: [docs/user-interface/pages/flyoutpage.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pages/flyoutpage.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 89019](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89019)

**Comment by davidbritch** [comment]
I've added the sample to the maui-samples repo. Once it's run through the build process, which can take up to 24 hours, I'll add a sample link to the page.
