### ISSUE TITLE
Unable to Define the cross-platform API: "Partial method must have an implementation" when targeting .Net 7

### ISSUE THREAD

**Issue by aarcoraci** [dotnet/docs-maui#1457]
[Enter feedback here]

Although the sample code does work when I try to write my own APIs I cannot define partial methods with modifiers or with a return type other than void. The Error I get is:

**Partial method 'XXXXXXX' must have an implementation part because it has accessibility modifier.**

I've gone over the documentation a couple of times but I'm not being able to determine what am I missing. At this point I think this has to be some sort of configuration or environment thing.

My current setup:
Visual Studio for mac (17.5.4 (build 8)) creating a MAUI class library. I'm using net7

**New Findings**

I updated the csproj file matching the one from the sample code and now I'm being able to correctly define cross platform APIs (in other words have public partial methods with diverse return types).

I changed:
```
<TargetFrameworks>net7.0;net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
```

to:
```
<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net6.0-windows10.0.19041.0</TargetFrameworks>
```

I think the problem is the default target for MAUI is .net7 and this is very confusing since it seems cross platform APIs are not supported or bugged.

**New Findings 2.0**
removing the targets net7.0 and net7.0-maccatalyst (and unloading and reloading the project) has solved my issue but I'm not sure if I should remove this issue since the MAUI class library enables this by default and people may run into the same problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Version Independent ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Content: [.NET MAUI invoking platform code - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code?view=net-maui-7.0)
* Content Source: [docs/platform-integration/invoke-platform-code.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/invoke-platform-code.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @aarcoraci 

Sounds like either (1) a problem with your .NET 7 install, or (2) something somewhere in your project was already using .NET 6, or (3) a problem with VSMac. Rest assured that what you're trying to do is supported and works in .NET 7 (I'm in the process of updating all the samples to .NET 7 and just tried it in VSMac and it worked fine).
