### ISSUE TITLE
xmlns don't work

### ISSUE THREAD

**Issue by HossamTash** [dotnet/docs-maui#1459]
I use  .NET MAUI ,I have used xmlns many times before, but suddenly xmlns stops recognizing its classes and their properties.
I am still a student, and  I am learning from Microsoft documentation this issue appears in the' behavior document' 
the code is
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
xmlns:local="clr-namespace:HossamTest1.behaviorsfolder"
             x:Class="HossamTest1.BehaviorPage"
             Title="BehaviorPage"
     
>
    <StackLayout >
        <Entry Placeholder="behavior" local: NumericBehaviorValidation.NumricValidation/>

    </StackLayout>
</ContentPage>
..........................................................
This issue repeated all over the projects, not only this project.
the code in NumericBehaviorValidation class is
.......................................................
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HossamTest1.behaviorsfolder
{
    public static class NumericBehaviorValidation
    {
        public static readonly BindableProperty NumricValidationProperty =
                    BindableProperty.CreateAttached("NumricValidation",typeof(bool),typeof(NumericBehaviorValidation),false,propertyChanged:OnValidation );
        public static bool getNumricValidationProperty(BindableObject view)
        {
            return (bool)view.GetValue(NumricValidationProperty);
        }
        public static void setNumricValidationProperty(BindableObject view,bool value)
        {
            view.SetValue(NumricValidationProperty,value);
        }
        public static void OnValidation(BindableObject view, object  oldvalue,object newvalue)
        {
            Entry entry=view as Entry;
            if (entry == null)
            {
                return;
            }
            bool valid = (bool)newvalue;
            if (valid) 
            {entry.TextChanged+= OnValidationHandler;
            }
            else
            {
                entry.TextChanged -= OnValidationHandler;
            }
        }
        static void OnValidationHandler(object sender, TextChangedEventArgs e)
        {
            Entry entry=sender as Entry;
            double result;
            bool isvalid=double.TryParse(e.NewTextValue, out result);
            entry.TextColor=isvalid?Colors.Green:Colors.Red;
        }
    }
}
 and the errors that appear is
Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0413	The property '<Unknown>' was not found in type 'Entry'.	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	XLS0112	Expected '='.	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	XLS0304	Expected an attribute value. Attribute values are delimited by a single quotation mark (') or a double quotation mark (").	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	XLS0415	The attachable property 'NumricValidation' was not found in type 'NumericBehaviorValidation'.	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	XLS0112	Expected '='.	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	XLS0304	Expected an attribute value. Attribute values are delimited by a single quotation mark (') or a double quotation mark (").	HossamTest1	D:\hossam\backup2\HossamTest1\HossamTest1\BehaviorPage.xaml	10	
Error	MAUIG1001	An error occured while parsing Xaml: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 10, position 45..	HossamTest1 (net7.0-android)	D:\hossam\backup2\HossamTest1\HossamTest1\HossamTest1.csproj	1	Active
Error	MAUIG1001	An error occured while parsing Xaml: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 10, position 45..	HossamTest1 (net7.0-ios)	D:\hossam\backup2\HossamTest1\HossamTest1\HossamTest1.csproj	1	Active
Error	MAUIG1001	An error occured while parsing Xaml: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 10, position 45..	HossamTest1 (net7.0-maccatalyst)	D:\hossam\backup2\HossamTest1\HossamTest1\HossamTest1.csproj	1	Active
Error	MAUIG1001	An error occured while parsing Xaml: Name cannot begin with the ' ' character, hexadecimal value 0x20. Line 10, position 45..	HossamTest1 (net7.0-windows10.0.19041.0)	D:\hossam\backup2\HossamTest1\HossamTest1\HossamTest1.csproj	1	Active
...................................................
I try to update, uninstall and reinstall my community visual studio but that doesn't work.``

**Comment by davidbritch** [comment]
Hi @HossamTash 

It looks like you've got a space between `local:` and `NumericBehaviorValidation.NumricValidation`, which looks like line 10 in your code. If in doubt, see the sample the Behaviours doc links to at the top of the page.
