### ISSUE TITLE
Add documentation for Application Indexing and Deep Linking in MAUI

### ISSUE THREAD

**Issue by raelsonraujo** [dotnet/docs-maui#1476]
Hi!

I'm having a bit of a hard time in figuring out what are the differences (if any) between MAUI and Xamarin Forms when it comes to supporting deep linking and indexing. In the [Official Documentation](https://learn.microsoft.com/en-us/dotnet/maui/) there isn't a source that we can rely on similar to what we have in the [Xamarin Forms documentation](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking). The little I could find revolved around:
- https://techcommunity.microsoft.com/t5/app-development/net-maui-applinks/m-p/3090344;
- https://stackoverflow.com/questions/74877924/how-do-i-register-an-applink-in-appdelegte-net-maui;

There might be a few other sources scattered around the internet, but having a single place to start in the official documentation that could also reflect the changes would be very helpful.

**Comment by davidbritch** [comment]
Hi @raelsonraujo 

AFAIK, it doesn't work properly in .NET MAUI, which is why I haven't added a doc. I'll ask internally to find out it's current status.

**Comment by davidbritch** [comment]
Hi @raelsonraujo 

Afraid it doesn't work. See https://github.com/dotnet/maui/issues/12295 and https://github.com/dotnet/maui/issues/11684 and https://github.com/dotnet/maui/issues/14671.

I'm going to close the issue here, because right now it's an engineering issue. Once they resolve it I'll add a doc.

**Comment by Yohancef** [comment]
See https://github.com/dotnet/maui/issues/14671 for the work around.
