### ISSUE TITLE
Seems the Windows platform view example has a mistake

### ISSUE THREAD

**Issue by wolfgang-ironsoftware** [dotnet/docs-maui#1478]
Trying to compile my own code, when inheriting the Maui platform view for Windows raises an error: 

> There is no implicit conversion from `*.MauiVideoView` to `Microsoft.UI.Xaml.FrameworkElement`.

It's better to use the fully qualified namespace to the Xaml Control Grid implementation, so inherit from `Microsoft.UI.Xaml.Controls.Grid` instead of just `Grid`. Afterwards compilation works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c00b995e-dfec-dcac-7951-38d6e05249ea
* Version Independent ID: c00b995e-dfec-dcac-7951-38d6e05249ea
* Content: [Create custom controls with .NET MAUI handlers - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/create?view=net-maui-7.0)
* Content Source: [docs/user-interface/handlers/create.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/create.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @wolfgang-ironsoftware 

It definitely wasn't a mistake - the code was fine at the time it was written. But whether it's still correct is another matter. I'll investigate.

**Comment by davidbritch** [comment]
The first time the Windows `Grid` is used in the article is in this code block:

```
using Microsoft.UI.Xaml.Controls;
using VideoDemos.Controls;
using Windows.Media.Core;
using Windows.Media.Playback;
using Windows.Storage;
using Grid = Microsoft.UI.Xaml.Controls.Grid;

namespace VideoDemos.Platforms.Windows
{
    public class MauiVideoPlayer : Grid, IDisposable
    {
        MediaPlayerElement _mediaPlayerElement;
        Video _video;
        ...

        public MauiVideoPlayer(Video video)
        {
            _video = video;
            _mediaPlayerElement = new MediaPlayerElement();
            this.Children.Add(_mediaPlayerElement);
        }
        ...
    }
}
```

It uses an alias to define exactly what `Grid` is being specified, so not seeing the need to update the article.
