### ISSUE TITLE
No MAUI option in Visual Studio 2022 Community 17.5.5 Installer

### ISSUE THREAD

**Issue by meir-toptal** [dotnet/docs-maui#1480]
I am trying to install VS2022 for MAUI development. The MAUI option shown on this page doesn't appear in the Desktop and Mobile section of the Installer options. The version is 17.5.5.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [Install Visual Studio 2022 to develop cross-platform apps using .NET MAUI - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=vswin)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @meir-toptal 

I had this exact same issue when I upgraded to VS 17.5.5 last week - the project templates vanished. A repair (from the installer) fixed it for me.
