### ISSUE TITLE
When can I expect PlatformImage to be available for Windows?

### ISSUE THREAD

**Issue by johnlim1001** [dotnet/docs-maui#1481]
When can I expect PlatformImage to be available for Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdb45230-f4a3-e5fe-62d7-1009d50e9e4f
* Version Independent ID: fdb45230-f4a3-e5fe-62d7-1009d50e9e4f
* Content: [Images - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/images)
* Content Source: [docs/user-interface/graphics/images.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/images.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @johnlim1001 

It looks like it's been done in https://github.com/dotnet/maui/pull/14816, which will be targeting .NET 8.
