### ISSUE TITLE
Webview on iOS

### ISSUE THREAD

**Issue by mancda** [dotnet/docs-maui#1483]
When viewing some html in the webview on iOS it appears rather small compared to the same text being viewed on the android platform.  I have tried to use RelScaleTo(2); which causes the text to appear the right size but it creates another problem of the text all positioned in the upper right corner of the control.  Is there a way to correct this?

Thanks for your help

**Comment by davidbritch** [comment]
Hi @mancda 

IIRC (from Xamarin.Forms), on iOS you need to add `<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1'/>` to your HTML:

```html
<head>
   <meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1'/>
</head>
<body>
  ...
</body>
```

**Comment by mancda** [comment]
Very helpful.  Thanks.
