### ISSUE TITLE
Sample using view models that have dependencies

### ISSUE THREAD

**Issue by Aculeo** [dotnet/docs-maui#1484]
In the sample shown, the view model is associated with the view like this:
```xaml
<ContentPage.BindingContext>
     <local:KeypadViewModel />
</ContentPage.BindingContext>
```

This requires/assumes that `KeypadViewModel` has a parameterless constructor. Now in almost all "real" applications this is not the case, we need to get some services injected. Can we perhaps get a sample or best practices how to make this work?

### More details

The main reason why I'm asking is because I expected this to be rather straightforward, but it doesn't seem to be.

`MauiProgram` follows the builder pattern, and I can register the view model there:

```csharp
builder.Services.AddTransient<LoginViewModel>();
```

So far so clear, but how do I get the IServiceProvider so I can get the view model instance? There is no `Application.Current.ServiceProvider` or something similar. As far as I can tell the only way is to assign it to a static field or property myself:

**MauiProgram.cs**:
```csharp
public static IServiceProvider ServiceProvider { get; private set; }

[...]
var mauiApp = builder.Build();
ServiceProvider = mauiApp.Services;
return mauiApp;
```

Then I can go into the code-behind of my page:

```csharp
BindingContext = MauiProgram.ServiceProvider.GetRequiredService<LoginViewModel>();
```

But now I get warnings in the XAML that it isn't aware of the context. Apparently I can use the new `x:DataType` in the XAML to get this resolved:

```
x:DataType="viewModels:LoginViewModel"
```

This all seems rather cumbersome just for basic MVVM stuff. Is this the correct course of action?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9905cd00-f3a1-7bdd-d678-ef6c71fb53b7
* Version Independent ID: 9905cd00-f3a1-7bdd-d678-ef6c71fb53b7
* Content: [Data binding and MVVM - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/mvvm)
* Content Source: [docs/xaml/fundamentals/mvvm.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/fundamentals/mvvm.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Aculeo 

It's slightly less cumbersome. In `MauiProgram`:

```csharp
		builder.Services.AddTransient<LoginViewModel>();
		builder.Services.AddTransient<MainPage>();
```

Then in your page class:

```csharp
public partial class MainPage : ContentPage
{
	public MainPage(IServiceProvider provider)
	{
		InitializeComponent();
                BindingContext = provider.GetService<LoginViewModel>();
	}
}
```

Then `x:DataType` in XAML, if required.

**Comment by Aculeo** [comment]
Ah, thank you! I didn't know you could register the view itself as well, and get dependencies injected that way

**Comment by davidbritch** [comment]
np. You couldn't have known because it's not documented yet. I'm going to close the issue here, because there's another issue open for doc'ing DI in MAUI.
