### ISSUE TITLE
ActivityIndicator documentation for Windows and MacCatalyst

### ISSUE THREAD

**Issue by indyjason79** [dotnet/docs-maui#1485]
[Enter feedback here]
There is only mention of Android & iOS for the ActivityIndicator in Maui. Please specify if one does not exist for Windows & Mac or mention them in some way so we don't think you just forgot about them. By looking at the documentation I'm not sure if they work on Windows & Mac so I may not try to use it because the OS's aren't mentioned. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8770371-5b53-c53f-25b4-f983e3beb4ce
* Version Independent ID: a8770371-5b53-c53f-25b4-f983e3beb4ce
* Content: [ActivityIndicator - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/activityindicator)
* Content Source: [docs/user-interface/controls/activityindicator.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/activityindicator.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 92647](https://dev.azure.com/msft-skilling/Content/_workitems/edit/92647)

**Comment by davidbritch** [comment]
Hi @indyjason79 

All controls work on all four platforms, unless the doc explicitly says otherwise.
