### ISSUE TITLE
Remove content on loading an image as an embedded resource

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1487]
The section on loading embedded images in XAML (https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/image#load-an-embedded-image-in-xaml) should be removed. It's carried over from Forms, and has been superseded by MauiImage.

See https://github.com/dotnet/maui/issues/8666 for more info.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb4d16da-8c0f-5b7e-54ee-1fe36c549837
* Version Independent ID: cb4d16da-8c0f-5b7e-54ee-1fe36c549837
* Content: [Image - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/image#load-an-embedded-image-in-xaml)
* Content Source: [docs/user-interface/controls/image.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/image.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 90898](https://dev.azure.com/msft-skilling/Content/_workitems/edit/90898)

**Comment by dotMorten** [comment]
I do like the bit where it shows how to load an image with a markup extension though. Could the sample be adapted to just not use embedded resources?

**Comment by davidbritch** [comment]
@dotMorten What's the scenario?
