### ISSUE TITLE
It would have been useful to include examples of how to include images stored in folders other than Resources\Images rather than keep repeating references to the project file.

### ISSUE THREAD

**Issue by istuart0** [dotnet/docs-maui#1489]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7dc547-5ff1-416d-450b-e39e56cb1e71
* Version Independent ID: 7d7dc547-5ff1-416d-450b-e39e56cb1e71
* Content: [Add images to a .NET MAUI app project - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/images)
* Content Source: [docs/user-interface/images/images.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/images.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
What's your scenario? Images typically have to go in Resources\Images.
