### ISSUE TITLE
MAUI WinUI Startup documentation is missing.

### ISSUE THREAD

**Issue by AvogadroSG1** [dotnet/docs-maui#149]
I believe there's some missing documentation on using the .WinUI portion of the base Maui App.  There's no reference that a developer needs to use the "Deploy" function that will deploy it to their local machine for use.  I think many users will try to "Start Debugging" in VS and wonder why they can't get it to do anything.

I think a small blurb about this after the iOS startup would be a good mention here and I'd be happy to do it if this is though of as a good addition.

Something along the lines of:

> ### Windows UI Project

> In order to run the WinUI project that is created, you will need to Deploy the project to your local machine and run it as standalone app in order to see the output of the program.  
> *insert a screen shot walk-through*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello! I believe this will be coming soon. I just got back from vacation but in .NET 6 Preview 7 the WinUI experience broke requiring you to deploy. I believe the plan is to fix this so we're holding off on documenting this because we'll just have to remove it.
