### ISSUE TITLE
Rotating a brush inside xaml

### ISSUE THREAD

**Issue by AghaKhan** [dotnet/docs-maui#1499]
We can transform inside the XAML file if you look at WPF or UWP applications using any gradient brush. However, for some unknown reason, Microsoft has removed that option from MAUI applications. I want to bring it back.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba7864ef-0225-76ce-d757-bbab7bc1e71d
* Version Independent ID: ba7864ef-0225-76ce-d757-bbab7bc1e71d
* Content: [Transforms - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/transforms)
* Content Source: [docs/user-interface/graphics/transforms.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/transforms.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @AghaKhan 

This needs logging as a feature request at https://github.com/dotnet/maui/issues/new/choose

Thanks!
