### ISSUE TITLE
Error XA3007 while running sample

### ISSUE THREAD

**Issue by firepascal** [dotnet/docs-maui#1501]
While trying to run the samples i run into a XA3007 Could not link native shared library: libxamarin-app.so error while trying to run the sample.
it show the following output message:
Build started...
1>------ Build started: Project: FlyoutPageSample, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>FlyoutPageSample -> G:\tabtest\maui-samples-main\7.0\Navigation\FlyoutPageSample\FlyoutPageSample\bin\Debug\net7.0-android\FlyoutPageSample.dll
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\tools\Xamarin.Android.Common.targets(2010,3): error XA3007: Could not link native shared library: libxamarin-app.so
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\tools\Xamarin.Android.Common.targets(2010,3): error XA3007: 
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\tools\Xamarin.Android.Common.targets(2010,3): error XA3007: stderr | ld: error: cannot open output file obj\Debug\net7.0-android\app_shared_libraries\x86_64\libxamarin-app.so: no such file or directory
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\tools\Xamarin.Android.Common.targets(2010,3): error XA3007: 
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\tools\Xamarin.Android.Common.targets(2010,3): error XA3007:
1>Done building project "FlyoutPageSample.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 3:57 PM and took 01:58,887 minutes ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy started at 3:57 PM and took 01:58,888 minutes ==========

any way how this can be fixed?

**Comment by davidbritch** [comment]
Weird error that I've never seen before. I've just successfully deployed a debug build of that sample to the emulator.
