### ISSUE TITLE
Issue deploying to a real device

### ISSUE THREAD

**Issue by GreatIdeaz** [dotnet/docs-maui#1505]
Whilst this seems to work fine when debugging the Azure B2C application on the iOS simulator.

It seems to fail when tying to run in debug mode on an actual device or packaging for an Ad-Hoc release.

The build deployment fails with an unverifable build message.

The issue is likely with the provisioning profiles. We have the same application running using basic user/password authentication and it works fine when deploying to devices.

Are we missing something relating to how to package the application?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9a8421b-ca5d-96e3-35ab-60118e356017
* Version Independent ID: a9a8421b-ca5d-96e3-35ab-60118e356017
* Content: [Publish a .NET MAUI app to a folder for Windows - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-visual-studio-folder?view=net-maui-7.0)
* Content Source: [docs/windows/deployment/publish-visual-studio-folder.md](https://github.com/dotnet/docs-maui/blob/main/docs/windows/deployment/publish-visual-studio-folder.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Is this the same issue as https://github.com/dotnet/runtime/issues/85722?
