### ISSUE TITLE
Span.GestureRecognizers don't work on Adroid

### ISSUE THREAD

**Issue by Kol-yan** [dotnet/docs-maui#1510]
Span.GestureRecognizers don't work on Adroid

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 243e6d1d-a276-814f-7943-ff0fa7ba017e
* Version Independent ID: 243e6d1d-a276-814f-7943-ff0fa7ba017e
* Content: [Label - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label)
* Content Source: [docs/user-interface/controls/label.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/label.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Kol-yan 

Yes, afraid it's a known issue: https://github.com/dotnet/maui/issues/4734
