### ISSUE TITLE
Feedback on the consume rest api with maui tutorial

### ISSUE THREAD

**Issue by octameter** [dotnet/docs-maui#1520]
[Enter feedback here]
This is tricky to replicate and test. 
- Provide more detailed code samples (including the classes, maybe test cases even, sample code for download)
- Give more context on how to implement this in an existing project

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 851edc00-2289-d52f-106f-0eb968a7792d
* Version Independent ID: 851edc00-2289-d52f-106f-0eb968a7792d
* Content: [Consume a REST-based web service - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/rest)
* Content Source: [docs/data-cloud/rest.md](https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/rest.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @octameter 

There's a link to a sample at the top of the article.
