### ISSUE TITLE
PanContainer

### ISSUE THREAD

**Issue by kj4bix** [dotnet/docs-maui#1523]
I think there is an issue in this example, by the way. I really like how this works, however your limits on the pan values doesn't seem to work. I have a 3d model and with the code as in the example, I cannot pan all the way to the right. It stops slightly after the center of the display. 

However, if I change the limits to use the clamp to the actual display window rectangle, it seems to work. Also, I combined the PanContainer with the PinchZoomContainer so I have both in a single class. That might be helpful for others. Here is how I change the "clamp" limit which seems to work really well. 

Again -  great solution, it works far better than the pan built into the graphicsview which has the clipping issues until you put it in a contentview, which does the clipping correctly. 

           case GestureStatus.Running:
                // Translate and ensure we don't pan beyond the wrapped user interface element bounds.
                var boundsX = (Content.Width);
                var boundsY = (Content.Height);
                Content.TranslationX = Math.Clamp(panX + e.TotalX, -boundsX, boundsX);
                Content.TranslationY = Math.Clamp(panY + e.TotalY, -boundsY, boundsY);
// Original code here:
                //Content.TranslationX = Math.Max(Math.Min(0, panX + e.TotalX), -Math.Abs(Content.Width - DeviceDisplay.MainDisplayInfo.Width));
                //Content.TranslationY = Math.Max(Math.Min(0, panY + e.TotalY), -Math.Abs(Content.Height - DeviceDisplay.MainDisplayInfo.Height));
                break;

The images below are with my change, previously I could not pan to the right much past the centerline.

Thanks
![normal view](https://github.com/dotnet/docs-maui/assets/9199409/800399af-d811-4b67-b6d3-0e9222ddf6a9)
![pan far right](https://github.com/dotnet/docs-maui/assets/9199409/2ffd444f-2a71-4822-9f7c-64869b6f037d)
![pan far left](https://github.com/dotnet/docs-maui/assets/9199409/790dee6e-010b-4ae2-9ffb-6611ea688b9a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6790172b-c85e-0b9a-575f-c8c40fc284c8
* Version Independent ID: 6790172b-c85e-0b9a-575f-c8c40fc284c8
* Content: [Recognize a pan gesture - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/pan)
* Content Source: [docs/fundamentals/gestures/pan.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/gestures/pan.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 117007](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117007)

**Comment by davidbritch** [comment]
Hi @kj4bix 

Thanks for this - much appreciated.

**Comment by kj4bix** [comment]
Thanks David, this is a really nice approach.
