### ISSUE TITLE
Filesystem  returns null

### ISSUE THREAD

**Issue by HossamTash** [dotnet/docs-maui#1524]
[Enter feedback here]
when I try to add sqlite database I use filesystem helper 
                string path1 = FileSystem.Current.AppDataDirectory;
the path1 returns null and the data did not be stored
I try 
                string dbpath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Employees.db3");
but  the dbpath returns null too.   

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Version Independent ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Content: [File system helpers - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=android)
* Content Source: [docs/platform-integration/storage/file-system-helpers.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/file-system-helpers.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @HossamTash 

Afraid that product questions need raising in the [engineering repo](https://github.com/dotnet/maui) with a full repro sample.
