### ISSUE TITLE
Deep linking in .Net MAUI WinUI

### ISSUE THREAD

**Issue by OnepunchmanSven** [dotnet/docs-maui#1525]
I'm developing a desktop application for Windows with .Net MAUI, I want to host the login in websites, so I redirect my app to: 
await Launcher.OpenAsync(new Uri("https://dev.myapp.io/login/user?redirect_uri=myapp:///callapp?token=token)"));

And I have registered my app for Windows:
<Extensions>
	<uap:Extension Category="windows.protocol">
		<uap:Protocol Name="myapp">
			<uap:DisplayName>myapp</uap:DisplayName>
		</uap:Protocol>
	</uap:Extension>
</Extensions>

In this case, when I type: myapp:///callapp?token=token in any browser, it redirects to my app, this is great, but each time it opens a new instance, so I solve the single instance issue by implementing the workaround in the last comment here:
https://github.com/dotnet/maui/issues/9973

But my issue is:
1.The uri didn't open the existing app instance, I mean make it visible
2.How can I redirect to the HomePage after login successfully, I'm not able to navigate the pages because it's written in WinUI specifically?

**Comment by OnepunchmanSven** [comment]
I need the deep linking to be smoothly running in MAUI WinUI because in my app we have quite a few cases to communicate with the websites, for some specific reasons.

**Comment by davidbritch** [comment]
Hi @OnepunchmanSven 

Afraid I'll have to let your question be answered in the [engineering issue](https://github.com/dotnet/docs-maui/issues/1531). There's no deep linking doc yet because of the issues with it on all platforms.
