### ISSUE TITLE
Please remove AuthenticateAsync API from Windows, or provide an working alternative

### ISSUE THREAD

**Issue by NuShrike** [dotnet/docs-maui#1526]
[Enter feedback here]
I find it ridiculous that AuthenticateAsync(..) still doesn't work in MAUI .NET 7 (latest) June, 2023 with a 2+ year old issue trail of brokenness on GitHub. This is a basic, essential feature to get any .NET app access to APIs that need an OAUTH token and flow.

Yet, there's an arrogant section that says don't use older patterns of authentication anymore: `We strongly recommend against using older mobile-only authentication libraries and patterns which do not leverage a web backend in the authentication flow, due to their inherent lack of security for storing client secrets.`

Maybe first get this API actually working before making recommendations.

I've already previously spent months of hell trying to get generic OAUTH logins working in a Blazor webassembly app in 2021 when there's at least 5 different alternative paths to use, and none were official. It hasn't gotten any better with MAUI.

If I was working in Qt again, this wouldn't have been an issue at all -- because their APIs work.

Please remove compatibility for "Windows" platform until this is actually resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 829bc017-4a10-6ca5-0717-e1e62f59aacc
* Version Independent ID: 829bc017-4a10-6ca5-0717-e1e62f59aacc
* Content: [Web Authenticator - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?tabs=windows)
* Content Source: [docs/platform-integration/communication/authentication.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/communication/authentication.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by SmartmanApps** [comment]
> inherent lack of security for storing client secrets

There's also an implicit assumption here (by both MS and Google, and Dropbox, and...) that the programmer and the user aren't one and the same. "If you're writing an app for clients you shouldn't be storing any secrets". Ok, but if I'm writing an app for **myself** then you shouldn't be doing things that stop me from doing that. Stop **assuming** that literally every app being developed has a different user than the one actually writing it! Argh.

**Comment by davidbritch** [comment]
@SmartmanApps @NuShrike Thanks for your feedback folks, but it's best directed to the [engineering repo](https://github.com/dotnet/maui).

**Comment by SmartmanApps** [comment]
> @SmartmanApps @NuShrike Thanks for your feedback folks, but it's best directed to the [engineering repo](https://github.com/dotnet/maui).

@davidbritch The request was to update the documentation to reflect the fact that it doesn't work on Windows, as opposed to the current state of it recommends to use something which doesn't work, so therefore shouldn't be there until the engineering team get it working.

**Comment by davidbritch** [comment]
@SmartmanApps The doc already says that it doesn't work on Windows:

![image](https://github.com/dotnet/docs-maui/assets/8092460/6936a369-0384-4fb3-b2f3-ae8afe40d73a)
