### ISSUE TITLE
How can you save or export the GraphicsView?

### ISSUE THREAD

**Issue by mattlovell** [dotnet/docs-maui#1534]
[Enter feedback here]

Hi, 

It would be very useful if there was some information about how to export, or save this GraphicsView - apologies if this already exists - but I cannot find anything?

Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2deb823c-ccc8-fdef-6cf8-bb70a2c21939
* Version Independent ID: 2deb823c-ccc8-fdef-6cf8-bb70a2c21939
* Content: [.NET MAUI GraphicsView - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/graphicsview#create-a-graphicsview)
* Content Source: [docs/user-interface/controls/graphicsview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/graphicsview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mattlovell 

Afraid there's nothing built into .NET MAUI to do this. The only path forward right now is to add your own code to do so - see https://github.com/dotnet/maui/discussions/8969
