### ISSUE TITLE
CollectionView in VerticalStackLayout doesn't scroll

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1535]
Update the CollectionView docs to specify that a `CollectionView` is in a `VerticalStackLayout` takes up all the space, which stops the CollectionView scrolling. Instead, users should use a `Grid`.

https://github.com/dotnet/maui/issues/15402

---
[Associated WorkItem - 98883](https://dev.azure.com/msft-skilling/Content/_workitems/edit/98883)

**Comment by borealoh** [comment]
this is good know however at least the samples show to use Stack Layout maybe the documentation as well.
