### ISSUE TITLE
Documentation About Visual States Not Up To Date

### ISSUE THREAD

**Issue by JediIzzyT** [dotnet/docs-maui#1540]
On the documentation page for Maui's Switch control, there is a section called "Switch Visual States" ([https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/switch#switch-visual-states](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/switch#switch-visual-states))

This section provides the example code:
`<Switch IsToggled="True">
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup x:Name="CommonStates">
            <VisualState x:Name="On">
                <VisualState.Setters>
                    <Setter Property="ThumbColor"
                            Value="MediumSpringGreen" />
                </VisualState.Setters>
            </VisualState>
            <VisualState x:Name="Off">
                <VisualState.Setters>
                    <Setter Property="ThumbColor"
                            Value="Red" />
                </VisualState.Setters>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
</Switch>`

However, this code causes Android apps to crash when deployed without hot reload. Per _Cfun_ on StackOverflow [https://stackoverflow.com/a/73691990/13983133](https://stackoverflow.com/a/73691990/13983133), "VisualStateGroup" tags must be wrapped in a "VisualStateGroupList" tag, even if there is only one "VisualStateGroup".

This was causing my app to crash, but _Cfun_'s fix resolved it for me. 

I believe that this should be updated in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00a39569-da70-b004-4d37-8a1999360518
* Version Independent ID: 00a39569-da70-b004-4d37-8a1999360518
* Content: [Switch - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/switch)
* Content Source: [docs/user-interface/controls/switch.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/switch.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 117009](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117009)

**Comment by davidbritch** [comment]
> Per Cfun on StackOverflow https://stackoverflow.com/a/73691990/13983133, "VisualStateGroup" tags must be wrapped in a "VisualStateGroupList" tag, even if there is only one "VisualStateGroup".

Afraid I haven't been able to repro this. I managed to deploy the linked sample app to devices on every platform, without using hot reload, and it worked in all cases. Only on Windows did I manage to get the "InvalidOperationException: VisualStateGroup Names must be unique at build time" error, which I also to eliminate.

While adding a `VisualStateGroupList` is technically allowed, we've deliberately used the shorthand approach in the examples in the docs. When you don't explicitly specify the `VisualStateGroupList` the XAML inflater will inject it for you.

So without a repro sample I'm afraid I'll have to close this issue.
