### ISSUE TITLE
Consume system fonts on Android

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1543]
In .NET 8, Android can consume system fonts in `Label`s.

https://github.com/dotnet/maui/pull/15010

This has been expanded with more system font names in https://github.com/dotnet/maui/pull/15759

---
[Associated WorkItem - 164934](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164934)

**Comment by andreiionita** [comment]
Hi @davidbritch
Can you tell us when this will be released? Android system fonts are not working for me on 8.0.6.

**Comment by davidbritch** [comment]
Hi @andreiionita

It's only a subset of the system fonts - see https://learn.microsoft.com/dotnet/maui/user-interface/fonts?view=net-maui-8.0#consume-fonts

I tried it in 8.0.3 and it was working then.
