### ISSUE TITLE
Documents is flawed

### ISSUE THREAD

**Issue by ranjeethmd** [dotnet/docs-maui#155]
The documentation looks like it is asking the extension to be installed first and then the other steps to be followed. However in actuality the maui-check needs to be performed and then the visual studio extension needs to be implemented for the workload to appeat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
This is probably related to #150 

I'll ask around about this potential workaround

**Comment by adegeo** [comment]
Visual Studio and .NET MAUI just had an update, eliminating the maui-check tool. I believe this can be closed as the documentation has been updated. Thank you for reporting it!
