### ISSUE TITLE
Flyout IconImageSource issue

### ISSUE THREAD

**Issue by Cisco0911** [dotnet/docs-maui#1550]
[Enter feedback here]
It is said in the doc that by setting "IconImageSource" property, the icon will appear on the detail page, provided that it have a title bar. But that is not working. My objectif is to customize that hamburger icon that toggle the "IsPresented" property of the flyout page. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86a77021-9359-304a-5d49-a4feadf2f8fb
* Version Independent ID: 86a77021-9359-304a-5d49-a4feadf2f8fb
* Content: [FlyoutPage - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage)
* Content Source: [docs/user-interface/pages/flyoutpage.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pages/flyoutpage.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Cisco0911 

I just tried it and it seems like it works correctly and iOS and Mac Catalyst, but not other platforms. The engineers have a bug logged for it: https://github.com/dotnet/maui/issues/15211
