### ISSUE TITLE
directions not accurate

### ISSUE THREAD

**Issue by coryryan269** [dotnet/docs-maui#1552]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: windows

The directions provided for adding .NET MAUI to an existing installation of Visual Studio Code are inaccurate. The URL below directs the user to **Select the Windows key, type Visual Studio Installer, and press Enter.**, but that does nothing but open up a browser searching bing for the text typed. It seems the intent is to have the user rerun the installer so that it will ask you about add-ons (or extensions), but doing so does not result in the installer prompting you to check any add-ons that you want to install.

https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install

**Comment by Eilon** [comment]
Hi @coryryan269 , that's quite odd! I'm getting the same behavior when I type out the whole thing:

![image](https://github.com/dotnet/maui/assets/202643/6f8a1021-7c0c-4bf4-abb4-aa0e13e5ecf9)

But if I type something shorter, such as just `installer`, then I get the right match:

![image](https://github.com/dotnet/maui/assets/202643/ea321a7d-1839-487e-aaf3-03b7aaa90308)

So I suspect this is perhaps a bug in the Windows Start Menu search feature.

**Comment by Eilon** [comment]
I've transferred this issue to the .NET MAUI docs repo so that we can look at updating the instructions in the doc to provide better results. I also suggest filing a Windows Feedback report to improve the quality of results in the Start Menu search box.

**Comment by davidbritch** [comment]
@mairaw Looks like one for you?

**Comment by davidbritch** [comment]
@Eilon 

This issue needs transferring to the dotnet/website repo, which I don't have access to. Can you oblige?

**Comment by Eilon** [comment]
> @Eilon
> 
> This issue needs transferring to the dotnet/website repo, which I don't have access to. Can you oblige?

I can't find that repo - is that the right name, or perhaps I don't have permission to access it?

**Comment by davidbritch** [comment]
@Eilon It used to be the dotnet/website repo, but it looks like it's split into multiple repos now. I'll track down which is the correct one.
