### ISSUE TITLE
Incorrect use of comma instead of semicolon, when multiple RuntimeIdentifiers

### ISSUE THREAD

**Issue by ToolmakerSteve** [dotnet/docs-maui#1553]
[Enter feedback here]
Section [Convert to RuntimeIdentifier](https://learn.microsoft.com/en-us/dotnet/maui/migration/apple-projects#convert-to-runtimeidentifier) has a mistake:
> ios-arm,ios-arm64

Must separate multiple RIDs with a semicolon `;` not a comma `,`. Correct document linked below.

ALSO should make it clearer that when multiple RIDs, use property `RuntimeIdentifiers` instead of `RuntimeIdentifier`. This is implied by the header at top of column, but I think that is not clear. Its best to show a sample line of xml, as in the doc mentioned below

See [MSBuild Properties / RuntimeIdentifiers](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#runtimeidentifiers):
> The RuntimeIdentifiers property lets you specify a semicolon-delimited list of runtime identifiers (RIDs) for the project. Use this property if you need to publish for multiple runtimes.
```xml
<PropertyGroup>
  <RuntimeIdentifiers>win10-x64;osx.10.11-x64;ubuntu.16.04-x64</RuntimeIdentifiers>
</PropertyGroup>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd522605-d607-f50b-3f18-71a5a16a3443
* Version Independent ID: fd522605-d607-f50b-3f18-71a5a16a3443
* Content: [Xamarin.iOS project migration - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/migration/apple-projects#convert-to-runtimeidentifier)
* Content Source: [docs/migration/apple-projects.md](https://github.com/dotnet/docs-maui/blob/main/docs/migration/apple-projects.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 117596](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117596)

**Comment by davidbritch** [comment]
Thanks for the issue. All makes sense and I'll get it done in the next few weeks.
