### ISSUE TITLE
why does swipe not work in the maui application in windows

### ISSUE THREAD

**Issue by g1357** [dotnet/docs-maui#1560]
why does swipe not work in the maui application in windows

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0249dadd-67f1-3bf4-a386-6b7b3429612a
* Version Independent ID: 0249dadd-67f1-3bf4-a386-6b7b3429612a
* Content: [SwipeView - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/swipeview)
* Content Source: [docs/user-interface/controls/swipeview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/swipeview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Afraid it looks like there are issues with that control: https://github.com/dotnet/maui/issues?q=is%3Aissue+is%3Aopen+SwipeView
