### ISSUE TITLE
Unclear when you need to set the [assembly: XamlCompilation(XamlCompilationOptions.Compile)] attribute

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/docs-maui#1566]
This documentation page says
> XAML compilation is enabled by default in .NET MAUI apps.

However, it also explains [how to enable XAML compilation](https://learn.microsoft.com/en-us/dotnet/maui/xaml/xamlc#enable-compilation) by setting the `[assembly: XamlCompilation(XamlCompilationOptions.Compile)]` attribute.

First of all, it is really easy to read over the short sentence "XAML compilation is enabled by default in .NET MAUI apps." when the big header "Enable XAML compilation" is drawing your eyes. Secondly, it is unclear why you would still need to enable it at assembly-level if it is already enabled by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12b6e5f6-7ab1-1373-242e-4f28cee2b773
* Version Independent ID: 12b6e5f6-7ab1-1373-242e-4f28cee2b773
* Content: [XAML compilation - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/xaml/xamlc)
* Content Source: [docs/xaml/xamlc.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/xamlc.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 118492](https://dev.azure.com/msft-skilling/Content/_workitems/edit/118492)

**Comment by davidbritch** [comment]
Hi @hansmbakker 

Thanks for the feedback - you raise good points. Some clarifications (which I'll add to the doc): XAML compilation is enabled by default in .NET MAUI app projects. However, if you have a class library that contains XAML files, you'll need to enable it there.

**Comment by hansmbakker** [comment]
Super fast answer, thank you for the clarification!

**Comment by davidbritch** [comment]
Hi again @hansmbakker 

My previous reply was wrong - there was a time in the past where you had to enable XAML compilation in class libraries, but that's no longer the case.  One use for disabling XAML compilation is when you get XAMLC errors in your build output (see https://github.com/dotnet/maui/issues?q=is%3Aissue+is%3Aopen+XAMLC for issues users have logged). In those cases disabling XAMLC on a type often lets you proceed with running/debugging your app.

As for enabling XAMLC, the only use case is enabling it in debug mode to mirror the exact behaviour of XAMLC in release mode (where IL is written to the assembly).
