### ISSUE TITLE
When and why PhoneDialer.Default.IsSupported is false?

### ISSUE THREAD

**Issue by MaziarH** [dotnet/docs-maui#1578]
If "PhoneDialer.Default.IsSupported" returns false while using the Android simulator on Windows, what options do we have?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 434134e2-02dc-840a-1a72-b784165254cd
* Version Independent ID: 434134e2-02dc-840a-1a72-b784165254cd
* Content: [Phone dialer - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/phone-dialer?tabs=windows#open-the-phone-dialer)
* Content Source: [docs/platform-integration/communication/phone-dialer.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/communication/phone-dialer.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MaziarH 

It'll return `false` unless you edit your manifest as described at https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/phone-dialer?tabs=android#get-started
