### ISSUE TITLE
Fehler in der Doku.

### ISSUE THREAD

**Issue by TheCodePilot** [dotnet/docs-maui#1581]
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="Notes.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:views="clr-namespace:Notes.Views"
    Shell.FlyoutBehavior="Disabled">

    <TabBar>
        <ShellContent
            Title="Notes"
            ContentTemplate="{DataTemplate views:AllNotesPage}"
            Icon="{OnPlatform 'icon_notes.png', iOS='icon_notes_ios.png', MacCatalyst='icon_notes_ios.png'}" />

        <ShellContent
            Title="About"
            ContentTemplate="{DataTemplate views:AboutPage}"
            Icon="{OnPlatform 'icon_about.png', iOS='icon_about_ios.png', MacCatalyst='icon_about_ios.png'}" />
    </TabBar>

</Shell>[Enter feedback here]

Bei den  ContentTemplate="{DataTemplate views:AllNotesPage}"
UND
 ContentTemplate="{DataTemplate views:AboutPage}"

ist es notwendig             Views           anstatt views zu schreiben.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Version Independent ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Content: [Tutorial: Create a .NET MAUI app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?tutorial-step=1)
* Content Source: [docs/tutorials/notes-app/index.yml](https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello, sorry, the feedback system for the tutorials doesn't tell me which page and which section has the error. Can you please be more specific? Thanks!
