### ISSUE TITLE
Linker behavior menu option gone from Visual Studio for Mac

### ISSUE THREAD

**Issue by wolfgang-ironsoftware** [dotnet/docs-maui#1582]
Seems the build settings options have changed in Visual Studio. I don't see any linker behavior menu option anymore in Visual Studio for Mac. I don't even see the MacCatalyst option.

I want to change the linker behavior, but no idea how to set it now. Would be useful to know the property / properties to use in project file perhaps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad968dfb-09e4-b062-2d96-43844a43c5ed
* Version Independent ID: ad968dfb-09e4-b062-2d96-43844a43c5ed
* Content: [Linking a .NET MAUI Mac Catalyst app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/linking)
* Content Source: [docs/mac-catalyst/linking.md](https://github.com/dotnet/docs-maui/blob/main/docs/mac-catalyst/linking.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @wolfgang-ironsoftware 

I just tried it in the latest stable release of VSMac. My first issue was that the MAUI project templates had vanished from my install. Once I got that sorted out I found that the linker options are still there:

![Screenshot 2023-07-27 at 09 47 05](https://github.com/dotnet/docs-maui/assets/8092460/45cfb94f-f7c2-4f4e-a376-8f5e11136234)

With that said, if you want to manually set the linker in your .csproj you want the `MtouchLink` property:

```xml
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0-maccatalyst|AnyCPU'">
	  <MtouchLink>Full</MtouchLink>
	</PropertyGroup>
```

Valid values for `MtouchLink` are  `None`, `SdkOnly`, or `Full`.
