### ISSUE TITLE
.NET MAUI Sucks!

### ISSUE THREAD

**Issue by khambley** [dotnet/docs-maui#1585]
I've tried repeatedly to work with Maps in MAUI and can't get it to work in Visual Studio for Mac 17.6. Other numerous bugs are getting me close to abandoning the framework all together. I've been working with .NET and Xamarin for over 7 years and you're end of life-ing it for this MAUI crap? So many bugs and workarounds, I might as well go native iOS and Android. Just wasted massive amounts of time trying to get a simple app to work. I'm DONE!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b9eb607-2e67-164a-b72b-c6750f05a972
* Version Independent ID: 3b9eb607-2e67-164a-b72b-c6750f05a972
* Content: [Map - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/map)
* Content Source: [docs/user-interface/controls/map.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/map.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for your feedback.
