### ISSUE TITLE
External storage not adressed.

### ISSUE THREAD

**Issue by Meersalzeis** [dotnet/docs-maui#1587]
I was trying to learn how to write into the shared external storage of android with .NET .
The page did not address this issue, despite its title implying it would, at least for a mobile development beginner.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Version Independent ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Content: [File system helpers - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=android)
* Content Source: [docs/platform-integration/storage/file-system-helpers.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/file-system-helpers.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Meersalzeis 

The `FileSystem` API only exposes common cross-platform concepts. As external storage isn't a cross-platform concept, accessing it requires the use of platform APIs. In your case, take a look at https://stackoverflow.com/questions/74996443/how-to-read-files-from-android-external-storage-in-maui-application
