### ISSUE TITLE
Using these samples does not work

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#1588]
I have created a simple page as follows:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:views="clr-namespace:CreateNHLStatsForYearFile.Views"
             x:Class="CreateNHLStatsForYearFile.MainPage">

    <Grid RowDefinitions="*,*,*" ColumnDefinitions="*,*,*">

        <Shell Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="3">
            <TabBar>
                    <ShellContent Title="Tab 1" ContentTemplate="{DataTemplate views:ContentPage1}"></ShellContent>
                    <ShellContent Title="Tab 2" ContentTemplate="{DataTemplate views:ContentPage2}"></ShellContent>
            </TabBar>
        </Shell>
    </Grid>
</ContentPage>

When I start the app (Android) it shows the ContentPage1 and both titles.  Clicking on a title then shows nothing and even  the first tab does not show.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b75579a-1ca4-376a-f5df-41de5c690acc
* Version Independent ID: 8b75579a-1ca4-376a-f5df-41de5c690acc
* Content: [.NET MAUI Shell tabs - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/tabs)
* Content Source: [docs/fundamentals/shell/tabs.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/tabs.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sqlguy6212 

You shouldn't be putting a `Shell` element in a `Grid`. `Shell` should always be the root element of the XAML file.
