### ISSUE TITLE
Need explanation and example of how to get something *into* a cache or app data directory

### ISSUE THREAD

**Issue by mprogers** [dotnet/docs-maui#1589]
I have a file that I need to copy onto an Android (and eventually iOS and macOS) device, and get its path. That should be easy but I've spent hours trying to Google this, without success.

In my case, I'm using Visual Studio for Mac, and the documentation doesn't really address that (at least on this page).

It's probably easy, but it am guessing it requires some prior knowledge -- maybe Xamarin Forms? Android development? -- that I am lacking.

An explanation would be welcome.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Version Independent ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Content: [File system helpers - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=android)
* Content Source: [docs/platform-integration/storage/file-system-helpers.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/file-system-helpers.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@mprogers If I understand you correctly, https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=android#copy-a-bundled-file-to-the-app-data-folder covers it?
