### ISSUE TITLE
How to install Android, iOS, macOS, tvOS, and Mac Catalyst SDK?

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/docs-maui#159]
[This](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation) Documentation said:

>Additionally, you'll need to install the platform SDKs for Android, iOS, macOS, tvOS, and Mac Catalyst.

But did not show any instruction. Even the `maui-check` instructions have been removed from the documentation.

Please tell me: 

1. How to install Android, iOS, macOS, tvOS, and Mac Catalyst SDK for .NET MAUI?
2. What is the reason for removing the `maui-check` instructions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. This article was recently updated to remove maui-check as its no longer required to run. I believe the only requirement now is to install the workloads via the Visual Studio installer. You'll need to manually download the platform SDKs though, and yes, as you pointed out, those should be linked to. I'll update the article for that.
