### ISSUE TITLE
Maui do not run in windows using VSCODE 

### ISSUE THREAD

**Issue by wjvelasquez** [dotnet/docs-maui#1597]
I need run it on my windows OS. Just like Visual Studio
Maui do not run in windows using VSCODE .
when i press F5 only show android and Mac. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=devices-windows&tabs=vswin)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @wjvelasquez 

What you're trying to do is a supported scenario, so should work. See https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=visual-studio-code#windows for more details.
