### ISSUE TITLE
Wrong Linux maui workload install in docs

### ISSUE THREAD

**Issue by bebenlebricolo** [dotnet/docs-maui#1600]
Hi team, 

I noticed that some parts of the docs are missing something important for dotnet maui development on Linux : 
When performing the maui workload installation, one should target the `maui-android`  instead of plain `maui`.
This is needed as (as far as I know) only the android support is enable for now on Linux.

So the appropriate  command shall be :
`dotnet workload install maui-android` 

Otherwise, dotnet CLI will fail, with the infamous message:
> "Workload ID maui isn't supported on this platform."

Which is correct, but the docs should indicate it.

Note : that guy has made a video of the full setup, that's how I found the solution to this issue :
[https://www.youtube.com/watch?v=4D2vUYUIqFU](https://www.youtube.com/watch?v=4D2vUYUIqFU)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [Install Visual Studio 2022 to develop cross-platform apps using .NET MAUI - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=visual-studio-code)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 143153](https://dev.azure.com/msft-skilling/Content/_workitems/edit/143153)

**Comment by davidbritch** [comment]
Hi @bebenlebricolo 

Afraid that the docs won't mention Linux as a dev environment. While Android dev on Linux is something that works, it's not an "official" platform for .NET MAUI dev. Hence it's not recommended, and there's no guarantee that it'll continue to work in future.

**Comment by bebenlebricolo** [comment]
Hi @davidbritch , thank you for your reply.

I understand this point or view, however Linux platform is currently being advertised on the page itself.

You can find references of Linux as a development host for DotNet Maui in the [docs/get-started/installation.md](docs/get-started/installation.md) page.

So either way, if Linux is effectively not a target host for development of .net Maui apps - and will never be-, I suggest that you remove everything regarding Linux from this doc as it misleads user to believe we can count on the vscode extension to work on Linux as well as on Windows.
Or at least that you indicate that this might be community driven so that you won't get further issues about Linux based stuff.

On the other hand, if Linux might become a potential development host at some point, you can also change the Installation step to match the one I gave, which worked for me and is perfectly valid to this day. It's fine if it comes with a disclaimer for Linux not being as well supported as Windows, at least users are aware.

Thanks for taking the time to review this, I imagine that a lot of bugs are coming and all need to be labelled and rerouted correctly, and that's easy to miss some stuff here and there.

Best regards

**Comment by davidbritch** [comment]
Hi @bebenlebricolo 

Thanks for your time explaining this to me. The VSCode docs were added while I was off, so I wasn't aware of the Linux references in there. Re-opening your issue!
