### ISSUE TITLE
Project Path is invalid instead of upgrading Xamarin project

### ISSUE THREAD

**Issue by valsar6** [dotnet/docs-maui#1601]
[Enter feedback here]
When I launch the command upgrade-assistant upgrade <sln or csproj> --non-interactive it results in "Project path is invalid" 
It doesn't  upgrade all eligible projects as enunciated in the page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f87ed969-8c7a-6921-ee37-deeb98d4ffde
* Version Independent ID: f87ed969-8c7a-6921-ee37-deeb98d4ffde
* Content: [Upgrade a Xamarin.Forms app to .NET MAUI with the .NET Upgrade Assistant - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/migration/upgrade-assistant)
* Content Source: [docs/migration/upgrade-assistant.md](https://github.com/dotnet/docs-maui/blob/main/docs/migration/upgrade-assistant.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by mrstrong79** [comment]
Same here. Followed instructions as of here:
https://learn.microsoft.com/en-us/dotnet/maui/migration/upgrade-assistant?view=net-maui-7.0

From command prompt on Windows 11 with Visual Studio 2022 installed - navigated to the solution directly then ran:
upgrade-assistant upgrade <My Xamarin Solution>.sln --non-interactive --skip-backup

Received:
Project path is invalid '<My Xamarin Solution>.sln'.

have tried various combinations including using the relative and full path to the solution file but same message received

**Comment by inimirpaz** [comment]
Same here (trying to upgrade a Xamarin.Forms to a .NET MAUI single project) . An up-to-date thorough guide would be great! (and required)
All Xamarin->.NET MAUI guides, not to mention the official one, leaves too many blank spaces to be filled in by hard guessing.

A step-by-step guide for upgrading to a .NET MAUI single project would be appreciated.

EDIT: Not to mention, when doing the procedure on a Mac instead of Windows.

**Comment by Saurbaum** [comment]
Glad to know I'm not the only one feeling this pain. Does this tool work at all?

**Comment by davidbritch** [comment]
The guide has since been updated. The recommended approach is now to use the Visual Studio upgrade assistant, rather than the CLI tool.

**Comment by inimirpaz** [comment]
@davidbritch what about VS for Mac (ok, it has been dismissed but how are we supposed to do that on MacOS then?)

**Comment by davidbritch** [comment]
@inimirpaz Use the CLI tool on a Mac. If it doesn't work it needs reporting to the engineers (see the file feedback link on the page).
