### ISSUE TITLE
How to do the steps in Visual Studio?

### ISSUE THREAD

**Issue by MaziarH** [dotnet/docs-maui#1602]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79b73ca7-405f-2916-b938-c2c0647f59b8
* Version Independent ID: 79b73ca7-405f-2916-b938-c2c0647f59b8
* Content: [Publish a .NET MAUI app for Android - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/)
* Content Source: [docs/android/deployment/index.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/index.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by MaziarH** [comment]
Thank you for the fundamentals, but how to do the steps in VS, and how to transfer to a device?

**Comment by davidbritch** [comment]
Take a look at https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-google-play and https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-ad-hoc
