### ISSUE TITLE
False or outdated information

### ISSUE THREAD

**Issue by hinnerkweiler** [dotnet/docs-maui#1603]
At
#### Ensure correct package format
I tried to follow these steps but on VS for Mac 17.6.1 (build 452) I do not have any options at least close to what is described or shown on the screenshots. Also the screenshots do not match the written advice.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52ddc473-7f14-f391-2589-1484ce1aa3be
* Version Independent ID: 52ddc473-7f14-f391-2589-1484ce1aa3be
* Content: [Publish a .NET MAUI Android app for Google Play distribution - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-google-play)
* Content Source: [docs/android/deployment/publish-google-play.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/publish-google-play.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @hinnerkweiler 

The doc is accurate for Android publishing from Visual Studio, not Visual Studio for Mac. Afraid that there are no plans to add instructions for doing the same from VSMac.

**Comment by hinnerkweiler** [comment]
Uh, wow...Thanks for the info @davidbritch

>there are no plans to add instructions for doing the same from VSMac.

As Microsoft has always been providing good documentation for their software. May I ask: Is that just "As a maintainer I personally don't care" or is this to be understood as another hint that VSMac is going to be abandoned in the foreseeable future?
