### ISSUE TITLE
Code doesn't work for TapGestureRecognizer for Span inside Label in MAUI

### ISSUE THREAD

**Issue by ajay-verma8245** [dotnet/docs-maui#1605]
Code doesn't work for TapGestureRecognizer for Span inside Label in MAUI. I have used all the approaches mentioned in this page but code is not working. 
Detailed information is mentioned in below StackOverflow question. 

https://stackoverflow.com/questions/76745269/tapgesturerecognizer-doesnot-work-for-span-inside-label-in-maui-net

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c427e307-ceac-31d6-95e6-d0de9638d371
* Version Independent ID: c427e307-ceac-31d6-95e6-d0de9638d371
* Content: [Recognize a tap gesture - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/tap)
* Content Source: [docs/fundamentals/gestures/tap.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/gestures/tap.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @inviajay 

Afraid this is due to a bug in .NET MAUI - see https://github.com/dotnet/maui/issues/8004. AFAIK, it's been fixed but I suspect the fix is only targeting the .NET 8 release.
