### ISSUE TITLE
Photo is always null

### ISSUE THREAD

**Issue by colemd1** [dotnet/docs-maui#1607]
[Enter feedback here]

Does not work.  Photo is always Null.  Capabilities for webcam and microphone were added to app manifest package.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e5277f4-f2e4-dffe-0c08-06531d4145a1
* Version Independent ID: 1e5277f4-f2e4-dffe-0c08-06531d4145a1
* Content: [Media picker for photos and videos - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device-media/picker?tabs=windows)
* Content Source: [docs/platform-integration/device-media/picker.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device-media/picker.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@colemd1 Which platform?

**Comment by colemd1** [comment]
Windows 11

**Comment by davidbritch** [comment]
Hi @colemd1 

Afraid this is a bug in WinUI3 that needs to be worked around. For more info, see https://github.com/dotnet/maui/issues/7660

This workaround is shipping as part of .NET MAUI 8.
