### ISSUE TITLE
FlexLayout position absolute reference is not available

### ISSUE THREAD

**Issue by ajay-verma8245** [dotnet/docs-maui#1617]
FlexLayout position absolute reference is not available

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b597471-8e79-032f-e023-f14ad564405d
* Version Independent ID: 1b597471-8e79-032f-e023-f14ad564405d
* Content: [FlexLayout - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/flexlayout)
* Content Source: [docs/user-interface/layouts/flexlayout.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/layouts/flexlayout.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Afraid this needs reporting in the [engineering repo](https://github.com/dotnet/maui) so that the engineers can fix the problem.
