### ISSUE TITLE
Copyable code full with "..."-s making it non working

### ISSUE THREAD

**Issue by jungjanos** [dotnet/docs-maui#1625]
Annoying that instead presenting a copy-pastable working example, its full with "..."-s which need to be manually cut after copy-pasting and ofcourse XAM and code behind do not fit together. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe0e2ced-1369-0fb5-bac9-d6678dfd913c
* Version Independent ID: fe0e2ced-1369-0fb5-bac9-d6678dfd913c
* Content: [ContentView - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/contentview)
* Content Source: [docs/user-interface/controls/contentview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/contentview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jungjanos 

Understood, but afraid it's something where we can't win. When we place full verbose XAML in the docs people complain about the examples being too long. The alternative is the approach we've gone with - only showing XAML relevant to the concept being covered.

Thanks for your feedback.
