### ISSUE TITLE
Notes tutorial: dotnet_bot PNG or SVG?

### ISSUE THREAD

**Issue by MV10** [dotnet/docs-maui#1628]
Minor, but confusing: 

On the [step 2](https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?tutorial-step=2) page of the Notes tutorial, the XAML breakdown says:

> `<Image>` displays an image, in this case it's using the `dotnet_bot.png` image that comes with every .NET MAUI project.

The XAML also references the PNG filename, but the solution template only includes an SVG file. 

I expected a crash, but it works... Is there some on-the-fly conversion that should be mentioned? 

![image](https://github.com/dotnet/docs-maui/assets/794270/070abb0b-642b-4c08-a17c-d52dd589835d)

Also, should each step link to Github issues? I had to jump ahead to the Conclusion page, so I guess the details below may be incorrect (or maybe not, I haven't really looked at the doc structure).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Version Independent ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Content: [Tutorial: Create a .NET MAUI app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?tutorial-step=0)
* Content Source: [docs/tutorials/notes-app/index.yml](https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 147524](https://dev.azure.com/msft-skilling/Content/_workitems/edit/147524)

**Comment by adegeo** [comment]
Hi @MV10 Since you have this open, can you test that if you change the XAML reference to .svg, it continues to work? It's been a few months since I've been in this area and I think the reason why it works is that MAUI actually takes the svg's and resizes them into png at build or runtime.

If changing the XAML to .svg is OK and everything works, then the tutorial should use .svg just to keep it the same as the actual source file.

**Comment by MV10** [comment]
@adegeo changing the XAML to .svg does not work.

Thought it was interesting the csproj can reference svg, but I suppose that's a build thing as well:

```
<!-- App Icon -->
<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

<!-- Splash Screen -->
<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

<!-- Images -->
<MauiImage Include="Resources\Images\*" />
<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />
```

**Comment by adegeo** [comment]
OK. So my assumption that it's transformed to .png during build is correct. Really just the reference to the project item needs to be fixed and perhaps a note added that says images are transformed to .png files, so the XAML uses .png.

Thanks for spotting this!

**Comment by MV10** [comment]
For what it's worth, I stumbled across a mention of this in [Change a .NET MAUI app icon](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons):

>  Important .NET MAUI converts SVG files to Portable Network Graphic (PNG) files. Therefore, when adding an SVG file to your .NET MAUI app project, it should be referenced from XAML or C# with a .png extension. The only reference to the SVG file should be in your project file.
