### ISSUE TITLE
Menu key accelerators

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1634]
.NET MAUI 8 includes keyboard accelerators for menu items. Keyboard accelerators enable you to assign keyboard shortcuts to any menu item, whether visible or not, and attach them to any UI element. 

```xaml
<ContentPage.MenuBarItems>
    <MenuBarItem Text="File">
        <MenuFlyoutItem Text="Preferences"
            Command="{Binding PreferencesCommand}"
        />
    </MenuBarItem>
    <MenuBarItem Text="Products">
        <MenuFlyoutItem 
            x:Name="AddProductMenu"
            Text="Add Product"
            Command="{Binding AddProductCommand}"
        />
        <MenuBarItem Text="Add Product Category"/>
    </MenuBarItem>
</ContentPage.MenuBarItems>
```

```csharp
MenuItem.SetAccelerator(AddProductMenu, Accelerator.FromString("Ctrl+A"));
```

https://github.com/dotnet/maui/pull/14740

See https://github.com/dotnet/maui/pull/16740 for the refactored API.

---
[Associated WorkItem - 164932](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164932)

**Comment by PureWeen** [comment]
FYI https://github.com/dotnet/maui/pull/16740
