### ISSUE TITLE
MVVM tutorial missing building blocks for mapping the VM

### ISSUE THREAD

**Issue by cabbruzzese** [dotnet/docs-maui#1638]
Making data binding to the values of sibling components is much less common than binding to a VM derived from a model. This tutorial contains no example of generating a VM from a model (without default properties) and do not serve as building blocks to get to that point. Since in a real world application data should be loaded from somewhere, mapped to a VM, and then displayed, this misdirect adds an unnecessary roadblock. Nobody finishing this will be able to take the next step in the MVVM process.

Providing an example of mapping a VM from another data source, which I assume would need to be done in the code-behind, is a much more important building block than the first 2 examples. I recommended replacing them with that kind of example or making a clear progression to another tutorial that focuses on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9905cd00-f3a1-7bdd-d678-ef6c71fb53b7
* Version Independent ID: 9905cd00-f3a1-7bdd-d678-ef6c71fb53b7
* Content: [Data binding and MVVM - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/mvvm)
* Content Source: [docs/xaml/fundamentals/mvvm.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/fundamentals/mvvm.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 157525](https://dev.azure.com/msft-skilling/Content/_workitems/edit/157525)

**Comment by davidbritch** [comment]
Hi @cabbruzzese 

It's a fair comment. We actually have a completely separate tutorial on MVVM - https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-mvvm/

The doc you saw should link to the tutorial. There's also https://learn.microsoft.com/en-us/dotnet/architecture/maui/ for more content about MVVM.
