### ISSUE TITLE
Release will only work with [XamlCompilation(XamlCompilationOptions.Skip)] on android

### ISSUE THREAD

**Issue by clharrysmith** [dotnet/docs-maui#1639]
Release version will only work with [XamlCompilation(XamlCompilationOptions.Skip)] on android MAUI C# app. 
After much frustration because the app that I would publish would crash on launch, I discovered by reading an obscure article that I should use   [XamlCompilation(XamlCompilationOptions.Skip)]  in my MainPage.cs file. It has worked fine snice, yet the article here states that this is not recommended. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12b6e5f6-7ab1-1373-242e-4f28cee2b773
* Version Independent ID: 12b6e5f6-7ab1-1373-242e-4f28cee2b773
* Content: [XAML compilation - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/xaml/xamlc)
* Content Source: [docs/xaml/xamlc.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/xamlc.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @clharrysmith 

That sounds like a linker issue - in some situations the linker can link out XAML. Were you using LinkAll?

**Comment by clharrysmith** [comment]
> Hi @clharrysmith 
> 
> That sounds like a linker issue - in some situations the linker can link out XAML. Were you using LinkAll?

I don't know what linkall is never heard of that setting. Where do I find that setting. I'm using the standard visual studio Maui templates, so I don't know what other information you could possibly require. I have also noticed that the Maui templates leave off a critical directory that you need to add. AKA images in resources. Why are Maui templates incomplete, and how do we complete them? What other settings or options or directories or classes do they leave out or have set incorrectly?

**Comment by davidbritch** [comment]
When you switch from Debug to Release mode it enables the linker, and in some situations the linker can remove parts of your code: https://learn.microsoft.com/en-us/dotnet/maui/android/linking?tabs=vs

The templates have these entries for images:

```xml
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />
```

The first entry tells .NET MAUI to include all images stored in the Resources\Images folder.
