### ISSUE TITLE
The sample can't work on iOS 

### ISSUE THREAD

**Issue by dingxiaolong** [dotnet/docs-maui#1641]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c787fde2-1c9c-62d4-2cdd-93681e0c1ff5
* Version Independent ID: c787fde2-1c9c-62d4-2cdd-93681e0c1ff5
* Content: [Reuse custom renderers in .NET MAUI - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/migration/custom-renderers)
* Content Source: [docs/migration/custom-renderers.md](https://github.com/dotnet/docs-maui/blob/main/docs/migration/custom-renderers.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by thimanshu1993** [comment]
Hello @dingxiaolong,

The sample appears to be functioning well on both iOS and Android platforms. I've included a .gif below for your reference.

Ensure that you're accessing the solution correctly on your MAC/Windows device, which is connected to a remote MAC machine via a network.

Follow these steps:

- Open the .sln file by double-clicking: maui-samples-main/Upgrading/CustomRenderer/MauiCustomRenderer.sln

- Run the project on a simulator. If you're using a physical device, ensure you have the appropriate provisioning profile.

Please provide details about the specific issue you're encountering if it still persists.

![Simulator Screen Recording - iPhone 14 Plus - 2023-08-17 at 16 00 26](https://github.com/dotnet/docs-maui/assets/56357686/4f0a6175-1eb5-4b23-b5d5-2d33bf39aa6f)

**Comment by davidbritch** [comment]
Closing, as the animated GIF above shows the sample working on iOS.
