### ISSUE TITLE
Where is the Blazor SwipeView?

### ISSUE THREAD

**Issue by genifycom** [dotnet/docs-maui#1648]
XAML is simply not going to fly. It is Blazor all the way.

We need a Blazor SwipeView equivalent.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0249dadd-67f1-3bf4-a386-6b7b3429612a
* Version Independent ID: 0249dadd-67f1-3bf4-a386-6b7b3429612a
* Content: [SwipeView - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/swipeview)
* Content Source: [docs/user-interface/controls/swipeview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/swipeview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @genifycom 

Engineering requests for Blazor should go to https://github.com/dotnet/aspnetcore

Thanks!
