### ISSUE TITLE
Installing OpenJDK, should we set JAVA_HOME variable or not?

### ISSUE THREAD

**Issue by ncarandini** [dotnet/docs-maui#165]
Following the instruction, I've downloaded the `microsoft-jdk-11.0.12.7.1-windows-x64 (1).msi` install program and run it.
As a rookie, I don't know if the predefined installation setup will work fine or if I have also to set JAVA_HOME variable:

![image](https://user-images.githubusercontent.com/139274/133896259-68b7dd25-4f4b-4077-903c-1628e92f46e2.png)

May I suggest to explain also this step in more detail (maybe with some clarifing text, maybe also with an image of the needed installation setup).

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
I don't believe it's required, I've never set this setting and Visual Studio seems to detect everything correctly.

Adding @jamesmontemagno and @ThisIsKirsch for comment.

If anything, we can at least explain install with the default options.

**Comment by jamesmontemagno** [comment]
I did not set it. I don't think you need to. Eventually this will be bundled into the installation of VS from my understanding like it is today for Xamarin.
