### ISSUE TITLE
Do we need to recreate a certificate and profile when publish the MAUI app?

### ISSUE THREAD

**Issue by DavidGuo0818** [dotnet/docs-maui#1651]
I am creating an MAUI app for IOS by using visual studio, and I am using the function of pair of Mac(it works). and the development is done, so I need to publish the app for the test, and I have researched the post of https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-ad-hoc?tabs=vs 

now, I have one question, my development Apple account has many certificates and a distributed profile for another app, do I need to create another certificate and profile for the current app, or just use the existing certificate and profile? Thank you

**Comment by davidbritch** [comment]
Hi @DavidGuo0818 

If it's a new app you'll need to create a new App ID, which in turn will require a new provisioning profile. But you should be able to use an existing certificate.

Having said all that, Apple provisioning is difficult. If you run into difficulties, create a new everything!
