### ISSUE TITLE
Documentation insufficient

### ISSUE THREAD

**Issue by SteveSwaringen** [dotnet/docs-maui#1664]
"In your project file, the `<MauiIcon>` item designates the icon" is not particularly helpful. I can't find any files in my project that have a `<MauiIcon>` tag in them. Can you be more specific about which project file this would be in?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Version Independent ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Content: [Change the app icon - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=android)
* Content Source: [docs/user-interface/images/app-icons.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/app-icons.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SteveSwaringen 

The project file (.csproj) for your .NET MAUI app project. Within it you should see:

```xml
<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
```
