### ISSUE TITLE
Do you need the MAUI workload for .NET SDK 7?

### ISSUE THREAD

**Issue by Suthaharjs** [dotnet/docs-maui#1665]
Hi,
I am setting up a DevOps pipeline on a Mac server and have already installed .NET SDK 7. Now, I'm wondering if I need to install the MAUI workload as well. If the answer is yes, could you please provide the script to do so? is it correct below one

sudo dotnet workload install maui

if i use sudo, how to provide  administrative access to system directories.

Thanks

**Comment by davidbritch** [comment]
Yes, `sudo dotnet workload install maui` is correct.
