### ISSUE TITLE
publish android

### ISSUE THREAD

**Issue by pcapozzi** [dotnet/docs-maui#1669]
[Enter feedback here]
completely missing the necessary details.  I have spent hours trying to get a apk that will run.  This doc is totally incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79b73ca7-405f-2916-b938-c2c0647f59b8
* Version Independent ID: 79b73ca7-405f-2916-b938-c2c0647f59b8
* Content: [Publish a .NET MAUI app for Android - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/)
* Content Source: [docs/android/deployment/index.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/index.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pcapozzi 

The overview doc is just that - an overview. There are three other docs that show how to generate an APK, depending on your publishing scenario.

**Comment by pcapozzi** [comment]
Why are they not mentioned in this doc?

**Comment by pcapozzi** [comment]
Why are they not mentioned in this doc?

**Comment by pcapozzi** [comment]
Why are those docs not referenced in this doc?

**Comment by davidbritch** [comment]
You're meant to use the TOC on the left hand side: 

![image](https://github.com/dotnet/docs-maui/assets/8092460/3d68e7b9-1f4f-430e-93fe-f5e72d257fdf)
