### ISSUE TITLE
Pretty much useless to help

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#1670]
No real how to and not up to date
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 479ebe15-bfd2-d049-7213-8f87c1887b92
* Version Independent ID: 479ebe15-bfd2-d049-7213-8f87c1887b92
* Content: [Set up a device for development - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/device/setup)
* Content Source: [docs/android/device/setup.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/device/setup.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sqlguy6212 

What exactly in the doc is inaccurate?
