### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by rogersm-uwosh** [dotnet/docs-maui#1676]
I'm running .NET MAUI on VSC using the .NET MAUI extension. Neither of those code samples - either in .cs or .xaml - worked, both generated errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 039cf416-fa7c-dca3-ef72-f9029c613ecd
* Version Independent ID: 039cf416-fa7c-dca3-ef72-f9029c613ecd
* Content: [TabbedPage toolbar placement on Android - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/platform-specifics/tabbedpage-toolbar-placement)
* Content Source: [docs/android/platform-specifics/tabbedpage-toolbar-placement.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/platform-specifics/tabbedpage-toolbar-placement.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rogersm-uwosh 

I've just tried the code in VS (see https://github.com/davidbritch/dotnet-maui-samples/tree/main/PlatformIntegration/PlatformSpecifics) and there are no errors. So it's either a VSCode setup problem for you, or a problem with the MAUI extension for VSCode.
