### ISSUE TITLE
Windows Debug - A cycle occurred while laying out the GUI

### ISSUE THREAD

**Issue by pishah** [dotnet/docs-maui#1683]
I get this debug error "A cycle occurred while laying out the GUI" when using the Windows Key to snap to size, but only for the smallest size that takes up 25% of the Screen. So if I do Windows Key + Left, it is fine and takes up half the screen. But if I then do Windows Key + Up to use the top left or right of the screen I get that error and the app closes.

It doesn't happen on all Maui apps, trying to reproduce what creates the error but so far having trouble finding the issue. I will update if I can find the exact cause. I am doing a lot of WinUI margins/padding etc in this app. Wish the error gave more information to try to help find the problem.

**Comment by davidbritch** [comment]
Hi @pishah 

Afraid this belongs in the [engineering repo](https://github.com/dotnet/maui) with a full reproduction project. Thanks!

**Comment by pishah** [comment]
Hi, thank you, sorry about that.
