### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#1684]
Like way too much "documentation" in Maui there is not enough information to be usefull.  Since you can create the DataTemplate in both XAML and C# there should be examples for both.  But there isn't
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39bf5dc2-df41-d0bc-55d6-e18aca8acabf
* Version Independent ID: 39bf5dc2-df41-d0bc-55d6-e18aca8acabf
* Content: [Data templates - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/datatemplate)
* Content Source: [docs/fundamentals/datatemplate.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/datatemplate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for your feedback.
