### ISSUE TITLE
Migrate from Xamarin.Forms App.Properties to .NET MAUI Preferences

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1690]
Users updating their apps from Xamarin.Forms to .NET MAUI will hit an issue if they stored data in their Forms app using the App.Properties dictionary. In .NET 6/7 App.Properties exists but throws a `NotSupportedException`, and tells them to use Microsoft.Maui.Storage.Preferences instead. In .NET 8, the App.Properties dictionary has been removed.

Write a doc on how to migrate their app data from App.Properties to .NET MAUI Preferences.

https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/application-class#properties-dictionary
https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.application.properties?view=net-maui-7.0
https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Core/Application.cs

---
[Associated WorkItem - 157241](https://dev.azure.com/msft-skilling/Content/_workitems/edit/157241)

**Comment by pawelFelcyn** [comment]
When will this be done? I'm experiencing this problem and it is very painfull and quite urgent for me. But I haven't found any solution so far.

**Comment by davidbritch** [comment]
@pawelFelcyn It should be ready by the end of the week.
