### ISSUE TITLE
This do not work -> Application.Current.UserAppTheme = AppTheme.Light; Always use System theme

### ISSUE THREAD

**Issue by robivin** [dotnet/docs-maui#1701]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6273db86-0a2f-d5c6-9be0-a30d495ceb45
* Version Independent ID: 6273db86-0a2f-d5c6-9be0-a30d495ceb45
* Content: [Respond to system theme changes - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/system-theme-changes)
* Content Source: [docs/user-interface/system-theme-changes.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/system-theme-changes.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Can you describe the problem in more detail?
