### ISSUE TITLE
Documentation on NumericValidationStyleBehavior is incorrect

### ISSUE THREAD

**Issue by Medit8r** [dotnet/docs-maui#1702]
[Enter feedback here]
I'm fairly certain that the code associated with the '.NET MAUI behaviour with a style' is incorrect.  If I have understood correctly, the intention is to create an attachedBehaviorProperty, which controls the attachement of another behavior.  So in this example, the **NumericValidationStyleBehavior** controls the attachment of the **NumericValidationBehavior** behavior.  Look at the NumericValidationStyleBehavior class.  **It does not contain any code which does numeric validation**.  The OnAttachBehaviourChanged handler, should set up **NumericValidationBehavior** objects, and add them to the entry.Behaviors, NOT MORE **NumericValidationStyleBehaviour** objects! 

So in the OnAttachBehaviorChanged method:

...
if(attachBehavior)
{
   // Attach the Numeric validation code to the view here.
   var validationBehavior = new NumericValidationBehavior();
   validationBehavior.OnAttachedTo(view);
   entry.Behaviors.Add(validateBehavior);
}
else
{
   Behavior toRemove = entry.Behaviors.FirstOrDefault(b => b is NumericValidationBehavior);
   if( toRemove != null) entry.Behaviors.Remove(toRemove);
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef07fb0b-8ad4-0d83-dbe0-8ecd2e281ad3
* Version Independent ID: ef07fb0b-8ad4-0d83-dbe0-8ecd2e281ad3
* Content: [Behaviors - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/behaviors)
* Content Source: [docs/fundamentals/behaviors.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/behaviors.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 167087](https://dev.azure.com/msft-skilling/Content/_workitems/edit/167087)

**Comment by davidbritch** [comment]
Hi @Medit8r 

That's one way of doing it. The issue here was the `...` in the code example, which indicated more code. I've added that code in now.
