### ISSUE TITLE
Off color Switch bar

### ISSUE THREAD

**Issue by Remusqs1** [dotnet/docs-maui#1709]
I'm not sure if this is the right place for this, and if it's not, I apologize.

The color of the Switch bar in the off state doesn't look good when the background color is dark. Currently, you can style the Switch bar for the On state with the OnColor property, but there is no similar property for the off state (the background property creates a rectangle around the entire Switch, so it's not useful in most cases).

I searched in the official Microsoft and .Net Maui documentation, but it doesn't seem like there's a way to style the bar in the off state. There is a post on StackOverflow that says that there is currently no way to do this: (https://stackoverflow.com/questions/74712389/net-maui-change-off-color-of-switch).

Does anyone know if there is actually a way to do this? Would it be possible to add a property to the Switch in the future to handle this case (something similar to OnColor, maybe "OffColor")?

Thank you in advance for your help.

**Comment by davidbritch** [comment]
Hi @Remusqs1 

You're correct - there's no way to currently do this. I'd recommend you open an enhancement request in the [engineering repo](https://github.com/dotnet/maui).
