### ISSUE TITLE
MAUI workloads not available for.

### ISSUE THREAD

**Issue by Prashanth-BC** [dotnet/docs-maui#171]
I am not able to see MAUI workloads in VS preview for mac anymore. How do I install it on mac? The installer for mac doesn't have the option of MAUI preview. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Prashanth-BC 

As per https://devblogs.microsoft.com/visualstudio/visual-studio-2022-for-mac-preview-1-is-now-available/, VS Mac 2022 for Mac Preview 1 only has very limited support for .NET MAUI. It will be extended to include workload installation, templates, build/deploy/debug in early 2022.
