### ISSUE TITLE
DeviceDisplay - more displays

### ISSUE THREAD

**Issue by gorkhadk** [dotnet/docs-maui#1710]
[Enter feedback here]
How do you get info/access second (or more) display(s)?
An array of available displays should be exposed and documented how or if you cannot.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e4536d2-1a25-9fbc-cb6b-6682131dee1b
* Version Independent ID: 6e4536d2-1a25-9fbc-cb6b-6682131dee1b
* Content: [Device Display Information - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/display?tabs=windows)
* Content Source: [docs/platform-integration/device/display.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device/display.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gorkhadk 

Afraid that .NET MAUI doesn't currently provide the ability to enumerate all the displays. You're best opening an enhancement request in the [engineering repo](https://github.com/dotnet/maui).
