### ISSUE TITLE
Details need updating

### ISSUE THREAD

**Issue by JRosanowski** [dotnet/docs-maui#1711]
CreateSupportFragment no longer takes a MauiContext. 
If you try to use the method it states that Forms.Init must be called beforehand.
All the Forms.Init methods are obsolete.
Even if you call Forms.Init then when you call CreateSupportFragment it throws a NullReferenceException.
This was using Visual Studio 17.8 Preview 2. 
Does this functionality still work?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94962e96-0bcc-18ee-8a87-3d75bd11a390
* Version Independent ID: 94962e96-0bcc-18ee-8a87-3d75bd11a390
* Content: [Native embedding - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/native-embedding)
* Content Source: [docs/platform-integration/native-embedding.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/native-embedding.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @JRosanowski 

The `CreateSupportFragment` method in the doc is an extension method that you're meant to add to your project, that does take a `MauiContext`. It's not the `CreateSupportFragment` method from Xamarin.Forms, which it sounds like you're inadvertently attempting to call.
