### ISSUE TITLE
`BindableProperty`: What is the difference between `propertyChanged` and `coerceValue` callbacks?

### ISSUE THREAD

**Issue by MartyIX** [dotnet/docs-maui#1713]
I have a bindable property in a control:

```cs
public partial class MarketsSelector : ContentView
{
  /// <summary>Bindable property for the selected markets property.</summary>
  public static readonly BindableProperty SelectedMarketsProperty = BindableProperty.Create(propertyName: nameof(SelectedMarkets), returnType: typeof(HashSet<Market>), declaringType: typeof(MarketsSelector), defaultBindingMode: BindingMode.TwoWay, coerceValue: OnSelectedMarketsChanged);
  
  /// <summary>Set containing the currently selected markets.</summary>
  public HashSet<Market> SelectedMarkets
      => (HashSet<Market>)this.GetValue(SelectedMarketsProperty);

  // ...
}
```

now I modify elements of the `SelectedMarkets` hash set (I add `Market` or remove a market) and I want to be notified of that. 

`SelectedMarketsProperty` can be assigned the `coerceValue` callback and `propertyChanged` callback but documentation for these two callbacks seem very similar (or it's somewhat hard to spot the difference for me):

* https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/bindable-properties#detect-property-changes
* https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/bindable-properties#coerce-value-callbacks

Notably the documetnation sentence `The specified callback method will be invoked when the value of the bindable property changes.` is exactly the same:

![image](https://github.com/dotnet/docs-maui/assets/203266/4aa63167-88c6-4966-8ec3-ee6a8fced37d)

![image](https://github.com/dotnet/docs-maui/assets/203266/e764bd1e-48c2-486a-a394-b88c70d88640)

Could that sentence be clarified a bit for one or the other callback? 

The reason why I mention this is because in my specific scenario, it seems like `propertyChanged` is called exactly once when `SelectedMarkets` is assigned a reference and `coerceValue` is called whenever I modify `SelectedMarkets` (which is what I want).

---
[Associated WorkItem - 167613](https://dev.azure.com/msft-skilling/Content/_workitems/edit/167613)

**Comment by davidbritch** [comment]
Hi @MartyIX 

Good spot! Obviously the property changed callback is invoked when the value of the bindable property has changed. Whereas the coerce value callback is invoked when the value of the bindable property is about to change, so that you can adjust the new value before it's applied.

So the coerce value callback is always invoked before the property changed callback.

**Comment by MartyIX** [comment]
Thank you for improving the documentation.

> So the coerce value callback is always invoked before the property changed callback.

So then I have discovered a bug because in my specific case, it did happen that my _coerce callback_ was called but not my _property changed callback_.

**Comment by larsduewel** [comment]
Same here, coerce callback is called i manipulate the return value. And in some cases the property changed handler, which should be called afterwards is not always being called. These seems to be a bug. :(
