### ISSUE TITLE
Java JDK versions

### ISSUE THREAD

**Issue by lywyn** [dotnet/docs-maui#173]
[Enter feedback here]
Switched to OpenJDK 11 but that breaks the Android Device Manager and the emulators cannot be created/edited/deleted. To get that working you have to set Visual Studio - Options - Xamarin - JDK path to OpenJDK version 8. So the Android tools break when using the new version 11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @lywyn 

Yes, afraid that's everyone's experience. You need OpenJDK 8 to manipulate emulators, but you need OpenJDK 11 to actually build apps. It's something that will hopefully be fixed for the next preview.
