### ISSUE TITLE
Sqlite Support by Microsoft

### ISSUE THREAD

**Issue by ysipankaja** [dotnet/docs-maui#1736]
Hi Team,

On this page you have provided support for SQLite via 3rd Party Nuget.
Why don't Microsoft themselves provide SQLite Nuget/Support for Maui, like the Community Toolkit that you created?
The same thing can also be said for Biometric support.

Also, SQLite Encryption info should also be provided as it would help the App Developer create more secure apps.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73164f27-28e1-7bf6-64ec-277ade9ac973
* Version Independent ID: 73164f27-28e1-7bf6-64ec-277ade9ac973
* Content: [.NET MAUI local databases - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/database-sqlite)
* Content Source: [docs/data-cloud/database-sqlite.md](https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/database-sqlite.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Yardi-PankajA 

Microsoft provides [Microsoft.Data.Sqlite](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/?tabs=netcore-cli) as a NuGet package, and it works on the platforms MAUI supports. It's also more fully featured and doc'd than sqlite-net-pcl. At some point after the .NET 8 launch in November I hope to update the docs to specify its use. In the meantime, give it a spin!
