### ISSUE TITLE
Replace sqlite-net-pcl with Microsoft.Data.Sqlite

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1770]
Microsoft has it's own Xamarin/MAUI compliant version of sqlite, [Microsoft.Data.Sqlite](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/?tabs=netcore-cli), which is available as a NuGet package. Update the [.NET MAUI local databases](https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/database-sqlite) to use it, with links back to the docs for Microsoft.Data.Sqlite.

While this is a priority work item, it's doubtful it'll be completed until after the .NET 8 launch mid-November.

Don't forget to update SUPPORT.md.

---
[Associated WorkItem - 177248](https://dev.azure.com/msft-skilling/Content/_workitems/edit/177248)

**Comment by davidbritch** [comment]
Scrapping this work item. It's too much of a step backwards.

**Comment by BaY1251** [comment]
it may useful

**Comment by dationguyen** [comment]
i must admit that using sqlite-net-pcl is a lot easier
