### ISSUE TITLE
Visual Studio for Mac has a fixed EOL date

### ISSUE THREAD

**Issue by AlexUrbanAc** [dotnet/docs-maui#1786]
### Type of issue

Outdated article

### Description

You are recommending to use Visual Studio for Mac to create .NET MAUI Apps that run under macOS.

However, Visual Studio for Mac will go EOL in August 2024: https://learn.microsoft.com/en-us/lifecycle/announcements/visual-studio-mac-end-of-servicing

Please advise on a non-EOL environment to build .NET MAUI Apps with macOS support.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=vswin#installation

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md

### Document Version Independent Id

9a62d421-d009-30b3-843e-a92bfc21c061

### Article author

davidbritch

---
[Associated WorkItem - 177249](https://dev.azure.com/msft-skilling/Content/_workitems/edit/177249)

**Comment by davidbritch** [comment]
This has been dealt with by #1865
