### ISSUE TITLE
Where are the steps to start an emulator before building ?

### ISSUE THREAD

**Issue by ocallesp** [dotnet/docs-maui#180]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ocallesp 

At the moment the [Build your first app](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=dotnet-cli) doc links to the Xamarin [Android emulator setup](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/) doc to talk you through creating an emulator. It will be replaced with inline steps on how to create an emulator soon. However, even in the latest preview it's a really error prone process.

**Comment by davidbritch** [comment]
Fixed by #183
