### ISSUE TITLE
Target Frameworks

### ISSUE THREAD

**Issue by abhidotnet** [dotnet/docs-maui#181]
There is a minor issue with the build. I am using a Windows Desktop with no access to iOS or iTunes.
This causes a hiccup in the build process. I have to go and edit the Target frameworks in the Application.

It would be helpful if the users could pick the OS that they are targetting via a wizard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @abhidotnet 

I hear you! I suggest you open an issue at [Developer Community](https://developercommunity.visualstudio.com/home) and it'll get forwarded to the correct engineering team for consideration. Thanks!
