### ISSUE TITLE
Style apps using Cascading Style Sheets

### ISSUE THREAD

**Issue by Magedn** [dotnet/docs-maui#1810]
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
I apply the steps in your page on .net7 project on VS. 2022, but it gives me error in compilation.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/styles/css

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/styles/css.md

### Document Version Independent Id

7897e970-6807-a516-d029-d5d0c27e15de

### Article author

davidbritch

**Comment by davidbritch** [comment]
Hi @Magedn 

As far as I can see the code in the doc works perfectly for me. You can see it in action at https://github.com/davidbritch/dotnet-maui-samples/tree/main/UserInterface/Styles/CSS
