### ISSUE TITLE
BuildAction

### ISSUE THREAD

**Issue by BillFulton** [dotnet/docs-maui#1830]
### Type of issue

Missing information

### Description

Hi. Nice docs. Maybe mention Build Action = MauiIcon.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=android

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/app-icons.md

### Document Version Independent Id

2fc2b28d-e403-c63e-b7c4-6639fcd05a89

### Article author

davidbritch

---
[Associated WorkItem - 194100](https://dev.azure.com/msft-skilling/Content/_workitems/edit/194100)

**Comment by davidbritch** [comment]
I'll give it a mention, but if you add the icon to the Resources\AppIcon of your project it should automatically get the correct build action.
