### ISSUE TITLE
There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed [C:\Users\Rudolf.Meyer\HelloMauiPreview\HelloMauiPreview.csproj]

### ISSUE THREAD

**Issue by Rudolf-Meyer** [dotnet/docs-maui#186]
How to **pair a mac for the dotnet cli build**? or how to refer to a mac thic is connected to either Visual Studio 2022 Preview or Visual Studio 2019? Do I have to add directives to HelloMauiPreview.csproj?

Console output see below:

C:\Users\Rudolf.Meyer\HelloMauiPreview> **dotnet build -f net6.0-ios**
Microsoft (R) Build Engine version 17.0.0-preview-21458-01+2c5510013 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
**C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.0.101-preview.10.61\tools\msbuild\iOS\Xamarin.Messaging.Apple.targets(31,3): warning : There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed [C:\Users\Rudolf.Meyer\HelloMauiPreview\HelloMauiPreview.csproj]**
  HelloMauiPreview -> C:\Users\Rudolf.Meyer\HelloMauiPreview\bin\Debug\net6.0-ios\iossimulator-x64\HelloMauiPreview.dll

Build succeeded.

C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.0.101-preview.10.61\tools\msbuild\iOS\Xamarin.Messaging.Apple.targets(31,3): warning : There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed [C:\Users\Rudolf.Meyer\HelloMauiPreview\HelloMauiPreview.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.47

C:\Users\Rudolf.Meyer\HelloMauiPreview>

**Comment by davidbritch** [comment]
Hi @Rudolf-Meyer 

Afraid the tooling isn't ready yet for pairing to Mac.
