### ISSUE TITLE
Add User Messaging Platform SDK of Google in DotNet Maui mobile app 

### ISSUE THREAD

**Issue by MaVietTung** [dotnet/docs-maui#1866]
### Type of issue

Other (describe below)

### Description

Google proivide a sdk for UMP on android mobile https://support.google.com/admob/answer/10113005 but I dont know how to add this in my dotnet maui project

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/supported-platforms

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/supported-platforms.md

### Document Version Independent Id

ba07354c-611d-5efe-0fbb-48a24d02cafe

### Article author

davidbritch

**Comment by davidbritch** [comment]
Hi @MaVietTung 

You basically have to bind the library yourself in a .NET Android project (class library). Then reference that class library from your MAUI project. The instructions for Xamarin.Android are still valid: https://learn.microsoft.com/en-us/xamarin/android/platform/binding-java-library/
