### ISSUE TITLE
How to reuse Xamarin Dependency Service in .NET MAUI?

### ISSUE THREAD

**Issue by quanvm97** [dotnet/docs-maui#187]
I have an interface:

> public interface ITest
>     {
>         string GetString();
>     }

And implement:

> public class Test : ITest
>     {
>         public Test() { }
> 
>         public string GetString()
>         {
>             return "Message for testing";
>         }
>     }

At implement class, do we need to call "`[assembly: Dependency(typeof(Test))]`"?

And when I want to use the GetString function, will I call:

> var test = DependencyService.Get<ITest>().GetString();

Is it same as we use in Xamarin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62c6f63-7e33-d81d-28db-b9ba40919408
* Version Independent ID: e3bf5b48-ed62-c664-1c33-294c0e762e57
* Content: [.NET MAUI app startup - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/app-startup)
* Content Source: [docs/fundamentals/app-startup.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/app-startup.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @quanvm97 

`DependencyService` will eventually work, purely to provide an easy upgrade path for Xamarin.Forms to .NET MAUI. However, it won't be the optimal way to invoke code on a platform.

The .NET MAUI approach is to use partial classes. The idea is that in your cross-platform code you'd call `GetString`, and place your platform implementations as partial classes in the **Platforms > Android**, **Platform > iOS** (etc.) folders. Multi-targeting will then take care of the rest (only compiling the iOS GetString method for iOS, the Android GetString method for Android etc.).

Hope this makes sense.

**Comment by quanvm97** [comment]
@davidbritch , So how can i use it in any function? I just call "GetString()" or have to declare the service in main() before called?

**Comment by davidbritch** [comment]
Hi @quanvm97 

I've put together a simple demo to demo the technique (see attachment). I forgot to mention it requires partial methods, as well as partial classes.

In your xplat code define a partial method in a partial class:

```
namespace MauiApp3
{
    public partial class MyService
    {
        public partial string GetString();
    }
}
```

Then in the relevant Platform folder in the project, define the same partial class (in the same namespace) and the same partial method, but also provide the method implementation.

Android:

```
namespace MauiApp3
{
    public partial class MyService
    {
        public partial string GetString()
        {
            return "Android";
        }
    }
}
```

Windows:

```
namespace MauiApp3
{
    public partial class MyService
    {
        public partial string GetString()
        {
            return "Windows";
        }
    }
}
```

Then invoke it in xplat code as you might expect:

```
			MyService service = new MyService();
			System.Diagnostics.Debug.WriteLine(service.GetString());
```

Hope this helps!

[MauiApp3.zip](https://github.com/dotnet/docs-maui/files/7424782/MauiApp3.zip)
