### ISSUE TITLE
iOS BundleResource is not available

### ISSUE THREAD

**Issue by vindberg** [dotnet/docs-maui#1870]
### Type of issue

Typo

### Description

Regarding the infoPlist.strings for localization of iOS. The build action of the file properties "**BundleResource**" is not available in the dropdown.

Looking in the demo solution "LocalizationDemo" the iOS .strings files are all set to Build Action: "**None**".

How do I include the files in the build?
Thanks.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/localization#perform-platform-setup

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/localization.md

### Document Version Independent Id

ce02582a-559e-5276-761c-d4bcb33c68ae

### Article author

davidbritch

---
[Associated WorkItem - 185289](https://dev.azure.com/msft-skilling/Content/_workitems/edit/185289)

**Comment by davidbritch** [comment]
VS or VSMac?

**Comment by davidbritch** [comment]
Ultimately it should be BundleResource. It's possible that switching the solution between VS + VSMac has messed up what's in the .csproj. IIRC, the build action was automatically set to BundleResource provided that the file was dropped into the correct folder.

**Comment by vindberg** [comment]
In VS. 
Also, In the demo project, the .strings files are not set to any build action.

**Comment by davidbritch** [comment]
Hi again,

After some investigation I agree that `BundleResource` isn't settable in VS, but is settable in VSMac. I remember now that I did the iOS/MacCat part of the sample in VSMac, then checked it worked in VS.

I also remember that the .csproj for the sample originally had lots of entries (e.g. a BundleResource for each .strings file on iOS). So I simplified the .csproj file manually to include all the contents of the Platforms\iOS\Resources\ folder as BundleResource items: https://github.com/dotnet/maui-samples/blob/0b2580f00ebfbe97a299e73d6dd74d79c9c23f7a/7.0/Fundamentals/Localization/LocalizationDemo/LocalizationDemo.csproj#L88

This ensures that both VS and VSMac include the contents of that folder as BundleResource files, even if you can't set the build action directly in VS. Obviously this should have been explained in the doc. So I'll leave this issue open until I can update it.

Hope this helps.

**Comment by vindberg** [comment]
Thanks for clearing up the confusion. I will add the folders as in the demo. 

Cheers.
