### ISSUE TITLE
Color Font  TextType Html

### ISSUE THREAD

**Issue by elquintero** [dotnet/docs-maui#1898]
### Type of issue

Typo

### Description

The following example does not work if it shows the style "strong" but the font is not displayed in red :

`<Label Text="This is &lt;strong style=&quot;color:red&quot;&gt;HTML&lt;/strong&gt; text." TextType="Html"  />`

```
Label label = new Label
{
    Text = "This is <strong style=\"color:red\">HTML</strong> text.",
    TextType = TextType.Html
};
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/label?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/label.md

### Document Version Independent Id

243e6d1d-a276-814f-7943-ff0fa7ba017e

### Article author

davidbritch

### Metadata

* ID: 243e6d1d-a276-814f-7943-ff0fa7ba017e 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @elquintero 

Are you using hot reload? When I tried it with hot reload the red text wasn't strong. But after a full build it was strong and red:

![image](https://github.com/dotnet/docs-maui/assets/8092460/b3c0361e-b5ca-43af-94e6-6d8ac585edde)
