### ISSUE TITLE
The <MauiVersion>8.0.0-rc.2.9511</MauiVersion> shown in the example, should be the RTM version, should it not?

### ISSUE THREAD

**Issue by TonyLugg** [dotnet/docs-maui#1906]
### Type of issue

Other (describe below)

### Description

Sample MauiVersion shows an RC version, should be RTM.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-8?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/whats-new/dotnet-8.md

### Document Version Independent Id

1abc248e-68ab-afa8-4b3d-7fc5e77f255b

### Article author

davidbritch

### Metadata

* ID: 1abc248e-68ab-afa8-4b3d-7fc5e77f255b 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

---
[Associated WorkItem - 185490](https://dev.azure.com/msft-skilling/Content/_workitems/edit/185490)

**Comment by davidbritch** [comment]
Hi @TonyLugg 

Yes and no. What I was trying to do was showing how to pin to a specific version other than the latest release. As there's only one RTM version right now I chose to use the last RC. But as it's causing some confusion I'll change it to the RTM version. That way when the first SR is released the example will make a bit more sense.
