### ISSUE TITLE
"Build you first .NET MAUI app" guide does not seem to be right

### ISSUE THREAD

**Issue by Stuart88** [dotnet/docs-maui#191]
Following these guides: 
https://docs.microsoft.com/en-gb/dotnet/maui/get-started/installation
https://docs.microsoft.com/en-gb/dotnet/maui/get-started/first-app?pivots=windows

I've installed VS 2022 Preview as directed, created a new MAUI project, but there is no option to run or install any Android emulator. So I'm first having to go back to the VS Installer and manually add the Android emulator.

Also when I build the project it tells me to "Setup Hot Restart", the first step of which is to download iTunes??? I don't want that on my computer. I cannot bypass this, so my second look into the MAUI framework is once again stopped short. 

I find this strange because the guide only seems to focus on Android, yet the issue I'm facing here is relating to iOS, which I have no intention of ever working with.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-gb/dotnet/maui/get-started/first-app?pivots=windows)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by Stuart88** [comment]
Could not get Android emulator working on my machine, so maybe it's a local issue for me. It runs fine if I connect a real device by USB.

However I still wonder about that iOS 'Setup Hot Restart' warning!

**Comment by davidbritch** [comment]
Hi @Stuart88 

Visual Studio uses a feature called hot restart to deploy iOS apps to a device. Hot restart uses functionality that Apple only bundle in iTunes (on Windows), hence the request to install it. Visual Studio trying to build/deploy for iOS, when you probably didn't tell it to, is a bug. It's happened to me too (although it doesn't happen regularly). It's a bug that the engineers are aware of, so will hopefully be fixed soon enough.
