### ISSUE TITLE
About ActivityIndicator documentation is useless

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#1922]
### Type of issue

Other (describe below)

### Description

The examples here are useless,  they do not show how to show it with its properties when there is a long activity to deal with

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/activityindicator?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/activityindicator.md

### Document Version Independent Id

a8770371-5b53-c53f-25b4-f983e3beb4ce

### Article author

@davidbritch

### Metadata

* ID: a8770371-5b53-c53f-25b4-f983e3beb4ce 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @sqlguy6212 

What's the issue here? It's just a case of binding to a bool (view model) property that says whether the task is still running or not?
