### ISSUE TITLE
MSB6006: "java.exe" exited with code 2

### ISSUE THREAD

**Issue by nl3rz** [dotnet/docs-maui#193]
Hello Team, 

I'm not sure why this code keeps following me around but it must be something I changed from an update to a Java package somewhere.  I'm not able to debug to Android for MAUI or Xamarin for any brand new project creation.

After performing deep research for this issue, I still have not been able to identify a solution which works for me.

Would someone from your team be able to provide advice, a solution, or be able to point me in the right direction on how to resolve this issue?  Thanks for all your help.

Best Regards,

**Comment by davidbritch** [comment]
Hi @nl3rz 

This is an issue to direct to the [engineering repo](https://github.com/dotnet/maui), with full reproduction details.

**Comment by nl3rz** [comment]
Thanks David for the feedback.  I'll definitely follow up there.  Have a great weekend.
