### ISSUE TITLE
Custom namespace documentation refers to AssemblyInfo.cs which is autogenerated

### ISSUE THREAD

**Issue by agrisyst-slo** [dotnet/docs-maui#1932]
### Type of issue

Missing information

### Description

The documentation states that the custom namespace definitions should be added to the AssemblyInfo.cs file.
But since this file is autogenerated for the different platforms, where should the definitions be declared?

And a working example project should be welcome too. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/xaml/namespaces/custom-namespace-schemas?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/xaml/namespaces/custom-namespace-schemas.md

### Document Version Independent Id

5f1f8814-d976-7a43-edde-79ead359ec1c

### Article author

@davidbritch

### Metadata

* ID: 5f1f8814-d976-7a43-edde-79ead359ec1c 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

---
[Associated WorkItem - 192375](https://dev.azure.com/msft-skilling/Content/_workitems/edit/192375)

**Comment by davidbritch** [comment]
Hi @agrisyst-slo 

Now that AssemblyInfo.cs doesn't exist, you can add the relevant attributes to any code file in your project. You could even add a file called AssemblyInfo.cs and add them there.
