### ISSUE TITLE
How do you share a class between MAUI and an ASP.NET Web API Service?

### ISSUE THREAD

**Issue by jbendler1** [dotnet/docs-maui#1935]
### Type of issue

Missing information

### Description

[Enter feedback here]
You talk about it, but how do you share a class between MAUI and an ASP.NET Web API Service?

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/rest?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/rest.md

### Document Version Independent Id

851edc00-2289-d52f-106f-0eb968a7792d

### Article author

@davidbritch

### Metadata

* ID: 851edc00-2289-d52f-106f-0eb968a7792d 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

---
[Associated WorkItem - 194101](https://dev.azure.com/msft-skilling/Content/_workitems/edit/194101)

**Comment by davidbritch** [comment]
Hi @jbendler1 

There's nothing special involved in doing this - you just have to duplicate your POCO class in each project. The key point is you can't used any .NET MAUI types in your duplicated class.

**Comment by medkane** [comment]
The 2 projects can be holded in the same VS solution and they refer to the same shared project in which you define your models and DTOs
