### ISSUE TITLE
Windows paths seem incorrect, compared to iOS & Android paths

### ISSUE THREAD

**Issue by wolfgang-ironsoftware** [dotnet/docs-maui#1943]
### Type of issue

Typo

### Description

The Windows paths configured in the csproj file don't include a sublevel, whereas the Mac OS, iOS & Android paths do.

I believe this:

```xml
<!-- Windows -->
<ItemGroup Condition="$(TargetFramework.Contains('-windows')) != true">
  <Compile Remove="**\*.Windows.cs" />
  <None Include="**\*.Windows.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
</ItemGroup>
```

... should be ...

```xml
<!-- Windows -->
<ItemGroup Condition="$(TargetFramework.Contains('-windows')) != true">
  <Compile Remove="**\**\*.Windows.cs" />
  <None Include="**\**\*.Windows.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
</ItemGroup>
```

I think this mistake is repeated in several other docs (e.g. documentation on how to create a custom video control for MAUI using handlers).

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/configure-multi-targeting?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/configure-multi-targeting.md

### Document Version Independent Id

bf87eb8f-c235-d80d-ca9f-827d4e55f74d

### Article author

@davidbritch

### Metadata

* ID: bf87eb8f-c235-d80d-ca9f-827d4e55f74d 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

---
[Associated WorkItem - 192824](https://dev.azure.com/msft-skilling/Content/_workitems/edit/192824)

**Comment by davidbritch** [comment]
Hi @wolfgang-ironsoftware 

Thanks for raising this issue. Looks like you're right, but investigating further because I have a solution with identical XML and it appears to be working fine on Windows.

**Comment by wolfgang-ironsoftware** [comment]
Yeah it's weird it seems to work fine on Windows. Not sure if that makes sense. I think changing the path to be similar to macOS, iOS and Android **_also_** works fine. But doing the shorter paths on macOS, iOS or Android causes issues.

Maybe this hides a bug somewhere ...

**Comment by davidbritch** [comment]
So the honest answer as to why the docs use `/**/**/` for Android/iOS/Mac, and then `/**/` for Windows is because that's exactly what MAUI does: https://github.com/dotnet/maui/blob/main/src/MultiTargeting.targets

It looks like using `/**/**/` is fine on all platforms (but still confirming). https://learn.microsoft.com/en-us/dotnet/core/extensions/file-globbing tells us that `/**/` defines an arbitrary directory depth.

It may be that this all comes down to the runtimes. CoreCLR is used on Windows, but Mono on iOS/Android/Mac.

**Comment by davidbritch** [comment]
Although, I have a project with:

```xml
	<ItemGroup Condition="$(TargetFramework.StartsWith('net8.0-android')) != true">
		<Compile Remove="**\*.Android.cs" />
		<None Include="**\*.Android.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.StartsWith('net8.0-ios')) != true AND $(TargetFramework.StartsWith('net8.0-maccatalyst')) != true">
		<Compile Remove="**\*.MaciOS.cs" />
		<None Include="**\*.MaciOS.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.Contains('-windows')) != true ">
		<Compile Remove="**\*.Windows.cs" />
		<None Include="**\*.Windows.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>
```

It's built on iOS/Android with the modified paths.

**Comment by davidbritch** [comment]
So yeah, it's been confirmed to me that the above XML (in my last comment) is correct. So unless you've seen a problem in using that syntax, I'll update the docs to that effect.
