### ISSUE TITLE
Nested virtualization allowed for Android emulator

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#1956]
Generally, the Android Emulator can run accelerated on Azure VMs, as long as nested virtualization is enabled.

Update [Enable hardware acceleration for the Android emulator (Hyper-V & AEHD) - .NET MAUI | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/maui/android/emulator/hardware-acceleration?view=net-maui-8.0) to remove the message that says that nested virtualization doesn't work:

![image](https://github.com/dotnet/docs-maui/assets/8092460/d480767c-17a2-44fe-8c70-6fb6887df6e2)

We should instead say it can work on virtual machines with Hyper-V, including Microsoft DevBox, as long as nested virtualization is enabled in the VM.

---
[Associated WorkItem - 192823](https://dev.azure.com/msft-skilling/Content/_workitems/edit/192823)

**Comment by davidbritch** [comment]
@BretJohnson Is this purely about DevBox? e.g. you can run an Android emulator in DevBox provided that nested virtualization is enabled, but that might not apply to VirtualBox, VMWare, or Docker?

**Comment by BretJohnson** [comment]
@davidbritch It's not just DevBox.

For WHPX/Hyper-V as the hypervisor: The Android emulator can work on Azure VMs (e.g. for Azure DevTest Labs VMs) with nested virtualization enabled for the image using the steps here https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1505821. It can work for local Hyper-V images, using similar steps.

For VMware as the hypervisor: This doc https://www.nakivo.com/blog/vmware-nested-virtualization-explained-use-cases-and-tutorial seems to indicate that VMware and modern versions of other hypervisors also now support nested virtualization. So it may work there (but we can't say that with confidence without trying it).

Could we add Hyper-V requirement text like this, under "Verify support for Hyper-V"?:   "If Windows itself is running inside a virtual machine, nested virtualization must be enabled in the host hypervisor."
