### ISSUE TITLE
roadmap for .NET MAUI 9 & 10

### ISSUE THREAD

**Issue by shilpaCM** [dotnet/docs-maui#1959]
### Type of issue

Typo

### Description

Hi, Would like to know features planned part of .NET MAUI version 9 & 10. please provide me where i can find roadmap for .NET MAUI version 9 and 10. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-7?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/whats-new/dotnet-7.md

### Document Version Independent Id

d951aa88-bfc9-1071-9ed8-d4e8f37f3bce

### Article author

@davidbritch

### Metadata

* ID: d951aa88-bfc9-1071-9ed8-d4e8f37f3bce 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @shilpaCM 

The roadmap lives in the engineering repo - https://github.com/dotnet/maui/wiki/Roadmap

It's a bit thin right now because it's still being planned.
