### ISSUE TITLE
Incomplete documentation around .NET 8 SDK with Visual Studio for Mac

### ISSUE THREAD

**Issue by Kapusch** [dotnet/docs-maui#1961]
### Type of issue

Missing information

### Description

From the current documentation, we could suppose everything would work with .NET 8 after we followed steps mentioned below:

1. Download the Visual Studio 2022 For Mac
2. ...
3. Install .NET 8 through the [standalone installer](https://dotnet.microsoft.com/en-us/download/dotnet/8.0).
4. After .NET 8 has finished installing, run dotnet workload install maui in a terminal.

But, [according to this ticket](https://developercommunity.visualstudio.com/t/Net-8-not-working-on-VS-for-mac/10516623#T-N10517725), there is one missing step which is to activate .NET 8 SDK under "Preferences/Preview Features":
> Hi, in order to use the .NET 8 SDK with Visual Studio for Mac you have to enable this feature in Preferences - Other - Preview Features - Use the .NET 8 SDK if installed.
> 
> Also note that the .NET 8 support in Visual Studio for Mac is still in preview and some things may not work or be fully implemented.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=vsmac#installation-2

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md

### Document Version Independent Id

9a62d421-d009-30b3-843e-a92bfc21c061

### Article author

@davidbritch

### Metadata

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

---
[Associated WorkItem - 194249](https://dev.azure.com/msft-skilling/Content/_workitems/edit/194249)

**Comment by davidbritch** [comment]
Hi @Kapusch 

This is explained when you build your first app, at https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=devices-ios&view=net-maui-8.0&tabs=vsmac, rather than in the installation doc.

**Comment by Kapusch** [comment]
Thank you @davidbritch , I understand this is not a miss then.
But still, this section is confusing for scenario where I am redirecting my readers to the installation steps before they can launch my open source project.

Shouldn't we "duplicate" the same information there as well?

**Comment by davidbritch** [comment]
@Kapusch Sure, why not. One for tomorrow.
