### ISSUE TITLE
This article mentions Command but no example

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#1971]
### Type of issue

Other (describe below)

### Description

I have done tests and I cannot get Command to work with TapGestureRecognizer.  Perhaps this is why there is no example??

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/tap?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/gestures/tap.md

### Document Version Independent Id

c427e307-ceac-31d6-95e6-d0de9638d371

### Article author

@davidbritch

### Metadata

* ID: c427e307-ceac-31d6-95e6-d0de9638d371 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

**Comment by davidbritch** [comment]
This sample shows the `Command` property working:  https://github.com/davidbritch/dotnet-maui-samples/tree/main/Fundamentals/Gestures/TapGesture
