### ISSUE TITLE
Steps only documented for Android... but Windows (and/or iOS)?

### ISSUE THREAD

**Issue by jaldinger** [dotnet/docs-maui#198]
I have been trying to find the steps to launch a MAUI Windows App forever, but can't find anything at all. This should be the best place to actually include the steps on how to run (and debug) MAUI on Windows, too, not just Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jaldinger 

As the product moves nearer to completion these docs, and more, will be added.
