### ISSUE TITLE
Error with .NET MAUI 7.0: Documentation implementation not working

### ISSUE THREAD

**Issue by Ruben1204** [dotnet/docs-maui#1980]
### Type of issue

Outdated article

### Description

I tried to apply the code provided in the documentation, but I was surprised to see that it does not work. Specifically, it does not recognize the KeyboardAccelerators property as an attached property of MenuFlyoutItem. I would appreciate it if this were fixed so that I can implement this functionality.

### Page URL

https://learn.microsoft.com/es-es/dotnet/maui/user-interface/keyboard-accelerators?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/keyboard-accelerators.md

### Document Version Independent Id

cb419d01-581a-15ae-65f6-c6d86e451c3e

### Article author

@davidbritch

### Metadata

* ID: cb419d01-581a-15ae-65f6-c6d86e451c3e 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

**Comment by Ruben1204** [comment]
In .NET MAUI 8.0, it works perfectly.

**Comment by davidbritch** [comment]
Hi @Ruben1204 

You've hit the nail on the head with what the issue is. Keyboard accelerators were only introduced in .NET 8, hence you have to be using .NET 8 to use them. The doc about them only appears if you've selected .NET MAUI 8 in the version selector.

**Comment by Ruben1204** [comment]
Thanks.
