### ISSUE TITLE
using display alert message cut in dialogue

### ISSUE THREAD

**Issue by Parthu11** [dotnet/docs-maui#1990]
### Type of issue

Other (describe below)

### Description

using display alert my message cut in alert dialogue not proper show my full message

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pop-ups?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pop-ups.md

### Document Version Independent Id

144c1b04-ddfc-e59b-773f-94124fbbce7a

### Article author

@davidbritch

### Metadata

* ID: 144c1b04-ddfc-e59b-773f-94124fbbce7a 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @Parthu11 

If you believe this is a bug you need to report it in the [engineer repo](https://github.com/dotnet/maui). Thanks!
