### ISSUE TITLE
Build your first Maui app - not working

### ISSUE THREAD

**Issue by PaulGH** [dotnet/docs-maui#200]
Hi, 
Version 17.1.0 Preview 1.0 

Step 5 "In the Android SDK License Acceptance window..."
How do we get to this window?  

Also, the app was born with 11 errors.  Among these are:
**NETSDK1139	The target platform identifier android was not recognized.
NETSDK1139	The target platform identifier maccatalyst was not recognized.
NETSDK1139	The target platform identifier ios was not recognized.**

and several of these:
**CS0234	The type or namespace name 'Maui' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	MauiApp1 (net6.0-windows10.0.19041)**	

Any help on these would also be appreciated.

Thanks in advance,
Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by PaulGH** [comment]
Reinstalled the Android SDK - the process actually uninstalled the packages that were installed by the Preview, then re-installed these.
Next, closed and re-opened the solution.  Instead of 11 errors, there are now 4
**NETSDK1139**	The target platform identifier android was not recognized.	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets
NETSDK1139	The target platform identifier ios was not recognized.	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets
NETSDK1139	The target platform identifier maccatalyst was not recognized.	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets

**NETSDK1047**	Assets file 'C:\Projects\Maui\MauiApp1\obj\project.assets.json' doesn't have a target for 'net6.0-windows10.0.19041/win-x64'. **_Ensure that restore has run_** and that you have included 'net6.0-windows10.0.19041' in the TargetFrameworks for your project. You may also need to include 'win-x64' in your project's RuntimeIdentifiers.	MauiApp1	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	

How do I "ensure that restore has run"?  Confirmed that 'net6.0-windows10.0.19041' is in the TargetFrameworks section of the .CSProj file.

Thanks in advance.

**Comment by PaulGH** [comment]
Just tried uninstalling the Preview and reinstalling.  Same result.  For some reason the dependencies are never 'restored'.  not sure what that means. is 'restoring' something I should be able to do in VS?

Thanks again.

**Comment by davidbritch** [comment]
Hi @PaulGH 

The dependencies should be restored automatically. It's something Visual Studio should do for you.

As this is a product issue, it's something best raised in the [engineering repo](https://github.com/dotnet/maui).

**Comment by aoshiwik** [comment]
Why was this closed, encountered the same error

**Comment by amsaighi** [comment]
Hello, 

I got the same issue, I verified all my config, it was good. 
The resolve this issue, I used to updated my Android SDK Tools using SDK Manager in Android Studio

Here :

![SDK Tools](https://user-images.githubusercontent.com/3142753/163668047-260da143-d208-44e8-8210-0e8d4aff9b72.PNG)

 After updating my SDK Tools, I cleaned to solution, I had chose my Android Emulator 

![AVM](https://user-images.githubusercontent.com/3142753/163668092-bcb12855-1b1a-4dd7-aff4-061b9f88066a.PNG)

Good luck, and happy MAUI
