### ISSUE TITLE
Label Font Sizes like Medium Large, Value reference is missing

### ISSUE THREAD

**Issue by ajay-verma8245** [dotnet/docs-maui#2000]
### Type of issue

Missing information

### Description

[Enter feedback here]
Label Font Sizes like Medium Large, Value reference is missing

It should state What is the value of below items:
Medium - 
Large - 
Extra Large

etc...

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/fonts?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/fonts.md

### Document Version Independent Id

76a7b4ff-2889-6a85-aa3f-075ae6c07387

### Article author

@davidbritch

### Metadata

* ID: 76a7b4ff-2889-6a85-aa3f-075ae6c07387 
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @inviajay 

The `NamedSize` enumeration, which allows you set a font size like `Medium`, `Large` etc. is deprecated in .NET MAUI (https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.namedsize?view=net-maui-8.0). This is why the doc doesn't mention it.
