### ISSUE TITLE
Add mobile deep linking docs

### ISSUE THREAD

**Issue by davidortinau** [dotnet/docs-maui#2006]
With .NET 8 we have deep linking for mobile. Please add this to the MAUI docs, and consolidate the Blazor Hybrid doc on this topic as needed. 

https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-8.0&pivots=maui#deep-linking
https://github.com/Redth/MAUI.AppLinks.Sample

---
[Associated WorkItem - 205439](https://dev.azure.com/msft-skilling/Content/_workitems/edit/205439)

**Comment by davidbritch** [comment]
Related: https://github.com/dotnet/docs-maui/issues/382
