### ISSUE TITLE
Step 4 of Build your first Maui app - Dependencies not present/restored

### ISSUE THREAD

**Issue by PaulGH** [dotnet/docs-maui#201]
VS 2022 Preview 17.1
Step 4: 
it appears that the Dependencies have not been 'restored' - all of these have a yellow yield sign.
how do we get these to restore?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @PaulGH 

The dependencies should be restored automatically by Visual Studio. The fact that they haven't either indicates a broken install, internet connectivity issues, or a bug. It's one to raise in the [engineering repo](https://github.com/dotnet/maui).
