### ISSUE TITLE
GraphicsView example canvas.SetFillPaint(imagePaint, RectF.Zero); doesn't work for WinUI

### ISSUE THREAD

**Issue by Overdrive77** [dotnet/docs-maui#2017]
### Type of issue

Code doesn't work

### Description

The following example works on an Android device but not on Windows. When running as a windows app, I get a plain white rectangle and not the selected image. 

using System.Reflection;
using IImage = Microsoft.Maui.Graphics.IImage;
using Microsoft.Maui.Graphics.Platform;

IImage image;
Assembly assembly = GetType().GetTypeInfo().Assembly;
using (Stream stream = assembly.GetManifestResourceStream("GraphicsViewDemos.Resources.Images.dotnet_bot.png"))
{
    image = PlatformImage.FromStream(stream);
}

if (image != null)
{
    ImagePaint imagePaint = new ImagePaint
    {
        Image = image.Downsize(100)
    };
    canvas.SetFillPaint(imagePaint, RectF.Zero);
    canvas.FillRectangle(0, 0, 240, 300);
}

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/paint?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/paint.md

### Document Version Independent Id

38f24e06-7bff-f379-035a-aedbed87a8af

### Article author

@davidbritch

### Metadata

* ID: 38f24e06-7bff-f379-035a-aedbed87a8af 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @Overdrive77 

When something works on one platform but not others, it's a product bug. Afraid that we'll have to wait for the product team to fix this.
