### ISSUE TITLE
Clairfication of code

### ISSUE THREAD

**Issue by Legends** [dotnet/docs-maui#2025]
### Type of issue

Other (describe below)

### Description

> The overall effect is that when a user changes the app window size on Windows, the action specified in the AddEvent method is executed.

Why shoud we use `events.AddEvent(nameof(Microsoft.UI.Xaml.Window.SizeChanged)`, cause we already have attached to the `SizeChanged` event using eventhandler `OnSizeChanged` ?
Or is this just another way of doing it?

 ```
events.AddWindows(windows => windows
                           .OnWindowCreated(window =>
                           {
                                  window.SizeChanged += OnSizeChanged;
                           }));

                    events.AddEvent(nameof(Microsoft.UI.Xaml.Window.SizeChanged), () => LogEvent("Window SizeChanged"));
#endif
                    static bool LogEvent(string eventName, string type = null)
                    {
                        System.Diagnostics.Debug.WriteLine($"Lifecycle event: {eventName}{(type == null ? string.Empty : $" ({type})")}");
                        return true;
                    }
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/app-lifecycle.md

### Document Version Independent Id

b2c2cef1-8fc3-6e53-cc28-393e00e31b85

### Article author

@davidbritch

### Metadata

* ID: b2c2cef1-8fc3-6e53-cc28-393e00e31b85 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @Legends 

It's just a mechanism, typically for library authors, that enables apps to be notified when platform events are raised. So in this example `AddEvent` is just used to specify an `Action` that'll be invoked when `Microsoft.UI.Xaml.Window.SizeChanged` is raised. It's not compulsory. So it's decoupling any notification of the platform event occurring (if required - e.g. for logging purposes) from the platform event being raised. Hope this helps!
