### ISSUE TITLE
Create .NET MAUI APP For VS Code on Mac

### ISSUE THREAD

**Issue by SainteEpee** [dotnet/docs-maui#2026]
### Type of issue

Code doesn't work

### Description

- Cannot Create .NET MAUI APP with VS Code. Does appear on Apps to Create. 
- ONLY showed when I re-installed Visual Studio 2022 for Mac with .NET MAUI  options.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=devices-ios&view=net-maui-8.0&tabs=visual-studio-code

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md

### Document Version Independent Id

e77ba6a7-e59d-1e1e-52e1-935f98a985cf

### Article author

@davidbritch

### Metadata

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @SainteEpee 

Afraid that this sounds like a product issue, and so needs logging at https://github.com/microsoft/vscode-dotnettools/issues

Thanks!
