### ISSUE TITLE
デフォルトのStyle.xamlではわかりづらい

### ISSUE THREAD

**Issue by pon-ex** [dotnet/docs-maui#2034]
### Type of issue

Missing information

### Description

新規プロジェクトを作成時
Resources\Styles\Styles.xaml
に問題があるように思えます。
    
こちらがデフォルトのStyles.xaml 場合
![image](https://github.com/dotnet/docs-maui/assets/69337417/6a5cf842-ef2b-4571-841c-a5acef6bd48c)

チュートリアルのStyles.xaml 場合
![image](https://github.com/dotnet/docs-maui/assets/69337417/9ead91ab-75c0-4d90-ae28-018ea68be147)

### Page URL

https://learn.microsoft.com/ja-jp/dotnet/maui/tutorials/notes-app/?view=net-maui-8.0&tutorial-step=5

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml

### Document Version Independent Id

720bf7f0-db92-f738-b864-ee149a02377b

### Article author

@adegeo

### Metadata

* ID: 720bf7f0-db92-f738-b864-ee149a02377b 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 214901](https://dev.azure.com/msft-skilling/Content/_workitems/edit/214901)

**Comment by davidbritch** [comment]
Hi @pon-ex 

I just created a brand new app and it looks like the correct styles are being applied:

![Screenshot 2024-01-29 at 15 33 42](https://github.com/dotnet/docs-maui/assets/8092460/dfdafda6-35f5-4886-9374-7f0d5e57a9cc)

When you change styles in an app you should really delete the project's bin and obj folders being running the app again - that'll make sure the new style is picked up correctly.

**Comment by pon-ex** [comment]
こんにちは @davidbritch 
もし私が勘違いをしてるのであればごめんなさい。
また、言葉が足りなかったりしてるようであれば訂正します。
画像を見る限り私の言いたいことが伝わってない可能性があると思いましたのでもう1度失礼します。
私はこちらのチュートリアルの通りに進めました。
問題は1枚目の画像のほうです。
`
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Add" Clicked="Add_Clicked" IconImageSource="{FontImage Glyph='+', Color=White, Size=22}" />
    </ContentPage.ToolbarItems>
`
こちらの部分を目視することが出来ませんでした。

**Comment by adegeo** [comment]
I think the reason you don't see it, is because your copy of Styles.xaml seems wrong and uses a `White` background. The `ToolbarItem` is using a `White` color for the glyph `+`. It's there, you just can't see it. I don't know why your project has a `White` background.

**Comment by pon-ex** [comment]
@adegeo 
1枚目の画像がチュートリアルに沿ってコードを記載していったプロジェクトです。
2枚目の画像は下記URLよりコピーしたプロジェクトです。
https://github.com/dotnet/maui-samples/tree/main/8.0/Tutorials/CreateNetMauiApp
あなたの言うように、白の背景で見えないだけなのですが、コピーしたプロジェクトだと問題ありません。
再度新しくプロジェクトを作成してみましたが、やはり背景は白の状態で見えません。
バージョンの問題でしょうか

**Comment by adegeo** [comment]
It could be that the styles.xaml has changed. In March I'm going to update these tutorials to .NET 8, so I'll create it all from scratch and make sure it's OK. I'll reopen this issue and assign it to myself to make sure I check it.

**Comment by adegeo** [comment]
@pon-ex Thanks for the issue again! It does look like the templates changed and altered the style and project files. I'm going to update all the code and screenshots to the latest.
