### ISSUE TITLE
Display a menu bar in a .NET MAUI desktop app

### ISSUE THREAD

**Issue by genifycom** [dotnet/docs-maui#2037]
### Type of issue

Missing information

### Description

[Enter feedback here]
This page provides zero help to a DotNet Maui Blazor developer.

Please provide info for BOTH XAML and Blazor. I see many more people using Blazor than XAML.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/menu-bar?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/menu-bar.md

### Document Version Independent Id

184c91af-4cb0-10a6-bf4b-14b5469f4318

### Article author

@davidbritch

### Metadata

* ID: 184c91af-4cb0-10a6-bf4b-14b5469f4318 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @genifycom 

Afraid there's far more XAML devs than Blazor devs. Also, Blazor hybrid docs live in a different location (https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-8.0).
