### ISSUE TITLE
explicitly explain the difference between ICanvas "Draw" vs "Fill" methods

### ISSUE THREAD

**Issue by hedgewizards** [dotnet/docs-maui#2039]
### Type of issue

Missing information

### Description

I was using the ICanvas.DrawRoundedRectangle method to draw a shape when I noticed it only draws an outline on iOS, not the fill. From the rest of the documentation, it seems to me like this is intended behavior.

This is unintuitive based on the naming conventions of these functions. "Draw" doesn't mean to outline. I would expect a Draw function to add both the stroke and the fill. I think rather than changing the name to make this more obvious, or even worse changing the behavior, the best option is to just explain this at the top of this page in the docs.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/draw?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/draw.md

### Document Version Independent Id

0ca86947-204f-9c45-223d-724fb59b4938

### Article author

@davidbritch

### Metadata

* ID: 0ca86947-204f-9c45-223d-724fb59b4938 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 205438](https://dev.azure.com/msft-skilling/Content/_workitems/edit/205438)

**Comment by davidbritch** [comment]
Hi @hedgewizards 

A fair comment, so I'll get the doc updated as per your suggestion.
