### ISSUE TITLE
i am to programming with maui it is very amazing

### ISSUE THREAD

**Issue by mohammed-reda-elakhal** [dotnet/docs-maui#2042]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?view=net-maui-8.0&tutorial-step=2

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml

### Document Version Independent Id

720bf7f0-db92-f738-b864-ee149a02377b

### Article author

@adegeo

### Metadata

* ID: 720bf7f0-db92-f738-b864-ee149a02377b 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Thanks for your feedback!
