### ISSUE TITLE
The iOS App Extension migration link does not work. Where is documentation on creating App Extension project for .NET 8?

### ISSUE THREAD

**Issue by AlexNik4** [dotnet/docs-maui#2043]
### Type of issue

Missing information about iOS App Extension ever since .NET 6 was released.

### Description

No official documentation on how to create an iOS App Extension project after migrating from Xamarin to .NET. Says this is supported and has link, but the link takes you to generic Xamarin migration page. Where is the documentation?

![image](https://github.com/dotnet/docs-maui/assets/53029348/8440511b-bf89-4509-bd5d-18df807011b6)

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/migration/?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/migration/index.md

### Document Version Independent Id

51da2d09-32e6-d516-0d3c-bd46ce507485

### Article author

@davidbritch

### Metadata

* ID: 51da2d09-32e6-d516-0d3c-bd46ce507485 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @AlexNik4 

The link is actually as intended, because it should just be a case of migrating your existing iOS extension project to use an SDK-style .csproj. Alternatively, you could create a new iOS extension project in Visual Studio and copy the code from your existing project into it.

Afraid that iOS extension projects won't be covered from this repo, because it's for the .NET iOS product rather than .NET MAUI.

**Comment by AlexNik4** [comment]
@davidbritch 
We tried modifying the extension project to SDK-style csproj. Finally got it to build after a bunch of different errors, but it is not working. It works fine in the old Xamarin project. Since there is no documentation, we are not sure if we migrated correctly. Best we found is this unofficial thread. https://github.com/dotnet/maui/discussions/3289. Were hoping to have clear documentation from Microsoft now that Xamarin is going out of support.

Creating a new extension project keeps failing. So there is nothing to reference. The only target Frameworks are .NET Framework which is not correct.
![image](https://github.com/dotnet/docs-maui/assets/53029348/587ff58d-6f7a-4fa7-be89-8629ef0a4910)

**Comment by davidbritch** [comment]
Hi @AlexNik4 

I recommend you email maui-upgrades@microsoft.com with details about your problem. That'll put you in touch with team members who'll work with you to get you unblocked.

**Comment by davidbritch** [comment]
@AlexNik4 

It's come back to me that last time I asked there weren't any iOS extension project templates for .NET iOS. Hence the need to convert your .csproj file to an SDK-style .csproj yourself. But again, email maui-upgrades to get fully unblocked.
