### ISSUE TITLE
Please call out explicitly that your handler code will be called only once if you use a random handler key name

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/docs-maui#2044]
### Type of issue

Missing information

### Description

In the [documentation about custom handlers](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize?view=net-maui-8.0) it is written that for the handler key names you can use a control's property, or you can use a random name (like `MyCustomization` as in the documentation).

The consequences of this are not clear from the article.

If you do not use a property name but a random name then it will be called only when the control is created. The code is not run when properties are updated.

If you want to run the `action` code from e.g. `AppendMapping` when a property is updated, then the key should be `nameof(`ClassName.PropertyName`)

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md

### Document Version Independent Id

70227b04-808f-1370-186b-10cfef525959

### Article author

@davidbritch

### Metadata

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 205437](https://dev.azure.com/msft-skilling/Content/_workitems/edit/205437)

**Comment by davidbritch** [comment]
Hi @hansmbakker 

Yes, you're right. It's a fair comment so I'll get the doc update.d
