### ISSUE TITLE
MSFT .net Maui Radio Buttons documentation probably in the wrong place at the time of this writing.

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs-maui#2046]
---
**Issue moved from MicrosoftDocs/feedback#3974**
- Please respond to @nickolasnikolic.

---

_From @nickolasnikolic on Tuesday, January 9, 2024 11:40:37 PM_

Thank you for your awesome platform! Good luck with your documentation! Thanks again.

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3974**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Tuesday, January 9, 2024 11:40:40 PM_

Thank you for opening an issue! One of our team members will get back to you with additional information.
  
If this is a product issue, please close this issue and contact the product's support instead. For a list of support websites, see [Support for Microsoft products and apps](https://support.microsoft.com/all-products).

**Comment by davidbritch** [comment]
Hi @nickolasnikolic

What's the problem exactly?
