### ISSUE TITLE
How to create header, left and right side panel and footer as like visual studio design?  

### ISSUE THREAD

**Issue by coder-neel** [dotnet/docs-maui#2047]
### Type of issue

Other (describe below)

### Description

Hi, 

I am trying to create master layout as like visual code UI using .net MAUI.

![code](https://github.com/dotnet/docs-maui/assets/35185835/59d03594-ccdc-4ed7-940d-5812c215d64d)

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="DataCenterx.MVVM.Views.MasterLayoutPage"
             Title="MasterLayoutPage">
    
    
    <ContentPage.ControlTemplate>
        <ControlTemplate x:Name="MasterLayout">

            <Grid RowDefinitions="30,*,30">

                
                <VerticalStackLayout Grid.Row="0" BackgroundColor="Aqua">
                    
                    <Label Text="Header Section" />

                    
                    

                </VerticalStackLayout>

                <ContentPresenter Grid.Row="1"/>

                <Label Text="Footer Section" Grid.Row="2"/>

            </Grid>
            
        </ControlTemplate>
    </ContentPage.ControlTemplate>
    
</ContentPage>`

I tried this article for Menu bar but its not work. Ref https://learn.microsoft.com/en-us/dotnet/maui/user-interface/menu-bar?view=net-maui-8.0

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/controltemplate?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/controltemplate.md

### Document Version Independent Id

d55cdb6d-0144-0c97-c373-8728b20664a9

### Article author

@davidbritch

### Metadata

* ID: d55cdb6d-0144-0c97-c373-8728b20664a9 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @coder-neel 

You could use a FlexLayout or Grid to get the layout you're after. However, if you want it to use draggable panels, there's nothing out of the box in .NET MAUI to do that.

**Comment by coder-neel** [comment]
Hi @davidbritch,

Yes, I tried but nothing happen. Could you please create a sample demo project for me if you have clear my concept?
 
![menu](https://github.com/dotnet/docs-maui/assets/35185835/80348a06-0291-434c-839c-0a23fa6452be)
