### ISSUE TITLE
Azure Communication Services Support for MAUI

### ISSUE THREAD

**Issue by mcblacksea** [dotnet/docs-maui#207]
As a community, 
we'd like to ask about opportunity to use Azure Communication Services with MAUI apps.
This allows many developers across the world to use Communication Services with appropriate NuGet packages from MS Team.
Would be also great to have documentation with steps "How to" use Communication Services with MAUI / Xamarin apps.

--
Many thanks

**Comment by davidbritch** [comment]
Hi @aodegov 

Apologies for the delayed response, but it's taken a while to find out the answer. The Azure Communication Services team is currently looking at implementing .NET MAUI controls for Azure Communication Services [Storybook](https://azure.github.io/communication-ui-library/?path=/story/overview--page). They'll end up doc'ing whatever they create, and the MAUI docs will link to it.

**Comment by mcblacksea** [comment]
Hi @davidbritch ,
thanks for your reply.

My questions: 
Am I correctly understanding, that the package(or library) with connection MAUI to the Azure Communication Services will be processed by the ACS team?
Any help from MAUI team in this process?
And eventually, which Team will create documentation with points how it will work for the mobile devices (MAUI + ACS) ?
 
Many thanks.
