### ISSUE TITLE
Publish a .NET MAUI app for Windows is just WRONG SO VERY WRONG

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#2073]
### Type of issue

Other (describe below)

### Description

To use the Manifest Designer, find the Solution Explorer pane, then right-click Platforms\Windows\Package.appxmanifest > Properties.
To use the XML editor, find the Solution Explorer pane, then right-click Platforms\Windows\Package.appxmanifest > View Code.
[Enter feedback here]

Now the above is so wrong it is pathetic.
First properties.  Right click does nothing except bring up file properties.
Second use the editor.  View code - DOES NOTHING.  And opening the App.xaml shows some code but what to do with it is not shown in this documentation

Basically this article is useless.  Things it tells don't work and then there is no docs on what to do.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/overview?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/windows/deployment/overview.md

### Document Version Independent Id

46808586-50e1-acfa-68b3-c3ca6572dc62

### Article author

@davidbritch

### Metadata

* ID: 46808586-50e1-acfa-68b3-c3ca6572dc62 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 217466](https://dev.azure.com/msft-skilling/Content/_workitems/edit/217466)

**Comment by davidbritch** [comment]
Hi @sqlguy6212 

> To use the Manifest Designer, find the Solution Explorer pane, then right-click Platforms\Windows\Package.appxmanifest > Properties.

Admittedly this was out of date.

> To use the XML editor, find the Solution Explorer pane, then right-click Platforms\Windows\Package.appxmanifest > View Code.

This worked fine in the latest Visual Studio.
