### ISSUE TITLE
This page tells you nothing

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#2074]
### Type of issue

Other (describe below)

### Description

Any connection between the page title and what it says is .... just not there.

It does not tell you how the publish an Android app
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/index.md

### Document Version Independent Id

79b73ca7-405f-2916-b938-c2c0647f59b8

### Article author

@davidbritch

### Metadata

* ID: 79b73ca7-405f-2916-b938-c2c0647f59b8 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @sqlguy6212 

It's an overview page, as denoted by the TOC:

![image](https://github.com/dotnet/docs-maui/assets/8092460/0e77139b-3b66-4bd3-8976-72e73fe8174a)

You then use the TOC, or chooser at the top of the page to choose a doc that corresponds to your publication mechanism:

![image](https://github.com/dotnet/docs-maui/assets/8092460/bdfe59df-2209-4446-8cea-2be6363eac5c)
