### ISSUE TITLE
Migration documentation has misleading Xamarin namespaces

### ISSUE THREAD

**Issue by SebastianBone** [dotnet/docs-maui#2080]
### Type of issue

Typo

### Description

I noticed that the documentation for the custom renderers is using the **Xamarin** namespaces for the **Maui** parts.

You can see it here:
https://learn.microsoft.com/en-us/dotnet/maui/migration/custom-renderers?view=net-maui-8.0#register-renderers
https://learn.microsoft.com/en-us/dotnet/maui/migration/custom-renderers?view=net-maui-8.0#consume-the-custom-renderers

If this is not intentional, the namespaces for those files should be updated to use new the Maui platform namespaces.
A note on this part of documentation would be nice:
https://learn.microsoft.com/en-us/dotnet/maui/migration/custom-renderers?view=net-maui-8.0#modify-using-directives-and-other-code

Thanks and keep up the good work 🙂 

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/migration/custom-renderers?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/migration/custom-renderers.md

### Document Version Independent Id

c787fde2-1c9c-62d4-2cdd-93681e0c1ff5

### Article author

@davidbritch

### Metadata

* ID: c787fde2-1c9c-62d4-2cdd-93681e0c1ff5 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @SebastianBone 

It's intentional - it's taken from https://github.com/dotnet/maui-samples/tree/main/Upgrading
