### ISSUE TITLE
Binding doesn't work

### ISSUE THREAD

**Issue by rwb196884** [dotnet/docs-maui#2083]
### Type of issue

Code doesn't work

### Description

How the fuck do you do 'binding'?
Is this supposed to work? 
```
        class FooBindingContext
        {
            public string Foo{ get; set; }
        }
```
and then 
```
        private readonly FooBindingContext _BindingContext;
        public Foo()
        {
            _BindingContext = new FooBindingContext()
            {
                Foo = "foo"
            };
            BindingContext = _BindingContext;
            InitializeComponent();
        }
```
and
```
<Label Text="{Binding Foo}" />
```

But when I assign a new value to `_BindingContext.Foo` nothing happens.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/basic-bindings?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/basic-bindings.md

### Document Version Independent Id

1ce42af9-5ff2-9b3f-4618-65ba90a67813

### Article author

@davidbritch

### Metadata

* ID: 1ce42af9-5ff2-9b3f-4618-65ba90a67813 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by MartyIX** [comment]
You can try an app from samples: https://github.com/dotnet/maui-samples/tree/main/8.0/Fundamentals/DataBindingDemos

Anyway, this snippet 

```
class FooBindingContext
        {
            public string Foo{ get; set; }
        }
```

does not contain a `OnPropertyChanged(); // reports this property` call to notify your view that something has changed. See https://learn.microsoft.com/en-gb/dotnet/maui/xaml/fundamentals/mvvm?view=net-maui-8.0:

![image](https://github.com/dotnet/docs-maui/assets/203266/90700ba8-abb3-4535-b9b5-c64c5fa764c0)

**Comment by davidbritch** [comment]
@rwb196884 What @MartyIX says. Alternatively, make your `Foo` property a `BindableProperty`.

This training course may help: https://learn.microsoft.com/en-us/training/modules/separate-ui-and-logic-with-data-binding/
