### ISSUE TITLE
Typo in grid documentation

### ISSUE THREAD

**Issue by BlueRaja** [dotnet/docs-maui#2087]
### Type of issue

Typo

### Description

Two usages of `SetColumnSpan` on this page. I believe they should be `SetColumn`

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/grid?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/layouts/grid.md

### Document Version Independent Id

5f34c45a-afa7-e650-a83d-b99a712d50e3

### Article author

@davidbritch

### Metadata

* ID: 5f34c45a-afa7-e650-a83d-b99a712d50e3 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 217471](https://dev.azure.com/msft-skilling/Content/_workitems/edit/217471)

**Comment by davidbritch** [comment]
Hi @BlueRaja 

The code is correct, it's more that the comment in the code is incorrect. I'll get it updated.

**Comment by BlueRaja** [comment]
So the documentation that's supposed to demonstrate how to set the row & column of an element _intentionally_ doesn't demonstrate how to set the column of the element? But instead it - again, intentionally - needlessly and confusingly sets the column span?  And then it places both of the elements into the same place in the grid because the column was never set??
