### ISSUE TITLE
So close yet so far -- where is the pointer to running the app on a physical device?

### ISSUE THREAD

**Issue by BobFrankston** [dotnet/docs-maui#209]
[Enter feedback here]

This page gets me to the emulator but doesn't give me a pointer to how to run the app on the physical devices.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BobFrankston 

It'll be added once the feature works correctly. At the moment there are problems debugging when the app is running on a device.
