### ISSUE TITLE
CarouselView with forms-to-fill as Items

### ISSUE THREAD

**Issue by grandvan709** [dotnet/docs-maui#2095]
Hello, Guys!

Can you help me? I wanna make RegisterPage where user will register his account in my app. And I wanna make page with carouselview. First, user fill first three entries and click button "Next", then carouselview will select second part (second form as item of carouselview), but second form is different by amount of entries (has two entries, not three like in first part), and has button "OK".

Screenshots how it would be are attached.

![FirstForm_RegPage](https://github.com/dotnet/docs-maui/assets/110721031/cc393725-9d6a-4235-8ed4-3cbcb69e8763)
![SecondForm_RegPage](https://github.com/dotnet/docs-maui/assets/110721031/7460aab6-b49d-42bc-92e7-06c14613a9d6)

**Comment by davidbritch** [comment]
You need to use a `DataTemplateSelector` to decide which content to display in the `CarouselView`. An update to the docs on doing this is underway, courtesy of https://github.com/dotnet/docs-maui/issues/2219
