### ISSUE TITLE
Where's a link to actual programming documentation for using MAUI?

### ISSUE THREAD

**Issue by DarkChocoholicDev** [dotnet/docs-maui#210]
So far I see nothing about what XAML controls and such are available with MAUI. Is it Xamarin Forms, WPF, something else? Being new to Xamarin (but seasoned with WPF), I can find nothing in the documentation that tells what flavor of XAML is to be used, or the location of documentation for the individual controls. There don't even appear to be header blocks in the library files, so I can't glean documentation even by looking at the class definitions.

Where's the actual programming documentation?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62c6f63-7e33-d81d-28db-b9ba40919408
* Version Independent ID: e3bf5b48-ed62-c664-1c33-294c0e762e57
* Content: [.NET MAUI app startup - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/app-startup#feedback)
* Content Source: [docs/fundamentals/app-startup.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/app-startup.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @DarkChocoholicDev 

It'll be published between now and when the finished product is released.

**Comment by davidbritch** [comment]
@DarkChocoholicDev 

To answer the rest of your question, controls use the same API surface as in Xamarin.Forms, and the same XAML flavour as Xamarin.Forms.
