### ISSUE TITLE
Questions about the Android platform

### ISSUE THREAD

**Issue by xhhaha** [dotnet/docs-maui#2101]
### Type of issue

Missing information

### Description

Unable to call the microphone on the Android platform, wanting to obtain microphone data on the Android platform，Hope to develop more APIs available on Android platforms, such as IMEI codes

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/maui/platform-integration/invoke-platform-code?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/invoke-platform-code.md

### Document Version Independent Id

a06cfff1-c728-dbd9-4fb5-aa42363753ea

### Article author

@davidbritch

### Metadata

* ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
This is more of a .NET Android issue, rather than .NET MAUI. The fundamental problem here is there's no docs for .NET Android. The product team is aware of this and is working on it.
