### ISSUE TITLE
MacOS supported versions (Catalyst)

### ISSUE THREAD

**Issue by asysmala** [dotnet/docs-maui#211]
There's a statement on the supported platforms page: "macOS 10.13 or higher (using Mac Catalyst)". 

But this is confusing, since Mac Catalyst support was added since version macOS 10.15. I may be wrong about this, but to my understanding macOS versions prior to 10.15 Catalina don't support Catalyst?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb754bf-48db-4f6c-7e87-7cb3b59c34d5
* Version Independent ID: ba07354c-611d-5efe-0fbb-48a24d02cafe
* Content: [.NET MAUI supported platforms - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms)
* Content Source: [docs/supported-platforms.md](https://github.com/dotnet/docs-maui/blob/main/docs/supported-platforms.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello @asymala I'm going through issue we may have missed and found yours. What you pointed out, sounds correct. @Redth would you be able to confirm that minimum OS requirements for both running a .NET MAUI app and developing a .NET MAUI app for mac?
