### ISSUE TITLE
Documentation for handlers/mappers/renderers is terrible

### ISSUE THREAD

**Issue by BlueRaja** [dotnet/docs-maui#2111]
### Type of issue

Missing information

### Description

I've read these docs 5 times and I still have no idea how to use any of them.

* The documentation for where to find CommandMappers is non-existent. I have no idea how to use these, or where to even find what command-strings I can hook into.  There are no code examples.
* The documentation for where to find PropertyMappers is "here's a link to the code, have fun".  There is exactly one example, on a different page (Handlers --> Customize Controls), but it only shows how to add custom code to a custom control, not customize one of the default controls
* The "Reuse custom renderers" (found in a completely different part of the documentation, lol?) gives an alternative solution, but the documentation for that is also terrible.  It just says "use a VisualElementRenderer" with no code example of how to do that. It doesn't even tell you which VisualElementRenderer class to use (there are 3 in MAUI, all three compile but only one doesn't crash)

I've now spent 12 hours attempting to remove the padding from the native Android `Switch`, and am no closer to figuring it out.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/index.md

### Document Version Independent Id

68990f2c-45ae-8d81-24cc-4004a2fa994c

### Article author

@davidbritch

### Metadata

* ID: 68990f2c-45ae-8d81-24cc-4004a2fa994c 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Closing as it's a known issue that the handler docs need a big revamp, and it's being tracked in other issues inc. #958
