### ISSUE TITLE
Support Hawaiian dialect on documentation site

### ISSUE THREAD

**Issue by RobKenis** [dotnet/docs-maui#2115]
Support Hawaiian dialect on https://dotnet.microsoft.com/en-us/apps/maui. Their wikipedia page is above the framework documentation, so it's only fair.

**Comment by davidbritch** [comment]
Hi @RobKenis 

The dotnet.microsoft.com website is what we call the marketing website, and it's a completely different repo, for which feedback should be left at https://github.com/dotnet/website-feedback/issues

Unfortunately I don't have permissions to transfer your issue to that repo, so I recommend you create a new issue there. Thanks!
