### ISSUE TITLE
On Android, the list of tabs appears at the top of the screen, and the page content is below.

### ISSUE THREAD

**Issue by Legends** [dotnet/docs-maui#2137]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
.NET 8.0, Android 11- API 30,

> On Android, the list of tabs appears at the top of the screen, and the page content is below.

On my Android the tabs are the bottom

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/tabbedpage?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pages/tabbedpage.md

### Document Version Independent Id

d9f1977c-bc41-c096-0b17-6db418d440b0

### Article author

@davidbritch

### Metadata

* ID: d9f1977c-bc41-c096-0b17-6db418d440b0 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @Legends 

I just tried .NET 8, API 30, and `TabbedPage` tabs still appear at the top:

![Screenshot_1710852340](https://github.com/dotnet/docs-maui/assets/8092460/91bd862f-7bde-4357-964b-706ed744ef20)

However, tabs do appear at the bottom if you're using a Shell-based app, which doesn't use a `TabbedPage`.
