### ISSUE TITLE
How to Deploy/Publish MAUI Apps to AppStore and PlayStore ?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/docs-maui#214]
Is there any document around how to publish to Appstore and Play Store ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nssidhu 

Not until MAUI is finished and released. In the meantime, you can look at the Xamarin.Forms publishing docs - the process will be pretty similar.

**Comment by nssidhu** [comment]
The doc are very different, for example,

I was following this one
https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=windows#enable-automatic-provisioning

I cannot find Automatic Provisioning section in Lates Project Template of MAUI app.

I have seen lots of video on how to Run iOS simulator, but nobody talks about how to set it up.

I have not been able to run iOS, not even when using local iPhone device.

**Comment by iamsourabh-in** [comment]
Hi Followed the exact same method to sign and upload the abb file, but getting the Error as show Below.

Tried the same using the documentation provided by microsoft. Still getting the same error. I have provided the configuration to be release still getting the issue the app is in debug mode.

Step : 1 : keytool -genkey -v -keystore myapp.keystore -alias key -keyalg RSA -keysize 2048 -validity 10000

Step : 2 :

```xml
<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>myapp.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>key</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>*******</AndroidSigningKeyPass>
    <AndroidSigningStorePass>*******</AndroidSigningStorePass>
</PropertyGroup>
```

Step : 3 : dotnet publish -f:net6.0-android -c:Release


![image](https://user-images.githubusercontent.com/22702292/188068647-be390bf8-82ae-4bd9-9360-ae3c35f21abf.png)
