### ISSUE TITLE
Cannot connect to Web API on MAUI iOS simulator

### ISSUE THREAD

**Issue by banhthanhvi** [dotnet/docs-maui#2140]
### Type of issue

Code doesn't work

### Description

Cannot connect to Web API on MAUI iOS simulator, it run on Android.
I declared in info.plist
<key>NSAppTransportSecurity</key>    
<dict>
    <key>NSAllowsLocalNetworking</key>
    <true/>
</dict>
Do I miss something.
Thank you.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/local-web-services?view=net-maui-8.0#Overview

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/local-web-services.md

### Document Version Independent Id

663379bf-421a-57f1-39b7-e92f830de0ed

### Article author

@davidbritch

### Metadata

* ID: 663379bf-421a-57f1-39b7-e92f830de0ed 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Tried the sample the doc links to?
