### ISSUE TITLE
What's the project property parameter to set the path for xcode?

### ISSUE THREAD

**Issue by seansparkman** [dotnet/docs-maui#2143]
### Type of issue

Missing information

### Description

You need to include the documentation on how to specific which XCode to use. You provide multiple versions using xcodes in Azure DevOps. This should be included in your documentation.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/ios/cli?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/ios/cli.md

### Document Version Independent Id

da0a1dce-0ab0-7d18-8dc9-e37854995ace

### Article author

@davidbritch

### Metadata

* ID: da0a1dce-0ab0-7d18-8dc9-e37854995ace 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 232736](https://dev.azure.com/msft-skilling/Content/_workitems/edit/232736)

**Comment by davidbritch** [comment]
Hi @seansparkman 

It's not a build property, so isn't settable in .NET CLI or your .csproj. But it is possible, so I'll get the doc updated.

**Comment by davidbritch** [comment]
.NET iOS uses the following process to determine which version of Xcode to use.

1. If the `MD_APPLE_SDK_ROOT` environment variable is set, use its value. 
1. If the *~/Library/Preferences/Xamarin/Settings.plist* file exists, use the value defined inside it. 
1. Use the value of `xcode-select -p`.
1. Use `/Applications/Xcode.app`.

(1) is the recommended approach to use, as (2) assumes that Visual Studio for Mac is installed on the machine.

Using `xcode-select -s` to set the version of Xcode to use isn't recommended.
