### ISSUE TITLE
These instructions are very confusing.

### ISSUE THREAD

**Issue by razaraz** [dotnet/docs-maui#215]
I did not know what the dotnet upgrade assistant was before this. Without any hyperlinks, or mention that the upgrade assistant is an additional tool that you need to install, It was really hard to tell. On the step that it said to copy the code files to the app folder, I tried copying over the files of my project to the created sample, and was very confused as to how the .csproj, references, project type and everything was going to get upgraded.

I am now trying out with the installed upgrade-analyzer tool: https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-overview

**Comment by davidbritch** [comment]
Hi @razaraz 

.NET MAUI is still in preview and is still a work in progress. The .NET upgrade assistant, for .NET MAUI, is still a work in progress. Once they are finished, and work correctly, the docs will be updated with full instructions etc.
