### ISSUE TITLE
Tiny typo in xaml code: views -> Views

### ISSUE THREAD

**Issue by EskeRahn** [dotnet/docs-maui#2150]
### Type of issue

Code doesn't work

### Description

At the almost bottom of [this](https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?view=net-maui-8.0&tutorial-step=4)

```
ContentTemplate="{DataTemplate views:AllNotesPage}"
```
should have been
```
ContentTemplate="{DataTemplate Views:AllNotesPage}"
```
With a capital V.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml

### Document Version Independent Id

720bf7f0-db92-f738-b864-ee149a02377b

### Article author

@adegeo

### Metadata

* ID: 720bf7f0-db92-f738-b864-ee149a02377b 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by adegeo** [comment]
@EskeRahn I just went through these tutorials and made sure everything was up-to-date with .NET 8. The code works fine with a lowercase `v`. My guess is that you accidentally put an uppercase `V` in the xmlns import name of the .NET namespace. It should be `xmlns:views="` not `xmlns:Views="`

```xml
<Shell
    x:Class="Notes.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:views="clr-namespace:Notes.Views"
    Shell.FlyoutBehavior="Disabled">
```
