### ISSUE TITLE
No macOS for devs anymore?

### ISSUE THREAD

**Issue by hot33331** [dotnet/docs-maui#216]
I have to say I am very sad to see that all support for macos seems to be gone from the documentation. Am I not able to find it, or is it just gone? Is there any way I can help to bring it back?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @hot33331 

Do you meant the content that's commented out in https://raw.githubusercontent.com/dotnet/docs-maui/main/docs/get-started/first-app.md ?

**Comment by hot33331** [comment]
Yes, I basically do not see any getting started for a macOS dev. It is either use windows or nothing. I am currently struggeling with installing the maui bits on my m1 arm mac and I had hoped that there would be something here on how I could do that. But even for intel I cannot find anything. :-(
Before there was at least a section on how to use the CLI and VS Code on the Mac...

**Comment by davidbritch** [comment]
Part of the problem is there's no clear path to using the CLI.  For example, to build/run on Android using the CLI you first have to:

1. Install VS with the mobile dev workload.
2. Create a MAUI project in VS.
3. Let VS prompt you to install the Android SDK/build tools/emulator.
4. Let VS prompt you to create an emulator.

Then you can use the CLI to build/deploy to Android. There's no nice way of explaining that, and it was causing user confusion. That's why we removed the CLI commands, for the time being.

CLI commands will be restored, in a new doc, by the time MAUI launches. In the meantime if you scroll down to the end of https://raw.githubusercontent.com/dotnet/docs-maui/main/docs/get-started/first-app.md you should find what you need (commented out). Sorry I can't be more helpful right now!

**Comment by hot33331** [comment]
I fully understand David, thanks anyway for pointing me to the commented stuff! Maybe just put in a note that currently there is no easy / supported way for mac and that this will be supported later on and documented here?

**Comment by MaxFelinger** [comment]
A concise manual would probably be enough: Something like

1. Be sure you've installed Xcode 13 or greater. You can update it via the App Store.
2. Download and install .Net 6 from here https://dotnet.microsoft.com/en-us/download/dotnet/6.0
3. Open your terminal and execute the following commands
 - dotnet tool install -g redth.net.maui.check
 - export PATH=$HOME/.dotnet/tools:$PATH
 - maui-check
The command maui-check will make sure that you've installed all the necessary parts to start developing with .NEt MAUI. If it encounters anything that is not install, it will prompt you with something like "Should xy be install (y/n): ".

Create a new project.
- Open a terminal and go to a folder where you want to create your new MAUI project.
- Execute the command “dotnet new maui“. The name maui indicates the project type that will be created.
- Open the new project with VisualStudio for Mac https://visualstudio.microsoft.com/de/vs/mac/preview/
- Select iOS as you destination platform (top left in VS4M)
- Press play (top left) for build and deploy.

FYI: I've got this information from a youtube video made by James Montemagno https://www.youtube.com/watch?v=eF5YcpyzQIo

**Comment by davidbritch** [comment]
Afraid that maui-check isn't an officially supported route, so won't be mentioned in the docs.

The doc model is such that nothing gets doc'd until it (1) works reliably enough and (2) is set in stone. So rest assured that this will get doc'd, once (1) and (2) are met.
