### ISSUE TITLE
MauiSplashScreen Aspect Fill all of screen 

### ISSUE THREAD

**Issue by ibrahimahmed1998** [dotnet/docs-maui#2161]
### Type of issue

Missing information

### Description

MauiSplashScreen Aspect Fill all of screen doesn't exists in documentation 

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?view=net-maui-8.0&tabs=android

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/splashscreen.md

### Document Version Independent Id

44323c6e-d65c-b254-ee3c-cd9415bdf3bc

### Article author

@davidbritch

### Metadata

* ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @ibrahimahmed1998 

What exactly do you mean?

**Comment by ibrahimahmed1998** [comment]
When I need to make Splash screen take size of mobile screen size it not handled to take it automatic 
it need to write fixed size and may be a lot of mobile phone has a different screen size.
I mean this attribute -> BaseSize="460,890" 
I need it to like CSS attribute take Fullscreen of window

**Comment by ibrahimahmed1998** [comment]
any updates ?

**Comment by davidbritch** [comment]
Hi @ibrahimahmed1998 

Afraid there's no way of easily doing this right now.
