### ISSUE TITLE
CheckBox Documentation Missing Required Element For Visual Style

### ISSUE THREAD

**Issue by heribertolugo** [dotnet/docs-maui#2175]
## Issue description

[Documentation ](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/checkbox?view=net-maui-8.0) for **CheckBox** provides the following example for manipulating the color of the **CheckBox**:
```
<CheckBox ...>
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup x:Name="CommonStates">
            <VisualState x:Name="Normal">
                <VisualState.Setters>
                    <Setter Property="Color"
                            Value="Red" />
                </VisualState.Setters>
            </VisualState>

            <VisualState x:Name="IsChecked">
                <VisualState.Setters>
                    <Setter Property="Color"
                            Value="Green" />
                </VisualState.Setters>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
</CheckBox>
```

If you copy and paste that code you will receive the following error when trying to run the project:

![image](https://github.com/dotnet/docs-maui/assets/26213368/9adefbf5-c3ee-441b-b2e2-135c2c5bdc45)

The fix is to include the `<VisualStateGroupList>` as the child for the `<VisualStateManager.VisualStateGroups>` as stated in this [StackOVerFlow post](https://stackoverflow.com/a/73691990/6368401), like so:
```
<CheckBox ...>
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroupList>
            <VisualStateGroup x:Name="CommonStates">
                <VisualState x:Name="Normal">
                    <VisualState.Setters>
                        <Setter Property="Color"
                            Value="Red" />
                    </VisualState.Setters>
                </VisualState>

                <VisualState x:Name="IsChecked">
                    <VisualState.Setters>
                        <Setter Property="Color"
                            Value="Green" />
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateGroupList>
    </VisualStateManager.VisualStateGroups>
</CheckBox>
```

This should be reflected in the documentation.

---
[Associated WorkItem - 286736](https://dev.azure.com/msft-skilling/Content/_workitems/edit/286736)

**Comment by davidbritch** [comment]
The code in the sample is correct, it's just that the docs need updating to reflect the sample.
