### ISSUE TITLE
.NET MAUI 9: Compiled bindings support the Source property

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#2187]
In .NET MAUI 9, it will be possible to compile bindings that set the `Source` property.

https://github.com/dotnet/maui/pull/20610

---
[Associated WorkItem - 318109](https://dev.azure.com/msft-skilling/Content/_workitems/edit/318109)

**Comment by awasilik** [comment]
Any plans to fix that in .NET9 final release or we need to stick to workaround?
