### ISSUE TITLE
.NET MAUI 9: Compiled binding warnings disabled

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#2188]
In .NET MAUI 9, `x:DataType` warnings will be disabled. However, the behaviour can be opted back into by setting the `$(MauiStrictXamlCompilation)` build property to `true`. This strict compilation will remain enabled by default for NativeAOT.

https://github.com/dotnet/maui/pull/21418

---
[Associated WorkItem - 314389](https://dev.azure.com/msft-skilling/Content/_workitems/edit/314389)

**Comment by simonrozsival** [comment]
The warnings were disabled in a .NET 8 servicing release but they should be enabled by default in .NET 9. The reason why we disabled them was that they were introduced in a .NET 8 servicing release and started breaking customers' app builds.
