### ISSUE TITLE
Device could not be created with visual studio 2022

### ISSUE THREAD

**Issue by Laurenshine** [dotnet/docs-maui#2203]
### Type of issue

Other (describe below)

### Description

Please file an issue by choosing "Send Feedback > Report a Problem" in the Help menu.  
Error summary: avdmanager has returned non-zero exit code: 1. Please check logs for more information.
![Screenshot 2024-04-15 214505](https://github.com/dotnet/docs-maui/assets/107372621/a4edd812-8742-4322-8173-049de4135296)

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?view=net-maui-8.0&tabs=vswin

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md

### Document Version Independent Id

e77ba6a7-e59d-1e1e-52e1-935f98a985cf

### Article author

@davidbritch

### Metadata

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by timeshift92** [comment]
i also get this error

**Comment by davidbritch** [comment]
Hi @Laurenshine 

Afraid that all I can recommend you do is to file an issue by choosing "Send Feedback > Report a Problem" in the Help menu.
