### ISSUE TITLE
Crash caused by activity.Finish(); line

### ISSUE THREAD

**Issue by ahoffmandevelopment** [dotnet/docs-maui#2212]
### Type of issue

Code doesn't work

### Description

In the "Read the data from the incoming intent" section, in the example code there is a line `activity.Finish();` . Having this line included causes the app to behave incorrectly when opening it from a deep link.

The app won't "crash" in the traditional sense, but does immediately go into the background. Opening the app switcher and choosing the app again just repeats the behavior.

Removing that line from my code allowed my deep link to behave correctly. I recommend removing this line.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/android/app-links?view=net-maui-8.0#read-the-data-from-the-incoming-intent

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/android/app-links.md

### Document Version Independent Id

8a77b383-4209-5406-59a1-5df947a75e47

### Article author

@davidbritch

### Metadata

* ID: 8a77b383-4209-5406-59a1-5df947a75e47 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 255342](https://dev.azure.com/msft-skilling/Content/_workitems/edit/255342)

**Comment by ahoffmandevelopment** [comment]
Pull Request #2213

**Comment by davidbritch** [comment]
Fixed by #2213
