### ISSUE TITLE
NotePage.xaml.cs - InitializeComponent does not exist in the current context

### ISSUE THREAD

**Issue by LintonSol** [dotnet/docs-maui#2220]
### Type of issue

Code doesn't work

### Description

InitializeComponent does not exist in the current context.

TextEditer does not exist in the current context.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?view=net-maui-8.0&tutorial-step=3

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml

### Document Version Independent Id

720bf7f0-db92-f738-b864-ee149a02377b

### Article author

@adegeo

### Metadata

* ID: 720bf7f0-db92-f738-b864-ee149a02377b 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @LintonSol 

If you try the sample that the tutorial links to you'll see that it builds just fine. So the problem will most likely be with your installation.
