### ISSUE TITLE
"should>>>n't<<< be placed in any of the Platforms child folders" in "Important" box

### ISSUE THREAD

**Issue by thomiel** [dotnet/docs-maui#2234]
### Type of issue

Typo

### Description

There is a contradiction in the text:

The "Important" box reads 
> The cross-platform partial class should**n't** be placed in any of the Platforms child folders of your project.

In the text below it's the opposite case:
> The partial method implementations are then defined in the platform-specific partial classes, which **should** be placed in the correct Platforms child folders

The text in the box needs to be changed to:
> The cross-platform partial class **should** be placed in any of the Platforms child folders of your project.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md

### Document Version Independent Id

70227b04-808f-1370-186b-10cfef525959

### Article author

@davidbritch

### Metadata

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 252786](https://dev.azure.com/msft-skilling/Content/_workitems/edit/252786)

**Comment by davidbritch** [comment]
Hi @thomiel 

Having looked at this I think the text is correct. What it's saying is that the following code is cross-platform code, and as such shouldn't go in any of the *Platforms* child folders, because we want it to be compiled for all platforms rather than one specific platform:

```
namespace CustomizeHandlersDemo.Views;

public partial class CustomizeEntryPartialMethodsPage : ContentPage
{
    public CustomizeEntryPartialMethodsPage()
    {
        InitializeComponent();
    }

    partial void ChangedHandler(object sender, EventArgs e);
    partial void ChangingHandler(object sender, HandlerChangingEventArgs e);

    void OnEntryHandlerChanged(object sender, EventArgs e) => ChangedHandler(sender, e);
    void OnEntryHandlerChanging(object sender, HandlerChangingEventArgs e) => ChangingHandler(sender, e);
}
```

Then the rest of the implementation does go into *Platforms* child folders, as they contain platform-specific code.

Agreed that the text is a bit unclear on this though, so I'll see what I can do to clarify it.

**Comment by thomiel** [comment]
ah, ok. maybe refer to the code above or add a "... while the platform specific partial class goes ..."

**Comment by thomiel** [comment]
or call it "platform independent partial class". in my head, the platform-specific code is part of the cross-plattform whole.

**Comment by davidbritch** [comment]
There's a sample link at the top of the page that hopefully clarifies it all (in addition to the text).
