### ISSUE TITLE
I am unable to submit to microsoft store 

### ISSUE THREAD

**Issue by maharasa** [dotnet/docs-maui#2236]
### Type of issue

Typo

### Description

I have ugrated .net6.0 to .net 8.0 of my blazor maui project when I submit my application in store
the following issue 
10.2.4.1 Security - Software Dependencies
Products may depend on non-integrated software (such as another product or module) to deliver primary functionality only as long as the additional required software is disclosed within the first two lines of the description in the Store. 
.NET

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-visual-studio-folder?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/windows/deployment/publish-visual-studio-folder.md

### Document Version Independent Id

a9a8421b-ca5d-96e3-35ab-60118e356017

### Article author

@davidbritch

### Metadata

* ID: a9a8421b-ca5d-96e3-35ab-60118e356017 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @maharasa 

Looks like you've got your answer: https://learn.microsoft.com/en-us/answers/questions/1662961/how-to-fix-10-2-4-1-security-software-dependencies
