### ISSUE TITLE
Splashscreen on iOS cannot be tested in Simulators

### ISSUE THREAD

**Issue by sandeshkarki55** [dotnet/docs-maui#2268]
### Type of issue

Typo

### Description

The splashscreen on iOS doesn't work on simulators and needs to be signed to be seen. User will require phycasl device to test. 

Can a note for this be added?

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?view=net-maui-8.0&tabs=android

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/splashscreen.md

### Document Version Independent Id

44323c6e-d65c-b254-ee3c-cd9415bdf3bc

### Article author

@davidbritch

### Metadata

* ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 259812](https://dev.azure.com/msft-skilling/Content/_workitems/edit/259812)

**Comment by Yuritzia** [comment]
[HomeHistory.pdf](https://github.com/dotnet/docs-maui/files/15467761/HomeHistory.pdf)
