### ISSUE TITLE
Missing parenthesis in the description of sdkmanager packages installation for macOS

### ISSUE THREAD

**Issue by mariuszmatusiak** [dotnet/docs-maui#2269]
### Type of issue

Typo

### Description

`./sdkmanager --install system-images;android-33;google_apis;x86_64` 
doesn't execute properly in zsh terminal in VS Code.

One should use:
`./sdkmanager --install "system-images;android-33;google_apis;x86_64"`

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?view=net-maui-8.0&pivots=devices-windows&tabs=visual-studio-code#choose-your-target-device

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md

### Document Version Independent Id

e77ba6a7-e59d-1e1e-52e1-935f98a985cf

### Article author

@davidbritch

### Metadata

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 258786](https://dev.azure.com/msft-skilling/Content/_workitems/edit/258786)

**Comment by jonpryor** [comment]
#2275 would fix this.

**Comment by davidbritch** [comment]
Fixed by #2275
