### ISSUE TITLE
AndroidPlatformMAUI2; PackageAction:Install; ReturnCode:-1 

### ISSUE THREAD

**Issue by ManishAgrawaal** [dotnet/docs-maui#2272]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=vswin

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md

### Document Version Independent Id

9a62d421-d009-30b3-843e-a92bfc21c061

### Article author

@davidbritch

### Metadata

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @ManishAgrawaal 

What's your issue?
