### ISSUE TITLE
"First .Net MAUI App" is outdated

### ISSUE THREAD

**Issue by cosmo0** [dotnet/docs-maui#2277]
### Type of issue

Outdated article

### Description

The screenshots and steps are out of sync with the current .Net MAUI experience:

- the wizard creates a project for each platform, not just one
- I couldn't find the "debug target" menu with Android emulators etc (but maybe I'm missing something)

The result screenshot is also out of date: it displays a racing car, but the actual result is a "hello" bot

![image](https://github.com/dotnet/docs-maui/assets/3973850/a33d9322-59d7-4e56-979d-54257e586f4f)

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?view=net-maui-8.0&tabs=vswin&pivots=devices-windows

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md

### Document Version Independent Id

e77ba6a7-e59d-1e1e-52e1-935f98a985cf

### Article author

@davidbritch

### Metadata

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 259810](https://dev.azure.com/msft-skilling/Content/_workitems/edit/259810)

**Comment by davidbritch** [comment]
Hi @cosmo0 

Sounds like you've created a multi-project .NET MAUI project, rather than a single project. The tutorial is specifically for a single project .NET MAUI app.

**Comment by cosmo0** [comment]
Right! I didn't notice there were multiple similar types of projects. So maybe the page should just specify to use the single-project template.

**Comment by davidbritch** [comment]
No action required. The tutorial states and shows the correct template to use.
