### ISSUE TITLE
try to disable hover effect during nivation between TabBar Tabs in .NET MAUI

### ISSUE THREAD

**Issue by ibrahimahmed1998** [dotnet/docs-maui#2282]
### Type of issue

Missing information

### Description

I tried a lot to hide or delete Hover effect as below form app but I can't get the item which has this effect the issue when I click on any menu tap make short hover circle and it affect UI Badly

XAML Code :

` <?xml version="1.0" encoding="UTF-8" ?>
<Shell 
    x:Class="MauiApp1.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:views="clr-namespace:MauiApp1.Views.Main"
    xmlns:auth_folder="clr-namespace:MauiApp1.Views.Auth"
    Shell.TabBarUnselectedColor="White" Shell.TabBarIsVisible="True" Shell.TabBarForegroundColor="White"
    Shell.TabBarBackgroundColor="{StaticResource PrimaryColor}" Shell.TabBarDisabledColor="{StaticResource PrimaryColor}"
    Shell.UnselectedColor="{StaticResource PrimaryColor}"
    Shell.FlyoutBehavior="Disabled"
    Shell.ForegroundColor="White" 
    Shell.BackgroundColor="{StaticResource PrimaryColor}"
    Shell.TitleColor="White"  
    Shell.NavBarHasShadow="False" >

    <Shell.Resources>
        <Style TargetType="TabBar">
            <Setter Property="Shell.TabBarBackgroundColor" Value="Blue" />
            <Setter Property="Shell.TabBarCurrentBackgroundColor" Value="Orange" /> // New API function
            <Setter Property="Shell.TabBarUnselectedColor" Value="White"/>
            <Setter Property="Shell.TabBarTitleColor" Value="White"/>
        </Style>
    </Shell.Resources>

    <ShellContent ContentTemplate="{DataTemplate auth_folder:GetStarted}" Route="GetStarted"/>
    <ShellContent ContentTemplate="{DataTemplate auth_folder:LoginForm}" Route="LoginForm"/>

    <TabBar>
        
        <Tab Icon="b_home.png">
            <ShellContent  ContentTemplate="{DataTemplate views:Home}" Route="Home" PropertyChanged="ShellContent_PropertyChanged"
                           Icon="{OnPlatform 'b_home.png', iOS='b_home.png' }" />
        </Tab>

        <Tab Icon="b_persona.png">
            <ShellContent ContentTemplate="{DataTemplate views:Profile}" Route="About" PropertyChanged="ShellContent_PropertyChanged"
            Icon="{OnPlatform 'b_persona.png', iOS='b_persona.png'}" />
        </Tab>
   
        <Tab Icon="b_tel.png">
            <ShellContent ContentTemplate="{DataTemplate views:Red365}" Route="Red365" PropertyChanged="ShellContent_PropertyChanged"
            Icon="{OnPlatform 'b_tel.png', iOS='b_tel.png'}" />
        </Tab>
    </TabBar>
</Shell>
`

![xBp11MiI](https://github.com/dotnet/docs-maui/assets/27674492/e0381fa0-0552-4f05-adb5-28738a4d4022)

![4ODCVHLj](https://github.com/dotnet/docs-maui/assets/27674492/3f4c25ec-4208-47b5-83f6-5ee9251413d2)

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/tabs?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/tabs.md

### Document Version Independent Id

8b75579a-1ca4-376a-f5df-41de5c690acc

### Article author

@davidbritch

### Metadata

* ID: 8b75579a-1ca4-376a-f5df-41de5c690acc 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
I recommend asking on the [Q&A forums](https://learn.microsoft.com/answers/tags/247/dotnet-maui). Thanks!
