### ISSUE TITLE
.NET MAUI 9: Compiled bindings can be used with C# markup

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#2304]
In .NET MAUI 9, compiled bindings can be used with C# markup (to replace reflection-based bindings with string paths).

Example:

```csharp
// in .NET 8
MyLabel.SetBinding(Label.TextProperty, "Text");

// in .NET 9
MyLabel.SetBinding(Label.TextProperty, static (Entry entry) => entry.Text);
```

This new approach has several advantages:

- better performance (benefits are already summarized in the docs: https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings?view=net-maui-8.0#performance)
- intellisense while editing
- compile-time check of path validity

This approach is required instead of string-based bindings in NativeAOT apps, and in apps with full trimming enabled.

More info: https://github.com/dotnet/maui/pull/21725

---
[Associated WorkItem - 314390](https://dev.azure.com/msft-skilling/Content/_workitems/edit/314390)

**Comment by simonrozsival** [comment]
~~Hopefully we will have~~ We have a second related API to create compiled bindings in C#: https://github.com/dotnet/maui/pull/23239

```c#
BindingBase binding = Binding.Create(static (Entry entry) => entry.Text);
```

The PR mentions several scenarios where this new API is useful.

**Comment by maonaoda** [comment]
@simonrozsival 
Is it really usable now?

**Comment by simonrozsival** [comment]
@maonaoda yes, these features were released in .NET MAUI 9. Please, if you are having trouble using it, open a new issue in https://github.com/dotnet/maui so we can look into it.

**Comment by maonaoda** [comment]
@simonrozsival 
I did try to use it, but when I opened the page, the app crashed, and it is currently impossible to bind.

I can't see where it is actually implemented in the code
https://github.com/dotnet/maui/blob/d3784a49dd6b473ca6adc17baa5c32b1742c53ae/src/Controls/src/Core/BindableObjectExtensions.cs#L143C1-L147C4

**Comment by simonrozsival** [comment]
discussion moved here: https://github.com/dotnet/maui/discussions/26145
