### ISSUE TITLE
.NET MAUI 9: Configure fire and forget for Android disposal on BlazorWebView

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#2306]
In .NET MAUI 9, if you encounter hangs on Android with `BlazorWebView` you can enable an `AppContext` switch in `MauiProgram`:

```csharp
AppContext.SetSwitch("BlazorWebView.AndroidFireAndForgetAsync", isEnabled: true);
```

This switch enables `BlazorWebView` to fire and forget the async disposal that occurs. By default, `BlazorWebView` does async-over-sync for disposal, meaning that it blocks the thread until the async disposal is complete. However, this can cause deadlocks if the disposal needs to run code on the same thread (because that thread is blocked while waiting).

Enabling this new switch means that disposal can return before all objects are disposed, which can cause behavioral changes in an app. The items that are disposed are partially Blazor's own internal types, but also app-defined types such as scoped services used within the `BlazorWebView` portion of the app.

More info: https://github.com/dotnet/maui/pull/22496

---
[Associated WorkItem - 314395](https://dev.azure.com/msft-skilling/Content/_workitems/edit/314395)

**Comment by Kebechet** [comment]
is this going to be enabled by default in .NET9?

**Comment by Eilon** [comment]
> is this going to be enabled by default in .NET9?

I logged https://github.com/dotnet/maui/issues/24250 to consider changing it.
