### ISSUE TITLE
Hot Reload required Configuration = Debug (literally)

### ISSUE THREAD

**Issue by rcarde** [dotnet/docs-maui#2315]
### Type of issue

Missing information

### Description

If custom build configurations are used with a MAUI build, Hot Reload stops working if the debug build isn't called `Debug` (literally).

Can we please get clarification in the documentation that MAUI builds are sensitive to build configuration names and that `Release` and `Debug` are required to avoid issues with builds?

The .NET 6+ [documentation](https://learn.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022#unsupported-net-projects) for Hot Reload states that "_Release or custom build configurations aren't supported. Your project must use the Debug build configuration._"

Related[ issue on GitHub](https://github.com/dotnet/maui/issues/9627) which still seems relevant today.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/xaml/hot-reload?view=net-maui-8.0&tabs=vswin

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/xaml/hot-reload.md

### Document Version Independent Id

31cbef98-89fe-fb8a-c1a5-3119c1f0c207

### Article author

@davidbritch

### Metadata

* ID: 31cbef98-89fe-fb8a-c1a5-3119c1f0c207 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 270741](https://dev.azure.com/msft-skilling/Content/_workitems/edit/270741)

**Comment by davidbritch** [comment]
Hi @rcarde 

Just confirming that:

1. Yes, .NET MAUI XAML Hot Reload only works with Debug configuration. There's a feature request to enable XAML hot reload for other configs (https://github.com/dotnet/maui/issues/9745) but I suspect it won't be implemented anytime soon .
2. .NET Hot Reload is different in that it just requires that the configuration isn't optimising the code during the build.

I'll get the docs updated.
