### ISSUE TITLE
Add Link to .Net Upgrade Assistant

### ISSUE THREAD

**Issue by savionlee** [dotnet/docs-maui#233]
Would be handy so a user doesn't have to go search for the approved upgrade assistant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e223-a9cc-1efb-07ec-01c8501d7a46
* Version Independent ID: 538673ca-22c5-2a5c-97c0-1552ae9f7b79
* Content: [Migrate your app from Xamarin.Forms to .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/migrate)
* Content Source: [docs/get-started/migrate.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/migrate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @savionlee 

It'll be linked to once it's finished and works :)
