### ISSUE TITLE
按照此方式创建项目速度极慢

### ISSUE THREAD

**Issue by onedotone-wei** [dotnet/docs-maui#2350]
### Type of issue

Typo

### Description

[在此处输入反馈]
按照此方式创建项目速度极慢

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/maui/get-started/first-app?view=net-maui-8.0&tabs=vswin&pivots=devices-android

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md

### Document Version Independent Id

e77ba6a7-e59d-1e1e-52e1-935f98a985cf

### Article author

@davidbritch

### Metadata

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @onedotone-wei 

Afraid that there's not much the docs team can do about that!
