### ISSUE TITLE
How to debug a .Net for iOS app.

### ISSUE THREAD

**Issue by jbouche-work** [dotnet/docs-maui#2351]
### Type of issue

Missing information

### Description

[Enter feedback here]
Hi,

There is not a chapter to debug an .Net for iOS app with the VSC debugger.

Jérôme.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/ios/cli?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/ios/cli.md

### Document Version Independent Id

da0a1dce-0ab0-7d18-8dc9-e37854995ace

### Article author

@davidbritch

### Metadata

* ID: da0a1dce-0ab0-7d18-8dc9-e37854995ace 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @jbouche-work 

I might be missing the point here - what is it you need to know? It's no different to debugging any other app?

**Comment by jbouche-work** [comment]
> Hi @jbouche-work
> 
> I might be missing the point here - what is it you need to know? It's no different to debugging any other app?

Hello, I found the solution in the meantime :).
Maybe mention which plugins are necessary under VSC to debug .Net for iOS?

**Comment by davidbritch** [comment]
@jbouche-work  Is this a .NET MAUI app that uses .NET for iOS, or a 100% .NET for iOS app?

**Comment by jbouche-work** [comment]
> @jbouche-work Is this a .NET MAUI app that uses .NET for iOS, or a 100% .NET for iOS app?

This a 100% .Net for iOS app (I've also a .Net for Android app).
I just migrated it from Xamarin Native :).

No MAUI in my stack (only for MAUI Essentials).

**Comment by davidbritch** [comment]
So I'm afraid I'll be closing this issue. The docs are for .NET MAUI, not for .NET for iOS. While the docs do mention .NET for iOS, it's more in the context of using it inside .NET MAUI.

There aren't any docs for .NET for iOS at all.

**Comment by jbouche-work** [comment]
> So I'm afraid I'll be closing this issue. The docs are for .NET MAUI, not for .NET for iOS. While the docs do mention .NET for iOS, it's more in the context of using it inside .NET MAUI.
> 
> There aren't any docs for .NET for iOS at all.

Where can I open an issue to have docs for .NET for iOS ?
;)

**Comment by davidbritch** [comment]
> Where can I open an issue to have docs for .NET for iOS ? ;)

Good question - there is a repo for them but it's private. The best place for it is https://github.com/xamarin/xamarin-macios

There's a plan to publish some to learn.microsoft.com/dotnet/ios (just as there's already some Android docs at learn.microsoft.com/dotnet/android), but whether it'll happen is anybody's guess.
