### ISSUE TITLE
Add information to the CoillectionView documentation showing how to handle a reselect scenario

### ISSUE THREAD

**Issue by PureWeen** [dotnet/docs-maui#2362]
## Help make content visible

A common scenario is that users will select something and then navigate away. Once they navigate back the element is still selected which will result in users being unable to reselect the given item.
 
https://github.com/dotnet/maui/pull/21490#discussion_r1623301225

The original issue also points to our samples, because our samples don't allow reselection.
https://github.com/dotnet/maui/issues/20273

So, it might be useful to update our samples so that re-selection works and users can see it working.

**Comment by kubaflo** [comment]
@PureWeen
https://github.com/dotnet/maui-samples/pull/495
https://github.com/dotnet/docs-maui/pull/2388
