### ISSUE TITLE
How #ifdef compiler directive in Maui Blazor

### ISSUE THREAD

**Issue by snowfalcon27** [dotnet/docs-maui#238]
(1) I appreciate seeing how to do the #ifdef compiler directive to multi-target code based on the platform example here for c# code in Maui Blazor. But how do I do the same #ifdef definitions in the .razor code when I need conditional logic to display the UI differently based on the platform?

i.e., A simple example would be how the NavMenu would display vs the MainLayout may differ greatly between mobile devices vs Windows, Mac or WASM.

(2) Additional question: were are Maui Blazor examples to show us how to access the Native devices in each platform?

Thanks,
Tom
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6
* Version Independent ID: 70227b04-808f-1370-186b-10cfef525959
* Content: [.NET MAUI control customization with handlers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize)
* Content Source: [docs/user-interface/handlers/customize.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @snowfalcon27 

I spoke to the engineer responsible for Blazor support in .NET MAUI and he says that #if *might* work in the `@ code { ... }` part, but not anywhere else. It should be possible to use Microsoft.Maui.Essentials to detect the platform the app is running on, and display different UI based on the platform.

Full docs will be added by the time the product launches.
