### ISSUE TITLE
The installation instructions don't work. 

### ISSUE THREAD

**Issue by hallambaker** [dotnet/docs-maui#239]
No, the install does not work with VS Community preview 2022 17.1.0 P 1.1

Had to do a maui-check to find out that the android workloads are not complete, and that even after doing an install of the android payload.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation#feedback)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @hallambaker 

The installation instructions are correct. There's nothing more to it than installing the mobile workload. However, the Android build tools/SDK/emulator aren't installed until you first try to build/deploy to Android from a .NET MAUI project in Visual Studio.

Afraid that maui-check isn't an officially supported product.
