### ISSUE TITLE
.NET-MAUI Information

### ISSUE THREAD

**Issue by EJE-2** [dotnet/docs-maui#240]
I read the different MAUI paragraphs and didn't see the words Linux or UNIX or any other flavor of them anywhere which was a little disappointing as it would appear that there will be zero support for them in the great new world of Microsoft "Open Source" initiatives!

    It appears they are giving IOS/Android and MacOS brand new versions of forms/functions that already at least work but are unwilling to complete the development for the remainder of the smaller developers who have foolishly been waiting for the imminent arrival of WinForm functionality on UNIX/Linux - it would have been easier on all if MS would just admit they aren't going to do it - for whatever reason .... even if that reason is "...is doesn't fit our current business model or direction...".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be98396-dc5f-1a99-f96a-a346c3098e2c
* Version Independent ID: e5c64f3c-1ca2-a0d8-b16a-e189918eedb7
* Content: [What is .NET MAUI? - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui)
* Content Source: [docs/what-is-maui.md](https://github.com/dotnet/docs-maui/blob/main/docs/what-is-maui.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for your feedback.
