### ISSUE TITLE
Article seems to be missing instructions to get the result from Permissions.RequestAsync

### ISSUE THREAD

**Issue by kevcrooks** [dotnet/docs-maui#2414]
### Type of issue

Missing information

### Description

After experimenting, it seems that `Permissions.RequestAsync` will never return first time the app is started, unless overriding `OnRequestPermissionsResult` from `MainActivity`:
```
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
        {
            Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

Without this step, first time calling `RequestAsync` will hang, and the task will never return a value.

Can this be checked, and if it is the case that this instruction is missing, can it be added to the documentation?

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/push-notifications?view=net-maui-8.0#configure-the-android-app

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/push-notifications.md

### Document Version Independent Id

1de68bd7-d1d2-9dfa-5eea-c4d5da6c4a62

### Article author

@davidbritch

### Metadata

* ID: 1de68bd7-d1d2-9dfa-5eea-c4d5da6c4a62 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @kevcrooks 

The sample (linked to at the top of the doc) doesn't override `OnRequestPermissionsResult`.

**Comment by kevcrooks** [comment]
Yes I see the same, and it does seem to be running there. I was attempting to use in a new app, where we ask for permissions at a later point, and the task wasn't returning. I'd based our fix on this old document, which did work for us (calling the .MAUI library instead): https://github.com/xamarin/Essentials/issues/1227

However I don't know why it works in the sample, but in our program we need to override `OnRequestPermissionsResult`. Happy for this to be closed though, if it definitely isn't needed.
