### ISSUE TITLE
Installation instructions missing for macOS 

### ISSUE THREAD

**Issue by MosCD3** [dotnet/docs-maui#243]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-ca/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MosCD3 

Afraid there won't be any instructions for macOS until Visual Studio for Mac has .NET MAUI support. In the meantime, here's the workaround: https://dev.to/davidortinau/installing-net-maui-on-macos-4mmc
