### ISSUE TITLE
Installation instructions miss a step

### ISSUE THREAD

**Issue by AArnott** [dotnet/docs-maui#244]
The maui installation instructions only say the "Mobile development for .NET" workload needs to be installed. But in fact the "Maui (preview)" component within that workload is optional and off by default. It too must be checked by the user in order to acquire this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by PureWeen** [comment]
@AArnott what version of VS did you test this with? I just tested with the latest VS 17.1 preview installer and for me it's auto checked

![image](https://user-images.githubusercontent.com/5375137/148266358-cb68c0cd-761f-4ce7-8a56-1404fe0f9c9b.png)

**Comment by AArnott** [comment]
I'm on 17.1.0 Preview 3.0 (32103.382.main) right now. I might have been on a build just a few days older than that when I reported this ticket. 
I wonder if the issue isn't the default, but simply that I already had "Mobile development for .NET" installed, before Maui was added. So when I was following the instructions, I saw the workload selected which fit the instructions, but the optional component wasn't selected because it simply wasn't available before. If that's a reasonable scenario, perhaps the instructions should include verifying that the optional component is selected.

**Comment by PureWeen** [comment]
@AArnott That sounds about right. In that case I wonder if this is a VS Installer bug that should be installing that workload. I'm not sure what the current plan is for this path. 

Let me get back to you

**Comment by davidbritch** [comment]
Closing this, following internal discussion, that it's not something external users will see.

**Comment by AArnott** [comment]
Hi @davidbritch, I wasn't privy to the internal discussions I guess, but I question the conclusion. Why wouldn't external users see this? I suspect the repro is as simple as installing VS 17.0 then upgrading to a later version. Since Maui wasn't installed with 17.0, I suspect the update to a later version with Maui won't *add* the component automatically. If that's true, then the docs could be improved to avoid the confusion I went through.
