### ISSUE TITLE
Apple music sdk examples for Maui.

### ISSUE THREAD

**Issue by rfustino** [dotnet/docs-maui#2452]
### Type of issue

Other (describe below)

### Description

Having a hard time finding an Apple music sdk example for Maui. Please point me to one.
Thanks!

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/?view=net-maui-8.0&viewFallbackFrom=net-maui-7.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/ios/deployment/index.md

### Document Version Independent Id

892d0e81-3825-e03d-5b30-1170b2918791

### Article author

@russfustino

### Metadata

* ID: 892d0e81-3825-e03d-5b30-1170b2918791 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @rfustino 

If you can't find anything out there, it'll be a case of having to convert code from Apple's docs to .NET for iOS.
