### ISSUE TITLE
Bundled SQLite Database

### ISSUE THREAD

**Issue by EmDe-NJ** [dotnet/docs-maui#2455]
### Type of issue

Code doesn't work

### Description

As per "File system helper"
File copy method works fine on windows, but throwing error in Android and IOS that couldn't find source file, interestingly working fine on small files on Windows, Android and IOS.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?view=net-maui-8.0&tabs=windows

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/file-system-helpers.md

### Document Version Independent Id

5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8

### Article author

@davidbritch

### Metadata

* ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @EmDe-NJ 

If that's the case you'll need to provide a full code repo, showing the situations where it works and doesn't work (and on which platform) to the dotnet/maui repo. Thanks!

**Comment by EmDe-NJ** [comment]
Thank you for your response, I am sending the codes, please look at it, what I am doing wrong? its working with this Db, but large Db only work on Windows platform, either getting a message, "No such Table" or " IO file not [found" (how can I send you the files or project) Posted on Git to take a look at it, here I am unable to attach any file or data, Thanks!

**Comment by EmDe-NJ** [comment]
Dear Sir,
I think you didn't get a chance to look at it yet, sending you the GitHub link again, I did little changes to call the Copy method, but still unable to run it on the other platforms besides Windows!
https://github.com/EmDe-NJ/BundledSQLiteDbExample

Regards!

eMDe-NJ
________________________________

**Comment by EmDe-NJ** [comment]
Issue resolved, it is working now, problem was with one table of the database. Thank you!
