### ISSUE TITLE
Missing ResourceDictionary

### ISSUE THREAD

**Issue by mthanson8333** [dotnet/docs-maui#2468]
### Type of issue

Missing information

### Description

Try to implement TargetNullValue in MonkeyPage.xaml and MonkeyDetailsPage.xaml but resource dictionary is missing. 
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/binding-fallbacks?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/binding-fallbacks.md

### Document Version Independent Id

cac8aa5b-ccba-2152-f88e-6b2f14c25448

### Article author

@davidbritch

### Metadata

* ID: cac8aa5b-ccba-2152-f88e-6b2f14c25448 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @mthanson8333 

If you look at the top of the doc there's a link to download the sample for the page. That has the ResourceDictionary that you require.

**Comment by mthanson8333** [comment]
Thanks for the info.  Problem is I'm trying to understand flow.  Nowhere on the web page does it say add the following ResourceDictionary to the App.xaml file.  I shouldn't have to download code, all information should be on the web page.  Looking at the App.xaml file there is a lot of code there I haven't been adding.

Sent from Samsung Galaxy smartphone.
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
