### ISSUE TITLE
iOS Device information requires additional configuration

### ISSUE THREAD

**Issue by jdarwood007** [dotnet/docs-maui#2475]
### Type of issue

Missing information

### Description

Apple has changed how device information may be returned, specifically the device name.

> In iOS, the user-assigned device name is available in the Settings app under General > About > Name. In iOS 15 and earlier, the [name](https://developer.apple.com/documentation/uikit/uidevice/1620015-name) property returns this name. In iOS 16 and later, the name property returns a generic device name by default instead.

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_device-information_user-assigned-device-name

Documentation should reflect his requirement and additional configuration.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device/information?view=net-maui-8.0&tabs=android

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device/information.md

### Document Version Independent Id

c35bd633-398f-ed9f-888d-a72d457a5745

### Article author

@davidbritch

### Metadata

* ID: c35bd633-398f-ed9f-888d-a72d457a5745 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

---
[Associated WorkItem - 314348](https://dev.azure.com/msft-skilling/Content/_workitems/edit/314348)

**Comment by davidbritch** [comment]
After looking at this I realised the page already has the required information in the Platform differences section at the bottom of the page.

**Comment by jdarwood007** [comment]
wow, that is very hidden. Perhaps there is a better way to identify that a platform-specific configuration is required to make the functionality work.

**Comment by davidbritch** [comment]
Agreed, I'll move it up the doc.
