### ISSUE TITLE
Article is about Maui but shows screenshots for native Android app

### ISSUE THREAD

**Issue by freever** [dotnet/docs-maui#2478]
### Type of issue

Other (describe below)

### Description

The section about downloading the google services json shows instructions for including it into a native Android project using Android Studio, but the article is specifically about setting up push notifications in a Maui app. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/push-notifications?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/push-notifications.md

### Document Version Independent Id

1de68bd7-d1d2-9dfa-5eea-c4d5da6c4a62

### Article author

@davidbritch

### Metadata

* ID: 1de68bd7-d1d2-9dfa-5eea-c4d5da6c4a62 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
>The section about downloading the google services json shows instructions for including it into a native Android project using Android Studio, but the article is specifically about setting up push notifications in a Maui app.

It shows how to download google-services.json from your Firebase project (see https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/push-notifications?view=net-maui-8.0#create-a-firebase-project), and then later on in the tutorial tells you where to place google-services.json in your .NET MAUI project.  The Firebase project screenshot mentions adding google-services.json to your Android Studio project, but we have no control over that and the doc doesn't tell you to do that.
