### ISSUE TITLE
WebView didn't show up Camera function with MAUI android platoform .net 8.0

### ISSUE THREAD

**Issue by eephyu** [dotnet/docs-maui#2482]
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
My WebView does not show the camera functionality when the user interacts with the web page. This issue affects the ability to capture or upload images from the page. I have already added the necessary camera-related permissions to the AndroidManifest.xml file and tried using the WebChromeClient method, but neither solution worked for me. Could you please provide sample source code or share working code if possible?

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/android/platform-specifics/webview-mixed-content?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/android/platform-specifics/webview-mixed-content.md

### Document Version Independent Id

8053e62d-9d3a-90fd-f59f-3f6427579147

### Article author

@davidbritch

### Metadata

* ID: 8053e62d-9d3a-90fd-f59f-3f6427579147 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @eephyu 

Take a look at https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?view=net-maui-8.0&pivots=devices-android#handle-permissions-on-android

**Comment by eephyu** [comment]
Hi David, 

Thank you for your help.

I had been followed given link documentation from day 1 and it wasn't working. That's why I am looking for working solution. You may have a look this repository [https://github.com/eephyu/WebViewCameraDemo]     
as I created demo for anyone who can help me on this issue.

I had a page where can define html url and the next page will show the form to submit employee information with upload photo. You may follow default url that I had been hard coded or change based on your preferences. 

https://github.com/eephyu/WebViewCameraDemo
