### ISSUE TITLE
There is no Debug Target dropdown

### ISSUE THREAD

**Issue by rade-projects** [dotnet/docs-maui#2484]
### Type of issue

Outdated article

### Description

In section 6 there is no Debug Target dropdown in the VS toolbar. This makes it impossible to install the Android Emulator and get started with Maui development training.

I have VS 2022 V17.11.2 installed with the Maui Workload.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?view=net-maui-8.0&tabs=vswin

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md

### Document Version Independent Id

e77ba6a7-e59d-1e1e-52e1-935f98a985cf

### Article author

@davidbritch

### Metadata

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @rade-projects 

Afraid it's not something I can help with. If your debug target drop-down isn't present, it most likely indicates an installation problem.
