### ISSUE TITLE
.NET MAUI 9: Markup extensions and extended type converters need `[RequiresService(typeof(T))]` or `[AcceptEmptyServiceProvider]` annotations

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/docs-maui#2486]
## Help make content visible

In .NET MAUI 9, we now require all classes implementing `IMarkupExtension`, `IMarkupExtension<T>`, `IValueProvider`, and `IExtendedTypeConverter` to be annotated with either `[RequireService(typeof(T))]` or `[AcceptEmptyServiceProvider]` attributes. This was introduced in https://github.com/dotnet/maui/pull/19945.

- For markup extensions, I think we need to update the examples and the "Service providers" section of [Create XAML markup extensions](https://learn.microsoft.com/en-us/dotnet/maui/xaml/markup-extensions/create?view=net-maui-8.0)
- I currently don't know where the changes related to `IValueProvider` should go

In a migration guide or release notes, we should tell customers how to address warnings they might see, such as in the case of https://github.com/dotnet/maui/issues/24736:
```
XamlC warning XC0103: Consider attributing the markup extension "CommunityToolkit.Maui.Converters.IsNullConverter" with [RequireService] or [AcceptEmptyServiceProvider] if it doesn't require any.
```

## Describe the change

We introduced a new optimization to XamlC which allows us to generate more efficient code when compiling XAML. This optimization helps reduce the final app size and also improve runtime performance.

###  [Create XAML markup extensions](https://learn.microsoft.com/en-us/dotnet/maui/xaml/markup-extensions/create?view=net-maui-8.0)

The example should be updated:
```diff
+[AcceptEmptyServiceProvider]
 public class HslColorExtension : IMarkupExtension<Color>
 {
```

#### The "Service providers" section
We should add a new paragraph describing the change:
- for each use of `serviceProvider.GetService(typeof(T))` in the `ProvideValue` method, the class should be annotated with `[RequireService(typeof(T))]` ([`Microsoft.Maui.Controls.Xaml.RequireServiceAttribute`](https://github.com/dotnet/maui/blob/68b953b2ba020766ce8403455da209a12cf43564/src/Controls/src/Core/IMarkupExtension.cs#L23-L24)) such as for example here: https://github.com/dotnet/maui/blob/68b953b2ba020766ce8403455da209a12cf43564/src/Controls/src/Xaml/MarkupExtensions/ReferenceExtension.cs#L8-L40. It might be a good idea to show a more complete example of the usage of `IProvideValueTarget` with the attribute applied to the class.

- if the markup extension doesn't use any service from the service provider, the class should be attributed with `[AcceptEmptyServiceProvider]` ([`Microsoft.Maui.Controls.Xaml.AcceptEmptyServiceProviderAttribute`](https://github.com/dotnet/maui/blob/68b953b2ba020766ce8403455da209a12cf43564/src/Controls/src/Core/IMarkupExtension.cs#L18))

/cc @StephaneDelcroix @davidbritch 

---
[Associated WorkItem - 314394](https://dev.azure.com/msft-skilling/Content/_workitems/edit/314394)

**Comment by davidbritch** [comment]
> In a migration guide or release notes, we should tell customers how to address warnings they might see, such as in the case of https://github.com/dotnet/maui/issues/24736:

@simonrozsival That should be handled in the [breaking changes docs](https://learn.microsoft.com/en-us/dotnet/core/compatibility/breaking-changes),  which are an engineering responsibility to provide.
