### ISSUE TITLE
Configuring Maui Blazor WKWebView Does Not Work Using Sample 'Microsoft.Maui.Handlers.WebViewHandler.PlatformViewFactory = (handler) =>...'

### ISSUE THREAD

**Issue by Thomr77** [dotnet/docs-maui#2488]
### Type of issue

Code doesn't work

### Description

Hi,

We have tried to use the below example code to configure a Maui Blazor WKWebView but it does not have any effect (the delegate/code is not called).
```
#if IOS || MACCATALYST
    Microsoft.Maui.Handlers.WebViewHandler.PlatformViewFactory = (handler) =>
    {
        WKWebViewConfiguration config = MauiWKWebView.CreateConfiguration();

        // True to play HTML5 videos inliine, false to use the native full-screen controller.
        config.AllowsInlineMediaPlayback = false;

        // True to play videos over AirPlay, otherwise false.
        config.AllowsAirPlayForMediaPlayback = false;

        // True to let HTML5 videos play Picture in Picture.
        config.AllowsPictureInPictureMediaPlayback = false;

        // Media types that require a user gesture to begin playing.
        config.MediaTypesRequiringUserActionForPlayback = WKAudiovisualMediaTypes.All;

        return new MauiWKWebView(CGRect.Empty, (WebViewHandler)handler, config);
    };
#endif
```
We placed the code in MauiProgram.cs just before `return builder.Build();`. We also tried other places like App.xaml.cs etc with the same result.

Instead we found out that configuring the WKWebView via BlazorWebViewInitializing works well:

```
#if IOS || MACCATALYST
    blazor_web_view.BlazorWebViewInitializing += (_, args) =>
    {
        args.Configuration.AllowsPictureInPictureMediaPlayback = false;
    };
#endif
```

We had limited testing time and so we are not sure if this applies to Maui Blazor only or to any Maui application with webview...?

We have tried this with Mac Catalyst and iOS.

Thanks!

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview?view=net-maui-8.0&pivots=devices-maccatalyst

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/webview.md

### Document Version Independent Id

ace91785-d304-f161-408e-34511fb75ce3

### Article author

@davidbritch

### Metadata

* ID: ace91785-d304-f161-408e-34511fb75ce3 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @Thomr77 

I think the issue here is that the code you've pasted in is configuring a `Microsoft.Maui.Handlers.WebViewHandler` rather than a `Microsoft.AspNetCore.Components.WebView.Maui.BlazorWebViewHandler`.

**Comment by Thomr77** [comment]
@davidbritch - Apologies as I should have mentioned that we tried this first.

We really could not piece it together though. The below 'handler' (BlazorWebViewHandler) does not inherit/implement ViewHandler<IWebView, WKWebView> like WebViewHandler does, so it is unclear how to provide the WebViewHandler parameter to the MauiWKWebView constructor.

```
#if IOS || MACCATALYST
    BlazorWebViewHandler.PlatformViewFactory = (handler) =>
    {
        WKWebViewConfiguration config = MauiWKWebView.CreateConfiguration();
        config.AllowsPictureInPictureMediaPlayback = false;

        return new MauiWKWebView(CGRect.Empty, (?WebViewHandler?)handler, config);
    };
#endif
```
Is this the right way/is there a sample for this? - We could not find anything.

So that is why the other route felt to be a good alternative...

Thanks!

**Comment by davidbritch** [comment]
Hi @Thomr77 

Unlike `WebView`, `BlazorWebView` doesn't use `MauiWKWebView`. Instead, it works with a `WKWebView`. So you could get the `Configuration` object from the `WKWebView`, and then return a new `WKWebView`:

```csharp
#if IOS || MACCATALYST
	Microsoft.AspNetCore.Components.WebView.Maui.BlazorWebViewHandler.PlatformViewFactory = (handler) =>
	{
		WKWebViewConfiguration config = handler.PlatformView.Configuration;
		config.AllowsPictureInPictureMediaPlayback = false;

		return new WKWebView(CoreGraphics.CGRect.Empty, config);
	};
#endif
```

While this is syntactically correct, it may introduce side effects as it will have destroyed other bits of `WKWebView` config that's performed [here](https://github.com/dotnet/maui/blob/b2c1d25f7a71197666c2053c1e40dbdea6049cc7/src/BlazorWebView/src/Maui/iOS/BlazorWebViewHandler.iOS.cs#L58). So it may be best to stick to your approach of modifying the config via `BlazorWebViewInitializing` which exposes the `Configuration` object.

**Comment by Thomr77** [comment]
Hi @davidbritch - thank you very much for your help!
