### ISSUE TITLE
The publish button is disabled (greyed out) in MAUI Multi Platform template 

### ISSUE THREAD

**Issue by dush135** [dotnet/docs-maui#2505]
### Type of issue

Missing information

### Description

There is no way of publishing Windows app, when using Maui Multi Platform template

[Enter feedback here]
![Screenshot 2024-09-18 182430](https://github.com/user-attachments/assets/7aa8f641-c737-4fa8-8389-7977b2f9ffe2)

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-visual-studio-folder?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/windows/deployment/publish-visual-studio-folder.md

### Document Version Independent Id

a9a8421b-ca5d-96e3-35ab-60118e356017

### Article author

@davidbritch

### Metadata

* ID: a9a8421b-ca5d-96e3-35ab-60118e356017 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @dush135 

This needs reporting to the product team, via [Developer Community](https://developercommunity.visualstudio.com/home). Thanks!
