### ISSUE TITLE
Navigation Issue

### ISSUE THREAD

**Issue by mthanson8333** [dotnet/docs-maui#2506]
### Type of issue

Code doesn't work

### Description

Downloaded the following code: [https://github.com/dotnet/maui-samples/tree/main/8.0/UserInterface/Layouts/AbsoluteLayoutDemos](url)
The menu on the MainPage does not work under Windows emulator.  When app opens, I can click on a menu item and navigate to a page.  When I return to the menu I cannot navigate to anymore pages.  Menu DOES work under Android emulator as expected.  Asked Copilot and the last suggestion which didn't work, is included below:

`using System.Diagnostics;
using System.Windows.Input;

namespace AbsoluteLayoutDemos
{
    public partial class MainPage : ContentPage
    {
        public ICommand NavigateCommand { get; private set; }

        public MainPage()
        {
            InitializeComponent();
            Debug.WriteLine("MainPage constructor called");

            NavigateCommand = new Command<Type>(
                async (Type pageType) =>
                {
                    Debug.WriteLine($"Navigating to {pageType.Name}");
                    Page page = (Page)Activator.CreateInstance(pageType);
                    await Navigation.PushAsync(page);
                    Debug.WriteLine($"Navigation stack count: {Navigation.NavigationStack.Count}");
                });

            BindingContext = this;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();
            Debug.WriteLine("MainPage appeared");
            BindingContext = this; // Ensure BindingContext is set
        }

        protected override void OnDisappearing()
        {
            base.OnDisappearing();
            Debug.WriteLine("MainPage disappeared");
        }
    }
}
`
I noticed other samples didn't work as well.

P.S.  Couldn't figure out how to insert a link correctly.  Have to copy text and paste.  Please fix this issue as well or post instructions on different options available such as what does a slash command do.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/absolutelayout?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/layouts/absolutelayout.md

### Document Version Independent Id

d8aac004-9823-8211-3e9d-aefe7d9c4d95

### Article author

@davidbritch

### Metadata

* ID: d8aac004-9823-8211-3e9d-aefe7d9c4d95 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @mthanson8333 

The fact that it works on Android/iOS/MacCat, but not Windows, tells us that there's nothing wrong with the sample code. Instead, it's a problem with the control implementation on Windows.

Therefore, an issue needs opening in the [product repo](https://github.com/dotnet/maui) if one doesn't already exist.

**Comment by mthanson8333** [comment]
Can you explain the difference between "Open a document issue" and "product repos" so I don't make the same mistake.  To me they are the same.  Thanks.

**Comment by davidbritch** [comment]
Hi @mthanson8333 

It's a difficult one for users to make a judgment call on. Users see a problem with a doc/sample and so open an issue here. But sometimes it's not actually a doc/sample problem - it's a product problem (like in this case where the issue only affects a single platform) in which case it needs reporting on the product repo. However, in this you don't need to bother as it's been reported multiple times there, with the latest one being: https://github.com/dotnet/maui/issues/21112

**Comment by mthanson8333** [comment]
That clarifies things.  Thank you.

Sent from Samsung Galaxy smartphone.
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
