### ISSUE TITLE
Das Programm "[25828] MauiApp3.exe" wurde mit Code 2147942405 (0x80070005) beendet.

### ISSUE THREAD

**Issue by SchneFre** [dotnet/docs-maui#2512]
### Type of issue

Code doesn't work

### Description

I cannot run the hello World app on windows machine (Android works fine)
I'm using Windows 11 Pro
I have developer mode activated.
I'm running visual Studio as administrator 
I tried Debug & Release
I tried uninstalling visual Studio and reinstalled MAUI Workflows

![{BA8F40FA-8819-44C8-8A92-74737489F772}](https://github.com/user-attachments/assets/9e6bee2a-bcfe-4092-9827-d948212b8ac6)
![{B4B82EF4-5BC3-48D0-A2D4-34E3CFBFEBFE}](https://github.com/user-attachments/assets/692f02ff-c9f1-4c5b-8823-4d032cd829bf)
![{DACED36C-EE5A-4F97-8C6A-33567ED8EB31}](https://github.com/user-attachments/assets/d907d702-2bad-4a4c-80f2-1cc40352c6c8)
![{545935ED-DF5F-41D1-9AF7-DA4E9C6AD186}](https://github.com/user-attachments/assets/10b9c045-6e75-4f9e-bf09-2d133552a456)
![{6FE70D02-0A57-40E1-B901-464782AC98F1}](https://github.com/user-attachments/assets/89393ab0-5b3e-4c54-9412-5cfa1cbedb1d)

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?view=net-maui-8.0&tabs=vswin

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md

### Document Version Independent Id

e77ba6a7-e59d-1e1e-52e1-935f98a985cf

### Article author

@davidbritch

### Metadata

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @SchneFre 

What happens when you try and run the app on Windows?
