### ISSUE TITLE
No text is displayed with HorizontalTextLayoutPage on Windows

### ISSUE THREAD

**Issue by mthanson8333** [dotnet/docs-maui#2532]
### Type of issue

Code doesn't work

### Description

Downloaded sample code from website.  Clicked on first menu item 'Horizontal Layout' and no text appeared under Windows emulator.  Application works fine under Android emulator.  See pics.

![NoTextWindows](https://github.com/user-attachments/assets/39935d41-435f-4702-99c1-676aac32ba6c)
![Android](https://github.com/user-attachments/assets/12e05ea3-52ff-4fd0-9972-ca43010e9210)

[Enter feedback here]
I did consult Copilot.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/carouselview/?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/carouselview/index.md

### Document Version Independent Id

e60f53fb-388a-756d-618f-1c29e177d671

### Article author

@davidbritch

### Metadata

* ID: e60f53fb-388a-756d-618f-1c29e177d671 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

[Related Issues](https://github.com/dotnet/docs-maui/issues?q=is%3Aissue+is%3Aopen+e60f53fb-388a-756d-618f-1c29e177d671)

**Comment by davidbritch** [comment]
Hi @mthanson8333 

Agreed that it's an issue, but it's one the product team are aware of and is awaiting a fix.
