### ISSUE TITLE
Missing XAML Code for Visual State Manager

### ISSUE THREAD

**Issue by jbeen25** [dotnet/docs-maui#2545]
### Type of issue

Typo

### Description

Literally, add `<VisualStateGroupList>` into the sample code so that it will work properly.

Apparently, it's been a problem for a long time.
https://developercommunity.visualstudio.com/t/NET-MAUI-Switch-visual-states-not-worki/10097030?q=maui

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/switch?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/switch.md

### Document Version Independent Id

00a39569-da70-b004-4d37-8a1999360518

### Article author

@davidbritch

### Metadata

* ID: 00a39569-da70-b004-4d37-8a1999360518 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @jbeen25 

I just tried the sample the page links to, which doesn't use `<VisualStateGroupList>`, and it works fine.
