### ISSUE TITLE
Saving drawingView stream on Android version lower than 10

### ISSUE THREAD

**Issue by petarkrastev** [dotnet/docs-maui#2564]
### Type of issue

Code doesn't work

### Description

When saving drawingView stream on Android version lower than 10 it is losing the lines colors

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/supported-platforms?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/supported-platforms.md

### Document Version Independent Id

ba07354c-611d-5efe-0fbb-48a24d02cafe

### Article author

@davidbritch

### Metadata

* ID: 6fb754bf-48db-4f6c-7e87-7cb3b59c34d5 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Hi @petarkrastev 

This needs reporting in the [.NET MAUI Community Toolkit repo](https://github.com/CommunityToolkit/Maui), as `DrawingView` belongs to that product. Thanks!
