### ISSUE TITLE
I have serious issue with the doc provided for `RadioButton`

### ISSUE THREAD

**Issue by ParsaGachkar** [dotnet/docs-maui#2576]
### Type of issue

Missing information

### Description

i have serious issue with the doc provided for [RadioButton](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?view=net-maui-8.0#respond-to-a-property-change).

why radio button's value is a string? what's the point of it? what it's not an `Enum` (the usual case)?

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/radiobutton.md

### Document Version Independent Id

a4d9b4fe-c357-031e-3fc4-9c22ffee81db

### Article author

@davidbritch

### Metadata

* ID: a4d9b4fe-c357-031e-3fc4-9c22ffee81db 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

[Related Issues](https://github.com/dotnet/docs-maui/issues?q=is%3Aissue+is%3Aopen+a4d9b4fe-c357-031e-3fc4-9c22ffee81db)

**Comment by davidbritch** [comment]
@ParsaGachkar  Because the .NET MAUI developers chose to make it a `string`. Similarly, in WPF the `RadioButton` displays a `string`. It's pretty normal.
