### ISSUE TITLE
Such stupid documentations are of no use, you should provide better ones with data loading from an HTTP RESTful service

### ISSUE THREAD

**Issue by cjmakwana** [dotnet/docs-maui#2578]
### Type of issue

Typo

### Description

Not sure why you guys write unprofessional documentation with examples like - foo, bar, monkeys !!! Kindly be professional, and share some better examples with weather or temperature data from a RESTful service. You already have many GitHub code repo for ASP.NET services implementing HTTP APIs. You can refer to those if someone wants to simulate both client and service together.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/populate-data?view=net-maui-8.0&source=docs

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/collectionview/populate-data.md

### Document Version Independent Id

a8ec6047-0b7b-ca7b-f1f5-22b005fab87c

### Article author

@davidbritch

### Metadata

* ID: a8ec6047-0b7b-ca7b-f1f5-22b005fab87c 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by davidbritch** [comment]
Thanks for the feedback @cjmakwana 

The point of that content is how to use the `CollectionView` control, not where the data comes from. It's a trivial task for most developers to apply the learnings from that content to retrieve data via REST.
