### ISSUE TITLE
Bridging the Gap: Migrating Xamarin.Android and Xamarin.iOS Native Apps to MAUI

### ISSUE THREAD

**Issue by Lalitchauha** [dotnet/docs-maui#2601]
### Type of issue

Code doesn't work

### Description

Please help the people who are suffering from converting their Xamarin Android and iOS native apps to MAUI.
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/android/app-links?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/android/app-links.md

### Document Version Independent Id

8a77b383-4209-5406-59a1-5df947a75e47

### Article author

@davidbritch

### Metadata

* ID: 8a77b383-4209-5406-59a1-5df947a75e47 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

**Comment by Lalitchauha** [comment]
Please help the people who are suffering from converting their Xamarin Android and iOS native apps to MAUI.

**Comment by davidbritch** [comment]
Hi @Lalitchauha 

Please email maui-upgrades@microsoft.com for support. Thanks.
