### ISSUE TITLE
It feels like there should be some mention how Maui colors differ from Xamarin colors

### ISSUE THREAD

**Issue by SimonRev** [dotnet/docs-maui#261]
[Enter feedback here]
For example, in Maui Color is a class and in Xamarin it is a struct (which causes a number of porting issues if nullability is enabled)

Also, the named colors are in the Colors class instead of Color.

Finally a description of how to handle Xamarin's Color.Default in Maui.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2ecf945-4296-460c-7d53-7fbec80017ab
* Version Independent ID: d2ecf945-4296-460c-7d53-7fbec80017ab
* Content: [Colors - .NET MAUI Graphics](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/graphics/colors)
* Content Source: [docs/user-interface/graphics/colors.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/colors.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SimonRev 

Agreed. The plan is that there'll be a Migration node in the TOC, full of articles on migrating your app from Xamarin.Forms to .NET MAUI. It'll cover topics like the `Color` differences, using .NET upgrade assistant, migrating custom renderers to handlers etc. 

I'll leave this issue open until that content is created. But to be clear, that's months and months away yet.

**Comment by davidbritch** [comment]
I'm not seeing anywhere in the doc where `Color` should be `Colors`? It already says that named colors are in `Colors`.

**Comment by davidbritch** [comment]
This is covered in the migration docs.
