### ISSUE TITLE
How to install manually without internet?

### ISSUE THREAD

**Issue by lampuiho** [dotnet/docs-maui#2613]
## Help make content visible

[Link](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md) only describes how to install with the command line `dotnet workload install maui` but I would like to know how to get the package manually and extract it to my own dotnet path

## Describe the new article

The dotnet package can be obtained in an archive without the installer, and extracted manually to a folder. This allows me to setup a machine without access to internet for developing dotnet applications. But there is no instruction on how to do this for MAUI.

**Comment by davidbritch** [comment]
Hi @lampuiho 

You can do this with Visual Studio by creating something called a local layout. For more info see https://learn.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022 and https://stackoverflow.com/questions/73756032/how-to-create-a-local-layout-for-maui-and-install-it-offline

**Comment by lampuiho** [comment]
> Hi [@lampuiho](https://github.com/lampuiho)
> 
> You can do this with Visual Studio by creating something called a local layout. For more info see https://learn.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022 and https://stackoverflow.com/questions/73756032/how-to-create-a-local-layout-for-maui-and-install-it-offline

But that's for installing to a Visual studio install not the portable version of dotnet?
