### ISSUE TITLE
Trimming defaults don't use advised trimming behavior

### ISSUE THREAD

**Issue by breyed** [dotnet/docs-maui#2644]
[Trimming defaults](https://learn.microsoft.com/en-us/dotnet/maui/deployment/trimming?view=net-maui-9.0#trimming-defaults) vary by build configuration:
> By default, Android and Mac Catalyst builds use partial trimming when the build configuration is set to a release build.

However, the [trimming behavior](https://learn.microsoft.com/en-us/dotnet/maui/deployment/trimming?view=net-maui-9.0#trimming-behavior) advice says not to:
> The `$(TrimMode)` build property shouldn't be conditioned by build configuration.

Either the behavior should be changed to match the advice or the advice should be updated to indicate when it is and is not recommended to condition `TrimMode` by configuration.

---
[Associated WorkItem - 350513](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350513)

**Comment by davidbritch** [comment]
Hi @breyed 

The intent here is that users should either accept the trimming defaults or if they're going to change the defaults, do so across all build configurations. I appreciate that the language could use some clarification.

**Comment by breyed** [comment]
@davidbritch What are the underlying technical reasons for the default of partial trimming for release but not debug on Android and Mac Catalyst? Intuitively, I would expect that if for example the user switched to full trimming, the same release/debug distinction would apply. I'm trying to understand why the guidance would be in the example to use full trimming in both release and debug.

**Comment by breyed** [comment]
The guidance in the docs should be reconciled with guidance from @jonathanpeppers in dotnet/maui#26509 to not use "`<PublishTrimmed>true</PublishTrimmed>` in Debug mode on Android".

**Comment by jonathanpeppers** [comment]
Generally, I don't think you should have to set `$(PublishTrimmed)` on mobile or know this setting exists. It should pick the right thing by default for you. On Android, there isn't really a good reason to turn it on in Debug mode, or turn it off in Release mode. Doing either of those will cause issues. And then behavior differs on iOS or other platforms.

This has some details about the current behavior, that we might improve in .NET 10:
* https://github.com/dotnet/android/issues/9526

**Comment by davidbritch** [comment]
Fixed by #2688 and #2689
