### ISSUE TITLE
Image showing location of different types of content on the Windows TitleBar is incorrect

### ISSUE THREAD

**Issue by Bowman74** [dotnet/docs-maui#2647]
### Type of issue

Other (describe below)

### Description

The image that shows where the content is is incorrect. It shows the leading content to be after the sub title and before the content. However, when running with an icon, title and subtitle the leading content shows up before even the icon.

The order the documentation shows:
Icon|Title|Sub Title|Leading Content|Content|Trailing Content

The actual order displayed:
Leading Content|Icon|Title|Sub Title|Content|Trailing Content

I am running on an ARM M2 Mac with Windows in Parallels. I have not tried this on an Intel Windows machine.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/titlebar?view=net-maui-9.0#create-a-titlebar

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/titlebar.md

### Document Version Independent Id

06c3bd5e-922d-562a-ca22-7c9b28602c24

### Article author

@davidbritch

### Metadata

* ID: 06c3bd5e-922d-562a-ca22-7c9b28602c24 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

[Related Issues](https://github.com/dotnet/docs-maui/issues?q=is%3Aissue+is%3Aopen+06c3bd5e-922d-562a-ca22-7c9b28602c24)

---
[Associated WorkItem - 350512](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350512)

**Comment by Bowman74** [comment]
@davidbritch Thanks for correcting that!

This link also shows the old image with the incorrect order.

[https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0](https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0)

**Comment by davidbritch** [comment]
@Bowman74 Thanks for pointing that out. Fixed via https://github.com/dotnet/docs-maui/pull/2671

**Comment by Bowman74** [comment]
@davidbritch Thank you sir!
