### ISSUE TITLE
BlazorWebView Hosting Content documentation issue

### ISSUE THREAD

**Issue by Bowman74** [dotnet/docs-maui#2652]
### Type of issue

Typo

### Description

The section under BlazorWebView  for What's new in .NET MAUI for .NET 9 is incorrect.

The actual behavior is to switch the hosting between 1.1.1.1 (the new default) to 0.0.0.0. There was a time in .Net 8 where it switched to app://localhost but that is no longer the case.

**The documentation currently reads:**
On iOS and Mac Catalyst 18, .NET MAUI 9 changes the default behavior for hosting content in a [BlazorWebView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webview.maui.blazorwebview) to localhost. The internal 0.0.0.1 address used to host content no longer works and results in the [BlazorWebView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webview.maui.blazorwebview) not loading any content and rendering as an empty rectangle.

To opt into using the 0.0.0.1 address, add the following code to the CreateMauiApp method in MauiProgram.cs:

C#

```
Copy
// Set this switch to use the LEGACY behavior of always using 0.0.0.1 to host BlazorWebView
AppContext.SetSwitch("BlazorWebView.AppHostAddressAlways0000", true);
```

**Issue:**
This is incorrect. the legacy behavior of the switch is to use 0.0.0.0. Leaving it as the default under .Net 9 uses 0.0.0.1, this is completely different from the documentation. The relevant MAUI source code is in `HostAddressHelper.cs`

`public static string GetAppHostAddress()
		=> IsAppHostAddressAlways0000Enabled
			? "0.0.0.0"
			: "0.0.0.1";`

**The documentation should likely read something like:**

On iOS and Mac Catalyst 18, .NET MAUI 9 changes the default behavior for hosting content in a [BlazorWebView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webview.maui.blazorwebview) to 0.0.0.1. The internal 0.0.0.0 address used to host content no longer works and results in the [BlazorWebView](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webview.maui.blazorwebview) not loading any content and rendering as an empty rectangle.

To opt into using the 0.0.0.0 address, add the following code to the CreateMauiApp method in MauiProgram.cs:

C#

```
Copy
// Set this switch to use the LEGACY behavior of always using 0.0.0.0 to host BlazorWebView
AppContext.SetSwitch("BlazorWebView.AppHostAddressAlways0000", true);
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/whats-new/dotnet-9.md

### Document Version Independent Id

7fc9548e-ac05-3843-f568-be1ad5c06b1f

### Article author

@davidbritch

### Metadata

* ID: 7fc9548e-ac05-3843-f568-be1ad5c06b1f 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

[Related Issues](https://github.com/dotnet/docs-maui/issues?q=is%3Aissue+is%3Aopen+7fc9548e-ac05-3843-f568-be1ad5c06b1f)

---
[Associated WorkItem - 350468](https://dev.azure.com/msft-skilling/Content/_workitems/edit/350468)

**Comment by davidbritch** [comment]
Hi @Bowman74 

Thanks for the issue - you're of course correct. Not entirely sure what's happened here - I was aware that 0.0.0.1 is the new default.

**Comment by Bowman74** [comment]
@davidbritch Thank you sir!
