### ISSUE TITLE
Addressing warnings from CompiledBindings on .NET 9 on TemplateBinding

### ISSUE THREAD

**Issue by MichaelLHerman** [dotnet/docs-maui#2660]
### Type of issue

Missing information

### Description

After upgrading to .NET 9,  I am seeing XC0022 warnings on my TemplateBindings.   Documentation for neither Control Templates nor Compiled Bindings have been updated to provide information on what to do.   Specify the data type on the ControlTemplate, or is there a plan for the Xaml Compiler to be able to automatically infer the data type in the future if the control template is a ControlTemplate of a particular ContentView?   Samples need to be updated as well https://github.com/dotnet/maui-samples/issues/547#issuecomment-2515099253

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/controltemplate?view=net-maui-9.0
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings?view=net-maui-9.0#compiled-bindings-in-xaml

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings?view=net-maui-9.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/compiled-bindings.md

### Document Version Independent Id

d8079bc8-3987-9069-717e-c5cbf3512ae1

### Article author

@davidbritch

### Metadata

* ID: d8079bc8-3987-9069-717e-c5cbf3512ae1 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

[Related Issues](https://github.com/dotnet/docs-maui/issues?q=is%3Aissue+is%3Aopen+d8079bc8-3987-9069-717e-c5cbf3512ae1)

**Comment by davidbritch** [comment]
Hi @MichaelLHerman 

I'll be looking at this tomorrow, but in the meantime https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings?view=net-maui-9.0#xaml-compiled-bindings-warnings may help.

**Comment by MichaelLHerman** [comment]
@davidbritch  Looks like specifying x:DataType in the control template is all that needs to be done (though this should be documented somewhere).   In the ControlTemplateDemos sample, I added the data type and the warnings went away.   

```
<ControlTemplate x:Key="CardViewControlTemplate" x:DataType="controls:CardView">
```

**Comment by jfversluis** [comment]
Those changes are now in the samples as per this PR: https://github.com/dotnet/maui-samples/pull/552

Does that help you any further?

**Comment by davidbritch** [comment]
All the samples have been updated to use compiled bindings. The docs will be updated in January. I'm going to create issues in the next week or two to do this for the docs, so I'm going to close this issue now.
