### ISSUE TITLE
Access Contacts in .NET MAUI"

### ISSUE THREAD

**Issue by almatri-moh** [dotnet/docs-maui#2664]
I am developing an application using .NET MAUI and encountering an issue with accessing contacts on Android. The goal is to allow the user to select a contact and display their phone number in a specific Entry.

**Comment by davidbritch** [comment]
Hi @almatri-moh 

Take a look at https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/contacts?view=net-maui-9.0&tabs=android and in particular the sample link at the top of the page.
