### ISSUE TITLE
Maui-Blazor preview JIT issue prevents use of DevExpress blazor components, DbContext and others in iOS device

### ISSUE THREAD

**Issue by russellowen** [dotnet/docs-maui#267]
It seems iOS devices have severe limitations on the components they can use with Maui-Blazor. I can use DevExpress Blazor components in Windows version, Android, Android simulator and iPad simulator, but on actual iPad, they get a JIT error because iPad doesn't seem to handle JIT.  I have same problem with DbContext and others.

Will that problem continue, or will they fix it?

**Comment by davidbritch** [comment]
Hi @russellowen 

I spoke to the engineer responsible for .NET MAUI Blazor and he said it sounds like a bug, so recommends you file a bug in the MAUI repo. It looks like you already have - https://github.com/dotnet/maui/issues/4147

Hence, I'll close this issue here.
