### ISSUE TITLE
Forget this Mac

### ISSUE THREAD

**Issue by mattrobb49** [dotnet/docs-maui#2673]
### Type of issue

Typo

### Description

I am trying to pair to a Mac. I have used incorrect credentials. When I right click to 'forget this Mac' there is no forget this Mac option. Only connect. This is preventing me from correcting the credentials for my Mac and causing a real problem with my ios developemnt. I have restarted VS but there is never a 'Forget this Mac' option appearing after right clicking on the Mac I wish VS to forget!
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac?view=net-maui-9.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/ios/pair-to-mac.md

### Document Version Independent Id

df7f72f4-cf07-1f47-6400-432d8499edea

### Article author

@davidbritch

### Metadata

* ID: df7f72f4-cf07-1f47-6400-432d8499edea 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

[Related Issues](https://github.com/dotnet/docs-maui/issues?q=is%3Aissue+is%3Aopen+df7f72f4-cf07-1f47-6400-432d8499edea)

**Comment by davidbritch** [comment]
If you delete the folders listed at https://learn.microsoft.com/en-us/answers/questions/1502997/regular-solvable-issue-with-visual-studio-macos-pa you should get unblocked.
