### ISSUE TITLE
Opacity is not recognized or is not accessible

### ISSUE THREAD

**Issue by LeoJHarris** [dotnet/docs-maui#2674]
### Type of issue

Code doesn't work

### Description

Seems to be wrong here:

```xaml
<Setter TargetName="check"  Property="Opacity" Value="0" />
```

I believe the documentation should be which resolves the issue.

```xaml
<Setter TargetName="check" Property="Ellipse.Opacity" Value="0" />
```

**Property="Ellipse.Opacity"**

![Image](https://github.com/user-attachments/assets/e0387319-2af9-47ea-bf67-53a05e280061)

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/radiobutton.md

### Document Version Independent Id

a4d9b4fe-c357-031e-3fc4-9c22ffee81db

### Article author

@davidbritch

### Metadata

* ID: a4d9b4fe-c357-031e-3fc4-9c22ffee81db 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

[Related Issues](https://github.com/dotnet/docs-maui/issues?q=is%3Aissue+is%3Aopen+a4d9b4fe-c357-031e-3fc4-9c22ffee81db)

**Comment by LeoJHarris** [comment]
Appears related https://github.com/dotnet/docs-maui/issues/1153

**Comment by bhavanesh2001** [comment]
@LeoJHarris This only happens when we change something in the ControlTemplate while debugging. If we deploy again, the particular waning will not show

**Comment by LeoJHarris** [comment]
@bhavanesh2001 so we can close this issue?

**Comment by bhavanesh2001** [comment]
@LeoJHarris Yeah, I think so. Since there is nothing that can be done doc's repo.
