### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED

### ISSUE THREAD

**Issue by tmanallen** [dotnet/docs-maui#2675]
### Type of issue

Missing information

### Description

Would like to see how this is handled because Xamarin is not supported.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/migration/android-projects?view=net-maui-8.0

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/migration/android-projects.md

### Document Version Independent Id

1426ce50-85f4-8a53-95cb-8181b671eb47

### Article author

@davidbritch

### Metadata

* ID: 1426ce50-85f4-8a53-95cb-8181b671eb47 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

[Related Issues](https://github.com/dotnet/docs-maui/issues?q=is%3Aissue+is%3Aopen+1426ce50-85f4-8a53-95cb-8181b671eb47)

**Comment by davidbritch** [comment]
Hi @tmanallen 

I'm not entirely sure what your issue is - can you elaborate?

**Comment by tmanallen** [comment]
Hi @davidbritch,
  Thanks for reaching out, I figured it out, I had to read up on some documentation and the library that I was using silk.net was updated because I couldn't update the source. Apologies for not getting back sooner.
