### ISSUE TITLE
Command to install xcsync fails as tool is still in preview

### ISSUE THREAD

**Issue by Bowman74** [dotnet/docs-maui#2680]
### Type of issue

Code doesn't work

### Description

The article states to install the tool globally to use this command:

`dotnet tool install -g dotnet-xcsync`

However, that command will not work as the nuget package is in preview. The command will fail with:
dotnet-xcsync is not found in NuGet feeds https://api.nuget.org/v3/index.json.

Both this documentation and the documentation at [https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0](https://learn.microsoft.com/en-us/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0) indicate this tool was released with .Net 9 but it does not appear this was the case. It is still in preview and the tool cannot be downloaded as a released tool.

The nuget package can be found here in preview and contains the command that can be used to download the preview package:
[https://www.nuget.org/packages/dotnet-xcsync/0.1.0-preview.24509.2](https://www.nuget.org/packages/dotnet-xcsync/0.1.0-preview.24509.2)

The documentation in both places should be updated with the fact that this is in preview and with information on the correct way to download the preview.

### Page URL

https://learn.microsoft.com/en-us/dotnet/maui/macios/xcsync?view=net-maui-9.0&tabs=visual-studio-code

### Content source URL

https://github.com/dotnet/docs-maui/blob/main/docs/macios/xcsync.md

### Document Version Independent Id

d5f511c6-2870-5ca6-400e-afa302e40146

### Article author

@haritha-mohan

### Metadata

* ID: d5f511c6-2870-5ca6-400e-afa302e40146 
* Service: **dotnet-mobile**
* Sub-service: **dotnet-maui**

[Related Issues](https://github.com/dotnet/docs-maui/issues?q=is%3Aissue+is%3Aopen+d5f511c6-2870-5ca6-400e-afa302e40146)

---
[Associated WorkItem - 356253](https://dev.azure.com/msft-skilling/Content/_workitems/edit/356253)

**Comment by davidbritch** [comment]
@Bowman74 Agreed that you're correct, and thanks for pointing this out.

**Comment by Bowman74** [comment]
@davidbritch Thank you sir!
