### ISSUE TITLE
Where can I find  the .NET upgrade assistant for .NET MAUI

### ISSUE THREAD

**Issue by davefxy** [dotnet/docs-maui#274]
[Enter feedback here]

The page mentions  the .NET upgrade assistant for .NET MAUI but I have no idea where to find the utility. It would be helpful to include where to find the .NET upgrade assistant for .NET MAUI and how to use it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e223-a9cc-1efb-07ec-01c8501d7a46
* Version Independent ID: 538673ca-22c5-2a5c-97c0-1552ae9f7b79
* Content: [Migrate your app from Xamarin.Forms to .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/migrate)
* Content Source: [docs/get-started/migrate.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/migrate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @davefxy 

Instructions will be added once the migration path from Xamarin.Forms to .NET MAUI has been nailed down. At the moment it hasn't - work is ongoing on the upgrade assistant. It's not something you can expect until product launch.
