### ISSUE TITLE
Typos on NET MAUI invoking platform code - .NET MAUI

### ISSUE THREAD

**Issue by Countryen** [dotnet/docs-maui#278]
There are some minor **typos** on this page (notes are `highlighted`).
If possible/wanted I can create a PR, too.

(At the bottom, header "Configure multi-targeting")

For example, a standard multi-targeting pattern is to include the platform as an extension **in the** `twice` in the filename for the platform code. The build system can **be** `missing` configured to combine cross-platform partial classes with platform partial classes based on this pattern:

[...]

Another standard multi-targeting pattern is to include the platform as a folder name. The build system can **be** `missing` configured to combine cross-platform partial classes with platform partial classes based on this pattern:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Version Independent ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Content: [.NET MAUI invoking platform code - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code)
* Content Source: [docs/platform-integration/invoke-platform-code.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/invoke-platform-code.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Countryen 

A PR would be much appreciated!

**Comment by Countryen** [comment]
Hi @davidbritch, I've created the PR. Is it necessary to create an issue for such minor changes first or is a direct PR ok next time?

**Comment by davidbritch** [comment]
Hi @Countryen 

No need to create issues if you fix it yourself in a PR. Thanks so much!
