### ISSUE TITLE
changing appIcon fails the build

### ISSUE THREAD

**Issue by nssidhu** [dotnet/docs-maui#280]
When i change the AppIcon as shown in this article for Android, the build fails with the following error

Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2260	resource mipmap/appicon (aka com.companyname.blazorhybrid:mipmap/appicon) not found.

This error is likely caused by an issue with the AndroidManifest.xml file or an Android manifest generation attribute in a source code file.	BlazorHybrid	C:\Users\XXXXXXXX\BlazorHybrid\Platforms\Android\AndroidManifest.xml	1	

The error is pointing to the following location
<application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon" android:supportsRtl="true"></application>

but changing it here also does not help, it still reports the same error.

So it looks like documentation is not complete in sense what other places need to be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Version Independent ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Content: [App icons - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=android)
* Content Source: [docs/user-interface/images/app-icons.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/app-icons.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nssidhu 

The doc is correct. However, since it was written the app icon feature in the product has broken. All I can recommend is logging a bug in the [engineering repo](https://github.com/dotnet/maui).

**Comment by nssidhu** [comment]
How can something that does not work be correct ?

**Comment by jfversluis** [comment]
@nssidhu the process as documented is how it should work. So the doc is correct, however there seems to be a bug in .NET MAUI preventing it from working correctly. The thing being wrong here is with .NET MAUI, not the docs :)

**Comment by nssidhu** [comment]
got it, Thanks for clarification.

**Comment by nssidhu** [comment]
Any updates on this ?

**Comment by jfversluis** [comment]
@nssidhu there will not be updates for this here. If you still have an issue, see if there is an open issue on the .NET MAUI repo and if not, please open one.

**Comment by nssidhu** [comment]
I pinged on wrong thread, yes i did opened the issue https://github.com/dotnet/maui/issues/4340
