### ISSUE TITLE
Read BlazorWebView unhandled exceptions on iOS/Android

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs-maui#281]
Please see https://github.com/dotnet/maui/issues/2057 for context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Version Independent ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Content: [BlazorWebView - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview)
* Content Source: [docs/user-interface/controls/blazorwebview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/blazorwebview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by TanayParikh** [comment]
Closed out https://github.com/dotnet/maui/issues/2057, however I still think it'd be worthwhile having https://github.com/dotnet/maui/issues/2057#issuecomment-1022734750 documented at some point.

**Comment by TanayParikh** [comment]
Though may be worth holding off till https://github.com/dotnet/maui/issues/4441 is done. That may change things...

**Comment by TanayParikh** [comment]
@guardrex this is now unblocked 😄 . https://github.com/dotnet/maui/issues/4441 covers the .NET managed exception side of things. This'll still be great for JS exceptions.

MAUI exceptions will also show up in this console for now until they're integrated with the global exception context (https://github.com/dotnet/maui/issues/4441).

**Comment by guardrex** [comment]
**_Nevermind!_** I'm moving my question to the ASP.NET Core docs tracking issue at ...

https://github.com/dotnet/AspNetCore.Docs/issues/24956#issuecomment-1074187642

**Comment by danroth27** [comment]
@TanayParikh Could you please clarify what about dotnet/maui#2057 needs to be documented?

**Comment by TanayParikh** [comment]
Essentially we're looking to get:

https://github.com/dotnet/maui/issues/2057#issuecomment-1022734750

documented. It is the development steps to open the devtools for the iOS and Android webview. In regards to where it _should_ be documented I'll leave that to you and Luke.

**Comment by guardrex** [comment]
I see. This falls under ...

**_Use browser dev tools_**: `aspnetcore/blazor/hybrid/browser-developer-tools.md`

I've opened https://github.com/dotnet/AspNetCore.Docs/issues/25382, and I'll work that up this morning 🏃.

I think you can close here unless there's something in the .NET MAUI topic that you'd like to cross-link after the new topic goes up.

**UPDATE**: Ok ... the first draft is coming along well, but I must sleep on it 🛌💤 before calling for review. I'll ping on Wednesday morning.

I think you can close this issue because it's tracked and worked on the ASP.NET Core repo. I don't think that a cross-link will be necessary. If you do want a cross-link here, then @davidbritch can add it after the new topic goes live. I'll ping back here if you end up leaving this issue open.

**Comment by TanayParikh** [comment]
Sounds great, thanks @guardrex! Can you please close out the issue, I don't seem to have the requisite perms in this repo.
