### ISSUE TITLE
missing mac part / CLI

### ISSUE THREAD

**Issue by hot33331** [dotnet/docs-maui#29]
I am a mac user and on this page there is only windows and vs for windows. It would be cool to have something for mac, too and the cli commands to build and run because I always need to look them up :-D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app in Visual Studio](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?source=docs)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@hot33331 Yes, there's no support in VSMac for MAUI yet. Build commands are (currently) at: https://docs.microsoft.com/dotnet/maui/get-started/installation#build-and-launch-apps

**Comment by hot33331** [comment]
Wow, that was fast, thanks David. Maybe add a link to how to build it from the command line in the build section? I'll take a shot at changing it... :-D

**Comment by davidbritch** [comment]
Worry not - I'll fix it today. Makes no sense for the CLI commands to be in the installation doc!

**Comment by hot33331** [comment]
oops - just read this now... had a pr ready https://github.com/dotnet/docs-maui/pull/30 - well I guess you'll do a better job anyways... ;-)

**Comment by davidbritch** [comment]
No worries - I'll merge your PR (later today) so you get the contrib.

**Comment by davidbritch** [comment]
I've added instructions on how to create an app with .NET CLI. It'll be live in a few minutes.
