### ISSUE TITLE
Templates missing and emulators do not work

### ISSUE THREAD

**Issue by crawfis** [dotnet/docs-maui#290]
This is a repeat of Closed #150 but it bears reopening. New machine, but upgraded to Preview 17.1 prev. 5 today. Expert in C#, but only really deal in games, class libraries and Windows forms projects.

Problem #1 Maui was not installed. Tried the dotnet -new -u Microsoft.Maui.Templates, but they could not be found. Modified Visual Studio by going to the "Individual Components" and searching for Maui. Installing all of these SDK's gave me the templates. Problem #1 solved, but documentation may be updated.

Problem #2. HyperVision seems to need to be enabled for Android to work. Perhaps add a reference to that page. Proceeding without it failed.

Problem #3. Running the Windows "build" says "The project does not know how to run the profile Windows Machine.". Seems like it may want to create a DLL?

Problem #4: Trying iOS Simulators->Simulator wants me to pair to a Mac and gives the following in the Output window " warning : There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed"

**Comment by davidbritch** [comment]
Hi @crawfis 

The templates not appearing is a bug in the current preview that affects some users. It can be resolved by running `devenv.exe /updateConfiguration` after installing VS. It's mentioned at https://docs.microsoft.com/dotnet/maui/get-started/first-app

Agreed about your second and fourth issue. Setup docs for each platform (Android, iOS etc.) are being prepped.

Your third issue is (another) product bug.

**Comment by crawfis** [comment]
Thanks @davidbritch . The biggest one for me was the Windows Template (#3). Will try to download a project from Github and see if it works. Configuration issue or Visual Studio issue. Any advice on how to work around this or just wait for the bug fix?

**Comment by davidbritch** [comment]
Hi @crawfis 

The Windows issue isn't a known issue - you should be able to create a new project and deploy it to Windows. I'm deploying to Windows on a daily basis without any problems.

If you still have problems, there's a new preview release next week.

**Comment by crawfis** [comment]
Windows builds not working is a rather big bug, so not sure why this is closed. Many people are complaining about it on the web. I did manage to see that it wants to build a class library and then found the solution to running this library by installing this: [https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17](url) https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17.
Thanks to: https://giters.com/dotnet/maui/issues/2778 for the solution.

People like me coming from Windows Forms versus Xamarin will probably be confused by this.

**Comment by davidbritch** [comment]
Hi @crawfis 

It is a big bug, but a product bug. This repo is purely for docs bugs. Product bugs should be opened at https://developercommunity.visualstudio.com 

Thanks!
