### ISSUE TITLE
Add publish/archive from CLI docs

### ISSUE THREAD

**Issue by davidortinau** [dotnet/docs-maui#292]
When VS22 supports publish/archive, those docs with make sense coming from Xamarin.Forms. We also want to show how you can immediately do this.

Android: https://github.com/dotnet/maui/issues/4377
iOS: https://github.com/dotnet/maui/issues/4397
Windows: https://github.com/dotnet/maui/issues/4329

**Comment by davidbritch** [comment]
Closing and opening separate issues for each doc.
