### ISSUE TITLE
"Blazor component" isn't the formal name for components

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs-maui#295]
cc: @Eilon ... I wish I would've pinged you in my discussions with DR on this several years ago. *My bad.*

The term "Blazor component" is merely the **_informal name_** of components and completely avoided in [Blazor documentation](https://docs.microsoft.com/aspnet/core/blazor/). The formal name used 100% of the time is "**_Razor component_**."

Way back in Blazor preview days 👴, I initiated a discussion on the importance of component naming consistency with management, but I didn't reach out to other managers with the conclusion of that discussion. I also haven't been asked to review content outside of ASP.NET Core docs, so I haven't had a chance to head off this problem as new docs rolled out.

Consequently, MS content ... here in .NET MAUI docs ... Learn Modules ... blog posts ... elsewhere probably ... don't use the formal name, sometimes completely avoiding it. Making matters a little worse, most places don't link to the Blazor doc on Razor components. At this point, the community is left to draw the conclusion that **_Microsoft doesn't know what components are called_** by using **_TWO_** names for the same thing among doc sets 😵🙈.

I recommend that all Microsoft content use the formal name ...

* Possibly cross-linking to the Blazor doc on the subject where mentioned ... `[Razor components](/aspnet/core/blazor/components/)`.
* If it's felt that term "Blazor component" is in wide use now and can't be avoided at least as a mention in content, I recommend qualifying it explicitly as the informal name ...

  > Components in Blazor are formally referred to as *Razor components*, informally as *Blazor components*.

  ... and then never mention "Blazor components" again in the content.

Anyway 😄 ... *that's a lovely history, Professor Rex!* 😆 ... but this issue is really just asking if "Blazor component" in this topic on `BlazorWebView` can be replaced with "Razor component," possibly with a cross-link? A few cut-'n-pastes follow ...

* Singular: `[Razor component](/aspnet/core/blazor/components/)`
* Plural: `[Razor components](/aspnet/core/blazor/components/)`
* `Components in Blazor are formally referred to as [*Razor components*](/aspnet/core/blazor/components/), informally as *Blazor components*.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Version Independent ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Content: [BlazorWebView - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview#add-a-blazorwebview-to-an-existing-app)
* Content Source: [docs/user-interface/controls/blazorwebview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/blazorwebview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by Eilon** [comment]
I have no horse in this race, so whatever @danroth27 and @SteveSandersonMS say is 100% fine by me. And if they disagree with each other then I officially support writing it as `(Bl|R)azor Component` (literally) everywhere so as not to upset anyone. Or perhaps have an option in the docs to choose preferred language. Maybe `docs.microsoft.com/en-us-blazor/...` and `docs.microsoft.com/en-us-razor/...` and we could localize for those? (Those are valid custom cultures, assuming the Docs site supports it!)

😁

**Comment by guardrex** [comment]
I don't follow on the localization points. The naming isn't split across languages/cultures. It's different across doc sets. In some docs sets, they're called "Blazor components;" while in other doc sets (and the official Blazor docs), they're called "Razor components."

This inconsistency isn't necessary for any reason as far as I can tell ... except that third parties have picked up on the "Blazor components" naming and are incorporating that name into external doc sets, blog posts, products, and services. If something isn't done now, MS is probably doomed to having created two names for the same thing for no reason, resulting in confusion.

I recommend being allowed to do whatever I can today to stomp out the use of "Blazor components" wherever it lives in MS docs ... *just a suggestion*. If that's not desired, ok. I'll drop it and move on.

btw -- it's being discussed offline further at the moment as a side issue. I'll probably get @danroth27's final call on what I should do, if anything, shortly. I just wanted to make sure that I did what I could so that I can rest easy on it if a different direction is taken.

**Comment by Eilon** [comment]
Oh sorry it was 100% entirely purely a joke 😄

**Comment by guardrex** [comment]
Oh ... sorry. 😆 lol ..... Don't you know that I take this stuff **_VERY seriously?_**. ...... toooooo seriously perhaps. 🙈

**Comment by Eilon** [comment]
But, I mean, we _could_ do what I said 😄

**Comment by danroth27** [comment]
"Razor component" is the official terminology and is used in our tooling. Informal use of "Blazor component" to refer to a Razor component is fine.
