### ISSUE TITLE
This page is out of date. The latest VS-preview is not showing any maui templates. Would be nice to include some terminal command alternatives that aren't so dependent on VS versions and what they include in their options.

### ISSUE THREAD

**Issue by erikgassler** [dotnet/docs-maui#302]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @erikgassler 

The page isn't out of date. There's a bug that affects some users whereby the templates don't show. Changing the installation options doesn't effect whether templates show up or not. If you progress to the [Build your first app](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app) page it tells you how to resolve templates not appearing.

With all that said, there's a new preview being released this week in which the templates bug has been fixed.

**Comment by edgariscoding** [comment]
@davidbritch I'm running VS 2022 17.1.1, I followed the [installation instructions](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation) but the templates do not show up. The [build your first app](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app) page you linked to does not mention anything about resolving templates not appearing.

**Comment by davidbritch** [comment]
Hi @edgariscoding 

You need to be running VS 2022 17.2 P1 to use MAUI.
