### ISSUE TITLE
MAUI custom controls mapper documentation

### ISSUE THREAD

**Issue by nichojo89** [dotnet/docs-maui#303]
It would be helpful if we knew where to find all the mapper names such as "NoUnderline" as described in this post. Even better, a list of mapping constants would remove the need to even look up these mapping strings all together.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6
* Version Independent ID: 70227b04-808f-1370-186b-10cfef525959
* Content: [.NET MAUI control customization with handlers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize)
* Content Source: [docs/user-interface/handlers/customize.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nichojo89 

Agreed. The current handlers doc is only a temporary doc, published last summer. It's been overdue a replacement for a while now, but there are still API changes in the works. Once those are finished the doc will get a major overhaul.

One thing to bear in mind though is that the string values are largely irrelevant. In the example you mentioned, "NoUnderline" could be "JonNichols" and the example would still work.

**Comment by nichojo89** [comment]
Hello David,

I enjoyed your article over the weekend and found it very insightful. It
was very detailed and the level of detail allowed me to comprehend this new
concept & I'm excited to learn more about MAUI through the new
documentation.

Are you saying the "NoUnderline" is just an irrelevant name for the
mapping? If so, what is their purpose? AppendToMapping
<https://github.com/dotnet/maui/blob/f6ec70f6e8a0e3f922c13d3b7c45deec90de1f5a/src/Core/src/PropertyMapperExtensions.cs>

**Comment by davidbritch** [comment]
Hi @nichojo89 

"NoUnderline" is a string that acts as the key into a dictionary entry for the mapper. The "NoUnderline" example adds functionality to .NET MAUI, by providing the ability to remove the underline from an `Entry` control on Android. So "NoUnderline" is simply a dictionary key, and can be whatever string you want it to be (e.g. "JonNichols"). Really, its only use is if you want to later retrieve the mapping and modify it using the `ModifyMapping` method (which requires knowing the correct dictionary key).

All the examples in the current doc use `AppendMapping` to add to the mappers, and so aren't modifying an existing .NET MAUI mapping. Therefore, their dictionary keys are arbitrary.

Hope this helps, and just to clarify the existing doc will be replaced with something far more detailed over the next few months.
