### ISSUE TITLE
Stop leaving Windows builds out of documentation

### ISSUE THREAD

**Issue by jasonalls** [dotnet/docs-maui#311]
Your MAUI documentation leaves Windows building out. It covers Android, macOS, and iOS but not Windows:

dotnet build -t:Run -f net6.0-android
dotnet build -t:Run -f net6.0-ios
dotnet build -t:Run -f net6.0-maccatalyst

The documentation should also include Windows to be technically complete. MAUI is meant to be fully cross-platform and so leaving Windows out of MAUI/Xamarin.Forms documentation is bad.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e223-a9cc-1efb-07ec-01c8501d7a46
* Version Independent ID: 538673ca-22c5-2a5c-97c0-1552ae9f7b79
* Content: [Migrate your app from Xamarin.Forms to .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-gb/dotnet/maui/get-started/migrate)
* Content Source: [docs/get-started/migrate.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/migrate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jasonalls 

There's no dotnet command for building Windows app using .NET MAUI, at the moment.

**Comment by jasonalls** [comment]
When can we expect a Windows command?

**Comment by davidbritch** [comment]
By the time the product is released. There are still issues being worked out for Windows. It'll use msbuild and will be something like: `msbuild /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true`
