### ISSUE TITLE
How to use Native MAUI Control in .razor pages

### ISSUE THREAD

**Issue by nssidhu** [dotnet/docs-maui#315]
Is there any documentation on using MAUI controls inside of .razor pages ?
I am looking to use Map control (Display users' location and nearby business) and Camera for QR code Scanning in .razor pages
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Version Independent ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Content: [BlazorWebView - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview)
* Content Source: [docs/user-interface/controls/blazorwebview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/blazorwebview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nssidhu 

Afraid not. Aside from anything else, there's no Map or Camera control in MAUI. Docs concerning Blazor Hybrid apps are hosted at https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-6.0

**Comment by Marini88** [comment]
There is a Map in Maui right now.
