### ISSUE TITLE
FlexLayout inside ScrollView does not scroll

### ISSUE THREAD

**Issue by tjbarrott** [dotnet/docs-maui#317]
[Enter feedback here]
I've tried both in .xaml file and .xaml.cs file adding images to a flexLayout. In both cases, I see images halfed at the bottom, but I cannot scroll. Stacklayouts do not work either. The only layout that seems to work inside the scrollview is a grid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b597471-8e79-032f-e023-f14ad564405d
* Version Independent ID: 1b597471-8e79-032f-e023-f14ad564405d
* Content: [FlexLayout - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/layouts/flexlayout)
* Content Source: [docs/user-interface/layouts/flexlayout.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/layouts/flexlayout.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tjbarrott 

Agreed. There are problems due to the product still being in the preview phase. I'd recommend logging bugs in the [engineering repo](https://github.com/dotnet/maui). Thanks!
