### ISSUE TITLE
Chinese version is required。 ^o^

### ISSUE THREAD

**Issue by yajiegithub** [dotnet/docs-maui#318]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6700754e-ed5a-dadf-93b0-6617aaff3e30
* Version Independent ID: 6700754e-ed5a-dadf-93b0-6617aaff3e30
* Content: [Data binding - .NET MAUI](https://docs.microsoft.com/zh-cn/dotnet/maui/fundamentals/data-binding/?source=docs#feedback)
* Content Source: [docs/fundamentals/data-binding/index.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/index.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @yajiegithub 

There should be a Chinese version of this page now, right?
