### ISSUE TITLE
Field modifiers - clarification

### ISSUE THREAD

**Issue by MartyIX** [dotnet/docs-maui#333]
There are two lines https://github.com/dotnet/docs-maui/blame/main/docs/xaml/field-modifiers.md#L18-L19 that are the same:

```md
- `internal` – specifies that the generated field for the XAML element is accessible only within types in the same assembly.
- `notpublic` – specifies that the generated field for the XAML element is accessible only within types in the same assembly.
```

Is it true that `internal` and `notpublic` actually exist? If they do, it may be better to define `notpublic` as "the same as `internal`".

**Comment by davidbritch** [comment]
Hi @MartyIX 


The XAML 2009 spec defines `NotPublic`, which makes a generated field `internal`. However, there's no `Internal` field modifier in XAML 2009. 

.NET MAUI XAML, on the other hand, does accept `NotPublic` and `Internal` field modifiers, and they are equivalent. In fact, when parsing your XAML .NET MAUI internally replaces `NotPublic` with `Internal`.
