### ISSUE TITLE
BlazorWebView - What is the purpose of RootComponents collection?

### ISSUE THREAD

**Issue by janseris** [dotnet/docs-maui#336]
Hello,
I am running BlazorWebView in Windows Forms.
I have found out that it allows multiple independent Blazor applications to be run in the BlazorWebView via **div** elements with corresponding ID in index.html.

`
blazorWebView1.HostPage = @"wwwroot\index.html"; //makes wwwroot/index.html the hosting page for Blazor

blazorWebView1.Services = serviceProvider; //allows Dependency Injection in Blazor components etc.

blazorWebView1.RootComponents.Add<App>("#app"); //places App component into div id app in wwwroot/index.html

blazorWebView1.RootComponents.Add<Counter>("#app2"); //places Counter page into div id app2 in wwwroot/index.html

`

What is the intended usage of this? 
I want to avoid antipatterns or bad practices as I am the lead developer in our company.
Is there any documentation on how to use BlazorWebView properly or will it be available with the BlazorWebView release? 
Also, is BlazorWebView released with MAUI or independently?
Is BlazorWebView for MAUI the same project as BlazorWebView for Windows Forms?

Thank you and for making this all possible!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Version Independent ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Content: [BlazorWebView - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview)
* Content Source: [docs/user-interface/controls/blazorwebview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/blazorwebview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @janseris 

Blazor docs are located at https://docs.microsoft.com/aspnet/core/blazor/?view=aspnetcore-6.0. The folks in that repo are best able to comment on anti-patterns etc.

Blazor apps that are hosted by the `BlazorWebView` (those that run in .NET MAUI/WPF/WinForms) are referred to as Blazor hybrid apps and the docs are starting to appear at https://docs.microsoft.com/aspnet/core/blazor/hybrid/?view=aspnetcore-6.0. That docset will grow and be ready for when the product launches, and the .NET MAUI docs will link into them.

It's the same engineering team that produces `BlazorWebView` for each platform (.NET MAUI/WPF/WinForms), but technically it's a separate project from .NET MAUI (although the source is stored in the .NET MAUI repo - https://github.com/dotnet/maui/tree/main/src/BlazorWebView). 

Hope this helps!
