### ISSUE TITLE
Please Mention somewhere in the notes "DataTemplate is also used with BindableLayout. In Bindable Layout and CollectionView the DataTemple should not be wrapped within the ViewCell".

### ISSUE THREAD

**Issue by HobDev** [dotnet/docs-maui#341]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bf5dc2-df41-d0bc-55d6-e18aca8acabf
* Version Independent ID: 39bf5dc2-df41-d0bc-55d6-e18aca8acabf
* Content: [Data templates - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/datatemplate)
* Content Source: [docs/fundamentals/datatemplate.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/datatemplate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by HobDev** [comment]
After reading docs I was returning DataTemplate wrapped in ViewCell in a Bindable Layout.  Also `CollectionView` does not have concept of ViewCell which is not mentioned in the DataTemple docs.

**Comment by davidbritch** [comment]
Hi @HobDev 

Agreed that the doc needs an update. For the record, you only need to use a `ViewCell` in a `DataTemplate` on `ListView` and `TableView`. All other controls don't support the concept of cells.
