### ISSUE TITLE
Update .NET MAUI migration doc to demonstrate using the .NET Upgrade Assistant

### ISSUE THREAD

**Issue by danroth27** [dotnet/docs-maui#345]
The .NET MAUI migration doc says to use the .NET Upgrade Assistant, but the example steps don't actually use it.

From @davidortinau, the full migrations steps should be something like;

1. Run .NET Upgrade Assistant to 
    - Update csproj to SDK Style 
    - Rename namespaces
    - Evaluate NuGet dependencies for .NET 6 compatibility
1. Address unsupported dependencies by
    - Upgrading to .NET 6 versions
    - Replace or remove
1. (If Needed) Follow Xamarin.Forms to .NET MAUI migration guide for
    - Custom renderers - a few lines of code changes to wire them up
    - Effects - a few lines of code to register them
1. Compile and address 
    - Changed APIs should all have clear refactoring hints
    - Layout differences (Xamarin.Forms quirks have been fixed in .NET MAUI)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e223-a9cc-1efb-07ec-01c8501d7a46
* Version Independent ID: 538673ca-22c5-2a5c-97c0-1552ae9f7b79
* Content: [Migrate your app from Xamarin.Forms to .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/migrate)
* Content Source: [docs/get-started/migrate.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/migrate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
This will be done later in the year. The steps at the moment are documented at https://github.com/dotnet/maui/wiki/Migrating-from-Xamarin.Forms-(Preview)

**Comment by davidbritch** [comment]
Closing in favour of the issues at https://github.com/orgs/dotnet/projects/185/views/1
