### ISSUE TITLE
Missing documentation about styles

### ISSUE THREAD

**Issue by chsoft-rbi** [dotnet/docs-maui#349]
Styles are mentioned here and there, but I couldn't find any proper documentation about them. If you read the documentation in order, the first time you stumble upon an actual example is the Behaviors documentation. But that example just shows the how the style XML looks, but doesn't tell you where to add it. Comparing with other examples that pop up here and there you can figure it out, but i doubt that's what the user is intended to do.
The best thing would be to have a proper documentation about styles somewhere (i don't know whether it should be in the XAML section or somewhere else) and then link to it wherever styles are used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d30288a9-c2bb-8f74-a397-912597f7e6ee
* Version Independent ID: d30288a9-c2bb-8f74-a397-912597f7e6ee
* Content: [XAML - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/xaml/)
* Content Source: [docs/xaml/index.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/index.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Naryorill 

The styles docs are written, but aren't published yet. Take a look again at the end of the week.

**Comment by chsoft-rbi** [comment]
Perfect, thanks for the info.

**Comment by davidbritch** [comment]
https://docs.microsoft.com/dotnet/maui/user-interface/styles/xaml
