### ISSUE TITLE
Android target publishing/archiving

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#351]
We need a doc on publishing Android apps using the CLI. The process is doc'd at https://github.com/dotnet/maui/issues/4377, and it links into some Xamarin content on signing the app package that will need pulling into the new doc.

The Xamarin docs on publishing Android apps can be found at: https://docs.microsoft.com/xamarin/android/deploy-test/publishing/. There's no requirement to pull that content into the new doc. I've just included the link in case there's any useful intro content there you want to reuse. Note: the Xamarin docs mention publishing to an APK. However, Google Play store no longer accepts APKs, and so the package format must be AAB.

At the end of the doc, link to Google's doc on how to upload the AAB to the Play store. You could also link to any other Google docs on package requirements etc.

The doc should go in a new node at the bottom of the TOC that's called something like Deployment/Publishing/Packaging. Maybe Publishing, as it is the `dotnet publish` command.

**Comment by adegeo** [comment]
Will need to follow up with more docs around:

- App sizing
- Zipalign
- MSBuild reference material
- Baking the app into a ROM image
- Using a central keystore
