### ISSUE TITLE
NamedColor class used in sample code doesn't exist

### ISSUE THREAD

**Issue by chsoft-rbi** [dotnet/docs-maui#354]
The class NamedColor and thus its method GetNearesColorName don't seem to be part of the .NET library. I can't find anything with Google either. Thus the HslColorViewModel  as provided in the sample code doesn't compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97463723-c3a8-0647-d699-ececebdb527f
* Version Independent ID: 97463723-c3a8-0647-d699-ececebdb527f
* Content: [Binding mode - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/binding-mode)
* Content Source: [docs/fundamentals/data-binding/binding-mode.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/binding-mode.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Sample code is currently located in my personal GitHub account (https://github.com/davidbritch/dotnet-maui-samples). It can't be published to the samples gallery on docs.microsoft.com until MAUI GAs.

**Comment by chsoft-rbi** [comment]
@davidbritch I found an issue with one of the samples in the repository you linked (crash on Windows). Do you want more information about it, and if so, where? On the corresponding page of the documentation? Or as an issue in your personal samples repository? I wanted to the the latter first but noticed there hasn't been a single issue yet, so I wanted to ask about your preferred method.
