### ISSUE TITLE
Compiled bindings don't seem to work with MultiBindings

### ISSUE THREAD

**Issue by chsoft-rbi** [dotnet/docs-maui#356]
If you add the following label to the StackLayout in the "Use compiled bindings" section
```
      <Label>
        <Label.Text>
          <MultiBinding StringFormat="{}Hue = {0:F2}, Saturation = {1:F2}, Luminosity = {2:F2}">
            <Binding Path="Hue"/>
            <Binding Path="Saturation"/>
            <Binding Path="Luminosity"/>
          </MultiBinding>
        </Label.Text>
      </Label>
```
and then change e.g. "Hue" to "Hue2" as binding path, the file still compiles.

On the other hand with the verbose writing method of a normal binding
```
      <Label>
        <Label.Text>
          <Binding StringFormat="{}Hue = {0:F2}" Path="Hue"/>
        </Label.Text>
      </Label>
```
changing the Path to "Hue2" causes a compiler error as expected.

I don't know if this is a compiler bug or whether this is information missing in the documentation similar to the note saying "Compiled bindings are disabled for any binding expressions that define the Source property. This is because the Source property is always set using the x:Reference markup extension, which can't be resolved at compile time"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8079bc8-3987-9069-717e-c5cbf3512ae1
* Version Independent ID: d8079bc8-3987-9069-717e-c5cbf3512ae1
* Content: [Compiled bindings - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings)
* Content Source: [docs/fundamentals/data-binding/compiled-bindings.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/compiled-bindings.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Naryorill 

I've chatted to the engineers and as you've identified, compiled bindings don't work with multi-bindings. Therefore I'll update the doc with a note to that effect.

The engineers have an issue to add compiled bindings support to multi-bindings, but it's not something that will happen in the short term.

**Comment by Peter-Butler** [comment]
<MultiBinding StringFormat="{0} ({1}) {2}">
"*{0} ({1}) {2}" works
" {0} ({1}) {2}" leading space makes a compile error
"{0} ({1}) {2}" different compile errors with nothing between " and {
