### ISSUE TITLE
Workloads changed require running maui-check again.

### ISSUE THREAD

**Issue by nandostyle** [dotnet/docs-maui#38]
Please state somewhere on the page that maui-check needs to be run (again if previously ran) and that this needs to be done at the end after changing the workloads of the Visual Studio being used.

One might get the feeling that if maui-check was done already, then all is good. But when the VS workloads are changed then maui-check may find missing stuff!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Fixed by #98
