### ISSUE TITLE
Add guidance to set NuGet source for MAUI

### ISSUE THREAD

**Issue by ncarandini** [dotnet/docs-maui#39]
To complete the installation process we also need to set the Nuget source for MAUI.
While in Preview, IMHO the best practice is to add the source directly into the Visual Studio options:

![image](https://user-images.githubusercontent.com/139274/123453009-4cedac80-d5df-11eb-9dbe-f8e7caffe670.png)

So I think is better to add this to the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ncarandini 

This isn't required anymore.
