### ISSUE TITLE
Convert the GraphicsView's Drawable to an image

### ISSUE THREAD

**Issue by GabrieleMessina** [dotnet/docs-maui#391]
The [documentation](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/graphicsview#convert-the-drawable-to-an-image) says it's possible to create an `IImage` from an `IDrawable` using the `graphicsView.Drawable.ToImage(400, 500)` method but `IDrawable` doesn't declare any `ToImage` method.

Am i getting something wrong? What is the right way to extract an image from a `GraphicsView`?

I've also opened an [issue](https://github.com/dotnet/Microsoft.Maui.Graphics/issues/342) on the Microsoft.Maui.Graphics repository but they didn't answer me yet. I think is the case of removing this from the documentation to avoid confusion.

**Comment by davidbritch** [comment]
Hi @GabrieleMessina 

Afraid you're correct - it's no longer possible to convert an `IDrawable` to an `IImage`. That functionality has been removed for the time being. I'll get the doc updated today.

**Comment by FouadChaker** [comment]
@davidbritch is there any other way to create an image from `IDrawable` ?
