### ISSUE TITLE
'EntryHandler' does not contain a definition for 'EntryMapper'

### ISSUE THREAD

**Issue by HobDev** [dotnet/docs-maui#392]
I am using this line of code from the documentation in a `MauiProgram.cs` file of the App.

```
#if ANDROID
        Microsoft.Maui.Handlers.EntryHandler.EntryMapper.AppendToMapping("NoUnderline", (h, v) =>
        {
            h.NativeView.BackgroundTintList = ColorStateList.ValueOf(Colors.Transparent.ToAndroid());
        });
#endif
```
 But there is an error on `EntryMapper` as mentioned in the Title .

Another issue is that `ToAndroid()` is under the   `Microsoft.Maui.Controls.Compatibility.Platform.Android` namespace. why there is compatibility in the namespace as I want to use the latest maui bits not something compatible with previous Xamarin.Forms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6
* Version Independent ID: 70227b04-808f-1370-186b-10cfef525959
* Content: [.NET MAUI control customization with handlers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize)
* Content Source: [docs/user-interface/handlers/customize.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @HobDev 

Just pushing out a PR now to fix this. Instead of `Colors.Transparent.ToAndroid()`, use `Colors.Transparent.ToPlatform()`. `ToPlatform` is in the `Microsoft.Maui.Platform` namespace.

**Comment by davidbritch** [comment]
Fixed by https://github.com/dotnet/docs-maui/pull/390

**Comment by davidbritch** [comment]
Fixed by https://github.com/dotnet/docs-maui/pull/390
