### ISSUE TITLE
Update sample to reflect breaking changes introduced with Preview 14

### ISSUE THREAD

**Issue by Mephisztoe** [dotnet/docs-maui#396]
References to "Native" have been renamed to "Platform", so now it is PlatformView instead of NativeView.
Also, the sample shows how to remove the underline from Android entry views for example. However, "EntryMapper" has been simplified to Mapper with .NET MAUI PR#4780.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6
* Version Independent ID: 70227b04-808f-1370-186b-10cfef525959
* Content: [.NET MAUI control customization with handlers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize)
* Content Source: [docs/user-interface/handlers/customize.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Fixed by https://github.com/dotnet/docs-maui/pull/390
