### ISSUE TITLE
Listview ScrollTo can not location the item.

### ISSUE THREAD

**Issue by ewendeng** [dotnet/docs-maui#397]
hi guys,

It's location first item when add new item always.How can I contorl scroll to location right item after add new item?

private void OnListViewAppearing(object sender, EventArgs e)
	{
		var viewModel = BindingContext as PackageBaseViweModel;
		var barcode = viewModel.PackageEntityCollection.Last();
		if (barcode == null) return; 
		listViewShower.ScrollTo(barcode, ScrollToPosition.End, true);
		 
	}

**Comment by davidbritch** [comment]
Hi @ewendeng 

You'd be better using a `CollectionView` than a `ListView`. `CollectionView` is essentially ListView2. It has far more functionality in it, including what you're after - https://docs.microsoft.com/dotnet/maui/user-interface/controls/collectionview/scrolling#control-scroll-position-when-new-items-are-added
