### ISSUE TITLE
Unable to find any Android Emulators

### ISSUE THREAD

**Issue by MeaningOfLights** [dotnet/docs-maui#40]
Hi everyone,

On a fresh setup of Vs VS2022 there's a missing step, the Android Emulator hasn't been installed.

When I try to install the emulator in VS2022 it fails, asks to send a report. This is the maui-check report.

  **¡ Unable to find any Android Emulators.  You can use Visual Studio to create one if necessary:**

The report has this message:

Please file an issue by choosing "Report a Problem" in the Help menu, and attach your logs. 
Error summary: It looks like you are using an incompatible JDK. Please install and configure Microsoft Mobile OpenJDK.

I have the latest OpenJDK installed: C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25

I checked and this same error happened a year ago. I'm not sure if I shoudl try the solution as it seems like a regression caused by a different bug a year on?
https://developercommunity2.visualstudio.com/t/loading-Android-virtual-device-in-device/1154493

Any solution to install the Preview 5? 

<snip>

> OpenJDK 11.0 Checkup...
  - 11.0.10 (C:\Program Files\Microsoft\jdk-11.0.10.9-hotspot\bin\..)
  - 1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)

> Visual Studio 16.10.0 Checkup...
  - 17.0.0-pre.1.1 - E:\Program Files\Microsoft Visual Studio\2022\Preview
  - 16.10.0 - E:\Program Files (x86)\Microsoft Visual Studio\2019\Community

> Android SDK Checkup...
  - emulator (30.7.5)
  - build-tools;30.0.2 (30.0.2)
  - platforms;android-30 (3)
  - system-images;android-30;google_apis;x86 (9)
  - platform-tools (31.0.2)

> Android Emulator Checkup...
  ¡ Unable to find any Android Emulators.  You can use Visual Studio to create
one if necessary:
https://docs.microsoft.com/xamarin/android/get-started/installation/android-emulator/device-manager

> .NET SDK Checkup...
  - 5.0.201 - C:\Program Files\dotnet\sdk\5.0.201
  - 5.0.300 - C:\Program Files\dotnet\sdk\5.0.300
  - 6.0.100-preview.5.21302.13 - C:\Program
Files\dotnet\sdk\6.0.100-preview.5.21302.13

> .NET SDK - Workload Deduplication Checkup...

> .NET SDK - EnableWorkloadResolver.sentinel Checkup...
  - E:\Program Files\Microsoft Visual
Studio\2022\Preview\MSBuild\Current\Bin\SdkResolvers\Microsoft.DotNet.MSBuildSdkResolver\EnableWorkloadResolver.sentinel exists.
  - E:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Current\Bin\SdkResolvers\Microsoft.DotNet.MSBuildSdkResolver\EnableWorkloadResolver.sentinel exists.

> .NET SDK - Workloads (6.0.100-preview.5.21302.13) Checkup...
  - microsoft-android-sdk-full (Microsoft.NET.Sdk.Android.Manifest-6.0.100 :
30.0.100-preview.5.28) installed.
  - microsoft-ios-sdk-full (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 :
14.5.100-preview.5.894) installed.
  - microsoft-maccatalyst-sdk-full
(Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 14.5.100-preview.5.894)
installed.
  - microsoft-tvos-sdk-full (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 :
14.5.100-preview.5.894) installed.
  - microsoft-macos-sdk-full (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 :
11.3.100-preview.5.894) installed.

> .NET SDK - Packs (6.0.100-preview.5.21302.13) Checkup...
  - Microsoft.Maui.Templates (6.0.100-preview.5.794) installed.
  - Microsoft.Android.Sdk (30.0.100-preview.5.18) installed.
  - Microsoft.Android.Sdk.BundleTool (30.0.100-preview.5.18) installed.
  - Microsoft.Android.Ref (30.0.100-preview.5.18) installed.
  - Microsoft.Android.Templates (30.0.100-preview.5.18) installed.
  - Microsoft.iOS.Sdk (14.5.100-preview.5.881) installed.
  - Microsoft.iOS.Windows.Sdk (14.5.100-preview.5.881) installed.
  - Microsoft.iOS.Ref (14.5.100-preview.5.881) installed.
  - Microsoft.iOS.Templates (14.5.100-preview.5.881) installed.
  - Microsoft.MacCatalyst.Sdk (14.5.100-preview.5.881) installed.
  - Microsoft.MacCatalyst.Ref (14.5.100-preview.5.881) installed.
  - Microsoft.MacCatalyst.Templates (14.5.100-preview.5.881) installed.
  - Microsoft.tvOS.Sdk (14.5.100-preview.5.881) installed.
  - Microsoft.tvOS.Ref (14.5.100-preview.5.881) installed.
  - Microsoft.tvOS.Templates (14.5.100-preview.5.881) installed.
  - Microsoft.macOS.Sdk (11.3.100-preview.5.881) installed.
  - Microsoft.macOS.Ref (11.3.100-preview.5.881) installed.
  - Microsoft.macOS.Templates (11.3.100-preview.5.881) installed.
────────────────────────────────────────────────────────────────────────────────

¡ Things look almost great, except some pesky warning(s) which may or may not bea problem, but at least if they are, you'll know where to start searching!

Press enter to exit...

</snip>

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation](https://docs.microsoft.com/en-gb/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by MeaningOfLights** [comment]
In Visual Studio 2022, installing the "Emulator individual components" allowed the maui-check to pass and overcome the "Error summary: It looks like you are using an incompatible JDK. Please install and configure Microsoft Mobile OpenJDK." error.

Problem now is the MAUI Project templates are still missing. I did a repair on the SDK Preview and it complained that there was a conflict of components. I have VS2019 installed on the same drive. I uninstalled VS2019.

Now I'm stuck, the templates still aren't visible. When I initially install 2022 I got the WinUI components - they're gone now too.
 
So I followed this article:
https://dev.to/kkb_ktm/getting-started-with-net-multi-platform-app-ui-maui-for-android-a6k

And  with the *dotnet build HelloAndroid* I got:
 
 error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found.


E:\Dev\maui-samples\HelloAndroid\HelloAndroid.csproj : warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.android\WorkloadManifest.json'.
C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.100\microsoft.net.sdk.android\WorkloadManifest.json'.
C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found. [E:\Dev\maui-samples\HelloAndroid\HelloAndroid.csproj]


Thinking I need to add the aka.ms/maui-preview/index.jon I open VS2022 and open the maui sample projects and it prompts me that I need "F#".


The I open the project again and I get and error message:

*One or more projects in the solution were not loaded correctly.*

And in Solution Explorer I see projects with a "%s (unloaded)" ???

I'm going to uninstall VS2022. It's completely unstable and error prone. If you don't want another episode with VS2002/2003 installs then you'll need to get some good beta testers on this one VS2022 version... Sadly I am disappointed spending more than a few hours on this.

**Comment by davidbritch** [comment]
Hi @MeaningOfLights 

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please submit your issue at the [engineering](https://github.com/dotnet/maui) repo.
