### ISSUE TITLE
Docs Not Helpful

### ISSUE THREAD

**Issue by ctubig** [dotnet/docs-maui#404]
Please include step by step procedure. I can't follow the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86a77021-9359-304a-5d49-a4feadf2f8fb
* Version Independent ID: 86a77021-9359-304a-5d49-a4feadf2f8fb
* Content: [FlyoutPage - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage)
* Content Source: [docs/user-interface/pages/flyoutpage.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pages/flyoutpage.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello @ctubig without more information about which doc your talking about, we can't improve it or help you with whatever blocker you're running into. Can you please provide this information? There is a link at the bottom of every article that will create a github issue with the doc metadata embedded in it.

**Comment by ctubig** [comment]
> 

Here, the flyout page documentation. I don't know where to add flyoutpageitem.

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage

**Comment by davidbritch** [comment]
Hi @ctubig 

I've just updated the FlyoutPage doc to include the `FlyoutPageItem` definition.

**Comment by ctubig** [comment]
> Hi @ctubig
> 
> I've just updated the FlyoutPage doc to include the `FlyoutPageItem` definition.

Thank you!

Can you help me with this one?
![image](https://user-images.githubusercontent.com/24967122/160888968-aea81616-74d5-4d66-8f08-48f577ee9161.png)

![image](https://user-images.githubusercontent.com/24967122/160889130-d8652a93-7601-4aa4-ab24-935aab973417.png)

**Comment by davidbritch** [comment]
Take a look at https://github.com/davidbritch/dotnet-maui-samples/tree/main/UserInterface/Pages/FlyoutPage

**Comment by ctubig** [comment]
> Take a look at https://github.com/davidbritch/dotnet-maui-samples/tree/main/UserInterface/Pages/FlyoutPage

Thank you!
