### ISSUE TITLE
Difference between Border and Frame

### ISSUE THREAD

**Issue by chsoft-rbi** [dotnet/docs-maui#414]
Border and Frame seem to have very similar, if not the same, purpose. In which case do you use one over the other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f191eb-6743-c3c6-98d2-de82e088d27f
* Version Independent ID: 04f191eb-6743-c3c6-98d2-de82e088d27f
* Content: [Frame - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/frame)
* Content Source: [docs/user-interface/controls/frame.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/frame.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Use Border. Frame is for people migrating apps from Xamarin.Forms.
