### ISSUE TITLE
Screenshot in ScrollView as a child layout is missing the button

### ISSUE THREAD

**Issue by chsoft-rbi** [dotnet/docs-maui#415]
The screenshot in the ScrollView as a child layout section doesn't match the sample, it's missing the button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90d8ce77-4efb-b9b5-022e-075bb5c9f26e
* Version Independent ID: 90d8ce77-4efb-b9b5-022e-075bb5c9f26e
* Content: [ScrollView - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/scrollview)
* Content Source: [docs/user-interface/controls/scrollview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/scrollview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. I don't really think it's an issue. The screenshot is not demonstrating the button or the whole UI. It's just pointing out the two different labels, the header label and the text label. I think it's OK as it stands. Thank you though, for letting us know.
