### ISSUE TITLE
C# examples are missing in the border document

### ISSUE THREAD

**Issue by HobDev** [dotnet/docs-maui#416]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6b3a47-f4c8-c14a-badd-1b074b38765a
* Version Independent ID: cd6b3a47-f4c8-c14a-badd-1b074b38765a
* Content: [Border - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/border)
* Content Source: [docs/user-interface/controls/border.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/border.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @HobDev 

Afraid there are no plans to add C# examples to every doc. The vast majority of our users use XAML, so the focus will be on that. C# examples will generally only be added if there's something tricky about the syntax.

With that said, are you having a problem?

**Comment by HobDev** [comment]
Hi @davidbritch 
I am writing the UI in C#. I want to add a border around the Editor but it doesn't work. Additionally `StrokeShape` of type IShape is tricky and I can't comprehend how to apply `StrokeShape` in C#.  The example code below only displays editor without any border:

`Editor  codeEditor = new Editor {  BackgroundColor = Colors.White, HorizontalOptions = LayoutOptions.Fill };`

 ` Border border = new Border { Stroke = Colors.Pink, Background = Colors.White, StrokeThickness = 10, Padding = new Thickness(30, 20), HorizontalOptions = LayoutOptions.Fill,  };`

 `border.Content = codeEditor;`

**Comment by davidbritch** [comment]
Hi @HobDev 

I've converted the XAML examples to C#, and now I've done so I might as well update the doc at some point. In the meantime, here they are:

```
using Microsoft.Maui.Controls.Shapes;
using GradientStop = Microsoft.Maui.Controls.GradientStop;

namespace MauiApp1;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();

        VerticalStackLayout verticalStackLayout = new VerticalStackLayout
        {
            Margin = new Thickness(20),
            Spacing = 20
        };

        Label label = new Label
        {
            Text = ".NET MAUI",
            TextColor = Colors.White,
            FontSize = 18,
            FontAttributes = FontAttributes.Bold
        };

        Border border = new Border
        {
            Stroke = Color.FromArgb("#C49B33"),
            Background = Color.FromArgb("#2B0B98"),
            StrokeThickness = 4,
            Padding = new Thickness(16,8),
            HorizontalOptions = LayoutOptions.Center,
            StrokeShape = new RoundRectangle
            {
                CornerRadius = new CornerRadius(40,0,0,40)
            },
            Content = label
        };

        Label gradientLabel = new Label
        {
            Text = ".NET MAUI",
            TextColor = Colors.White,
            FontSize = 18,
            FontAttributes = FontAttributes.Bold
        };

        Border gradientBorder = new Border
        {
            StrokeThickness = 4,
            Background = Color.FromArgb("#2B0B98"),
            Padding = new Thickness(16,8),
            HorizontalOptions = LayoutOptions.Center,
            StrokeShape = new RoundRectangle
            {
                CornerRadius = new CornerRadius(40,0,0,40)
            },
            Stroke = new LinearGradientBrush
            {
                EndPoint = new Point(0,1),
                GradientStops = new GradientStopCollection
                {
                    new GradientStop { Color = Colors.Orange, Offset = 0.1f },
                    new GradientStop { Color = Colors.Brown, Offset = 1.0f }
                },
            },
            Content = gradientLabel
        };

        verticalStackLayout.Add(border);
        verticalStackLayout.Add(gradientBorder);
        Content = verticalStackLayout;
    }
}
```

Hope this helps!

I'll close this issue once I update the doc.

**Comment by HobDev** [comment]
Hi @davidbritch  Thanks a lot. This example helped me to use the border in one of my projects.
