### ISSUE TITLE
Do the maui only support edit on Windows ?  I download the visual studio for Mac preview , but can't create the maui APP 

### ISSUE THREAD

**Issue by dingxiaolong** [dotnet/docs-maui#417]
[Enter feedback here]

Do the maui only support edit on Windows ?  I download the visual studio for Mac preview , but can't create the maui APP ?
So when will it support on Mac ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dingxiaolong 

You specifically need Visual Studio Mac v17.0 Preview (build 8320). However, .NET MAUI support in VSMac is at a very early stage and is pretty unreliable at the moment. It won't be covered in the docs until it works reliably.
