### ISSUE TITLE
Possible typo in a sample of the Format strings section

### ISSUE THREAD

**Issue by SotoiGhost** [dotnet/docs-maui#422]
There's possible an extra "{}" next to the `StringFormat=` within the XAML sample in the [Format string section](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/multibinding#format-strings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830ef2e9-c1f3-e231-21b3-2534cea6e2b0
* Version Independent ID: 830ef2e9-c1f3-e231-21b3-2534cea6e2b0
* Content: [Multi-bindings - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/multibinding)
* Content Source: [docs/fundamentals/data-binding/multibinding.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/multibinding.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SotoiGhost 

Afraid that `<MultiBinding StringFormat="{}{0} {1} {2}">` is correct. If you remove the initial `{}` the XAML won't build. This is because if the string format starts with the `{` character, the XAML parser will confuse it for a markup extension. `{}` avoids this ambiguity.
