### ISSUE TITLE
Useless without the namespaces

### ISSUE THREAD

**Issue by hallambaker** [dotnet/docs-maui#459]
This documentation is utterly useless because it doesn't give the namespaces for the code snippets.

THOSE ARE THE MOST IMPORTANT PART.

Don't remove them as irrelevant boiler plate. The examples are impossible to replicate without the name spaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bf5dc2-df41-d0bc-55d6-e18aca8acabf
* Version Independent ID: 39bf5dc2-df41-d0bc-55d6-e18aca8acabf
* Content: [Data templates - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/datatemplate)
* Content Source: [docs/fundamentals/datatemplate.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/datatemplate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
.NET MAUI projects, created using the project template in Visual Studio, use implicit namespaces. Therefore, when the code snippets don't contain namespaces it's because they aren't required.

**Comment by hallambaker** [comment]
My point was that the examples are incomprehensible without the namespaces which is not the same thing as saying they don't run.

Without the namespaces, it is impossible to follow what the various XAML annotations are doing or how to adapt them. It is not even possible to find the reference pages, or at least not be sure if you have found the right ones.

**Comment by davidbritch** [comment]
@hallambaker That'll become available via API docs links, once API docs are added.
