### ISSUE TITLE
Shadow not working with frame

### ISSUE THREAD

**Issue by jakubjenis** [dotnet/docs-maui#461]
[Enter feedback here]
Are there any limitations to what Shadow can be attached to? It works with Image (as shown in docs) and BoxView, but when I try attaching to frame, no shadow is shown. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16ad8d82-c805-a58d-3ac1-76493461d1b6
* Version Independent ID: 16ad8d82-c805-a58d-3ac1-76493461d1b6
* Content: [Shadow - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/shadow)
* Content Source: [docs/user-interface/shadow.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/shadow.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jakubjenis 

`Frame` has a `HasShadow` property you can set to `true` to get a shadow. Confusing, right?

Here's the deal: `Frame` was in Xamarin.Forms and was the only way of putting a border (and shadow) around an element. `Frame` is in .NET MAUI for users migrating their apps from Xamarin.Forms. For users starting from scratch, `Frame` is best ignored. Instead the best bet is to use `Border` to put a border around a control, and `Shadow` to add a shadow.

So fundamentally, Shadow should work with every layout or view, except `Frame`.

I'll leave this issue open until I update the doc with something similar to the above.

**Comment by jakubjenis** [comment]
That actually makes much more sense now @davidbritch. As I am now looking at `Border`, it does all I ever wanted from `Frame` (different corner radius per corner, border thickness, background etc.). Since `Frame` was one of the first controls I tried to use `Shadow` with, I figured there was something I did not understand. Thanks for clarification!
