### ISSUE TITLE
 Microsoft.Maui.Graphics.IImage vs  Microsoft.Maui.IImage

### ISSUE THREAD

**Issue by HobDev** [dotnet/docs-maui#468]
[Enter feedback here]
Need the explanation on the difference between  Microsoft.Maui.Graphics.IImage vs  Microsoft.Maui.IImage in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb45230-f4a3-e5fe-62d7-1009d50e9e4f
* Version Independent ID: fdb45230-f4a3-e5fe-62d7-1009d50e9e4f
* Content: [Images - .NET MAUI Graphics](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/graphics/images)
* Content Source: [docs/user-interface/graphics/images.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/images.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @HobDev 

Will do. `Microsoft.Maui.IImage` is the interface that abstracts the `Image` control (it's used by `ImageHandler` to map the native image control on each platform to the cross-platform control). Whereas `Microsoft.Maui.Graphics.IImage` is used for any image display/manipulation in a `GraphicsView`.

**Comment by davidbritch** [comment]
Also, just an FYI that issues like this will be clearer once there are API docs. Then all the types in the conceptual docs will link to the API docs, so in this case you'd be able to see which version of an interface is required.
