### ISSUE TITLE
Incorrect Screenshot

### ISSUE THREAD

**Issue by chsoft-rbi** [dotnet/docs-maui#470]
The screenshot below "This results in the following flyout items:" in the "Flyout display options" section is incorrect. Because the display option are set to AsMultipleItems the flyout should show a Cats and a Dogs item instead of the Domestic item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d3c8f0-3066-5129-e6cd-3c3d05fcbb59
* Version Independent ID: 05d3c8f0-3066-5129-e6cd-3c3d05fcbb59
* Content: [.NET MAUI Shell flyout - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout)
* Content Source: [docs/fundamentals/shell/flyout.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/flyout.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog.

Thanks again!

**Comment by davidbritch** [comment]
Hi @Naryorill 

Afraid the screenshot is correct. `AsMultipleItems` only adds children to the flout, not grandchildren.
