### ISSUE TITLE
Graphics" should not be "显卡(graphics card)" under the automatic translation of the Simplified Chinese version.

### ISSUE THREAD

**Issue by SakuraNeko** [dotnet/docs-maui#482]
This problem exists on the page: https://docs.microsoft.com/zh-cn/dotnet/maui/user-interface/graphics/
![image](https://user-images.githubusercontent.com/22462516/165414294-674b987f-7464-4def-a573-a06e6b0d2817.png)
![image](https://user-images.githubusercontent.com/22462516/165414351-004dcf62-bbbe-4a3b-906f-a132556e5ecb.png)

**Comment by khoiph1** [comment]
Thanks @SakuraNeko for your feedback. Ou localizers will investigate this issue.

**Comment by SakuraNeko** [comment]
> Thanks @SakuraNeko for your feedback. Ou localizers will investigate this issue.

@khoiph1 Thank you very much, and I have subsequently reported this to the localization team as per the guidelines.

**Comment by davidbritch** [comment]
Hi @SakuraNeko 

The localization team will update the translation memory. Therefore I'll close the issue here. Thanks!
