### ISSUE TITLE
Sweep all docs and replace Frame with Border/Shadow

### ISSUE THREAD

**Issue by HobDev** [dotnet/docs-maui#488]
In order to encourage maui developers to use border in the place of frame sample code should have the practice of doing the same. The carouselview sample code have frame in it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a5fd0a-f166-09d6-4f3d-a915eda7e61d
* Version Independent ID: 61a5fd0a-f166-09d6-4f3d-a915eda7e61d
* Content: [Populate a CarouselView with data - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/carouselview/populate-data)
* Content Source: [docs/user-interface/controls/carouselview/populate-data.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/carouselview/populate-data.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@HobDev You're right. I've renamed the issue to better reflect the task.

**Comment by gfmoore** [comment]
And show an example of how to convert one from the other perhaps. I've now got to go and do this in my app. :)

**Comment by davidbritch** [comment]
Closing this issue, as it's being tracked by #2330
