### ISSUE TITLE
Bad tutorial

### ISSUE THREAD

**Issue by smiller7812** [dotnet/docs-maui#493]
How are supposed to "Copy the files" into the project? One by one?  Incredible amount of work.
Find a better way to show your point of this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e223-a9cc-1efb-07ec-01c8501d7a46
* Version Independent ID: 538673ca-22c5-2a5c-97c0-1552ae9f7b79
* Content: [Migrate your app from Xamarin.Forms to .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/migrate)
* Content Source: [docs/get-started/migrate.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/migrate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @smiller7812 

The usual way is to drag your files/folders into solution explorer in Visual Studio.

I've just completely simplified the article, following a request from the product team, to link to their migration doc in the .NET MAUI wiki.
