### ISSUE TITLE
Are you really listening your users ?

### ISSUE THREAD

**Issue by softlion** [dotnet/docs-maui#495]
Are you really going to make user write that down ??? A "run" with an, upper char ? Sometime a parameter with a ":" and sometime with a space ? 14 chars for the android target ? really ??

```
dotnet build -t:Run -f net6.0-android
dotnet build -t:Run -f net6.0-ios
dotnet build -t:Run -f net6.0-maccatalyst
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e223-a9cc-1efb-07ec-01c8501d7a46
* Version Independent ID: 538673ca-22c5-2a5c-97c0-1552ae9f7b79
* Content: [Migrate your app from Xamarin.Forms to .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/migrate)
* Content Source: [docs/get-started/migrate.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/migrate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @softlion 

Afraid you'd be better directing that feedback to https://developercommunity.visualstudio.com/home

Thanks!

**Comment by softlion** [comment]
plz replace dotnet build -t:Run with dotnet run AT LEAST

**Comment by davidbritch** [comment]
Afraid that doc has just been replaced completely, following a request from the product team.
