### ISSUE TITLE
Should RectF be RectangelF?

### ISSUE THREAD

**Issue by CBrauer** [dotnet/docs-maui#498]
I cannot find RectF in the current release of Maui.Graphics. Intellisense suggest RectangleF.  Is your web page in error?

**Comment by davidbritch** [comment]
Hi @CBrauer 

`RectangleF` was renamed to `RectF` back in Feb: https://github.com/dotnet/Microsoft.Maui.Graphics/blob/main/src/Microsoft.Maui.Graphics/RectF.cs

**Comment by CBrauer** [comment]
But why does Intellisense suggest RectangleF and not RectF?

**Comment by davidbritch** [comment]
I tried in the latest preview and intellisense reported the correct types:

![intellisense](https://user-images.githubusercontent.com/8092460/166723769-ea8591aa-e760-42b8-af95-e931ff68998d.PNG)

So afraid it sounds like Visual Studio has got confused on your machine. I'd recommend deleting the .vs folder in your solution folder. Hopefully that'll help.
