### ISSUE TITLE
explain the difference between #if __ANDROID__vs #if ANDROID`

### ISSUE THREAD

**Issue by nk54** [dotnet/docs-maui#501]
Can you explain the difference between `#if __ANDROID__` vs #if ANDROID` ? It's confusing
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6
* Version Independent ID: 70227b04-808f-1370-186b-10cfef525959
* Content: [.NET MAUI control customization with handlers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize)
* Content Source: [docs/user-interface/handlers/customize.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Nk54 

In the earlier .NET MAUI releases `#if ANDROID` didn't work but `#if __ANDROID__` did work. However, since then `#if ANDROID` works. They've since been equivalent.

The preferred and recommended approach from the product team is to use `#if ANDROID`. There's no guarantee that `#if __ANDROID__` support will remain forever.

Hope this helps.

**Comment by nk54** [comment]
Hi @davidbritch if it's the same now, the documentation may be explicit about it ?

Also, can you edit your answer and add the code glyph around because the double underscore got removed by markup 🤣 
So I can't find which one you recommand to use ;)

Last time I checked (this afternoon lol), it's not working the same (at least for WINDOWS)
![image](https://user-images.githubusercontent.com/13755220/166713628-39c819c1-8872-4f69-b215-c0137545a58c.png)

I'm on the latest VS 17.2.0 Preview 6.0

**Comment by davidbritch** [comment]
Hi @Nk54 

It's always been `#if WINDOWS` for .NET MAUI. Never `#if __WINDOWS__`.
