### ISSUE TITLE
Many NU1101 error messages generated when trying to run NET MAUI getting started first app

### ISSUE THREAD

**Issue by dppdoran** [dotnet/docs-maui#507]
[Enter feedback here]

I've followed the instructions and this simply does not work.  I keep getting lots of NuGet NU1101 errors indicating that that packages cannot be found.  Example:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package Microsoft.Extensions.DependencyInjection. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages	MauiApp2	C:\Users\dermotd\source\repos\MauiApp2\MauiApp2\MauiApp2.csproj	1	
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dppdoran 

Afraid this must be a product/installer issue. I installed 17.3 P1 in a VM yesterday and the instructions in the doc worked perfectly. All I can recommend is you do the uninstall/re-install dance.

**Comment by chezchez** [comment]
Works for me. Slow AF tho
