### ISSUE TITLE
Documentation is out-of-sync with Visual Studio 2022 - Preview version 17.2 Preview 6

### ISSUE THREAD

**Issue by Dbquity** [dotnet/docs-maui#509]
See the workaround found in this issue: https://github.com/dotnet/maui/issues/6831, which seems to indicate that calling msbuild from the command line is no longer needed (in fact, it does not work). Instead, building the ```Release``` profile targeting ```Windows Machine``` from the VS UI nicely produces a .msix file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46808586-50e1-acfa-68b3-c3ca6572dc62
* Version Independent ID: 46808586-50e1-acfa-68b3-c3ca6572dc62
* Content: [Publish a .NET MAUI app for Windows - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview)
* Content Source: [docs/windows/deployment/overview.md](https://github.com/dotnet/docs-maui/blob/main/docs/windows/deployment/overview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Related to #352

**Comment by jfversluis** [comment]
Added the updated TFM to a PR I had open to switch from MSBuild to dotnet already: https://github.com/dotnet/docs-maui/pull/508
