### ISSUE TITLE
A list of all the things which are in maui only to support porting of Xamarin.Forms apps 

### ISSUE THREAD

**Issue by HobDev** [dotnet/docs-maui#511]
A list of all the things which are in maui for the purpose of  porting Xamarin.Forms apps . The doc will guide new maui developers about what to avoid.  Few examples are : StackLayout, Frame etc. I am not sure but this list may include Behaviors and platform specifics. Also the alternatives of the all items in the list

---
[Associated WorkItem - 61814](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61814)

**Comment by davidbritch** [comment]
Hi @HobDev 

Good suggestion.

The quick answer is that the following controls are still based on renderers: BoxView, Frame, ListView, TableView. Their alternatives are Rectangle, Border, and CollectionView.

There's no restriction on behaviors - the same classes are in .NET MAUI. As for platform-specifics, while the APIs are present in .NET MAUI they actually NOOP in the public builds. The PRs that implement them are currently going through review. However, some of them won't make it into .NET MAUI.

**Comment by davidbritch** [comment]
This will be done when there's actually a porting story for Forms apps to MAUI.

**Comment by HobDev** [comment]
@davidbritch Based on your comment I wrote a blog post about this topic. The link to the post is:              https://learndotnetmaui.com/2022/05/23/xamarin-forms-to-net-maui/
Developers can learn from the post till the official docs are published.
