### ISSUE TITLE
how to start MAUI project on mac system. need a documentation for visual studio for mac 

### ISSUE THREAD

**Issue by Win14-dev** [dotnet/docs-maui#52]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e223-a9cc-1efb-07ec-01c8501d7a46
* Version Independent ID: 538673ca-22c5-2a5c-97c0-1552ae9f7b79
* Content: [Migrate your app from Xamarin.Forms to .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/migrate#port-an-app-example)
* Content Source: [docs/get-started/migrate.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/migrate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Win14-dev 

There is no VSMac support right now. To use it on a Mac you'd have to use .NET CLI, and an editor such as VSCode.

**Comment by Win14-dev** [comment]
@davidbritch okay, thank you for your answer.
