### ISSUE TITLE
iOS14+ Geolocation reduced accuracy support

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#531]
https://github.com/dotnet/maui/pull/5826

@adegeo to decide if this has doc impact.

This is only available in the GA build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e0c605-3e8e-3b61-7e9e-a31b482f3274
* Version Independent ID: 88e0c605-3e8e-3b61-7e9e-a31b482f3274
* Content: [Geolocation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/device/geolocation?tabs=ios#distance-between-two-locations)
* Content Source: [docs/platform-integration/device/geolocation.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device/geolocation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
I think so. I'll update this.
