### ISSUE TITLE
Error when trying the MAUI project template

### ISSUE THREAD

**Issue by csanin2016** [dotnet/docs-maui#537]
Hi all, I am trying to learn the new Maui framework, and got and error that I am not sure how to solve.
I think that I have tried a lot of things, but not success. Can you help?

The error is 

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\Users\fj8711\Train\Maui\MauiApp1\MauiApp1\obj\project.assets.json' doesn't have a target for 'net6.0-android'. Ensure that restore has run and that you have included 'net6.0-android' in the TargetFrameworks for your project.	MauiApp1	C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	

I checked, and saw that the target is defined in the project, but besides that I do not know what else to try.
Thanks in advance for any help

Carlos
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=devices-android)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @csanin2016 

It sounds like this issue: https://developercommunity.visualstudio.com/t/error-netsdk1005-assets-file-projectassetsjson-doe/1248649

I'd recommend you uninstall the latest VS 2022 Preview and re-install it.
