### ISSUE TITLE
Missing code samples links?

### ISSUE THREAD

**Issue by undavide** [dotnet/docs-maui#544]
Hi,
In [this page](https://docs.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/data-binding-basics) you mention:

> "Included in the XamlSamples project is a class called NamedColor."

In the documentation website I haven't been able to find a reference to the [MAUI code samples](https://github.com/dotnet/maui-samples). Although the ones you're referring to, I believe, are the [Xamarin ones](https://github.com/xamarin/xamarin-forms-samples).
Regardless, links to both would help :-)
Thanks!

PS
The documentation is _wonderfully written_, congrats! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67eff20e-d00f-c29c-c025-eb12f523acd1
* Version Independent ID: 67eff20e-d00f-c29c-c025-eb12f523acd1
* Content: [Data binding basics - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/data-binding-basics)
* Content Source: [docs/xaml/fundamentals/data-binding-basics.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/fundamentals/data-binding-basics.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @undavide 

Thanks for the feedback, and for catching the mistake. I'll update the doc.

At some point in the future, some docs will have a download link to a sample that has all the code in the doc. But for various reasons, that's still some time away yet. In the meantime, all the docs samples can be found at https://github.com/davidbritch/dotnet-maui-samples (warning: many of the .csproj files will need updates to make the samples build).
