### ISSUE TITLE
FontSize enums? e.g. large, small xlarge

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#547]
[Enter feedback here]
You have the example of setting a fontsize to a double, but where is the example showing how to do it with an enum?? (or whatever)

e.g. myElement.FontSize = fontsizeenum.large;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a7b4ff-2889-6a85-aa3f-075ae6c07387
* Version Independent ID: 76a7b4ff-2889-6a85-aa3f-075ae6c07387
* Content: [Fonts in .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/fonts)
* Content Source: [docs/user-interface/fonts.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/fonts.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gfmoore 

Afraid that what we called the named font sizes (e.g. Large, Medium etc.) have been obsoleted. [This PR](https://github.com/dotnet/maui/pull/5088) discusses it a little. At the moment, using a `double` is the recommended approach, and does support responding to accessibility changes on your device.

**Comment by gfmoore** [comment]
Thanks for such a quick response. So I guess there's no point using them in the xaml neither. (Don't need a reply to that ;) )

⁣Regards, 

Gordon Moore
***@***.***
​
