### ISSUE TITLE
Does the image for the flyout match the code for Flyout display options?

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#552]
it may be me, but with AsMultipleItems shouldn't the image be displaying the cats and dogs items on the flyout as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d3c8f0-3066-5129-e6cd-3c3d05fcbb59
* Version Independent ID: 05d3c8f0-3066-5129-e6cd-3c3d05fcbb59
* Content: [.NET MAUI Shell flyout - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout)
* Content Source: [docs/fundamentals/shell/flyout.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/flyout.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gfmoore 

I'll take a look. You're the second person to say that, so chances are it's the wrong image.

**Comment by davidbritch** [comment]
Hi @gfmoore 

Afraid the image is right, but I think the `AsMultipleItems` description needs to be more specific. It ensures that the direct children of the `FlyoutItem` are each wrapped into `FlyoutItem` objects and hence appear in the flyout. Cats and dogs are grand-children, and hence don't appear.

**Comment by gfmoore** [comment]
ahh ok. good to know, thanks

regards,

Gordon Moore
***@***.***
On 24/05/2022 16:46:40, David Britch ***@***.***> wrote:
Hi @gfmoore [https://github.com/gfmoore]
Afraid the image is right, but I think the AsMultipleItems description needs to be more specific. It ensures that the direct children of the FlyoutItem are each wrapped into FlyoutItem objects and hence appear in the flyout. Cats and dogs are grand-children, and hence don't appear.
