### ISSUE TITLE
How to make your own MAUI controls

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs-maui#556]
Hello,

I'm looking for some documentation on how to create my own controls for a MAUI application (probably a view rather than a layout or page). All I could find was this page which is mostly about the controls that already exist. Is there some documentation I've missed somewhere? If there is it would be handy to have a link to it on this page.

Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2fb56f3-048c-6bf6-a103-81ba9943d1bc
* Version Independent ID: e2fb56f3-048c-6bf6-a103-81ba9943d1bc
* Content: [Controls - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/)
* Content Source: [docs/user-interface/controls/index.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/index.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @martingbrown Issue #472 is tracking this work, which hasn't really started yet. You could try and use https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view as a reference for now, but it's quite possible a lot of things have changed, such as the new control infrastructure of handlers. I would read https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize and browse the MAUI source code for now.

**Comment by adegeo** [comment]
Duplicate of #472

**Comment by martingbrown** [comment]
@adegeo Thank you for your response. I'll be sure to check those resources out.
