### ISSUE TITLE
Incorrect name of element for Geolocation capability

### ISSUE THREAD

**Issue by dwperrin** [dotnet/docs-maui#557]
Under the heading "Getting Started", on the Windows tab for adding geolocation permissions to manifest it reads "In the Solution Explorer pane, right-click on the Platforms/Windows/Package.appxmanifest file, and select View Code. Under the <Capabilities> node, add the <uap:Capability Name="location"/> element."

The the element should be <uap:DeviceCapability Name="location" />  or simply  < DeviceCapability Name="location" />

Reference : https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#device-capabilities

I would be happy to do a PR if agreed this should be modified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e0c605-3e8e-3b61-7e9e-a31b482f3274
* Version Independent ID: 88e0c605-3e8e-3b61-7e9e-a31b482f3274
* Content: [Geolocation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/device/geolocation?tabs=windows)
* Content Source: [docs/platform-integration/device/geolocation.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device/geolocation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dwperrin 

Looks like the `uap` can be dropped: https://github.com/dotnet/maui/blob/d6bc1ca6ff47d49d0ce2d254df7416f0aee52e68/src/Essentials/samples/Samples/Platforms/Windows/Package.appxmanifest#L65

A PR would be excellent!
