### ISSUE TITLE
BlazorWebView is blank on WIndowsMachine

### ISSUE THREAD

**Issue by ricbrue** [dotnet/docs-maui#562]
Hi, I am trying to use the BlazorWebView on a MAUI Blazor hybrid application but when running the default project (without any modifications) on a WindowsMachine it shows nothing but a blank page.

I am sure that the project works correctly because when launching on the Android emulator it works as expected.

Development machine: Windows 10 x64 (developer option turned on)

**Comment by adegeo** [comment]
@ricbrue Can you share more information about your project? How did you create it? I'm not sure what to do replicate your problem.

I just tested creating a new blazor maui project and ran it on Windows 11 and it worked for me.
