### ISSUE TITLE
Does changing the app icon actually work? Failed for me

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#563]
So I have an svg icon called bicycle.svg

I copied it into the Resources/AppIcon folder via Visual Studio 2022 AND removed (excluded) the existing appIcon and appIconfg files.

In my csproj I have

	<ItemGroup>
		
		<MauiIcon Include="Resources\AppIcon\bicycle.svg" Color="#000000" />

The svg is white so expect a black background

Goto debug on a Pixel 5 emulator

Errors: (btw is there a way of capturing errors as a text copy in one go?
![image](https://user-images.githubusercontent.com/22768967/170742325-fe3f8514-9229-4988-9bf7-6702dbc2c3f4.png)

I'm obviously doing something stupid!  :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Version Independent ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Content: [Add an app icon to a .NET MAUI app project - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=android)
* Content Source: [docs/user-interface/images/app-icons.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/app-icons.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by gfmoore** [comment]
I've renamed it (bicycle.svg) to appicon.svg, it builds, but doesn't seem to display as the icon for an app.

Just to be clear I expect to see this bicycle icon when I draw the bottom drawer up to see the list of apps installed on my (emulator) android app?

I've uploaded the current state of my app to https://github.com/gfmoore/TSDZ2Monitor - but note this is liable to change as I continue developing.

**Comment by adegeo** [comment]
Hi @gfmoore I just tested and verified I too couldn't change the app icon. Once I ran a Clean operation on the project, it worked. Something must be cached and just changing the icon isn't rebuilding **everything** about the app. Right click on the project and choose Clean or run `dotnet clean` from the command line.

I'm going to close this issue as I think this will fix your problem. Cheers!

**Comment by gfmoore** [comment]
Uhmm, didn't work for me. I did rebuild, clean, build, I did dotnet clean from command. All I got was errors, mostly concerning the fact that my icon waslocked (even after rebooting!)
![image](https://user-images.githubusercontent.com/22768967/172142812-770ac762-99b9-4a7a-b87f-00d2788f9400.png)

Rebuild started...
Restored C:\Users\Gordon\source\repos\TSDZ2Monitor\TSDZ2Monitor.csproj (in 680 ms).
1>------ Rebuild All started: Project: TSDZ2Monitor, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.303\tools\msbuild\iOS\Xamarin.Messaging.Apple.targets(31,3): warning : There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): error MAUI0000: System.IO.IOException: The process cannot access the file 'C:\Users\Gordon\source\repos\TSDZ2Monitor\obj\Debug\net6.0-ios\iossimulator-x64\resizetizer\r\bicycle.png' because it is being used by another process.
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): error MAUI0000:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): error MAUI0000:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): error MAUI0000:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.SkiaSharpTools.Resize(DpiPath dpi, String destination) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 66
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 103
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 191
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass27_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 88
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21
1>C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.312\targets\Microsoft.Maui.Resizetizer.targets(522,9): warning : MAUI0000
1>Done building project "TSDZ2Monitor.csproj" -- FAILED.
1>TSDZ2Monitor -> C:\Users\Gordon\source\repos\TSDZ2Monitor\bin\Debug\net6.0-maccatalyst\maccatalyst-x64\TSDZ2Monitor.dll
1>TSDZ2Monitor -> C:\Users\Gordon\source\repos\TSDZ2Monitor\bin\Debug\net6.0-android\TSDZ2Monitor.dll
1>TSDZ2Monitor -> C:\Users\Gordon\source\repos\TSDZ2Monitor\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\TSDZ2Monitor.dll
1>Done building project "TSDZ2Monitor.csproj".


and also 

System.IO.IOException: The process cannot access the file 'C:\Users\Gordon\source\repos\TSDZ2Monitor\obj\Debug\net6.0-android\resizetizer\r\drawable-mdpi\bicycle.png' because it is being used by another process.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)   at Microsoft.Maui.Resizetizer.SkiaSharpTools.Resize(DpiPath dpi, String destination) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 66   at Microsoft.Maui.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 103   at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 191   at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass27_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 88   at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21

Severity	Code	Description	Project	File	Line	Suppression State
Warning		There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed	TSDZ2Monitor	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.303\tools\msbuild\iOS\Xamarin.Messaging.Apple.targets	31	


I'm not even using a Mac, just an android emulator (Pixel 5)

Anyhow, I'm guessing this should e posted in bugs which I will proceed to do.
