### ISSUE TITLE
How can I limit the size of the splashscreen image?

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#565]
I've tried following these instructions and have created an svg icon called bicycle.svg put it into Resources\Splash folder and checked that it is in my csproj file:
```
		<!-- App Icon -->
    <MauiIcon Include="Resources\AppIcon\appicon.svg" Color="#000000" />

		<!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\bicycle.svg" Color="#000000" />
```
At first the image was too large and was truncated on the splash page. I tried the basesize option and the resize="false" options but this made no difference. So I resized the actual image and things looked ok.

However, this morning after a reboot, the splash scrren is appearing too large again. I've checked my image and it is the one I resized. 

I clearly don't understand the principles involved here, perhaps the documentation could explain how the basesize and resize options are supposed to work wiuth some examples? Or is there a bug?

Thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc
* Version Independent ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc
* Content: [Add a splash screen to a .NET MAUI app project - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?tabs=android)
* Content Source: [docs/user-interface/images/splashscreen.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/splashscreen.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by gfmoore** [comment]
Repo at https://github.com/gfmoore/TSDZ2Monitor

**Comment by gfmoore** [comment]
Weird it now displays at the correct size. I have no idea what I have done to achieve this, but I tried to do a rebuild and obtained all sorts of errors - sorry I have no idea how to copy these errors other than by screen grabbing.
Doing a normal debug run seems to work?
![image](https://user-images.githubusercontent.com/22768967/170825994-aa0a0785-a89b-4995-b5bc-26dd9799951f.png)


I am also following example by Gerald Versluis at https://www.youtube.com/watch?v=-XG3ooVAA0w (though I appreciate this may be out of date?)

**Comment by adegeo** [comment]
@gfmoore You can select one or more errors in the list box and right-click and choose copy. This copies a text version of the errors, including all the columns. You'll need to paste them into a text editor and remove information you don't want, then copy\paste that into github.

The API and .NET MAUI framework were totally in flux a lot up until GA, so it's quite possible that videos published months ago  may be misleading. We're working hard to update any out-of-date information in the docs, but sometimes it's hard to find.

Related to your spashscreen problem, I'm unsure. Unfortunately, there is no API documentation at this moment for .NET MAUI, so I don't know what attributes would or wouldn't be valid on the splash screen, nor how they affect the result. Your best bet is to open a bug in the [dotnet/maui](https://github.com/dotnet/maui) repo. Doing a quick search there I found this bug which looks like it's related to your problem: https://github.com/dotnet/maui/issues/7305 

Make sure, as I stated in the icon issue you created, you CLEAN the project and then rebuild when you change these assets.

I'm going to close this issue as I don't think there is anything we can do at the moment from the docs perspective.

Let me know how it goes. Sorry I couldn't be more help!
