### ISSUE TITLE
How can I change the colour/style of the item separator line 

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#567]
Please indicate to peeps that 
```
    xmlns:sys="clr-namespace:System;assembly=mscorlib"
```

needs to be added to the xmlns statements for the line 
```
       <Label Text="{Binding Source={x:Static sys:DateTime.Now}, StringFormat='{0:MMMM dd, yyyy}'}"
```
Otherwise how will noobs like me know!!! Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d3c8f0-3066-5129-e6cd-3c3d05fcbb59
* Version Independent ID: 05d3c8f0-3066-5129-e6cd-3c3d05fcbb59
* Content: [.NET MAUI Shell flyout - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout)
* Content Source: [docs/fundamentals/shell/flyout.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/flyout.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @gfmoore I think you made a mistake here. The content of the issue doesn't match your subject and I'm unsure what you're referencing exactly.
