### ISSUE TITLE
Link to modeless Navigation refers to modal navigation.

### ISSUE THREAD

**Issue by kimpel70** [dotnet/docs-maui#569]
Hi,
The link [Perform modeless navigation](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/pages/navigationpage#perform-modal-navigation) links to the _modal_ navigation instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9387b82-6fbe-8cf9-3381-3fdbf90311cf
* Version Independent ID: e9387b82-6fbe-8cf9-3381-3fdbf90311cf
* Content: [.NET MAUI Shell lifecycle - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/lifecycle)
* Content Source: [docs/fundamentals/shell/lifecycle.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/lifecycle.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.

**Comment by stormbreakermerika** [comment]
This bug is back in
