### ISSUE TITLE
Code for NamedColor needed?

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#572]
Where is the code for NamedColor? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce42af9-5ff2-9b3f-4618-65ba90a67813
* Version Independent ID: 1ce42af9-5ff2-9b3f-4618-65ba90a67813
* Content: [Basic bindings - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/basic-bindings)
* Content Source: [docs/fundamentals/data-binding/basic-bindings.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/basic-bindings.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Sorry, I'm not sure what you're referring to. I searched the article for the word NamedColor and it doesn't appear.

Edit.. I see, I think you opened the issue on the wrong article. This article was ported from Xamarin, I think the code you want is here: https://github.com/xamarin/xamarin-forms-samples/blob/main/DataBindingDemos/DataBindingDemos/DataBindingDemos/NamedColor.cs

@davidbritch We should probably port the sample and add it to the https://github.com/dotnet/samples repo

**Comment by davidbritch** [comment]
This item was completed last year.
