### ISSUE TITLE
I think a much simpler example of binding to a viewmodel would be very helpful here

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#573]
I struggled with this viewmodel code a lot as I couldn't see the necessary code. It seemed overly complex (though perhaps to experienced programmers it's easy). 

I imagine a simple use case is having a label and a button. The label is populated with an initial value from the code behind e.g. "Starting value"

The button is pressed (but I suppose that means introducing the ICommand here) and the text changes to "Ending value"  I have managed to do this, but it took some working out. I come to the docs to see how to do things - even very simple things.

Maybe you can think of something very simple :)

I noted that intellisense wanted to change

PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Name"));

to

PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Name)));

etc.

Also did you know that when I post a new issue  for the document the old text from a previous post is still on the new issue page? Or am I doing something stupid there as well???

I am struggling to see the advantage of this binding to using code behind. There seems even more boilerplate to have to wire up that just a simple event handler!!!! Maybe it will become clear with more complex use cases like list?

Gordon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce42af9-5ff2-9b3f-4618-65ba90a67813
* Version Independent ID: 1ce42af9-5ff2-9b3f-4618-65ba90a67813
* Content: [Basic bindings - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/basic-bindings)
* Content Source: [docs/fundamentals/data-binding/basic-bindings.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/basic-bindings.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi. Yeah something seems strange. I don't know how the old text could be there. The links you click on literally set the text so there must be something in your browser causing the old text to reappear, but it isn't the docs site.

As such, I have no idea what article this comment is actually for 😿. The For example, the link at the bottom of the article is this:

```
https://github.com/dotnet/docs-maui/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%201ce42af9-5ff2-9b3f-4618-65ba90a67813%0A*%20Version%20Independent%20ID%3A%201ce42af9-5ff2-9b3f-4618-65ba90a67813%0A*%20Content%3A%20%5BBasic%20bindings%20-%20.NET%20MAUI%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Fmaui%2Ffundamentals%2Fdata-binding%2Fbasic-bindings)%0A*%20Content%20Source%3A%20%5Bdocs%2Ffundamentals%2Fdata-binding%2Fbasic-bindings.md%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs-maui%2Fblob%2Fmain%2Fdocs%2Ffundamentals%2Fdata-binding%2Fbasic-bindings.md)%0A*%20Product%3A%20**dotnet-mobile**%0A*%20Technology%3A%20**dotnet-maui**%0A*%20GitHub%20Login%3A%20%40davidbritch%0A*%20Microsoft%20Alias%3A%20**dabritch**
```

You can see it's all the comment data for the appropriate article embedded in the link. I passed the URL through an HTML decoder site and this is what it translate too, replacing all the `%20` characters with their appropriate types:

```
https://github.com/dotnet/docs-maui/issues/new?title=&body=

[Enter feedback here]


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce42af9-5ff2-9b3f-4618-65ba90a67813
* Version Independent ID: 1ce42af9-5ff2-9b3f-4618-65ba90a67813
* Content: [Basic bindings - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/basic-bindings)
* Content Source: [docs/fundamentals/data-binding/basic-bindings.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/basic-bindings.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**
```

**Comment by gfmoore** [comment]
I use the Brave browser - I'll check what happens more closely in future, but for now happy for you to kill this. :)

regards,

Gordon Moore
***@***.***
On 10/06/2022 18:43:48, Andy (Steve) De George ***@***.***> wrote:
Hi. Yeah something seems strange. I don't know how the old text could be there. The links you click on literally set the text so there must be something in your browser causing the old text to reappear, but it isn't the docs site.
As such, I have no idea what article this comment is actually for 😿. The For example, the link at the bottom of the article is this:
https://github.com/dotnet/docs-maui/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%201ce42af9-5ff2-9b3f-4618-65ba90a67813%0A*%20Version%20Independent%20ID%3A%201ce42af9-5ff2-9b3f-4618-65ba90a67813%0A*%20Content%3A%20%5BBasic%20bindings%20-%20.NET%20MAUI%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Fmaui%2Ffundamentals%2Fdata-binding%2Fbasic-bindings)%0A*%20Content%20Source%3A%20%5Bdocs%2Ffundamentals%2Fdata-binding%2Fbasic-bindings.md%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs-maui%2Fblob%2Fmain%2Fdocs%2Ffundamentals%2Fdata-binding%2Fbasic-bindings.md)%0A*%20Product%3A%20**dotnet-mobile**%0A*%20Technology%3A%20**dotnet-maui**%0A*%20GitHub%20Login%3A%20%40davidbritch%0A*%20Microsoft%20Alias%3A%20**dabritch**
You can see it's all the comment data for the appropriate article embedded in the link. I passed the URL through an HTML decoder site and this is what it translate too, replacing all the %20 characters with their appropriate types:
https://github.com/dotnet/docs-maui/issues/new?title=&body= [Enter feedback here] --- #### Document Details ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.* * ID: 1ce42af9-5ff2-9b3f-4618-65ba90a67813 * Version Independent ID: 1ce42af9-5ff2-9b3f-4618-65ba90a67813 * Content: [Basic bindings - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/basic-bindings) * Content Source: [docs/fundamentals/data-binding/basic-bindings.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/data-binding/basic-bindings.md) * Product: **dotnet-mobile** * Technology: **dotnet-maui** * GitHub Login: @davidbritch * Microsoft Alias: **dabritch**
