### ISSUE TITLE
Is it possible to call frontend C# from JavaScript in WebView?

### ISSUE THREAD

**Issue by jameslin0312** [dotnet/docs-maui#576]
I can do this by ["Customizing a WebView"](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview) using Xamarin. Is it possible using MAUI WebView?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace91785-d304-f161-408e-34511fb75ce3
* Version Independent ID: ace91785-d304-f161-408e-34511fb75ce3
* Content: [WebView - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview)
* Content Source: [docs/user-interface/controls/webview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/webview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello @jameslin0312 It should be. .NET MAUI is just the next evolutionary step for Xamarin. The one thing that is different now is how you create those handlers. See #556 for some information I posted about the handlers. The documentation for the handlers hasn't been written yet.

**Comment by davidbritch** [comment]
Hi @jameslin0312 

@eilon has created a `HybridWebView` control that can call .NET code from JavaScript, and JavaScript code from .NET. Check it out at https://github.com/Eilon/MauiCSharpInteropWebView
