### ISSUE TITLE
How to contribute translations for other languages?

### ISSUE THREAD

**Issue by Ironyho** [dotnet/docs-maui#577]
How to contribute translations for other languages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be98396-dc5f-1a99-f96a-a346c3098e2c
* Version Independent ID: e5c64f3c-1ca2-a0d8-b16a-e189918eedb7
* Content: [What is .NET MAUI? - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui)
* Content Source: [docs/what-is-maui.md](https://github.com/dotnet/docs-maui/blob/main/docs/what-is-maui.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Ironyho 

Afraid this isn't currently possible. Thanks for offering though!
