### ISSUE TITLE
Add Context for Shell Apps to "TabbedPage page swiping on Android"

### ISSUE THREAD

**Issue by EthanHipps** [dotnet/docs-maui#579]
Would it be possible to add context for apps that use Shell Tabs instead of a `TabbedPage`? As a newcomer to .NET MAUI/Xamarin.Forms, it's not clear whether the content can be applied to apps that use Shell too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad39449-00d9-3da7-b9f8-f79a6bfcfa21
* Version Independent ID: dad39449-00d9-3da7-b9f8-f79a6bfcfa21
* Content: [TabbedPage page swiping on Android - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/android/platform-specifics/tabbedpage-page-swiping)
* Content Source: [docs/android/platform-specifics/tabbedpage-page-swiping.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/platform-specifics/tabbedpage-page-swiping.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 57842](https://dev.azure.com/msft-skilling/Content/_workitems/edit/57842)

**Comment by davidbritch** [comment]
Hi @EthanHipps 

Sure, I'll get the doc updated. But to answer your question, this only applies to apps that use `TabbedPage`. Not Shell-based apps.

**Comment by EthanHipps** [comment]
Hey @davidbritch

Thank you so much for the clarification and doc updates!
