### ISSUE TITLE
Managing environment settings for MAUI Blazor apps?

### ISSUE THREAD

**Issue by robertwood62** [dotnet/docs-maui#582]
Could you add a section on how to manage environment settings for MAUI Blazor apps?

For browser based Blazor applications there are several patterns that can be used to manage Dev/Staging/Prod environment settings.
https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-6.0 

Could something similar be added for MAUI Blazor applications?

**Comment by adegeo** [comment]
Thank you for this suggestion, we'll add it to the backlog.

**Comment by davidbritch** [comment]
Hi @robertwood62 

Afraid that the docs for Blazor hybrid apps (inc. MAUI Blazor apps) are in a different repo, written by a different team. The Blazor Hybrid docs can be found at https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-6.0 and issues can be logged at https://github.com/dotnet/AspNetCore.Docs. I'd recommend making your suggestion there.
