### ISSUE TITLE
Missing docs for Page navigation events

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/docs-maui#583]
Page navigation events added in https://github.com/dotnet/maui/pull/1812 are not mentioned in the docs anywhere.

- `Page.NavigatingFrom`
- `Page.NavigatedFrom`
- `Page.NavigatedTo`

**Comment by mattjohnsonpint** [comment]
Note, the related events `Page.Appearing` and `Page.Disappearing` are documented at https://docs.microsoft.com/dotnet/maui/fundamentals/shell/lifecycle, though they really belong to `Page` (`Shell` inherits `Page`).  Not sure if these three should be there also, or if they all should go somewhere else together, or be split up.

**Comment by mattjohnsonpint** [comment]
There's also the shell navigation events (https://docs.microsoft.com/dotnet/maui/fundamentals/shell/navigation), `Shell.Navigating` and `Shell.Navigated`, though it's not clear how the page navigation events coordinate with the shell navigation events

**Comment by adegeo** [comment]
Thank you for this suggestion. I'll add it to our backlog.

**Comment by davidbritch** [comment]
Dupe of #102
