### ISSUE TITLE
"Create a Shell App" Without Any Actual Steps or Chronology

### ISSUE THREAD

**Issue by themannyprog** [dotnet/docs-maui#584]
There should be a step-by-step on how to actually create a Shell app, especially going from creating a template project to assigning the "views:CatsPage" or "views:DogsPage" as a data source to the ShellContent. All this, without indicating or showing how those data sources were arrived at or what they look like in code. We also don't know what's in the namespace "Xaminals.Views". There are too many leaps in the explanation and it doesn't provide any apparent chronology of events.

The reader has to guess how to get from one point in the explanation to the other and how to make sense of what they're seeing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a40e37d-f108-5f6a-a79b-012fc7f24c81
* Version Independent ID: 4a40e37d-f108-5f6a-a79b-012fc7f24c81
* Content: [Create a .NET MAUI Shell app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/create)
* Content Source: [docs/fundamentals/shell/create.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/create.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thank you for this feedback. It would probably be more beneficial to move some of this content into the overview article, and then transform this article into tutorial that takes you from the basic template to the final app presented in the current version of this article.

**Comment by davidbritch** [comment]
Hi @themannyprog 

This is now covered in https://learn.microsoft.com/en-us/dotnet/maui/tutorials/notes-app
