### ISSUE TITLE
How do you set up ICanvas?  Not clear in the documentation.

### ISSUE THREAD

**Issue by DAMcKinleySr** [dotnet/docs-maui#586]
Lots of example that say...
"Lines can be drawn on an `ICanvas` using the `DrawLine` method, ..."  Yet looking through the documentation  I cannot find out how to set up `ICanvas`.  One simple example using the "Learn Maui" Project would be great.

Have done NuGet for `Microsoft.Maui.Graphics`

 and in C#
```
using Microsoft.Maui.Graphics;

ICanvas canvas - new ICanvas();  // Can't figure out start up a new iCanvas 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca86947-204f-9c45-223d-724fb59b4938
* Version Independent ID: 0ca86947-204f-9c45-223d-724fb59b4938
* Content: [Draw graphical objects - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/graphics/draw)
* Content Source: [docs/user-interface/graphics/draw.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/draw.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. The canvas is provided to you through the visual objects on your XAML page. For example, if you add a `GraphicsView` to the XAML, you need to set the `Drawable` property to your drawing code. The `IDrawable` interface defines all the commands that you use to draw the "thing" you want to draw.

Basically, `GraphicsView` creates that canvas and passes it to your `IDrawable` object, which then draws on the canvas.

Take a look at the [GraphicsView](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/graphicsview) article.

The start of the article points this out:

> ![image](https://user-images.githubusercontent.com/67293991/172495738-c5cc07f0-c537-4770-b8d5-f1584913cba2.png)


Here is a quick example I threw together

Here is the XAML element to put in your page:
```xaml
<GraphicsView x:Name="view1" Loaded="view1_Loaded" WidthRequest="100" HeightRequest="100" />
```
The code behind:
```csharp
// The helper class
private class ActionDrawable : IDrawable
{
    private Action<ICanvas, RectF> _code;

    public ActionDrawable(Action<ICanvas, RectF> code) =>
        _code = code;

    public void Draw(ICanvas canvas, RectF dirtyRect) =>
        _code(canvas, dirtyRect);
}

// The graphics view load event to use the ActionDrawable and feed it commands
private void view1_Loaded(object sender, EventArgs e)
{
    view1.Drawable = new ActionDrawable((c, r) =>
    {
        SolidPaint solidPaint = new SolidPaint(Colors.Silver);

        RectF solidRectangle = new RectF(0, 0, 200, 100);
        c.SetFillPaint(solidPaint, solidRectangle);
        c.SetShadow(new SizeF(10, 10), 10, Colors.Grey);
        c.FillRoundedRectangle(solidRectangle, 12);
    });
}
```

I'm going to close this issue as I believe your question has been answered.
