### ISSUE TITLE
Typo in name of OpenMapAsync

### ISSUE THREAD

**Issue by dbullen-uk** [dotnet/docs-maui#589]
The example for OpenMapAsync has an extra 's' - OpenMapsAsync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 301d70e4-5866-50fd-2bfb-7ba92e88208e
* Version Independent ID: 301d70e4-5866-50fd-2bfb-7ba92e88208e
* Content: [Map - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/maps?tabs=windows)
* Content Source: [docs/platform-integration/appmodel/maps.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/appmodel/maps.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
It's supposed to be `OpenMapsAsync`. I'll change the text in the article. Thanks!
