### ISSUE TITLE
Error when trying to Build new Maui project

### ISSUE THREAD

**Issue by philipdekock** [dotnet/docs-maui#590]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	

Assets file 'D:\...\MauiApp1\obj\project.assets.json' doesn't have a target for 'net6.0-android'. Ensure that restore has run and that you have included 'net6.0-android' in the TargetFrameworks for your project.	

MauiApp1	C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	267	

I get this when trying to Build a freshly created Maui project. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cdfd37b-a119-da4e-a56e-a60dde31bb18
* Version Independent ID: 1cdfd37b-a119-da4e-a56e-a60dde31bb18
* Content: [Troubleshoot known issues - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/troubleshooting)
* Content Source: [docs/troubleshooting.md](https://github.com/dotnet/docs-maui/blob/main/docs/troubleshooting.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
@philipdekock It's possible you're not fully installed the android SDK and other requirements? Can you post your project file for more information? Can you provide what version of Visual Studio you're using and which template you used to create the project?

**Comment by philipjohndekock** [comment]
Hi, I eventually managed to sort this out. It was a rogue NuGet Library in my Visual Studio that cause an issue (don;t know exactly what). After I removed it, cleaned the solution and rebuilt it, it came right.
