### ISSUE TITLE
Binding to the Color.Red (etc) values

### ISSUE THREAD

**Issue by AlanJacobsSandnet** [dotnet/docs-maui#593]
[Enter feedback here]
Really clear useful description of MAUI data binding for newbie like me trying to learn MAUI.
However I did run into a problem trying to make the final section work (displaying colour values in hex).

The XAML code:
```
<Label Text="{Binding Color.Red,
                      Converter={StaticResource intConverter},
                      ConverterParameter=255,
                      StringFormat='R={0:X2}'}" />
```
produced no output of any kind whatsoever. I've played around with many variants and it seems that the issue lies in the definition of the MAUI Microrsoft.Maui.Grahics.Color class. The individual component colour values are defined, for example, thus:
    `public readonly float Red;`
In other words as fields and not properties. 
I tried a sideways experiment introducing a new class into the example namespace :
   ```
public class Id
    {
        public int Number { get; set; }
        public int Nmbr;
        public Id(int idNum)
        {
            Number = idNum;
            Nmbr = idNum;
        }
    }
```
and then  added a new property into the `NamedColor` class:
  ```
public class NamedColor
  {
      ...
      public Id IdTag {get; set;}
      ....
  }
```
The Id object was instantiated in the NamedColor class constructor and its members both set to a sequence number.
The XAML label below, inserted ahead of the labels for R, G, B values
`<Label Text="{Binding IdTag.Number}"/>
`
displayed the sequence number but 
`<Label Text="{Binding IdTag.Nmbr}"/>
`
displayed nothing at all.  
It looks like you can't bind to a field of a class only to a property. Is this the case?

BTW, I can make the example work by introducing extra properties to the `NamedColor` class, i.e.
`public float Rval => Color.Red;`
and modifying the XAML label as such:
`<Label Text="{Binding Rval, Converter={StaticResource intConverter}, ConverterParameter=255, StringFormat='R={0:X2},  '}"/>`
...
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67eff20e-d00f-c29c-c025-eb12f523acd1
* Version Independent ID: 67eff20e-d00f-c29c-c025-eb12f523acd1
* Content: [Data binding basics - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/data-binding-basics)
* Content Source: [docs/xaml/fundamentals/data-binding-basics.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/fundamentals/data-binding-basics.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @AlanJacobsSandnet thank you for reporting this. You're correct, you can only bind to the property. The previous iteration of .NET MAUI, named Xamarin (Forms), used properties for the `Color` class, and not fields. I suspect they changed it because `Color` is used everywhere and they wanted it to be as performant as possible.

That said, this article was ported from the Xamarin documentation, and while the properties were updated (going from `Color.R` to `Color.Red`) the code is now incompatible.

We'll have to look at rewriting this example a bit in the documentation. One thing you can do right now, though, is modify the `NamedColor` class and add properties that forward the information from the color fields:

```csharp
    public class NamedColor
    {
        public string Name { get; private set; }
        public string FriendlyName { get; private set; }
        public Color Color { get; private set; }

        public float ColorRed => Color.Red;
        public float ColorGreen => Color.Green;
        public float ColorBlue => Color.Blue;
```

Now just change your label bindings to the new property:

```xaml
<Label Text="{Binding ColorRed,
                      Converter={StaticResource intConverter},
                      ConverterParameter=255,
                      StringFormat='R={0:X2}'}" />
```

Sorry for the inconvenience!

@davidbritch FYI

**Comment by AlanJacobsSandnet** [comment]
Thanks for confirming my suspicions!
As I mentioned I had tried your suggested workaround and it does indeed successfully get around the issue - so hope this helps anyone else hitting the problem.
Still enjoying my investigations into .NET MAUI nonetheless.
