### ISSUE TITLE
ClockViewModel not works on macOS

### ISSUE THREAD

**Issue by WisJamison** [dotnet/docs-maui#597]
[Enter feedback here]
I tested on macOS and found DataTime Property can't changed by every second if set the timer as local variable in Constructor:

public ClockViewModel()
```
        {          
            this.DateTime = DateTime.Now;

            // Update the DateTime property every second.
            Timer timer= new Timer(new TimerCallback((s) => this.DateTime = DateTime.Now), null, 0, 1000);
        }
```
And if set it to a field, it works:
```
 public class ClockViewModel : INotifyPropertyChanged
    {
        Timer timer;
        DateTime dateTime;
        ...
    }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9905cd00-f3a1-7bdd-d678-ef6c71fb53b7
* Version Independent ID: 9905cd00-f3a1-7bdd-d678-ef6c71fb53b7
* Content: [Data binding and MVVM - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/mvvm)
* Content Source: [docs/xaml/fundamentals/mvvm.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/fundamentals/mvvm.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by reddvid** [comment]
Also tested on Windows 11, VS 2022 17.3.0 Preview 1.1 but then setting the timer to a field does nothing (both mac and Windows).

Debugging the ClockViewModel.cs shows that PropertyChanged is null therefore not firing the DateTime change.

**Comment by adegeo** [comment]
Hi @reddvid Thank you for reporting this bug.

After fixing the bug with the timer, you'll need to modify the XAML code to use the correct property. This is the next step in the article after the timer is introduced:

```xaml
    <Label Text="{Binding DateTime, StringFormat='{0:T}'}"
           FontSize="18"
           HorizontalOptions="Center"
           VerticalOptions="Center" />
```

**Comment by reddvid** [comment]
> Hi @reddvid Thank you for reporting this bug.
> 
> After fixing the bug with the timer, you'll need to modify the XAML code to use the correct property. This is the next step in the article after the timer is introduced:
> 
> ```
>     <Label Text="{Binding DateTime, StringFormat='{0:T}'}"
>            FontSize="18"
>            HorizontalOptions="Center"
>            VerticalOptions="Center" />
> ```

Yes, I found the mistake. Thanks!
