### ISSUE TITLE
Where's the Bluetooth permission?

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#599]
Please don't tell me you haven't even implemented the bluetooth permissions request?

If not how do I do it for Android?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c978effc-e14b-bb58-464a-263059ce4413
* Version Independent ID: c978effc-e14b-bb58-464a-263059ce4413
* Content: [Permissions - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/permissions?tabs=android)
* Content Source: [docs/platform-integration/appmodel/permissions.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/appmodel/permissions.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @gfmoore I feel your pain. That and WiFi aren't included. It's possible that at the time the permissions helper was written, there wasn't an easy way to abstract those interfaces into a single API? The paragraph kind of explains this:

> .NET MAUI attempts to abstract as many permissions as possible. However, each operating system has a different set of permissions. Even though the API allows access to a common permission, there may be differences between operating systems related to that permission. The following table describes the available permissions:


So the team must have omitted it at the time for some reason. Historically, these APIs were community contributed that made its way into the product, so they were omitted by a community member for some reason. But it does seem like an important gap to fill!

You should file a bug on the https://github.com/dotnet/maui code repo requesting this and wifi. I'm going to close this issue as there isn't anything we can do via the docs.

Sorry!
