### ISSUE TITLE
MauiIcon documentation is incomplete

### ISSUE THREAD

**Issue by mattleibow** [dotnet/docs-maui#611]
There are a few issues opened on the maui repo saying changing the app icon is not working.

This is a result of 2 things:

### 1. No Platform Docs

The docs do not say that the developer is supposed to actually go change values in the manifests. This is probably confusing because by default Windows updates the appxmanifest, but Android/iOS/Mac Catalyst do not. The fact Windows updates was just a byproduct of other things. The initial design was to take a more conservative approach and _just_ generate icons.

However, regardless of what is happening, the docs need to include a section of editing the platform manifests on _all_ platforms. This includes the Package.appxmanaifest on Windows, AndroidManifest on Android and Info.plist on iOS/Mac Catalyst.

### 2. Inconsistent Build Behavior

As mentioned above, Windows generates the correct manifest entries by default. The other platforms do not.

This is partially be addressed in https://github.com/dotnet/maui/pull/7968

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Version Independent ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Content: [Add an app icon to a .NET MAUI app project - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=android)
* Content Source: [docs/user-interface/images/app-icons.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/app-icons.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
@mattleibow Ok thanks for letting us know.

Quick questions:

1. So is the issue originally that this was _supposed_ to happen automatically by Maui at compile time? (icons being put/declared automatically for each platform in the appropriate places)
2. But do to whatever, this didn't happen so we'll have to update the docs to show how to get icons into each platform? 
3. If Q1 is true, is it going to go back to this eventually?

**Comment by mattleibow** [comment]
So the answers:

1. It was _not supposed_ to happen automatically - for some platforms. Genius, I know. Basically only Windows and Tizen. Obviously this was incredibly not-smart and confusing. And we never told anyone either. So technically "by design" but the design was wrong.
2. The docs need updating regardless because an app can have multiple icons generated, and as we found out, developers did not know anything about the manifests. So, the docs need to say how to either select alternate icons and/or override. An example would be that you maybe have some icon set from a designer and do not want to use resizetizer. Then, devs delete the MauiIcon and suddenly all is broken - weird errors about resources. What will happen is, devs need to go to each manifest and manually insert the correct values:   
   Android: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/?tabs=windows#Specify_the_Application_Icon
   iOS: https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/app-icons?tabs=macos
   Windows: https://docs.microsoft.com/en-us/windows/apps/design/style/app-icons-and-logos
3. It was sort of not supposed to happen, but will soon:  
    - GA only has basic support for Windows and Tizen
    - the big #8020 PR that I am hoping to get in for SR2 will make it work properly for Android
    - a later PR will make it work for iOS/MacCat

**Comment by davidbritch** [comment]
https://github.com/dotnet/maui/pull/8063

https://github.com/dotnet/maui/pull/8063
