### ISSUE TITLE
There's a mistake in the Android code sample

### ISSUE THREAD

**Issue by intellidream** [dotnet/docs-maui#614]
[Enter feedback here]

There's a mistake in the Web authenticator Android code sample (that's in the Get started section, after the intro "To access the WebAuthenticator functionality the following platform-specific setup is required.").

**Microsoft.Maui.WebAuthenticatorCallbackActivity should be Microsoft.Maui._Authentication_.WebAuthenticatorCallbackActivity**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 829bc017-4a10-6ca5-0717-e1e62f59aacc
* Version Independent ID: 829bc017-4a10-6ca5-0717-e1e62f59aacc
* Content: [Web Authenticator - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?tabs=android)
* Content Source: [docs/platform-integration/communication/authentication.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/communication/authentication.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thank you @intellidream for reporting this. I'll get it fixed.

**Comment by intellidream** [comment]
Great, saw that it’s fixed, thank you also! 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
