### ISSUE TITLE
Problem on running sample codes

### ISSUE THREAD

**Issue by MorpheusPoi** [dotnet/docs-maui#616]
[Enter feedback here]

I am trying to learn MAUI and tried sample codes in my PC but got error

codes
<ContentPage.Padding>
        <OnPlatform x:TypeArguments="Thickness">
            <On Platform="iOS" Value="0, 20, 0, 0" />
            <On Platform="Android" Value="10, 20, 20, 10" />
        </OnPlatform>
    </ContentPage.Padding>

Errors: 
Error	XLS0504	Property 'Padding' does not support values of type 'OnPlatform`1 (T)'.
Error	XLS0414	The type 'Thickness' was not found.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af30faaf-0e5a-6ea1-5dfa-a276e8e42f4e
* Version Independent ID: af30faaf-0e5a-6ea1-5dfa-a276e8e42f4e
* Content: [Essential .NET MAUI XAML syntax - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/essential-syntax)
* Content Source: [docs/xaml/fundamentals/essential-syntax.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/fundamentals/essential-syntax.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello, this is currently a known bug. https://github.com/dotnet/maui/issues/6619

This _should_ work but it doesn't. We'll leave the docs as they are as I believe the next release will have this fixed. Sorry for the inconvenience.
