### ISSUE TITLE
I have been trying to load images from xml/svg but it is not loading in iOS.

### ISSUE THREAD

**Issue by Awesomer9561** [dotnet/docs-maui#621]
[Enter feedback here]
Hi,
I am creating a new MAUI app but it is facing some issues when building the iOS app. It is not loading any images from xml/svg . Is there any solution or workaround for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4d16da-8c0f-5b7e-54ee-1fe36c549837
* Version Independent ID: cb4d16da-8c0f-5b7e-54ee-1fe36c549837
* Content: [Image - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/image)
* Content Source: [docs/user-interface/controls/image.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/image.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Awesomer9561 

Sorry to hear that you're having problems. This is an issue with the product rather than with the docs, so I suggest you open an issue in the [engineering repo](https://github.com/dotnet/maui) where the engineers will be able to advise whether there are issues on iOS. Thanks!
