### ISSUE TITLE
More documentation please

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#628]
Hi, okay so Maui recommends svg file format. I am unsure as to how determine what is the best underlying size to use for such files esp when used as an icon. I would like to have a consistent size for use, but when downloading icons from say https://www.svgrepo.com/ the icons seem to be of different sizes. When I (attempted) to use ReactNative there were many different libraries I could choose from (such as Material Design), but I am not sure what the best practice should be here. I also don't understand basesize. I appreciate the documentation has been transformed from Xamarin, but there will be other newbies such as myself who don't understand some of the concepts and come to the documentation to learn things.
Some basic examples of usage would be nice too, though I guess I am getting that through experience.

Also though I have used inkscape in the past, I have noted comments that there are issues, so what is a basic svg editor I should use to ensure that my icons, images are compatible with .net maui. 

Thanks as ever for your help. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7dc547-5ff1-416d-450b-e39e56cb1e71
* Version Independent ID: 7d7dc547-5ff1-416d-450b-e39e56cb1e71
* Content: [Add images to a .NET MAUI app project - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/images)
* Content Source: [docs/user-interface/images/images.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/images.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
I don't think we have a recommended SVG editor :D I would just default to inkscape myself...

There is a section in the article that talks about base size, which I understand it as saying it's the image size used for the base DPI you're targeting, if it needs to scale 2x the DPI for a giant screen, it would be 2x the base size you specified (or the size defined by the SVG if you omit base size).

I'll leave this bug open as your requests for clarification and visual examples is resonable.
