### ISSUE TITLE
Content for section doesn't match the title for section...

### ISSUE THREAD

**Issue by MollsAndHersh** [dotnet/docs-maui#631]
Section title is "Display a local HTML file"

Content shown is hardcoded HTML markup and does exemplify loading the content from a save resource file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace91785-d304-f161-408e-34511fb75ce3
* Version Independent ID: ace91785-d304-f161-408e-34511fb75ce3
* Content: [WebView - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/webview)
* Content Source: [docs/user-interface/controls/webview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/webview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MollsAndHersh 

The example's loading a local HTML file from the project. What are you trying to do?
