### ISSUE TITLE
Cross-Platform API: Partial Class Implementation

### ISSUE THREAD

**Issue by grapplingwithreality** [dotnet/docs-maui#633]
In the section on defining a cross-platform API:

```csharp
namespace InvokePlatformCodeDemos.Services
{
    public enum DeviceOrientation
    {
        Undefined,
        Landscape,
        Portrait
    }

    public partial class DeviceOrientationService
    {
        public partial DeviceOrientation GetOrientation();
    }
}
```

The getorientation() method will error out with code CS8795: Pertial method must have an implementation part because it has accessibility modifiers. I am trying to write code using a partial method with different implementations on each platform and cannot for the life of me get around this error or the other errors that will come up if you try to work around this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Version Independent ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Content: [.NET MAUI invoking platform code - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code)
* Content Source: [docs/platform-integration/invoke-platform-code.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/invoke-platform-code.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
@grapplingwithreality Hello. That class actually needs to be created OUTSIDE the `platforms/` folder, such as the root of your project. You need to then implement each platform's version of it in the individual platform folders.

I'll get the documentation updated to specify this.
