### ISSUE TITLE
Where do I find additional information for  { DevicePlatform.Android, new[] { "application/comics" } 

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#634]
So if I want to find a comic for android then I'm set, but what if I want to select a json file or a text file or some other file type. How do I know what I can put here and where is this information defined please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c527464b-c10d-4b13-10ed-aa07ed838651
* Version Independent ID: c527464b-c10d-4b13-10ed-aa07ed838651
* Content: [File picker - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-picker?tabs=android)
* Content Source: [docs/platform-integration/storage/file-picker.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/file-picker.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
At that point it's really specific to the Android OS, so you would search their documentation. Looking through various storage related Android articles, I see this article: https://developer.android.com/training/data-storage/shared/documents-files#open-file which uses an example of `application/pdf` for a pdf file, and it says its the MIME type of the file. So it would be whatever json is, I would just guess it's `application/json`.

I think this answers your question, so I'll close this issue.

**Comment by gfmoore** [comment]
That's fair enough, thanks.
