### ISSUE TITLE
How to run windows

### ISSUE THREAD

**Issue by hot33331** [dotnet/docs-maui#64]
Hi David, I am missing how to run the windows version from CLI...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app in Visual Studio](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=dotnet-cli&source=docs)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @hot33331 

Afraid there isn't a CLI command to run a .NET MAUI app on Windows, yet. They can only be run from VS.
