### ISSUE TITLE
Text in controls not expanding on Android

### ISSUE THREAD

**Issue by msibalik** [dotnet/docs-maui#645]
I'm able to run the app on both iOS (iPod Gen 7 running iOS 15.4.1) and Android (Google Pixel 5 running Android 11) physical devices. However, as I add text to the Hello, World! label, it expands as it should on iOS , but is truncated on Android. This is also true of the text in the button. As you click it, the text indicating number of times it is clicked is visible on iOS, but truncated on Android.

**Comment by davidbritch** [comment]
Hi @msibalik 

Sorry to hear that you're having problems. This is an issue with the product rather than with the docs, so I suggest you open an issue in the [engineering repo](https://github.com/dotnet/maui). Thanks!

**Comment by msibalik** [comment]
Thank you!

From: David Britch ***@***.***>
Sent: Friday, July 1, 2022 9:50 AM
To: dotnet/docs-maui ***@***.***>
Cc: Sibalik, Michael ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [dotnet/docs-maui] Text in controls not expanding on Android (Issue #645)

CAUTION: THIS EMAIL ORIGINATED FROM OUTSIDE OF FAIRFAX COUNTY GOVERNMENT. Do not click links or open attachments unless you recognize the sender and know the content is safe!


Hi @msibalik<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmsibalik&data=05%7C01%7Cmichael.sibalik%40fairfaxcounty.gov%7Cf7ffcf0285c14a8be3f608da5b6888e7%7Ca26156cb5d6f41729d7d934eb0a7b275%7C0%7C0%7C637922801776370782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MhYA8Q5XC5FI4Nb%2FhHWFPSNHN%2B31dIGQXRGRqSVRzMk%3D&reserved=0>

Sorry to hear that you're having problems. This is an issue with the product rather than with the docs, so I suggest you open an issue in the engineering repo<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fmaui&data=05%7C01%7Cmichael.sibalik%40fairfaxcounty.gov%7Cf7ffcf0285c14a8be3f608da5b6888e7%7Ca26156cb5d6f41729d7d934eb0a7b275%7C0%7C0%7C637922801776370782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tJfh9uOX1BB5Zl%2F1T21FBLrGdf%2B8n4%2BOCsL4zCfFjuQ%3D&reserved=0>. Thanks!

-
