### ISSUE TITLE
Maui Installation Notes Missing Install Templates Step

### ISSUE THREAD

**Issue by marqdouj** [dotnet/docs-maui#65]
I have installed all the latest versions of the pre-requisites indicated here:
https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation

I ran the maui-check tool and passed.

I then tried to build my first app:
https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=dotnet-cli

This instruction failed:
dotnet new maui -n HelloMauiPreview

I has to run this command first before the templates were available:
dotnet new -i Microsoft.Maui.Templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation?source=docs)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by marqdouj** [comment]
Installing the templates allowed me to create the project, however I discovered it would not build in VS.
I had to run this command: dotnet workload install maui
Note: this step will also install the templates.
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install

**Comment by davidbritch** [comment]
Hi @marqdouj 

`maui-check` should do all that for you - including installing the workloads and the templates (put another way, maui-check created a full correctly working install for me). `maui-check` remains the easiest way to currently install the MAUI previews. By the time of the final release, there'll be no need to use `maui-check` or the CLI commands to install it.

**Comment by davidbritch** [comment]
Re-opening because you are correct and I am wrong.
