### ISSUE TITLE
Are all Xamarin mobile classes available?

### ISSUE THREAD

**Issue by mrlife** [dotnet/docs-maui#653]
This page gives examples for getting device orientation. For iOS, it uses `UIKit`, of which the only docs I have found are for the [Xamarin SDK class](https://docs.microsoft.com/en-us/dotnet/api/uikit?view=xamarin-ios-sdk-12).

I checked the other .NET MAUI pages but don't have a clear picture of which platform-specific features are available. Can this be added here or another page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Version Independent ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Content: [.NET MAUI invoking platform code - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code)
* Content Source: [docs/platform-integration/invoke-platform-code.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/invoke-platform-code.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mrlife 

What was Xamarin.iOS is now .NET for iOS. Similarly, what was Xamarin.Android is now .NET for Android.

All the types/namespaces haven't changed in the move from Xamarin.iOS/Android to .NET iOS/Android. Unfortunately, there are currently no API docs for .NET iOS/Android but you can still use the types if you're familiar with them.

**Comment by mrlife** [comment]
@davidbritch, thank you for clarifying that. It's great that all of the documented iOS and Android SDK functionality from Xamarin is available in .NET MAUI. From the docs, that was not apparent. It may be worthwhile to have a temporary note on this page or another that's easy to find until the docs for MAUI are updated. If not, we can close this this issue. Thanks, again.

**Comment by mrlife** [comment]
Hi, I noticed after I commented that it says I got an error on something I created, though I didn't create anything. Any ideas?

https://github.com/dotnet/docs-maui/actions/runs/2570555567

**Comment by adegeo** [comment]
~~@mrlife  I was configuring some automation on the repo but I hadn't added it to an approve list. I did so a few hours later. Are you still getting the notification?~~

I just noticed I can see the github action runs which triggered the error. This was the only error and it hasn't repeated. So don't worry about responding! 😁
