### ISSUE TITLE
Battery is backed by the `IBattery` interface

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#655]
⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42400eea-3839-ac76-bac9-02e1473bcd87
* Version Independent ID: 42400eea-3839-ac76-bac9-02e1473bcd87
* Content: [Battery - .NET MAUI](https://docs.microsoft.com/en-gb/dotnet/maui/platform-integration/device/battery?tabs=android)
* Content Source: [docs/platform-integration/device/battery.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device/battery.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Did you mean to close this?

**Comment by davidbritch** [comment]
Yes. The issue really is that some Essentials docs lead with the interface up front, and some mention it a few paragraphs in. But regardless, the interface is mentioned (where it exists).
