### ISSUE TITLE
XamlCompilation attribute

### ISSUE THREAD

**Issue by ataparia** [dotnet/docs-maui#663]
As per the link, we need to put XamlCompilation attribute in the AssemblyInfo.cs file.
However, I don't see any AssemblyInfo.cs file in .net MAUI project structure.
Can you please clarify where exactly do we need to put this attribute to pre-compile all of our xaml files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12b6e5f6-7ab1-1373-242e-4f28cee2b773
* Version Independent ID: 12b6e5f6-7ab1-1373-242e-4f28cee2b773
* Content: [XAML compilation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/xaml/xamlc)
* Content Source: [docs/xaml/xamlc.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/xamlc.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ataparia 

You know that XAML compilation is enabled by default, right? So you only need to add the `XamlCompilation` attribute if you're disabling it (which isn't recommended). If you do want to disable it, just add a new file called AssemblyInfo.cs.

**Comment by ataparia** [comment]
Thank you for your response @davidbritch
