### ISSUE TITLE
Triggers Preview

### ISSUE THREAD

**Issue by jerry-synap** [dotnet/docs-maui#666]
Can you please put the resulting screenshots of the code shown on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d235822-6844-24ce-55e7-2515d3c023b2
* Version Independent ID: 4d235822-6844-24ce-55e7-2515d3c023b2
* Content: [Triggers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/triggers)
* Content Source: [docs/fundamentals/triggers.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/triggers.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jerry-synap 

Afraid there are no plans to add screenshots for every code snippet. However, I'm gradually publishing code samples for most pages so in the coming weeks there should be a sample available for this page that contains all the runnable code.

**Comment by jerry-synap** [comment]
Hello David,

I did a pull since my last clone and yes I can definitely see more examples posted. Thank you, that will suffice.


Regards

Jerry Naidoo

Software

Synap Labs South Africa (PTY)LTD

Mobile: +27 74 837 2280

***@***.******@***.***>

www.synapinc.com<http://www.synapinc.com/>

Skype: jeranio_007

[cid:40c6a2f2-cfa7-4019-bd6f-3b1655e76eb1]



Disclaimer: This e-mail message and all attachments thereto ("this message") contain confidential information intended for a specific addressee and purpose. If you are not the addressee (a) you may not disclose, copy, distribute or take any action based on the contents hereof; (b) kindly inform the sender immediately and destroy all copies thereof; (c) any disclosure, copying, distribution and or any action taken or omitted in reliance on it, is prohibited and may be unlawful. The views and opinions expressed in this e-mail message may not necessarily be those of the management or Executives of Synap Labs South Africa (PTY) LTD.

________________________________
