### ISSUE TITLE
Clearification about MAUI targeting WinUI

### ISSUE THREAD

**Issue by SDP190** [dotnet/docs-maui#67]
Docs on this page says:

> .NET MAUI apps can be written on PC or Mac, and compile into native app packages:
> ....
> * Windows apps built using .NET MAUI use Windows UI Library (WinUI) 3 to create native apps that can target the Windows desktop and the Universal Windows Platform (UWP)

Please make it clear whether MAUI for Windows apps, will support outputting any of WinUI flavors: 1) WinUI Desktop, 2) WinUI UWP, or only one of them, which then is the question: which one.

If both are planned to be supported, the next question comes up how this scenario for targeting both will work in development, is it either UWP only or Desktop, or will it be possible to develop for both targets (WinUI-Desktop, WinUI UWP) in the same project simultaneously, meaning, they will be treated as different platforms like iOS, and Android, and so will be able to use compile-time platform directives for when compiling, like 

`#if WIN_UWP` 

or

` #if WIN_DESKTOP`

The question gets even greater with the fact that UWP runs on a restricted sandbox environment, vs WinUI desktop can access all system resources, so when coding in MAUI if targeting both UWP and Windows Desktop environments is possible, how would it handle code which is using windows resources (such as System.Diagnostics.Process) which are not allowed in UWP

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be98396-dc5f-1a99-f96a-a346c3098e2c
* Version Independent ID: e5c64f3c-1ca2-a0d8-b16a-e189918eedb7
* Content: [What is .NET MAUI?](https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui)
* Content Source: [docs/what-is-maui.md](https://github.com/dotnet/docs-maui/blob/main/docs/what-is-maui.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SDP190 

I'm afraid that the WinUI team have since announced that WinUI 3 won't include any UWP support. It will be WinUI-desktop only. This will also limit MAUI to WinUI-desktop only.
