### ISSUE TITLE
Support questions platform?

### ISSUE THREAD

**Issue by julzmon** [dotnet/docs-maui#678]
Are there support forms for this product anywhere?

I'm looking to understand how we could use our own web component based design system within Maui and publish custom experiences for the web, android and ios?

**Comment by davidbritch** [comment]
Hi @julzmon 

What do you mean by support forms?

**Comment by julzmon** [comment]
Somewhere I can ask the question above. Like a slack or discord.

**Comment by davidbritch** [comment]
@julzmon There sure is. You want the #MAUI channel on the DotNetEvolution Discord server: https://aka.ms/dotnet-discord

Alternatively, you can ask a question on the engineering repo at https://github.com/dotnet/maui/discussions
