### ISSUE TITLE
Seemingly contradictory statement in MAUI resource reference

### ISSUE THREAD

**Issue by genifycom** [dotnet/docs-maui#682]
This page https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?tabs=android
Says:
A .NET MAUI splash screen can use any of the standard platform image formats, including Scalable Vector Graphics (SVG) files.

 Important
 .NET MAUI converts SVG files to PNG files. Therefore, when adding an SVG file to your .NET MAUI app project, it should be referenced from XAML or C# with a .png extension.

`<ItemGroup>
  <MauiSplashScreen Include="Resources\Splash\splashscreen.svg" />
</ItemGroup>`

The Important statement seems to be contradicted by the ItemGroup example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc
* Version Independent ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc
* Content: [Add a splash screen to a .NET MAUI app project - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?tabs=android)
* Content Source: [docs/user-interface/images/splashscreen.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/splashscreen.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @genifycom 

What the doc is trying to say is this: .NET MAUI converts .SVGs to .PNGs. However, always reference the .SVG from your .csproj. However, if you needed to reference an SVG image file from XAML/C# (e.g. load the image in an `Image` control) you should always use the .PNG extension (the version of the file converted by .NET MAUI).

I appreciate that the text is confusing so I'll give it an update.
