### ISSUE TITLE
MAUI in the index

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs-maui#683]
This probably isn't the correct place to leave this feedback, but now MAUI is released to the world should it not be on this page?

https://docs.microsoft.com/en-gb/documentation/

**Comment by davidbritch** [comment]
Hi @martingbrown 

Yes. Good idea. I'll take care of it. Thanks!

**Comment by davidbritch** [comment]
PR: https://github.com/MicrosoftDocs/DocsRoot/pull/1224
