### ISSUE TITLE
Theming documentation out of date?

### ISSUE THREAD

**Issue by nzcoward** [dotnet/docs-maui#684]
Documentation should be updated from using the *old* way of theming the application to instead use AppThemeBinding and UserAppTheme property on Application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04d29bb3-0ea9-e42a-d6d2-cf338baca362
* Version Independent ID: 04d29bb3-0ea9-e42a-d6d2-cf338baca362
* Content: [Theme an app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/theming)
* Content Source: [docs/user-interface/theming.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/theming.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nzcoward 

Thanks for pointing this out, and agreed. I'll take care of it this week.

**Comment by davidbritch** [comment]
Hi @nzcoward 

[Theme an app](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/theming) is about theming an app - while the examples are light/dark themes they could equally be red/blue themes. This deliberately doesn't use `AppThemeBinding`, which is for responding to system theme changes (light/dark).

[Respond to system theme changes](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/system-theme-changes) covers using `AppThemeBinding` and `UserAppTheme`.

So no significant update is required here. However, I think the above can be better pointed out on each doc, so I'll give them a minor update to clarify.
