### ISSUE TITLE
Clarify `this` in `MessageCenter.Send`

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#685]
Do you people not realise that most people who visit pages like this are NOT experts. The examples do not contain enough information to make any sense. Why can't you provide simple, yet complete examples of how to get this stuff working!!!! It is SO frustrating.

So I I have a ViewModels for a DisplayPage and a BluetoothPage. I want to send a message from the BluetoothPage to the DisplayPage.

So I have a command in my bluetooth page (using community MVVM) and I try to put the example code in there.

```
MessagingCenter.Send<DisplayPage>(this, "Hi");
```

Well MessagingCenter is recognised and so is DisplayPage, but "this" is not recognised, and no wonder. What is it referring to? Oh yeah, you still don't have any api documentation!!!! The intellisense says I need a DisplayPage sender. No idea what to put here.

In my MainPage page where do I put the 

```
public partial class DisplayPageViewModel : ObservableObject 
{
...
  MessagingCenter.Subscribe<MainPage>(this, "Hi", (sender) =>
  {
      Debug.WriteLine("Got message");
  });
...
}
```

Again I know enough to know that this doesn't make sense and the compiler agrees.

So how is this supposed to be used and can you please update the documentation to show more complete examples.

I'm sorry, but my journey with .Net Maui has been nothing but frustrating and difficult, not helped by such poor documentation.

:(

Gordon

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b861ace-1bd8-4eb1-32f8-957e4b60846f
* Version Independent ID: 9b861ace-1bd8-4eb1-32f8-957e4b60846f
* Content: [Publish and subscribe to messages - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/messagingcenter)
* Content Source: [docs/fundamentals/messagingcenter.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/messagingcenter.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by gfmoore** [comment]
This page helped  lot
https://codemilltech.com/messing-with-xamarin-forms-messaging-center/ 

However, I am still unsure of what "this" is referring to and how do I use it properly in ViewModel.

**Comment by Joebeazelman** [comment]
@gfmoore Thank god I came across this issue!  I was seriously worried I was suffering from early dementia. The documentation is awful.  It's incomplete with the endless ping pong linking between pages. Reading Microsoft's documentation almost always ends up in confusion, frustration, dead-ends and a major loss of productivity Surely, a company with revenues in the billions of dollars ought to know how to write proper documentation? I don't hear any developers remarking about the documentation. All I hear is: "Every thing is so cool , it's never been a better time to be a developer. "  I figured, it must be me.  

Thankfully, your post clarified everything for me. Indeed, the documentation is that bad. I'm no longer worried about dementia, but now I'm depressed realizing even the largest corporation with billions of dollars can't get its act together.  It's more depressing when intelligent people have come to accept such mediocrity as the norm.  Perhaps, society is on a slow downward collapse and I'm just a frog in the proverbial soup unaware of its inevitable boil.

**Comment by gfmoore** [comment]
It has already driven me mad. I figured it out though. See these posts: 
https://stackoverflow.com/questions/72913742/net-maui-how-to-read-write-get-set-a-global-object-from-any-content-page-mv
https://stackoverflow.com/questions/72806361/net-maui-mvvm-how-to-catch-a-return-from-a-different-page-using-shell-navigati

Shouldn't need to guess at this stuff, where's the api yet? And don't get me started on my new adventure - mapping and maps. What year are we in? :(

**Comment by gfmoore** [comment]
Oops closed by accident. Documentation itself needs improvement please.

**Comment by adegeo** [comment]
Hi @gfmoore That blog post that is pointing out the marker type, is providing a great point, decoupling from the view and other MVVM types. That said, both this doc and that block post are demonstrating the same thing. The point the blog post is bringing out is the decoupling, which is important if you're using multiple libraries that may not know anything about the other.

I'm going to leave this issue open as I think some things could be clarified, but I'm not totally sure which, is it just the `this` concept that wasn't working correctly for you?

Addressing specific feedback you had:

(1)
> Well MessagingCenter is recognised and so is DisplayPage, but "this" is not recognised, and no wonder. What is it referring to? Oh yeah, you still don't have any api documentation!!!! The intellisense says I need a DisplayPage sender. No idea what to put here.

The docs say:

> In this example, the Send method specifies two generic arguments. The first is the type that's sending the message, and the second is the type of the payload data being sent. To receive the message, a subscriber must also specify the same generic arguments.

The error in the docs here is it doesn't specify that this keyword is referring to the instance of `DisplayPage`, I'll get that clarified

For more information on the `this` keyword, please check out the [C# documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/this)

(2)
> In my MainPage page where do I put the `MessagingCenter.Subscribe`

You would put this code at the construction of the object, if you wanted to subscribe during the lifetime of the object. You use it when you want to start listening to the message.

> In this example, the Subscribe method subscribes the this object to Hi messages that are sent by the MainPage type, and executes a callback delegate in response to receiving the message.

(3)
> Oh yeah, you still don't have any api documentation!!!! ....... Shouldn't need to guess at this stuff, where's the api yet?

I totally agree with you! I wish it had been published, but for whatever reason, it wasn't. The product team is in charge of that, please file an issue in the [.NET MAUI code GitHub repo](https://github.com/dotnet/maui) requesting the API docs. I had done a search looking for an existing issue, but I couldn't find one.

**Comment by gfmoore** [comment]
Thanks. 

@ToolmakerSteve mentions in a comment on one of the Stackoverflow links that "this" could actually be any object and  is used when wanting to cancel the messaging for that messager. Makes sense. Ahh yes and I know it doesn't help when I don't understand some of the C# language that everyone seems to know so well.

**Comment by adegeo** [comment]
@gfmoore You can press the <kbd>F1</kbd> key for help when your caret is on top of keywords or APIs you want to learn more about. That won't help you with MAUI types, though, until the API is actually published.

_editing title to be more constructive on the doc issue_

**Comment by davidbritch** [comment]
`MessagingCenter` is now deprecated so no doc updates are required.

**Comment by gfmoore** [comment]
Wow, when did that happen and where is it documented? I relied a lot on that!

**Comment by davidbritch** [comment]
@gfmoore It's documented on the .NET 7 version of the MessagingCenter page. The idea is that it's deprecated in .NET 7, prior to being removed in .NET 8.
