### ISSUE TITLE
Wrong capabilties

### ISSUE THREAD

**Issue by gldfdp** [dotnet/docs-maui#691]
In the windows tab it is written

> Under the <Capabilities> node, add <uap:Capability Name="microphone"/> and <uap:Capability Name="webcam"/>

These two capabilties are not listed in https://docs.microsoft.com/fr-fr/uwp/schemas/appxpackage/uapmanifestschema/element-uap-capability and when we add it the compilation failed :

> The app manifest must be valid as per schema: [...] Reason: 'webcam' violates enumeration constraint of 'documentsLibrary picturesLibrary videosLibrary musicLibrary enterpriseAuthentication sharedUserCertificates userAccountInformation removableStorage appointments contacts phoneCall blockedChatMessages objects3D voipCall chat'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e5277f4-f2e4-dffe-0c08-06531d4145a1
* Version Independent ID: 1e5277f4-f2e4-dffe-0c08-06531d4145a1
* Content: [Media picker - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/device-media/picker?tabs=android)
* Content Source: [docs/platform-integration/device-media/picker.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device-media/picker.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gldfdp 

Try switching them to:

```
    <DeviceCapability Name="microphone"/>
    <DeviceCapability Name="webcam"/>
```

**Comment by gldfdp** [comment]
> Hi @gldfdp
> 
> Try switching them to:
> 
> ```
>     <DeviceCapability Name="microphone"/>
>     <DeviceCapability Name="webcam"/>
> ```

Thank you for the tip, the compilation error is not more here. The doc should be updated.
