### ISSUE TITLE
Requires ASP.Net and web development to be installed

### ISSUE THREAD

**Issue by CleverFoxDev** [dotnet/docs-maui#693]
[Enter feedback here]
You get compile errors do to missing nuget packages.

- Install preview 17.3 prv-3
- Only select .Net MAUI
- Create MAUI App project
- Packages are not resolved
- Compiled with errors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CleverFoxDev** [comment]
Follow Up...

I did not try "dotnet restore" or "dotnet restore -force" which may have resolved the issue without having to put in ASP.Net tools.

**Comment by adegeo** [comment]
This may need to be filed with the [product team as a bug](https://github.com/dotnet/maui/issues). Really the project should do its own restore after creation.
