### ISSUE TITLE
Get full source code

### ISSUE THREAD

**Issue by VanessaAk** [dotnet/docs-maui#694]
Is it possible to download the full source code of these samples? Much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d55cdb6d-0144-0c97-c373-8728b20664a9
* Version Independent ID: d55cdb6d-0144-0c97-c373-8728b20664a9
* Content: [Control templates - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/controltemplate)
* Content Source: [docs/fundamentals/controltemplate.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/controltemplate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @VanessaAk 

Samples or each doc are gradually appearing, week by week. What happens is:

1. I add them to the maui-samples repo (https://github.com/dotnet/maui-samples).
2. Samples are ingested into the samples browser (https://docs.microsoft.com/samples/browse/?expanded=dotnet&products=dotnet-maui). This can take a few days.
3. I add a link to the sample, in the sample browser, to the doc.

I actually prepared the ControlTemplates sample yesterday, and will be checking it into the maui-samples repo today. I'll ping you when that happens.

**Comment by VanessaAk** [comment]
Hi David,

Thanks a lot for getting back to me, looking forward to your updated samples.

Vanessa

**Comment by davidbritch** [comment]
@VanessaAk https://github.com/dotnet/maui-samples/tree/main/6.0/Fundamentals/ControlTemplateDemos

I'll leave this issue open until the link to the sample, in the sample browser, is added.

**Comment by VanessaAk** [comment]
Hi David,

Thank you for the link it helped a lot. I was wondering if you had any samples that show how to implement a wizard in maui.

Vanessa

**Comment by davidbritch** [comment]
Hi @VanessaAk 

Afraid not, right now.
