### ISSUE TITLE
Issues about examples

### ISSUE THREAD

**Issue by LITTOMA** [dotnet/docs-maui#695]
The ColorTo animation doesn't stopped immediatelt by calling `CancelColorAnimation`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89c67c12-a44c-4dc8-5bd3-d24fd9697762
* Version Independent ID: 89c67c12-a44c-4dc8-5bd3-d24fd9697762
* Content: [Custom animation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/animation/custom)
* Content Source: [docs/user-interface/animation/custom.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/animation/custom.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @LITTOMA 

Thanks for bringing that to our attention, but ideally it needs logging as an issue in the [engineering repo](https://github.com/dotnet/maui).
