### ISSUE TITLE
File System Helpers Seems Incomplete

### ISSUE THREAD

**Issue by billn6** [dotnet/docs-maui#700]
OK, the OpenAppPackageFileAsync is working for me.  Is there no write API for those files; only a read API as written?  If so, guidance on how to _write_ files ought to be included on this page.  Reading the MauiAssets using the stream from OpenAppPackageFileAsync and then writing them to FileSystem.Current.AppDataDirectory using a different stream seems to work fine.

I notice that a File | New Maui app project does not have any _Resources_ or _Resources\Raw_ folders under _Platforms_.  Instead, there is a _Resources_ folder at the same level as _Platforms_; this folder has a _Raw_ subfolder.  Some correction or clarification is needed.  _<Project>\Resources\Raw_ should be called out in the doc if that has the MauiAsset behavior described.  The doc should also mention that _Platforms\Resources\Raw_ needs to be created manually.

Enjoying Maui so far.  The docs are adding value.

Thanks,
Bill Needels
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Version Independent ID: 5b7e12aa-3c09-0f82-2fa2-a39c2c8065d8
* Content: [File system helpers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-system-helpers?tabs=windows)
* Content Source: [docs/platform-integration/storage/file-system-helpers.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/file-system-helpers.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @billn6 correct, no write API since those assets are loaded out of the app package itself, you can't update the app package with updated data. Thank you for spotting that error with the path, that had changed at some point and I didn't notice.

However, are you saying that you created and used a _Platforms\\{platform}\\Resources\\Raw_ folder and it loaded files from it correctly? The project has a definition for the non platform version you pointed out, which I'll correct.

**Comment by davidbritch** [comment]
@adegeo 

>However, are you saying that you created and used a Platforms\{platform}\Resources\Raw folder and it loaded files from it correctly?

I've never tried it, but it's meant to work (by design). Any valid resources (whether images, XML, raw assets etc) you put into Platforms\\{platform} should override the single project versions of them from the Resources folder.

**Comment by billn6** [comment]
No, just that File | New Maui project did not contain a Platforms\Resources\Raw as called out in the docs page in question, so I was unclear as to whether I needed to add that myself; I asked about Platforms\<Platform>\Resources\Raw as well because it did not make much sense to have Platforms\Resources\Raw when Resources\Raw already did the job for all platforms; calling out Platforms seemed to imply that MauiAssets would be specific to a platform, so a folder at Platforms (versus multiple Platform\<Platform*> folders) did not make much sense.  

In any event, the edits in #702 look good.

**Comment by adegeo** [comment]
@davidbritch I guess that's the question, if it works 😁 The project file generated by the template defines the item includes for the single-project raw resources, but it **doesn't** define item includes for the platform level.
