### ISSUE TITLE
Clamp Extension methods not available with MAUI

### ISSUE THREAD

**Issue by codeaphex** [dotnet/docs-maui#706]
I think the Clamp Extension methods (for double) are Xamarin specific and not available with MAUI?
I had to change the respective lines to
```csharp
               // Apply translation based on the change in origin.
                Content.TranslationX = Math.Clamp(targetX, -Content.Width * (currentScale - 1), 0);
                Content.TranslationY = Math.Clamp(targetY, -Content.Height * (currentScale - 1), 0);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fcfe4a4-609c-8151-6c35-f45d4123a6ac
* Version Independent ID: 6fcfe4a4-609c-8151-6c35-f45d4123a6ac
* Content: [Recognize a pinch gesture - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/pinch)
* Content Source: [docs/fundamentals/gestures/pinch.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/gestures/pinch.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@codeaphex Thanks for this. I'll get the doc updated. I remember the issue - they are Clamp extension methods so I'll have to update the doc.
