### ISSUE TITLE
When will the publish to exe functionality be ready?

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#707]
"You can't yet publish a Windows executable file for distribution."

When will this be ready? Thanks.

BTW please ask whoever is responsible to enable automation of MSIX!!

**Comment by adegeo** [comment]
Hi @gfmoore really that question is best suited for the product team, who is in charge of the roadmap. You'll need to ask it over at [dotnet/maui](https://github.com/dotnet/maui/)
