### ISSUE TITLE
Version number with Android deployment

### ISSUE THREAD

**Issue by christiannagel** [dotnet/docs-maui#710]
Specifying the version number with .NET MAUI Android apps, this documentation specifies the `ApplicationVersion` element, but misses the `ApplicationDisplayVersion` element which is mentioned by @jamesmontemagno with [TechCommunity - Versioning my Maui Android App](https://techcommunity.microsoft.com/t5/app-development/versioning-my-maui-android-app/m-p/3289666/highlight/true#M256)

It would also be great to show how the version number can be supplied passing command-line arguments (e.g. when using CI/CD).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e01dbc-832f-797a-a5a1-49908f2afa99
* Version Independent ID: 25e01dbc-832f-797a-a5a1-49908f2afa99
* Content: [Publish a .NET MAUI app for Android - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/android/deployment/overview)
* Content Source: [docs/android/deployment/overview.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/deployment/overview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---
[Associated WorkItem - 90442](https://dev.azure.com/msft-skilling/Content/_workitems/edit/90442)

**Comment by adegeo** [comment]
Hello. Thank you for letting us know setting was added back to .NET MAUI.
