### ISSUE TITLE
How raise "Completed" event

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#714]
The documentation says: The Completed event is raised when the user has ended input by pressing the return key on the keyboard, or by pressing the Tab key on Windows. The handler for the event is a generic event handler:

However on Android Pixel 5 emulator, the return/enter key does what I expect which is to move to a new line in the view (control). 

So how do I raise the completed event?

:)

![image](https://user-images.githubusercontent.com/22768967/180610540-d8b9b6ee-a916-4b62-a0fc-c633c144e1a3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70206b43-4cba-4dc2-d3ef-361b0ebfc6d6
* Version Independent ID: 70206b43-4cba-4dc2-d3ef-361b0ebfc6d6
* Content: [Editor - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/editor)
* Content Source: [docs/user-interface/controls/editor.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/editor.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi there. I just tested this and it works as expected on Windows, but not on Android. Completed via ENTER would never be raised on this control though, only on the ENTRY control.

I've opened this bug: https://github.com/dotnet/maui/issues/9796

I'll update the text of the article to remove that ENTER works
