### ISSUE TITLE
Mono is not installed on the Mac and the required version to install it automatically couldn't be determined.

### ISSUE THREAD

**Issue by gjmoyer** [dotnet/docs-maui#715]
I have Visual Studio 17.3.0 Preview 4.0 on Windows 10 21H2 19044.1826, and following these instructions to pair to Mac M1 (Monterey 12.5). After I successfully connect to my Mac it shows the error "Mono is not installed on the Mac and the required version to install it automatically couldn't be determined. The connection will be aborted. Please try to install a compatible Mono and try again."

The instructions on this page indicate that the only prerequisite on the Mac is Xcode. There is no mention of having to install Mono, and there is also no reference to this possible exception message, and what to do about it. Xcode is installed on the Mac and working correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df7f72f4-cf07-1f47-6400-432d8499edea
* Version Independent ID: df7f72f4-cf07-1f47-6400-432d8499edea
* Content: [Pair to Mac for iOS development - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac)
* Content Source: [docs/ios/pair-to-mac.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/pair-to-mac.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gjmoyer 

I checked with the engineers and pair to Mac should detect if Mono isn't installed (or needs updating), and then install it. However, they are aware that it's not working. They've got an open bug logged against it internally. The workaround is to manually install Mono. You can either do that by installing VSMac or by only installing Mono (https://www.mono-project.com/download/stable/#download-mac).
