### ISSUE TITLE
.NET MAUI Media picker not working for Windows

### ISSUE THREAD

**Issue by NextEraSoftwares** [dotnet/docs-maui#716]
[Enter feedback here]
.NET MAUI Media picker not working for Windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e5277f4-f2e4-dffe-0c08-06531d4145a1
* Version Independent ID: 1e5277f4-f2e4-dffe-0c08-06531d4145a1
* Content: [Media picker - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/device-media/picker?tabs=windows)
* Content Source: [docs/platform-integration/device-media/picker.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/device-media/picker.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SSITCS 

Apologies for the much delayed response to this issue. If this issue is still valid it needs reporting in the [engineering repo](https://github.com/dotnet/maui). Thanks!
