### ISSUE TITLE
.NET MAUI Full Screen and  Always on top 

### ISSUE THREAD

**Issue by NextEraSoftwares** [dotnet/docs-maui#717]
Hi, Do we have any update when MAUI can make available functionalities  for Fullscreen and Always on top

**Comment by davidbritch** [comment]
Hi @SSITCS 

Afraid there's no update to share right now on when MAUI will contain that functionality. All I can recommend is you start a [discussion](https://github.com/dotnet/maui/discussions) on it in the engineering repo. The product team will take note of discussions that are upvoted.
