### ISSUE TITLE
BlazorWebView does not seem to respect @media css

### ISSUE THREAD

**Issue by timahrentlov** [dotnet/docs-maui#719]
The default template for .NET Maui Blazor App has a navbar-toggler css class that should collapse the left menu when going below 641px. I can't get it to work. Any idea why?

I have a Hybrid App and a WASM App using the same shared RCL (default template) UI. The menu collapses on WASM but not on Hybrid. Same UI. Same css. Same pages.  Any ideas why?

**Comment by davidbritch** [comment]
Hi @timahrentlov 

Afraid all I can recommend is that you open an issue in the [engineering repo](https://github.com/dotnet/maui/issues), with a repro case, and the engineers will respond. Some users have mentioned potentially similar problems, but they are effectively ignored without a repro.
