### ISSUE TITLE
For Windows, How do I load an image resource and draw it on a GraphicsView?

### ISSUE THREAD

**Issue by techfan101** [dotnet/docs-maui#722]
I simply want to draw an image resource onto a `GraphicsView` (on Microsoft's Windows platform).  This seems like a fairly basic task.  After all, it's a "Multi-plAtform UI" right? :)

So, I fired up Google, found this documentation, and followed the sample code.  After failing to succeed, I went back to the documentation and noticed I missed this warning:

"Warning: The PlatformImage type isn't supported on Windows."

Any chance the page can be updated to provide something more useful? Perhaps, something like "On the Windows platform..." do this instead?  I'm really trying to like MAUI, but it simply doesn't seem ready for prime time yet.

I hope these early experiences don't scare other people away from it.  For my part, I'm going to wait 6 months and try again.  I was super-excited about its promise, but less so now,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca86947-204f-9c45-223d-724fb59b4938
* Version Independent ID: 0ca86947-204f-9c45-223d-724fb59b4938
* Content: [Draw graphical objects - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/graphics/draw)
* Content Source: [docs/user-interface/graphics/draw.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/draw.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@techfan101 

I hear you. I really do. I'm afraid there isn't a great alternative for the lack of `PlatformImage` on Windows. It used to work, during the preview phase. But then a refactoring broke it on Windows and it's stuck that way in the .NET 6 release. While it's an easy fix to make, the product team can't change the public API until .NET 7. 

A possible workaround gets mentioned [here](https://github.com/dotnet/Microsoft.Maui.Graphics/issues/457) but it's ugly. 

Sorry I don't have better news to tell you.

**Comment by davidbritch** [comment]
@techfan101  https://github.com/dotnet/Microsoft.Maui.Graphics/pull/464
