### ISSUE TITLE
VS 2022 17.3 Preview 3 - MAUI Email issue 

### ISSUE THREAD

**Issue by billn6** [dotnet/docs-maui#725]
Hi,

E-mail example code does not appear to work.  VS 2022 Community Preview 17.3 Preview 3 running under Windows 11 Home, with the Mail app working fine.  I saw no mention of a fix or known issue for 17.3 Preview 4 or 5 in the respective release notes.  See the image below.

- Are there any prerequisites for getting this to work that are not described in the docs?  Windows tab in the doc says "No additional setup required."
- Is  Email.Default.ComposeAsync broken, or perhaps Email.Default.IsComposeSupported?
- Are the docs wrong?

![image](https://user-images.githubusercontent.com/6184923/182005485-654f5890-9022-44f9-aedb-5c1be228ce36.png)

Thanks,

Bill Needels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb883e1b-a1ef-6684-d501-e9be8a57852b
* Version Independent ID: fb883e1b-a1ef-6684-d501-e9be8a57852b
* Content: [Email - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/communication/email?tabs=android)
* Content Source: [docs/platform-integration/communication/email.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/communication/email.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @billn6 

Apologies for the delayed response to this, but it's a question best asked of the engineers in the [engineering repo](https://github.com/dotnet/maui). Hopefully you've since become unblocked and it's working for you. Thanks!
