### ISSUE TITLE
Binding sample does not work

### ISSUE THREAD

**Issue by GT85** [dotnet/docs-maui#737]
Hello.
If I try to run the following xaml page, build from microsoft sample in https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton#group-radiobuttons, it does not display the name of the animal in the <Label> entry. How can I fix the issue?
Regards,
Gilbert

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestRadioButtonGroup.MainPage">

    <StackLayout RadioButtonGroup.GroupName="{Binding GroupName}"
             RadioButtonGroup.SelectedValue="{Binding Selection}">
        <Label Text="What's your favorite animal?" />
        <RadioButton Content="Cat"
                 Value="Cat" />
        <RadioButton Content="Dog"
                 Value="Dog" />
        <RadioButton Content="Elephant"
                 Value="Elephant" />
        <RadioButton Content="Monkey"
                 Value="Monkey"/>
        <Label x:Name="animalLabel">
            <Label.FormattedText>
                <FormattedString>
                    <Span Text="You have chosen:" />
                    <Span Text="{Binding Selection}" />
                </FormattedString>
            </Label.FormattedText>
        </Label>
    </StackLayout>
</ContentPage>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4d9b4fe-c357-031e-3fc4-9c22ffee81db
* Version Independent ID: a4d9b4fe-c357-031e-3fc4-9c22ffee81db
* Content: [RadioButton - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/radiobutton?source=docs)
* Content Source: [docs/user-interface/controls/radiobutton.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/radiobutton.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @GT85 

I just tried the sample (https://docs.microsoft.com/en-us/samples/dotnet/maui-samples/userinterface-radiobutton/) on both Android and Windows and the radio button values and selection were being displayed.

**Comment by GT85** [comment]
Hi David.

Sorry, I did not write that I was using and testing Mac OS (12.4). 

Nevertheless, I did a test on Android (see attached) and I get the same issue. Do you use exactly the same xcml file as me ?

Regards,
Gilbert

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestRadioButtonGroup.MainPage">

    <StackLayout RadioButtonGroup.GroupName="{Binding GroupName}"
             RadioButtonGroup.SelectedValue="{Binding Selection}">
        <Label Text="What's your favorite animal?" />
        <RadioButton Content="Cat"
                 Value="Cat" />
        <RadioButton Content="Dog"
                 Value="Dog" />
        <RadioButton Content="Elephant"
                 Value="Elephant" />
        <RadioButton Content="Monkey"
                 Value="Monkey"/>
        <Label x:Name="animalLabel">
            <Label.FormattedText>
                <FormattedString>
                    <Span Text="You have chosen:" />
                    <Span Text="{Binding Selection}" />
                </FormattedString>
            </Label.FormattedText>
        </Label>
    </StackLayout>
</ContentPage>

**Comment by davidbritch** [comment]
I've ran it on Windows and Android from VS, and on iOS/Android/Mac from VSMac. It works in all cases for me.

Here it is on iOS, Android, and Mac (12.5):

![Screenshot 2022-08-05 at 09 40 42](https://user-images.githubusercontent.com/8092460/183041752-929e3f06-e952-45a2-8b32-888b6d7c92b1.png)

![Screenshot_1659689622](https://user-images.githubusercontent.com/8092460/183041771-d2e0617f-627a-4b6c-bbff-9e8e34ee66e5.png)

![Screenshot 2022-08-05 at 09 55 47](https://user-images.githubusercontent.com/8092460/183041813-78aa12e2-78a0-45d8-99f9-2e58fca2b6a2.png)

I'm running the latest public previews of VS 17.3 and VSMac 17.3.
