### ISSUE TITLE
Insufficient instructions for the case when VS for Mac is not installed.

### ISSUE THREAD

**Issue by agr** [dotnet/docs-maui#738]
The page says VS for mac is optional, but trying to pair VS 2022 with Mac that only has XCode installed results in the following error:

> An error occurred while trying to connect to the Broker...
Probed locations for Mono on the Server: mono64, /Library/Frameworks/Mono.framework/Versions/Current/bin/mono64, /usr/bin/mono64, /bin/mono64, /usr/local/bin/mono64, /usr/sbin/mono64, /sbin/mono64, /Users/xxxxx/Library/Caches/Xamarin/XMA/Runtimes/mono/bin/mono64, mono, /Library/Frameworks/Mono.framework/Versions/Current/bin/mono, /usr/bin/mono, /bin/mono, /usr/local/bin/mono, /usr/sbin/mono, /sbin/mono, /Users/xxxxx/Library/Caches/Xamarin/XMA/Runtimes/mono/bin/mono

(I'm guessing VS for Mac would be the one bringing Mono there). If Mono is separate requirement, please cover it in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df7f72f4-cf07-1f47-6400-432d8499edea
* Version Independent ID: df7f72f4-cf07-1f47-6400-432d8499edea
* Content: [Pair to Mac for iOS development - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac)
* Content Source: [docs/ios/pair-to-mac.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/pair-to-mac.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @agr 

I checked with the engineers and pair to Mac should detect if Mono isn't installed (or needs updating), and then install it. However, they are aware that it's not working. They've got an open bug logged against it internally. The workaround is to manually install Mono. You can either do that by installing VSMac or by only installing Mono (https://www.mono-project.com/download/stable/#download-mac).
