### ISSUE TITLE
Supported platforms page doesn't say that macOS support is through Catalyst

### ISSUE THREAD

**Issue by rtharston** [dotnet/docs-maui#74]
The supported platforms page says that macOS 11 or higher is supported (which is already a problem, almost no developer supports only the latest version of macOS, but I digress).

It doesn't say what frameworks are supported. Is macOS supported natively using Cocoa? (As it should be.) Or just using Catalyst? Or both? I've seen conflicting information in the blog posts and as it is still in preview I don't really trust the current state of things to properly indicate the future.

I'd like to see the supported platforms page clearly state which UI framework is being used to support macOS. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb754bf-48db-4f6c-7e87-7cb3b59c34d5
* Version Independent ID: ba07354c-611d-5efe-0fbb-48a24d02cafe
* Content: [.NET MAUI supported platforms](https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms)
* Content Source: [docs/supported-platforms.md](https://github.com/dotnet/docs-maui/blob/main/docs/supported-platforms.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rtharston 

I'll update the doc, but in the meantime here's the answer. macOS support in MAUI is Catalyst. If you want to use Cocoa you'll have to use .NET for macOS (was Xamarin.Mac).

**Comment by rtharston** [comment]
Thanks David.
That is what I had gathered from reading the different Preview blogs, but I wanted to make sure.

I’ve been looking forward to MAUI since it was first announced (hard to believe how long it’s been), so I have to say I’m a bit bummed that the main platform I care about most is getting the shortest stick, but I get it. Catalyst will be easier to support since you already have iOS support in MAUI.

My main use case will be for a desktop macOS and Windows application, so I’ll have to see if Catalyst will work for my app, or I’ll just have to keep separate project like I would have done before.

I don’t mean to be a Debbie downer though, even if MAUI won’t meet all my needs, I’m still excited to see it happen, and I appreciate all the hard work has been put into it.

**Comment by davidbritch** [comment]
It *might* be possible to use Forms embedding in a .NET for macOS (Cocoa) app. So that way you'd still have a shared UI across macOS/Windows.

I say might, because right now I don't know how well Forms embedding will be supported on macOS. I'll find out and get back to you.

**Comment by davidbritch** [comment]
Afraid it won't be possible to use Forms embedding in a .NET for macOS (Cocoa) app when MAUI launches in November. Every platform but macOS!

**Comment by rtharston** [comment]
I’ve only used .NET framework for Windows, so I’m not as familiar with the new cross platform options. I hadn’t heard of Forms embedding before. Thanks for checking!

**Comment by davidbritch** [comment]
It's possible with Catalyst apps to select a UI idiom, so you can say whether it uses the iPad or macOS UI idiom. Not sure if that'll help you.
