### ISSUE TITLE
The system image could not be created

### ISSUE THREAD

**Issue by msglog** [dotnet/docs-maui#741]
I am in China, due to the Google service cannot be accessed, result in unable to download the images.  hope  this page is able to increase the mirror node

<img width="751" alt="cache_2022-08-05_16-10-19" src="https://user-images.githubusercontent.com/34530046/183033217-be04ca88-2465-4dbb-8714-437b99f31207.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @msglog 

Apologies for the delayed response. Afraid that there's not much we can do about this. The emulators are hosted by Google and there's nothing we can do to provide access to them in China.

**Comment by msglog** [comment]
> Hi @msglog
> 
> Apologies for the delayed response. Afraid that there's not much we can do about this. The emulators are hosted by Google and there's nothing we can do to provide access to them in China.

@davidbritch 

Would you like to consider adding the feature of "Custom Simulator Download Address" to this feature?

idea：

1. Set custom download address ?

2. Manually customizing the actual execution path and image of the simulator?

**Comment by msglog** [comment]
If 'custom download address' or' custom execution path or image 'is not supported.

this feature will not work properly in regions that do not support accessing Google services

**Comment by davidbritch** [comment]
Hi @msglog 

An alternative is to use the Windows Subsystem for Android. The docs don't mention it yet because there's still work to be done to make it work smoothly. However, it can be made to work. See https://marketplace.visualstudio.com/items?itemName=Redth.WindowsSubsystemForAndroidVisualStudioExtension and https://learn.microsoft.com/en-us/shows/on-net/debug-android-apps-with-wsa-and-visual-studio-2022
