### ISSUE TITLE
Mapping code doesn't work

### ISSUE THREAD

**Issue by mlopezqkd** [dotnet/docs-maui#743]
Using VS 2022 64-bit Preview version 17.3.0 preview 6, I created a new MAUI app, added an "<Entry .../>" control to the main page ("MainPage"), copied the code from the section titled "Customize a control with a mapper", am running Android emulator, changed "Colors.Transparent.ToPlatform()" to Red ("Colors.Red.ToPlatform()"), and the background color of the "<Entry .../>" doesn't change to Red when I run the app.

I then created a second ContentPage, added an "<Entry .../>" control, and changed the behavior of the button on the main page ("MainPage")  to not increment variable "count" but to navigate to the new page (PushAsync) and still no Red.

I then replaced "MainPage = new AppShell();" with "MainPage = new NavigationPage(new MainPage());", thinking maybe the Shell had something to do with the color not changing, and same thing; the background color doesn't change to Red.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659665da-2ff3-3550-2e0c-20902c15c3e6
* Version Independent ID: 70227b04-808f-1370-186b-10cfef525959
* Content: [.NET MAUI control customization with handlers - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/handlers/customize)
* Content Source: [docs/user-interface/handlers/customize.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/handlers/customize.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mlopezqkd 

Sorry to hear about your problem, but perfect timing. I'm currently rewriting that article, and have produced new sample code for it. The old sample code certainly worked at the time of writing, but I have no idea if it still works.

It'll probably be a week or two before the new doc appears, but in the meantime you can browse the new sample code at: https://github.com/dotnet/maui-samples/tree/dabritch-handlers-customize/6.0/UserInterface/Handlers/CustomizeHandlersDemo

Hope this helps.

**Comment by mlopezqkd** [comment]
Thanks, David.

I found some code on a different site and for the first parameter ("string key") to "AppendToMapping" they used "nameof(IView.Background) instead of a string literal ("MyCustomization", in your example). When I made that change it worked.

Mike
