### ISSUE TITLE
How to Consume .NET MAUI Control in .razor Page ?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/docs-maui#744]
Can you give an Example of how to use the .NET MAUI control/component in .razor Page of Blazor Hybrid App ?

I wan to use this QrCode Scanner in Blazor Hybrid App .

https://github.com/Redth/ZXing.Net.Maui/issues/22

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Version Independent ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Content: [Host a Blazor web app in a .NET MAUI app using BlazorWebView - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview)
* Content Source: [docs/user-interface/controls/blazorwebview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/blazorwebview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nssidhu 

Looks like your question was answered [here](https://github.com/dotnet/maui/issues/9378) so I'll close the issue now.
