### ISSUE TITLE
Validating Network Connectivity by calling NCSI

### ISSUE THREAD

**Issue by Mephisztoe** [dotnet/docs-maui#748]
The "Limitation" area explains why sometimes the connectivity might be reported as giving internet access, while in reality there isn't. For instance when the device has a successful connection to a router, but the router has no internet connection.

Microsoft Windows solves this issue by calling the network connectivity status indicator file, namely: http://[www.msftncsi.com/ncsi.txt](http://www.msftncsi.com/ncsi.txt).

Why not implementing this as a fallback?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d333ea5c-2d8e-6a0a-fb03-b324bbe6b750
* Version Independent ID: d333ea5c-2d8e-6a0a-fb03-b324bbe6b750
* Content: [Connectivity - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/communication/networking?tabs=windows)
* Content Source: [docs/platform-integration/communication/networking.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/communication/networking.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Mephisztoe 

I'd recommend opening an enhancement request in the [engineering repo](https://github.com/dotnet/maui). Thanks!
