### ISSUE TITLE
Unclear documentation with absolute routes

### ISSUE THREAD

**Issue by christiannagel** [dotnet/docs-maui#749]
The sample code for the *Absolute routes* section uses `"//animals/monkeys"` as a route.

In the *Relative routes* section, a list of relative routes is introduced with *The following relative route formats are supported*.
Along this list, the `//route` is shown.

With this explanation it's unclear if `//route` is an absolute or a relative route. 
I think `//route` is incorrectly listed as a relative route and should be removed from the relative routes section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97825438-0df2-dbc2-8f1e-fb1490697a2c
* Version Independent ID: 97825438-0df2-dbc2-8f1e-fb1490697a2c
* Content: [.NET MAUI Shell navigation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation)
* Content Source: [docs/fundamentals/shell/navigation.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/navigation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @christiannagel 

Apologies for the delayed response. The content is correct. You can navigate to a page by using its absolute route (.e.g `//animals/monkeys`). However, you could also navigate to a page by using its relative route (e.g. `//monkeys`, which would search upwards for the route from the current position in the visual hierarchy).
