### ISSUE TITLE
No information on where this code is to be written

### ISSUE THREAD

**Issue by nssidhu** [dotnet/docs-maui#752]
It is not clear where the code has to be written.
Does the code need to be written into Platform folder ? if so does in which file, which class any overrides etc.
if so do we need to wire it up in MauiProgram.cs ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c978effc-e14b-bb58-464a-263059ce4413
* Version Independent ID: c978effc-e14b-bb58-464a-263059ce4413
* Content: [Permissions - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/permissions?tabs=android)
* Content Source: [docs/platform-integration/appmodel/permissions.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/appmodel/permissions.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nssidhu 

It's cross-platform code, so you just request a permission wherever you need to use that functionality in your app.
