### ISSUE TITLE
.Net MAUI Data Binding Video : ICommand CommunityToolkit

### ISSUE THREAD

**Issue by comprodigy** [dotnet/docs-maui#753]
In the video you're instructed to use ICommand when thats been replaced with RelayCommand which works for part of the video, but whatever else has changed has also broken the cascading data binding, so the command within swipeitemview no longer work.

**Comment by davidbritch** [comment]
Hi @comprodigy 

Sounds like this is an issue for the [CommunityToolkit repo](https://github.com/communitytoolkit). Thanks!
