### ISSUE TITLE
Missing requirement: Mono framework

### ISSUE THREAD

**Issue by iamalexmang** [dotnet/docs-maui#755]
Please also mention that Mono framework must be manually installed. There's no reference to this and as a result, Pair to Mac fails with this rather obscure error, almost nowhere to be found among feedback of forums:
Error message: An error occurred while trying to connect to the Service Broker instance …

> Paths probed for Mono on the server: mono64, /Library/Frameworks/Mono.framework/Versions/Current/bin/mono64, /usr/bin/mono64, /bin/mono64, /usr/local/bin/mono64, /usr/sbin/mono64, /sbin/mono64, /Users/manfredi/Library/Caches/Xamarin/XMA/Runtimes/mono/bin/mono64, mono, /Library/Frameworks/Mono.framework/Versions/Current/bin/mono, /usr/bin/mono, /bin/mono, /usr/local/bin/mono, /usr/sbin/mono, /sbin/mono, /Users/manfredi/Library/Caches/Xamarin/XMA/Runtimes/mono/bin/mono

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df7f72f4-cf07-1f47-6400-432d8499edea
* Version Independent ID: df7f72f4-cf07-1f47-6400-432d8499edea
* Content: [Pair to Mac for iOS development - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac)
* Content Source: [docs/ios/pair-to-mac.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/pair-to-mac.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @iamalexmang 

It's not so much as a missing requirement in the doc. More a bug in Pair to Mac. The engineers tell me that it should detect if Mono isn't installed (or needs updating), and then install it. However, they are aware that it's not working and are investigating. The workaround is to manually install Mono. You can either do that by installing VSMac or by only installing Mono (https://www.mono-project.com/download/stable/#download-mac).

This has caught a number of folks recently, so I'll add a note to the doc saying to install VSMac/Mono.

**Comment by iamalexmang** [comment]
FWIW, I did install VS for Mac Preview, but that didn't help in bypassing the error.
