### ISSUE TITLE
Missing instructions on how to deploy MAUI project

### ISSUE THREAD

**Issue by dicong-Apption** [dotnet/docs-maui#77]
I love MAUI very much since it really solved our cross-platform desktop app problem. The biggest thing I like is that it improved our deployment process when the target environment is Windows. We used to implement Blazor Server with Electron.Net and convert the final executable into MSIX package. But because of MAUI WinUI, we can shrink the deployment process into a single step. 

However, while I am trying to do a production deployment, I have a couple questions and I couldn't find the information from the doc. 

For Windows, do we package the app using the old Xamarin.Win deployment process? Or MAUI has a different way to proceed here. I am fairly new to Xamarin, but I know Blazor very well.  

For Mac Catalyst, can we build/deploy the project without using Apple Developer Id? I am wondering if there is a way to deploy the project into a pkp package. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app in Visual Studio](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dicong-Apption 

Afraid that there won't be any deployment guidance until GA. What I can say about Mac Catalyst though is that the deployment experience is totally controlled by Apple.
