### ISSUE TITLE
WinUI: Support for unpackaged apps

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#772]
Unpackaged apps don't use MSIX. They're typically installed and updated using .exe or .msi files. Many unpackaged apps walk end-users through an installation wizard using a classic UI.

https://github.com/dotnet/maui/issues/3166

**Comment by charlesroddie** [comment]
What's the advantage of this? This just seems like a downgrade in terms of ease of deployment and automatic updates.

**Comment by davidbritch** [comment]
Hi @charlesroddie 

Unpackaged apps are completely unrestricted in terms of the APIs they call, access to the registry, and file system. They aren't for everyone.

At the same time, packaged apps do slow down the inner-dev loop. So it should be possible to set an app as unpackaged while it's being developed (for faster builds), then switch it to packaged towards the end of the development process.

**Comment by davidbritch** [comment]
We've had a doc on publishing unpackaged apps for a while now.
