### ISSUE TITLE
App icons should work correctly

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#774]
In .NET 7, the **MauiIcon** build action should start working correctly for app icons. This should result in a simplification of the app icon doc, which will probably need versioning.

https://github.com/dotnet/maui/issues/7786
https://github.com/xamarin/xamarin-macios/issues/12790
https://github.com/xamarin/xamarin-android/issues/7147

**Comment by TamerIrdais** [comment]
No it doesn't I tried it in .NET 7.0 and they look as bad as in .NET 6.0.

**Comment by adegeo** [comment]
@TamerIrdais Can you provide more information? Keep in mind that the generated icon looking good or bad isn't the point of this issue, it's the fact that you needed to clean the project to get a new icon to actually appear, and possibly the platform-specific configuration you needed to do if you changed the icon.

**Comment by adegeo** [comment]
@davidbritch I'll look at the platform-specific section.

**Comment by davidbritch** [comment]
I just had a look at this today and they behave pretty much the same in .NET 7 as they do in 6.
