### ISSUE TITLE
There is not enough information on how to invalidate the graphics

### ISSUE THREAD

**Issue by gfmoore** [dotnet/docs-maui#780]
graphicsView.Invalidate(); 

So how do I use this, since no where in the document or code is graphicsView defined.

In the xaml there is no reference to graphicsView.

I tried 
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:drawable="clr-namespace:TSDZ2Monitor.Classes"
             xmlns:local="clr-namespace:TSDZ2Monitor.ViewModels"
             xmlns:local2="clr-namespace:TSDZ2Monitor.Classes"
             x:Class="TSDZ2Monitor.Pages.Display1Page"
             Title="Display Page">
  
  <ContentPage.BindingContext>
    <local:Display1PageViewModel />
  </ContentPage.BindingContext>

  <ContentPage.Resources>
    <drawable:GraphicsDrawable x:Key="drawable" />
  </ContentPage.Resources>

  <local2:SwipeContainer Swipe="OnSwiped">
    <Grid RowDefinitions="*,50,30">

      <GraphicsView Grid.Row="0" 
                    x:Name="GraphicsArea"
                    Drawable="{StaticResource drawable}"
                    HeightRequest="1000"
                    WidthRequest="1000" 
                    
                    VerticalOptions="Start"
                    HorizontalOptions="Start"/>
...
```
and then in my code behind
GraphicsArea.Invalidate();

but no joy.

I really do wish ... :sigh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2deb823c-ccc8-fdef-6cf8-bb70a2c21939
* Version Independent ID: 2deb823c-ccc8-fdef-6cf8-bb70a2c21939
* Content: [.NET MAUI GraphicsView - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/graphicsview)
* Content Source: [docs/user-interface/controls/graphicsview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/graphicsview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
UI elements are automatically invalidated when they're shown, revealed (like an element moving across it) etc. The UI takes care of that. The only time you would call invalidate is when you wanted to force the visual to redraw itself.

**Comment by gfmoore** [comment]
The code did work after all, but not within a loop with a System.Threading.Thread.Sleep(1000);

However my point remains that for newbies you do have to add the additional information to documentation please.

The key information is

```xml
      <GraphicsView Grid.Row="0" 
                    x:Name="GraphicsArea"
                    Drawable="{StaticResource drawable}"
                    HeightRequest="1000"
                    WidthRequest="1000" 
                    
                    VerticalOptions="Start"
                    HorizontalOptions="Start"/>
```

and then GraphicsArea.Invalidate() in code behind. (Is it bindable?)

@adego That is exactly what I want to do to create an animation, in my case a speedometer that shows the current bicycle speed! :()

**Comment by adegeo** [comment]
The thread sleep I think would depend on how you're setting up your loop and thread. Can you share that? If you're setting up a Task to run a loop with delay, you should call the `Invalidate` from the main thread (as any other thread you create can't really talk to the things in the UI) There is a helper for this: [Run code on the UI thread](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/main-thread#run-code-on-the-ui-thread)

Just sort of guessing off the top of my head, you would want something like this, but you'll probably want a cancellation token or a check on a boolean to see if it should stop.

```csharp
Task.Run(async () =>
{

    do
    {

        await MainThread.InvokeOnMainThreadAsync(graphicsView.Invalidate);
        await Task.Delay(TimeSpan.FromSeconds(1));

    } while (true);

});
```

**Comment by gfmoore** [comment]
I did something like this in Codebehind and it works fine :)  (But I'm an old fashioned programmer... lol)  I like yours though, must try it out.

```
 private static readonly System.Timers.Timer timer = new(200);

public DisplayPage() {  //Constructor
    timer.Elapsed += OnTimedEvent;
    timer.AutoReset = true;
}

  private void OnTimedEvent(Object source, System.Timers.ElapsedEventArgs e)
  {
    
     graphicsView.Invalidate()
  }

  private void DoIt_Clicked(object sender, EventArgs e)  //from a button in XAML
  {
    timer.Start();
  }
```

**Comment by gfmoore** [comment]
Oh, and thanks for your help :)
