### ISSUE TITLE
Maybe include a link to the "2009 XAML Specifications" 

### ISSUE THREAD

**Issue by Cornan** [dotnet/docs-maui#782]
[Maybe make the phrase "2009 XAML Specification" a link, maybe to:

https://docs.microsoft.com/en-us/dotnet/desktop/xaml-services/xaml-2009-language-features]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bf5afc-9fe9-bdfd-f281-cde7ffdad2c1
* Version Independent ID: b0bf5afc-9fe9-bdfd-f281-cde7ffdad2c1
* Content: [Get started with .NET MAUI XAML - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/get-started)
* Content Source: [docs/xaml/fundamentals/get-started.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/fundamentals/get-started.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thank you for this suggestion, I'll add a link.
