### ISSUE TITLE
Mention that you need to install `ios` and `maccatalyst` workloads

### ISSUE THREAD

**Issue by dominoFire** [dotnet/docs-maui#783]
Please write that you need to install workloads using dotnet.exe to MAUI app to work correctly.

```
dotnet workload install ios maccatalyst
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
@davidbritch is this a supported scenario/target right now? Maybe in a few years? Maybe in .NET 7?

**Comment by davidbritch** [comment]
Hi @dominoFire 

You shouldn't need to manually install the iOS and MacCatalyst workloads using dotnet.exe. VS should install all the workloads for you. If VS isn't doing this for you, then it's a product bug that needs logging. Thanks!
