### ISSUE TITLE
Error running maui-check - something about an older version of .NET 6?

### ISSUE THREAD

**Issue by mprogers** [dotnet/docs-maui#79]
It would be great if the document would explain what to do when maui-check says:

x This version of the tool is incompatible with installing an older version of .NET 6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mprogers 

Afraid that's a question based raised in the [maui-check](https://github.com/Redth/dotnet-maui-check) repo.
