### ISSUE TITLE
There should be a section enumerating events.

### ISSUE THREAD

**Issue by MarownIOM** [dotnet/docs-maui#792]
The list of Events for an Entry is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f3b9bb-82d0-5c49-42c4-d80c20e96f5b
* Version Independent ID: 45f3b9bb-82d0-5c49-42c4-d80c20e96f5b
* Content: [Entry - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/entry)
* Content Source: [docs/user-interface/controls/entry.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/entry.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Do you mean list the events like the properties are, in bullet points?

**Comment by davidbritch** [comment]
Hi @MarownIOM 

This page now links to the `Entry` API doc, which lists all properties/events/methods.
