### ISSUE TITLE
Is there any way to control padding when using Entry?

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/docs-maui#802]
Relatively new to .Net MAUI and am trying to find a way to style / control the padding used by Entry XAML.  Doesn't seem to be a way from what exists in the docs (apologies if I missed it; if so, please post relevant link).

Below is what an Entry (field) looks like when using the Android emulator:

![net_maui_entry_padding](https://user-images.githubusercontent.com/5932728/185706196-3f491adf-fc1b-4be3-8fac-e485f81a88da.jpg)

Seems like no padding to the left of the entered text and plenty of padding for top and bottom.

Is there any way to change the padding used by Entry?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f3b9bb-82d0-5c49-42c4-d80c20e96f5b
* Version Independent ID: 45f3b9bb-82d0-5c49-42c4-d80c20e96f5b
* Content: [Entry - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/entry)
* Content Source: [docs/user-interface/controls/entry.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/entry.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by BobbyCannon** [comment]
Following because having the text touching the left side is just jarring. Feels really broken.

**Comment by bdcoder2** [comment]
Found this excellent video on building an outlined Entry control:
[https://www.youtube.com/watch?v=uKzIrp82b54](https://www.youtube.com/watch?v=uKzIrp82b54)

In the comments section, someone asked about padding and the author shows a solution; I can imagine building on this, although it does seems strange (and a lot of extra work) that the Entry control does not have attributes such as Margin, Padding, BorderColor, BorderSize, etc.

**Comment by BobbyCannon** [comment]
@bdcoder2 I used this video to build something similar but interesting enough the Windows UI vs Android UI is still significantly different. It's better but still not good.

**Comment by adegeo** [comment]
Hi. Using the [Handlers feature](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/) is how you gain access to the underlaying control and customize it. You'll need to read the documentation on the WinUI textbox control so you know what to customize, and I think that doc is here: https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.textbox?view=windows-app-sdk-1.1

I'll close this issue as I think this gets you in the right direction.
