### ISSUE TITLE
FlyoutPage.IsPresented throws InvalidOperationException when set to false for split layouts

### ISSUE THREAD

**Issue by CodeSetting** [dotnet/docs-maui#807]
I think a warning is needed that setting `FlyoutPage.IsPresented` to `false` will throw an `InvalidOperationException` when the `FlyoutPage.FlyoutLayoutBehavior` property indicates a split layout.

This can occur by default (`FlyoutLayoutBehavoir.Default`) for some platforms (e.g. Windows desktop) or when a split layout is explicitly indicated (via `Split`, `SplitOnLandscape`, or `SplitOnPortrait`).

The sample code used in the example will fail with an `InvalidOperationException` on the Windows platform for this reason.

To fix this failure, change:

```
IsPresented = false;
```

to

```
if (!((IFlyoutPageController)this).ShouldShowSplitMode)
  IsPresented = false;
```

This latter code works with either split or popover layouts.  Since I am new to MAUI, it took a couple of hours digging through the `FlyoutPage.cs` source code to figure this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86a77021-9359-304a-5d49-a4feadf2f8fb
* Version Independent ID: 86a77021-9359-304a-5d49-a4feadf2f8fb
* Content: [FlyoutPage - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/pages/flyoutpage)
* Content Source: [docs/user-interface/pages/flyoutpage.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pages/flyoutpage.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@CodeSetting Thanks for logging this issue and putting in the time to figure it out. Much appreciated.
