### ISSUE TITLE
When testing on IOS PhoneDialer.Default.IsSupported returns false

### ISSUE THREAD

**Issue by kne-itd** [dotnet/docs-maui#819]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434134e2-02dc-840a-1a72-b784165254cd
* Version Independent ID: 434134e2-02dc-840a-1a72-b784165254cd
* Content: [Phone dialer - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/communication/phone-dialer?tabs=ios)
* Content Source: [docs/platform-integration/communication/phone-dialer.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/communication/phone-dialer.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by kne-itd** [comment]
When testing on IOS PhoneDialer.Default.IsSupported returns false

**Comment by adegeo** [comment]
Does your device have phone capabilities? Make sure it does. If you feel like it should work, but it doesn't, please open a bug with the [product group](https://github.com/dotnet/maui/issues). Everything I find says this should work as is. 😦 If there is something to update in the docs, let us know.
