### ISSUE TITLE
No way to load image on Windows

### ISSUE THREAD

**Issue by cybercritic** [dotnet/docs-maui#820]
Example states that "The PlatformImage type isn't supported on Windows." and doesn't mention any way to load an image in windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca86947-204f-9c45-223d-724fb59b4938
* Version Independent ID: 0ca86947-204f-9c45-223d-724fb59b4938
* Content: [Draw graphical objects - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/graphics/draw)
* Content Source: [docs/user-interface/graphics/draw.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/graphics/draw.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @cybercritic 

Afraid there isn't one. It's an omission that should get fixed for .NET 7. See https://github.com/dotnet/Microsoft.Maui.Graphics/pull/464 for more info.
