### ISSUE TITLE
Is somewhere available repo for Learn "Build mobile and desktop apps with .NET MAUI" ?

### ISSUE THREAD

**Issue by apws** [dotnet/docs-maui#824]
It is this series of modules beginners tutorial:
https://docs.microsoft.com/en-us/learn/paths/build-apps-with-dotnet-maui/?WT.mc_id=dotnet-68837-masoucou

Please @adegeo, I am now trying to make from this single PDF suited for mobile/tablet easy reading as a whole, using (my) style tweaked for best viewing experience - and I am doing it now manually (pasting into WinWord and reformating), just to preview how it may be far better useful as simple beginners handbook (have made few similar ebooks already for other things and its very convenient, when proper formatting optimized for mobile experience is used, rather than screen/printed format), but if somewhere is accessible some source for this (even after some agreements), it can be also helpful - I in fact jumped today into MAUI after quite long time spent with androidstudio, javafx, delphi quite hard options to write some specific mini android app easily, but I quite a lot believe in MAUI, even if its not yet much production ready. I want to help with it somehow, if possible. Can you help me?

**Comment by davidbritch** [comment]
Hi @apws 

You can always find the repo for a doc by examining the page source. For example, the source for the URL you specified contains:

```
<meta name="original_content_git_url" content="https://github.com/MicrosoftDocs/learn-pr/blob/live/learn-pr/paths/build-apps-with-dotnet-maui/index.yml" />
```

Unfortunately, the repo in question is private and can only be accessed by Microsoft employees.
