### ISSUE TITLE
Clarify how targeting impacts compilation of partials for platform code

### ISSUE THREAD

**Issue by tylersouthard** [dotnet/docs-maui#827]
In the second paragraph under "Partial classes and methods", the docs say:

"At build time, the build system only includes the code from each folder when building for that specific platform. For example, when you build for Android the files in the Platforms > Android folder will be built into the app package, but the files in the other Platforms folders won't be."

It is subtly clarified later, under the "Implement the API per platform" section, but it's not clear enough (in my opinion) that the TargetFrameworks property in effect from the .csproj file determines which platforms must have the partial classes/methods implemented.

For example, I was on Windows and made a test app to try out the partial classes/methods style of doing platform code. I implemented the partials on Windows and iOS only (for whatever reason), and it built and ran fine. Then I hopped over to macOS to build it for iOS simulator, but it didn't work. This is because (as I found later) we must implement the partials for each target framework, even though we may be running for only one given platform at a time. Also, the default csproj produced by VS overwrites the TargetFrameworks for Windows to remove the other frameworks, but for iOS, Android and Mac Catalyst, they are all three included together.

It all makes sense in hind-sight, but I wish it was clearer in the docs so I didn't waste a few hours trying to track down why it was working in some cases and not others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Version Independent ID: a06cfff1-c728-dbd9-4fb5-aa42363753ea
* Content: [.NET MAUI invoking platform code - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code)
* Content Source: [docs/platform-integration/invoke-platform-code.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/invoke-platform-code.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. I don't understand what you mean by:

>  Also, the default csproj produced by VS overwrites the TargetFrameworks for Windows to remove the other frameworks, but for iOS, Android and Mac Catalyst, they are all three included together.

When I create a new app on Windows, all the frameworks are included.

I just tried creating a non-platform-specific partial class, implemented the partial method on android, and the compiler errors out saying it's missing for ios/windows/maccatalyst

**Comment by tylersouthard** [comment]
Yes, sorry, I was mistaken on that point. I missed the fact that on Windows it _appends_ the TargetFramework with the others.

The confusing part is that, if you do the default test app on Windows, create a non-platform-specific partial class, and implement it only for Windows, the app compiles and runs just fine. Switching over to build for the other platforms behaves inconsistently, because at that point the compiler forces you to implement all the other partials for the targeted frameworks.
