### ISSUE TITLE
How is a control template created? 

### ISSUE THREAD

**Issue by DonRobinson** [dotnet/docs-maui#831]
"A control template is created with the ControlTemplate type. When you create a ControlTemplate, you combine View objects to build the UI for a custom control, or page."

Is it created after some action with Visual Studio. What is a ControlTemplate type? Is type a class. I thought I knew C# but I don't know what a type is.

Is it created automatically or by me? Should it read "You have to create a ControlTemplate manually when you ...."? 
Is there a list of templates to choose from? 

A description of what a Control Template is would be a good idea.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d55cdb6d-0144-0c97-c373-8728b20664a9
* Version Independent ID: d55cdb6d-0144-0c97-c373-8728b20664a9
* Content: [Control templates - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/controltemplate)
* Content Source: [docs/fundamentals/controltemplate.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/controltemplate.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Yes, it's a type. It's usually declared in XAML markup as the example in the article does, specifically the second code example. We're working on adding more tutorials to documentation, but we're not there yet. Sorry.
