### ISSUE TITLE
Home 

### ISSUE THREAD

**Issue by Starr79** [dotnet/docs-maui#833]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb754bf-48db-4f6c-7e87-7cb3b59c34d5
* Version Independent ID: ba07354c-611d-5efe-0fbb-48a24d02cafe
* Content: [Supported platforms for .NET MAUI apps - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms)
* Content Source: [docs/supported-platforms.md](https://github.com/dotnet/docs-maui/blob/main/docs/supported-platforms.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. It looks like this was opened in error. I'll close it.
