### ISSUE TITLE
Images swapped

### ISSUE THREAD

**Issue by mprogers** [dotnet/docs-maui#838]
I'm really impressed with this page (I don't know about the rest of the docs but I had to start with Grid, and I've been impressed).

One nit: the grid picture showing row spacing and column spacing of 6 has been swapped with the one where the row spacing and column spacing is not specified (and therefore 0).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f34c45a-afa7-e650-a83d-b99a712d50e3
* Version Independent ID: 5f34c45a-afa7-e650-a83d-b99a712d50e3
* Content: [Grid - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/layouts/grid)
* Content Source: [docs/user-interface/layouts/grid.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/layouts/grid.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
@mprogers Thank you for the feedback.

@davidbritch I'm not sure what that image should be showing. It's in the `Space between rows and column` section.

**Comment by mprogers** [comment]
I just looked at the page now - the images are still wrong. 

The first image shows no space between. It's right after this "The following XAML shows the same Grid definition, and also positions child views in specific Grid cells:" There's no Spacing attributes, but there are spaces between the BoxViews.

Then later on, at this link -- https://learn.microsoft.com/en-us/dotnet/maui/user-interface/layouts/grid#space-between-rows-and-columns -- the BoxViews are cheek-by-jowl, no space whatsoever even though the attribute says RowSpacing and ColumnSpacing are both 6.

**Comment by davidbritch** [comment]
@mprogers 

It's all good at my end. You might need to refresh your cache.

First image:

![Screenshot 2022-09-20 at 11 14 15](https://user-images.githubusercontent.com/8092460/191232372-5581255c-8689-4034-a9cc-a32f80ee9206.png)

Second image:

![Screenshot 2022-09-20 at 11 14 24](https://user-images.githubusercontent.com/8092460/191232380-fec15e64-6c0a-4bd5-a546-fe8425dbf7d9.png)

**Comment by mprogers** [comment]
Yes, I guess it was a caching issue, but this is now correct - thank you, the disconnect was driving me crazy!!

Michael
