### ISSUE TITLE
MAUI Share Text/ File functionality Clarification 

### ISSUE THREAD

**Issue by hemant149** [dotnet/docs-maui#840]
Hi,

Below help  article describes how we can use the .NET Multi-platform App UI (.NET MAUI) to share Text/URL or File. 

https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/data/share?tabs=android

**Can you please tell what is Second Parameter in below ShareText task and what values should I pass ( ??? in call link) while making call to async Task ShareText.** 

Call Link 
----------
```cs
MudIconButton Icon="@Icons.Material.Filled.Share" Color="Color.Error" OnClick='@((e) => ShareText("Hello Share Text", **???** ))' 
```

Task
-------------------------------------------------------------
```cs
public async Task ShareText(string text, IShare share)
{
    await share.RequestAsync(new ShareTextRequest
    {
        Text = text,
        Title = "Share Text"
    });
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d340ffe1-24b6-ff95-39a5-057bf10826c9
* Version Independent ID: d340ffe1-24b6-ff95-39a5-057bf10826c9
* Content: [Share - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/data/share?tabs=android)
* Content Source: [docs/platform-integration/data/share.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/data/share.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi. This article is missing a key piece of information, which is that an instance of `IShare` is available from the `Microsoft.Maui.ApplicationModel.DataTransfer.Share.Default` property.
