### ISSUE TITLE
Source of image and text for tabor should be addressed

### ISSUE THREAD

**Issue by mprogers** [dotnet/docs-maui#841]
Where are the tabs getting their image and title from? That was not discussed on this page, but should be, IMHO. I'm about to go Google (or Bing) it, but it should be listed here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9f1977c-bc41-c096-0b17-6db418d440b0
* Version Independent ID: d9f1977c-bc41-c096-0b17-6db418d440b0
* Content: [TabbedPage - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/pages/tabbedpage)
* Content Source: [docs/user-interface/pages/tabbedpage.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pages/tabbedpage.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. I agree this should be clarified how the `TabbedPage` presents the content page.

The content page itself defines the properties `Title` and `IconImageSource`. So based on the type of content page you're going to use, you should refer to those articles specifically. Here are screenshots from the code examples in this article where you can see them demonstrated:

![image](https://user-images.githubusercontent.com/67293991/188231339-21228ea2-0f74-4139-83c0-afb62b681e20.png)

and

![image](https://user-images.githubusercontent.com/67293991/188231413-ceb51ba0-d85e-4e7e-964c-7e73f4968083.png)
