### ISSUE TITLE
AppIcon produced by .NET MAUI is too small

### ISSUE THREAD

**Issue by rogerms** [dotnet/docs-maui#844]
[Enter feedback here]
Adding MauiIcon to project property produces a normal size icon for the Start Menu but the one for the Taskbar is very small.
I want to find a way to fix that. The source icon image is in SVG format.
I am attaching a screenshot showing an icon from an UWP project and the one from the MAUI project.
Note that a type of padding is added to the MAUI project icon. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Version Independent ID: 2fc2b28d-e403-c63e-b7c4-6639fcd05a89
* Content: [Change the app icon - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/app-icons?tabs=windows)
* Content Source: [docs/user-interface/images/app-icons.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/app-icons.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**
![Screenshot-win-taskbar](https://user-images.githubusercontent.com/5874969/187835049-e80f22c0-6ccb-47ba-b050-33b3f140a75c.png)

**Comment by adegeo** [comment]
Hello. There are a few issues opened in the .NET MAUI code repo dealing with icons. I didn't really find one specific to your problem, but I would search there and/or open a new issue: https://github.com/dotnet/maui/issues

Unfortunately I tried to transfer this issue there but it won't let me. Sorry about that.
