### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by jasonrpeterson** [dotnet/docs-maui#845]
Link text has "Compiled nindings" instead of "Compiled bindings" in the section snipped below. 

Note

Compiled bindings can be enabled to improve data binding performance in .NET MAUI applications. For more information, see [Compiled **nindings**](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8ec6047-0b7b-ca7b-f1f5-22b005fab87c
* Version Independent ID: a8ec6047-0b7b-ca7b-f1f5-22b005fab87c
* Content: [Populate a CollectionView with Data - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/collectionview/populate-data)
* Content Source: [docs/user-interface/controls/collectionview/populate-data.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/collectionview/populate-data.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.
