### ISSUE TITLE
Undocumented error

### ISSUE THREAD

**Issue by petemillermultimedia** [dotnet/docs-maui#847]
.NET upgrade assistant

What does this error mean:

Target is still unavailable after restore. Please verify that the project has been restored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cdfd37b-a119-da4e-a56e-a60dde31bb18
* Version Independent ID: 1cdfd37b-a119-da4e-a56e-a60dde31bb18
* Content: [Troubleshoot known issues - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/troubleshooting)
* Content Source: [docs/troubleshooting.md](https://github.com/dotnet/docs-maui/blob/main/docs/troubleshooting.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
As far as I know, upgrading Xamarin Forms to .NET MAUI through the assistant isn't fully supported yet. There is an open issue in the upgrade assistant repo: https://github.com/dotnet/upgrade-assistant/issues/1265

**Comment by holecekp** [comment]
Upgrading Xamarin Forms to .NET MAUI through the assistant should be already supported according to information on the assistant GitHub main page (https://github.com/dotnet/upgrade-assistant):

_Currently, the tool supports the following project types: ..., Xamarin.Forms to .NET MAUI_

But in reality, it is completely broken and it does not work at all.
