### ISSUE TITLE
Error on line, no closing quote

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/docs-maui#850]
[Enter feedback here]
Line that contains the following:
<ItemGroup Condition="$(TargetFramework.StartsWith('net6.0-ios')) != true>
Is missing the closing quote after true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf87eb8f-c235-d80d-ca9f-827d4e55f74d
* Version Independent ID: bf87eb8f-c235-d80d-ca9f-827d4e55f74d
* Content: [Configure .NET MAUI multi-targeting - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/configure-multi-targeting)
* Content Source: [docs/platform-integration/configure-multi-targeting.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/configure-multi-targeting.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thanks! I'll get this fixed.
