### ISSUE TITLE
[Bug] "Drag a file into a layout which recognizes the drop gesture" raises Exception on Windows

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/docs-maui#854]
As instructed in [MAUI Drag and Drop documentation,](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/drag-and-drop) we implement a functionality which allows the user to drag a file from desktop into the app, for easy file selection. 

When run it on Windows, exception raises while dropping the file: "Object reference not set to an instance of an object."

Any more configurations need to be done to make it work in this scenario? Thanks.
Best Regards

**Comment by davidbritch** [comment]
Hi @SunshineSpring666 

No additional configuration is required. It sounds like you're trying to use it for an unsupported scenario. This functionality is specifically designed for dragging UI objects within the app (e.g. UI objects that exist on a page).
