### ISSUE TITLE
This page does not have correct information

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#855]
I tried to simply change the splashscreen to a jpg that I wanted to use.  This page just says to put it where you want in resources and change the <MauiSplashScreen Include

So I do this and 

Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2260	resource drawable/splash (aka com.companyname.DEVEXFullProject:drawable/splash) not found.	DEVEXFullProject	C:\Visual Stuido Stuff\Maui\DEVEXFullProject\Resources\Resources\drawable\maui_splash_image.xml	2	

Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2061	failed linking file resources.	DEVEXFullProject	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.Aapt2.targets	156	

I really don't know how anyone can say Maui is GA  !!!!!!!!!!!!!!!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc
* Version Independent ID: 44323c6e-d65c-b254-ee3c-cd9415bdf3bc
* Content: [Add a splash screen to a .NET MAUI app project - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/splashscreen?tabs=android)
* Content Source: [docs/user-interface/images/splashscreen.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/images/splashscreen.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sqlguy6212 

Apologies for the much delayed response. I just tried doing this (splash screen with a new filename) and it worked just fine.
