### ISSUE TITLE
Storage.Preferences - Clarify when to use Default

### ISSUE THREAD

**Issue by tschramme86** [dotnet/docs-maui#858]
There is ``Storage.Preferences`` and ``Storage.Preferences.Default``, both offering the ``Get`` and ``Set``methods for storing preferences.
Please document the difference between the two of them.

In the documentation you call ``Set`` on ``Storage.Preferences.Default`` but ``Get`` on ``Storage.Preferences``.
When I do the same in my project, the ``Get`` call always just returns the passed default value, never the actual value I stored by a previous ``Set`` call.

In code:
````
// as used in the documentation:
Preferences.Default.Set("test1", new DateTime(2002, 01, 01));
var y1 = Preferences.Get("test1", new DateTime(1999, 01, 01));
// does not work, y1 is now the passed default value 01/01/1999

// but when calling like this
Preferences.Set("test2", new DateTime(2002, 01, 01));
var x1 = Preferences.Get("test2", new DateTime(1999, 01, 01));
// it does work, x1 is as expected 01/01/2002
````

Tested on Maui for Android, VS 17.3.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a973c0ae-6fc0-2218-2809-2d5973373ce2
* Version Independent ID: a973c0ae-6fc0-2218-2809-2d5973373ce2
* Content: [Preferences - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/preferences?tabs=android)
* Content Source: [docs/platform-integration/storage/preferences.md](https://github.com/dotnet/docs-maui/blob/main/docs/platform-integration/storage/preferences.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
@tschramme86 Thank you for opening this issue up. They are the same at the moment. The `.Default` way is the new way to access the default implementation of the preferences interface. The example should be using that.

The introduction to the article explains it:

> The default implementation of the `IPreferences` interface is available through the `Preferences.Default` property. Both the `IPreferences` interface and `Preferences` class are contained in the `Microsoft.Maui.Storage` namespace.
