### ISSUE TITLE
Is there a repository of fonts anywhere?

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/docs-maui#859]
Completely new to .Net MAUI ...

As per the docs, **NEW projects** by default are configured to use the following fonts:

```
builder.ConfigureFonts(fonts =>
   {
   fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
   fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
   });
```

But if I want to use a different set of fonts, then where does one find the true type (.ttf) files to download and include in the project? 

The documentation should provide a reference to a repository where other font files can be found.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a7b4ff-2889-6a85-aa3f-075ae6c07387
* Version Independent ID: 76a7b4ff-2889-6a85-aa3f-075ae6c07387
* Content: [Fonts in .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/fonts)
* Content Source: [docs/user-interface/fonts.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/fonts.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
You'll just need to search the internet for fonts :)
