### ISSUE TITLE
.NET MAUI for windows publish and install issue. Access denied error

### ISSUE THREAD

**Issue by kamranattari4192** [dotnet/docs-maui#862]
I published .NET MAUI Windows MSIX to sideload that is signed with a valid certificate. When I click .msix file, nothing happened because msix extension was not known on windows 10 by default. It seems that I have to install App Installer from Microsoft Store to recognise msix extension. After installing App Installer, I clicked on .msix file it showed me installer window, when I clicked on Install button it showed me following error: App installation failed with error message: Access is denied. (0x80070005). Why am I getting this error? Then I open power shell without elevated admin rights and run Install.ps1 script it showed me Add-AppxPackage : Deployment failed with HRESULT: 0x80070005, Access is denied. error. After that I run power shell with elevated admin rights, and run Install.ps1, then it installed my package. So it is installing sideload package only from powershell with admin rights. How can we make it installable by double clicking misx file without admin rights?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46808586-50e1-acfa-68b3-c3ca6572dc62
* Version Independent ID: 46808586-50e1-acfa-68b3-c3ca6572dc62
* Content: [Publish a .NET MAUI app for Windows - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview)
* Content Source: [docs/windows/deployment/overview.md](https://github.com/dotnet/docs-maui/blob/main/docs/windows/deployment/overview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @kamranattari4192 I don't really know why you would be getting that error. I think you should file a bug with the product team: https://github.com/dotnet/maui/issues/

There is an update in progress to this doc that removes the `<GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>` setting from the project file. Can you remove that and try again? If that doesn't work, I think you should open a bug on the .NET MAUI repo.
