### ISSUE TITLE
Android emulator unable to call local web api via 10.0.2.2 via http or https - stuck after hours of trying

### ISSUE THREAD

**Issue by tradegear** [dotnet/docs-maui#866]
Section: Connect to local web services from Android emulators and iOS simulators
Looks and reads as well-written.  However unfortunately after failing to gain success implementing the advice in the first portion of the document entitled "Local web services running over HTTP", I decided to instead deploy "Local web services running over HTTPS".  The document is not clear that one should choose one or the other.  I decided that was the case; this could be made more clear in the intro.
I could not achieve success because on my web api, when I used Swagger to directly reach the http endpoint (via the http port), I received a "CORS" error with a lot of detail that was unhelpful.  Since I have seen no other mention of CORS related to MAUI / Android / iOS reaching a local development web api, I chose to not go down the path of implementing "CORS". 
So I decided to implement: "Local web services running over HTTPS".
I trusted the local certificate (it was already trusted - I'm not sure when that ever happened in the past.)
I located the file in my Maui app that references "10.0.2.2" via a text search since your document doesn't give much direction on where to find that, and being a newbie to Maui, I didnt' know.
in "Bypass the certificate security check", the description made sense.  The sample code following: "The following example shows a class that configures the AndroidMessageHandler class on Android and the NSUrlSessionHandler class on iOS to trust localhost communication over HTTPS:" ... well.. I didn't know where I should put that, so I created a class file within the same namespace as where the httpClient is initialized.

```csharp
namespace MTRMauiClient.DataServices
{
    public class RestDataService : IRestDataService
    {
        private readonly HttpClient _httpClient;
        private readonly string _baseAddress;
        private readonly string _url;
        private readonly JsonSerializerOptions _jsonSerializerOptions;

        public RestDataService(HttpClient httpClient)
        {
//HERE IS THE Sample code under paragraph:
//"The resulting HttpClientHandler object can then be passed as an argument to the HttpClient constructor for debug builds:"
#if DEBUG
            HttpMessageHandler handler = new HttpsClientHandlerService();
            HTTPClient client = new HttpClient(handler.GetPlatformMessageHandler());
#else
            client = new HttpClient();
#endif
```
There is an error for line `HttpMessageHandler handler = new HttpsClientHandlerService();` indicating:

> CS0029: Cannot implicitly convert type 'MTRMauiClient.DataServices.HttpsClientHandlerService' to 'System.Net.Http.HttpMessageHandler'

I clearly didn't copy/paste the sample code into the correct place.

Also, if the DI process supplies an httpClient parameter, why are we "NEWING UP" a new HttpClient ?
This makes me question if I am putting this code in the correct place, because the info in the document wasn't sufficient for me to be confident in knowing where to place it.

I am completely stuck.  Neither route has allowed me to successfully call my web api from the Maui app.  
After spending a few hours last night, and my entire day today fighting with this, I'd like to suggest that this is an exceedingly weak and wasteful section of this otherwise amazing platform.
I will greatly appreciate any assistance.  I don't know where to turn after this because I'm pretty much I've reviewed virtually every forum post on this topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663379bf-421a-57f1-39b7-e92f830de0ed
* Version Independent ID: 663379bf-421a-57f1-39b7-e92f830de0ed
* Content: [Connect to local web services from Android emulators and iOS simulators - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/data-cloud/local-web-services)
* Content Source: [docs/data-cloud/local-web-services.md](https://github.com/dotnet/docs-maui/blob/main/docs/data-cloud/local-web-services.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. I think the code may have an error in it. It doesn't compile correctly. I want to guess that it was supposed to be a static method. I was able to get it to work by changing the handler service code to the following (I cut out the iOS bits, they remain unchanged)

```csharp
public class HttpsClientHandlerService
{
    public static HttpMessageHandler GetPlatformMessageHandler()
    {
#if ANDROID
        var handler = new CustomAndroidMessageHandler();
        handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
        {
            if (cert != null && cert.Issuer.Equals("CN=localhost"))
                return true;
            return errors == System.Net.Security.SslPolicyErrors.None;
        };
        return handler;
#elif IOS
    // some code
#else
    throw new PlatformNotSupportedException("Only Android and iOS supported.");
#endif
    }

#if ANDROID
    internal sealed class CustomAndroidMessageHandler : Xamarin.Android.Net.AndroidMessageHandler
    {
        protected override Javax.Net.Ssl.IHostnameVerifier GetSSLHostnameVerifier(Javax.Net.Ssl.HttpsURLConnection connection)
            => new CustomHostnameVerifier();

        private sealed class CustomHostnameVerifier : Java.Lang.Object, Javax.Net.Ssl.IHostnameVerifier
        {
            public bool Verify(string hostname, Javax.Net.Ssl.ISSLSession session)
            {
                return Javax.Net.Ssl.HttpsURLConnection.DefaultHostnameVerifier.Verify(hostname, session) ||
                    hostname == "10.0.2.2" && session.PeerPrincipal?.Name == "CN=localhost";
            }
        }
    }
#elif IOS
  // some code
#endif
}
```

And then you use it directly like so:

```csharp
HttpClient client = new HttpClient(HttpsClientHandlerService.GetPlatformMessageHandler());
```

The reason a new `HttpClient` is created is so that you can pass in the message handler instance for bypassing invalid certificates (when you're in dev mode), otherwise you don't need to create a new one.

Regarding the CORS error, I don't know, that seems more like a problem on the ASP.NET side of things.

@davidbritch Am I correct in these assumptions Dave? I can fix this article if I am.

**Comment by davidbritch** [comment]
@adegeo Afraid not. The code in the article compiles and works as is.

@tradegear At the top of the article there's a link to a sample, that has all the code in it. That should make it clear exactly where everything should live.

**Comment by adegeo** [comment]
Ahh I figured out what is going on with the code. I'll open a PR
