### ISSUE TITLE
Can't run iOS simulator, in spite of being successfully connected to Mac.

### ISSUE THREAD

**Issue by tradegear** [dotnet/docs-maui#867]
I bought a new mac for this purpose.  Nothing else installed besides Mono and Xcode.  Existing documentation didn't inform me whether I had to install Mono, XCode, both/neither?  I installed both after trial-and-error.
From VS2022 Maui Client project, I connected to my Mac via the toolbar.  Everything seems fine.
I went into Tools --> Options --> Xamarin --> iOS.  The Mac didn't appear connected there.  There is an inconsistency between the status of the Mac connection when displayed from the toolbar, and when the connection status is displayed in the Tools Options Xamarin iOS panel.  I disconnected and then connected via the Tools Options Xamarin iOS panel, and this time in this panel it appears my Mac is connected to the correct IP of the Mac.
"Simulator" - "Remote Simulator to Windows" is checked on enabled.  I toggled that in addition to toggling things by restarting both machines and getting things reconnected.
Here is the main problem:  I am unable to run an iOS simulator, even with a confirmed connected Mac.  I really haven't made many changes to my VS2022 environment, and I've done nothing to this new Mac except install mono and XCode.
I have a Maui Client that runs fine in the Windows Machine environment.
The same Maui Client runs fine in an Android simulator (although there is an issue with Android connecting to local web api, which I have submitted feedback on that issue separately.)
The same Maui Client will not run an iOS simulator.  There appear to be no iOS simulators in my list.  I can't see how to get my iOS simulator list populated.  I choose "iOS Simulator", and then the only option is "iOS Simulator".  When I attempt to run the Maui Client app from "iOS simulator", I get this error:
Please select a valid device before running the application.
Well, there are no simulators to select from.
After about an hour googling around and looking for other fixes, this (a) appears to be a common problem (b) None of the proposed solutions resolve the issue.
New Mac.
Pretty much clean Windows 11 machine with VS2022 updated to latest as of 2022-09-10.
I'm at a loss for what to try next.  I'll greatly appreciate any fix advice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3e5ccb-ecdd-c174-6e36-ce3e74a68e4e
* Version Independent ID: 9a3e5ccb-ecdd-c174-6e36-ce3e74a68e4e
* Content: [Remote iOS Simulator for Windows - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/ios/remote-simulator)
* Content Source: [docs/ios/remote-simulator.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/remote-simulator.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tradegear 

Apologies for the much delayed response to this. For help and questions about using this product, please ask a question at [Microsoft Q&A](https://github.com/dotnet/docs-maui/blob/main/answers/topics/dotnet-maui.html). Thanks!
