### ISSUE TITLE
TimePicker control displays seconds, but does not allow seconds to be entered?

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/docs-maui#869]
New to .Net MAUI and was hoping the TimePicker would allow the hours / minutes / seconds to be selected.

The documentation states that "a [standard](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings/) or [custom](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings/) .NET formatting string may be used", implying that all of the time fields (hours, minutes, seconds, milliseconds) could be displayed or selected.  However, when the following code is used:

```
<TimePicker 
   Time="4:15:26" 
   Format="HH:mm:ss"
/>
```

**On the Android simulator:**
- The hours, minutes and seconds are displayed
- When the control is clicked on, only hours and minutes can be selected and an AM / PM selector is displayed (even though 24 hour format specifiers for hours are used, i.e.: hours range from 0-23, but emulator only allows 1-12 to be selected).

**On the Windows Machine simulator**
- The hours and minutes are displayed (seconds are not).
- When the control is clicked on, only hours and minutes can be selected.

I haven't tried the on a Mac / iOS as I do not have a machine to test.

One can only infer that when using the TimePIcker control, only hours and minutes can be selected -- regardless of the Format used.   I had mistakenly assumed that if the format display showed hours, minutes and seconds, the control would allow hours, minutes and seconds to be selected.   Should this be mentioned in the documentation?  I think it might be a good idea.

On another note - is there any TimeSpanPicker available in .Net MAUI?  I have a use case where I need to select a number of days, hours, minutes and seconds -- I guess I could use 4 sliders, but again, for TimeSpan data, it would be great if the docs suggested other resources.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 159cee98-fe87-2242-400a-9ee4f8b3bb8b
* Version Independent ID: 159cee98-fe87-2242-400a-9ee4f8b3bb8b
* Content: [TimePicker - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/timepicker)
* Content Source: [docs/user-interface/controls/timepicker.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/timepicker.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
.NET MAUI translates the controls to their native counterparts, basically what a TimePicker control is in WinUI3 and what it is in Android. Looking at their documentation, it looks like they only allow hours/minutes to be selected. This probably should be noted in the documentation along with the example that is used.

Thank you for reporting this and providing excellent detail.

**Comment by bdcoder2** [comment]
@adegeo - Thanks and yes, would probably be a good idea to mention that the time control allows only hours and minutes to be selected.  I think the confusion (for me) was the mention of a TimeSpan -- which implied more fields.   I ended up using 4 sliders to configure the Day, Hour, Minutes and Seconds -- works like a charm and is very intuitive.

**Comment by adegeo** [comment]
@davidbritch So I took a look and the `Format` property works on Android but doesn't have any effect on Windows. This makes me wonder how many other controls will have description problems like this? 😬
