### ISSUE TITLE
Label with Hyperlink - code incorrect and does not work ...

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/docs-maui#873]
In the section entitled **Create a reusable hyperlink class** code example, the following code is incorrect:

`TextColor = Color.Blue;`

... and should be changed to the following:

`TextColor = Colors.Blue;`

... Also, the code does not work, the hyperlink is displayed, however, when the mouse is hovered over the hyperlink, it does not change (remains a pointer) and if the hyperlink is clicked the Command defined in the TapGestureRecognizer never fires.

Have tried on both Windows and Android -- neither work.

Looking for a working example of how to include a hyperlink in a Label.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 243e6d1d-a276-814f-7943-ff0fa7ba017e
* Version Independent ID: 243e6d1d-a276-814f-7943-ff0fa7ba017e
* Content: [Label - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/label)
* Content Source: [docs/user-interface/controls/label.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/label.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thank you for reporting this problem

**Comment by bdcoder2** [comment]
@adegeo - Also related, and just posted this with regard to gester recognizers in Labels: [https://stackoverflow.com/questions/73695949/net-maui-how-to-include-a-link-in-a-label](https://stackoverflow.com/questions/73695949/net-maui-how-to-include-a-link-in-a-label)

**Comment by davidbritch** [comment]
Hi @bdcoder2 

I just tried this and the hyperlink works when it's on a `Label`, but not when it's on a `Span`. I confirmed that on Windows & Android. It not working on a Span is due to product bugs. See https://github.com/dotnet/maui/issues/4734 and https://github.com/dotnet/maui/issues/8004.

I'll work on getting the sample the page published this week.

**Comment by fgiacomelli** [comment]
Hello, I read that this issue was moved to status "Done" 70 days ago, but at this time I'm still having the bug with .net 7. When can I expect to found the bug fixed?

**Comment by davidbritch** [comment]
Hi @fgiacomelli 

This docs issue is closed because the it's not a docs issue - it's a product issue. The product issues (https://github.com/dotnet/maui/issues/4734 and https://github.com/dotnet/maui/issues/8004) are still open.
