### ISSUE TITLE
Request for a Github project page for this tutorial series

### ISSUE THREAD

**Issue by akoranteng** [dotnet/docs-maui#879]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Version Independent ID: 720bf7f0-db92-f738-b864-ee149a02377b
* Content: [Tutorial: Create a .NET MAUI app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/tutorials/notes-app/?tutorial-step=5)
* Content Source: [docs/tutorials/notes-app/index.yml](https://github.com/dotnet/docs-maui/blob/main/docs/tutorials/notes-app/index.yml)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by akoranteng** [comment]
The tutorials presented for the series for lessons one through lesson five are great for beginners. Can you add a completed version of each lesson to Github to allow the community to review it against our local versions. It will allow for collaboration and pull request

**Comment by adegeo** [comment]
Hi @akoranteng yes this is something I've been meaning to do.

**Comment by akoranteng** [comment]
How do I become a contributor to this issue. I have .Net experience, but just starting to get up to speed with .Net MAUI. 
Should I go through the tutorial and put it on my Github page. Please advise.

Alex

**Comment by adegeo** [comment]
Sorry for the delay @akoranteng I was on vacation and in/out of work the last few weeks. I'm doing this now.

**Comment by akoranteng** [comment]
Thanks for the update

Regards
Alex

Sent from my iPhone

On Oct 3, 2022, at 3:57 AM, David Britch ***@***.***> wrote:

﻿

Closed #879<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs-maui%2Fissues%2F879&data=05%7C01%7C%7C01865dc0fced44c8140908daa514f4f0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638003806672447401%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9B3H77FYFOrbwSyrIN%2FzbatsWDD2KPwQAMyQw0QdZ2E%3D&reserved=0> as completed via #955<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs-maui%2Fpull%2F955&data=05%7C01%7C%7C01865dc0fced44c8140908daa514f4f0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638003806672447401%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ovAJmDBYJzkM3HuCScKLU8GCQ1dzvTJhgtbghvgmT1s%3D&reserved=0>.
