### ISSUE TITLE
Missing steps for building WinUI project for .NET CLI

### ISSUE THREAD

**Issue by reub-the-cube** [dotnet/docs-maui#88]
There are no steps that I can find for how to build the WinUI project through the command line. 

I had assumed it was simple but has started to get complicated beyond what I understand so maybe I am missing the magic step. When I run the `dotnet build` command on the WinUI project, I get an error:
> error MSB4086: A numeric comparison was attempted on "$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)" that evaluates to "" instead of a number, in condition "'$(AppxUseResourceIndexerApi)' == '' AND '$(registry:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion@CurrentVersion)' < '6.3'"

It does work OK through Visual Studio 2022 - because of the [Single-project MSIX Packaging Tools for VS 2022](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17) (I think).

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app in Visual Studio](https://docs.microsoft.com/en-gb/dotnet/maui/get-started/first-app?pivots=dotnet-cli)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @reub-the-cube 

Afraid you can't currently build the WinUI version of the project through the command line. It only currently builds in Visual Studio 2022 because of the tooling you mentioned.

Rest assured that the docs will be updated once it becomes possible.
