### ISSUE TITLE
What's a FlyOut?

### ISSUE THREAD

**Issue by mprogers** [dotnet/docs-maui#881]
What is a FlyOut? A sentence or two explaining what they are would be beneficial for those of us who immediately thought it was a reference to baseball.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6df1eb5-23fc-8a22-2083-3555cb7f9b6f
* Version Independent ID: a6df1eb5-23fc-8a22-2083-3555cb7f9b6f
* Content: [.NET MAUI Shell overview - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/?source=docs)
* Content Source: [docs/fundamentals/shell/index.md](https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/shell/index.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
@mprogers Perhaps the article should link to https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout for more information. A quick description of the flyout could be copied from that page too.

**Comment by mprogers** [comment]
That sounds good to me. If I'd been systematically reading through the docs I might've already encountered this -- it's obviously important and well known to people experienced in .NET MAUI -- but I didn't, so I hadn't.

**Comment by davidbritch** [comment]
This has been done.
