### ISSUE TITLE
Followed all the directions and result is .... nothing

### ISSUE THREAD

**Issue by sqlguy6212** [dotnet/docs-maui#884]
Have Hot Reload enabled according to page.  Try to use it, Visual XAML Preview no changes on changes to XAML, app no changes also
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31cbef98-89fe-fb8a-c1a5-3119c1f0c207
* Version Independent ID: 31cbef98-89fe-fb8a-c1a5-3119c1f0c207
* Content: [XAML Hot Reload for .NET MAUI - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/xaml/hot-reload)
* Content Source: [docs/xaml/hot-reload.md](https://github.com/dotnet/docs-maui/blob/main/docs/xaml/hot-reload.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hello. Sorry for the delay in response. You can try updating to the latest preview version of Visual Studio. Other than that you'll probably want to file a bug with the .NET MAUI team if something isn't working with this. The doc is correct in how you enable it, so there isn't anything we can change here.

[Create a new .NET MAUI issue](https://github.com/dotnet/maui/issues/new/choose)
