### ISSUE TITLE
From MenuBarItem, Commands are not being executed

### ISSUE THREAD

**Issue by manuelesvi** [dotnet/docs-maui#887]
From MenuBarItem, Commands are not being executed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca7fb0b7-d8e0-b263-1f5a-c90f51a2cc22
* Version Independent ID: ca7fb0b7-d8e0-b263-1f5a-c90f51a2cc22
* Content: [Display a menu bar in a .NET MAUI desktop app - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/menubar)
* Content Source: [docs/user-interface/menubar.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/menubar.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @manuelesvi 

Afraid this will be a product bug that needs reporting in the [engineering repo](https://github.com/dotnet/maui), if it hasn't been already.
