### ISSUE TITLE
Reorder Prerequisites

### ISSUE THREAD

**Issue by spnm** [dotnet/docs-maui#89]
The bullets under Prerequisites should be reordered (Installation of the new Visual Studio should be the first thing).  In order to install  .NET MAUI workloads, Visual studio 2022 must be already installed in the machine (.net 6 is necessary). At least, this happened to my case. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app in Visual Studio](https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @spnm 

Agreed. I'll get the doc updated today.
