### ISSUE TITLE
Template fails to build with errors NU1012 and NETSDK1139

### ISSUE THREAD

**Issue by alecjames** [dotnet/docs-maui#918]
[Enter feedback here]
Also, the Android emulator is missing from the "Debug Target " list.  
I'm following the tutorial on Microsoft Learn and this article and have the same issues.  

My problem is caused because I have 2 SDKs installed, both x86 without .NET6 and x64 with .NET6.  I need the x86 SDK first in the environment path to build a legacy project. When it is first in the path I see these errors.  Also dotnet --info does not report the .NET 6 SDK even though it is installed.  Adding global.json to the project explicitly specifying the .NET SDK version does not help. (I have VS2022 17.3.4 with >NET 6 SDK 6.0.401).  

I can resolve the issue by re-ordering my path so x64 appears first (although my legacy project then fails to build).  As a new user trying to follow a tutorial, this is hard to find / resolve.  Maybe a comment in the article stating that there must not be multiple SDKs would help the few that hit this issue.  Or if there can be both sdks, how the system should be configured. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?tabs=vswin&pivots=devices-android)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Thank you for this feedback. We have a troubleshooting article which this information should be in. It's also documented in the (Install .NET on Windows article](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#it-was-not-possible-to-find-any-installed-net-core-sdks).
