### ISSUE TITLE
Error While installing  .NET SDK - Workloads (6.0.100-preview.7.21379.14)

### ISSUE THREAD

**Issue by rahulpahuja** [dotnet/docs-maui#95]
.NET SDK - Workloads (6.0.100-preview.7.21379.14) Checkup...
  x android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 30.0.100-preview.7.110) not installed.
  x ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-preview.7.230) not installed.
  x maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-preview.7.230) not installed.
  x tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-preview.7.230) not installed.
  x macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-preview.7.230) not installed.
  x maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-preview.7.1345) not installed.
  - wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-preview.7.21377.19) installed.
  - microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-preview.7.21377.2) installed.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
☼ Recommendation: Install or Update SDK Workloads
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

! Attempt to fix? [y/n] (y): y
» Attempting to fix: .NET SDK - Workloads (6.0.100-preview.7.21379.14)
SHELL: C:\Program Files\dotnet\dotnet.exe workload repair --source "https://api.nuget.org/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21379.14-shipping-1/nuget/v3/index.json"

Repairing workload installation for workloads: maui
Installing pack Microsoft.Maui.Core.Ref.android version 6.0.100-preview.7.1063+sha.f5acc965e-azdo.5006556...
Rolling back pack Microsoft.Maui.Core.Ref.android installation...
Workload repair failed: microsoft.maui.core.ref.android::6.0.100-preview.7.1063 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21379.14-shipping-1/nuget/v3/index.json".
repair
  Repair workload installations.

Usage:
  dotnet [options] workload repair

Options:
  --sdk-version <VERSION>                                                  The version of the SDK.
  --configfile <FILE>                                                      The NuGet configuration file to use.
  -s, --source <SOURCE>                                                    The NuGet package source to use during the restore.
  -v, --verbosity <d|detailed|diag|diagnostic|m|minimal|n|normal|q|quiet>  Set the MSBuild verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
  --disable-parallel                                                       Prevent restoring multiple projects in parallel.
  --ignore-failed-sources                                                  Treat package source failures as warnings.
  --no-cache                                                               Do not cache packages and http requests.
  --interactive                                                            Allows the command to stop and wait for user input or action (for example to complete authentication).
  -?, -h, --help                                                           Show help and usage information

Fix failed - Workload Repair failed: `dotnet workload repair --source "https://api.nuget.org/v3/index.json" --source
"https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.7.21379.14-shipping-1/nuget/v3/index.json"`
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

! There were one or more problems detected.
Please review the errors and correct them and run maui-check again.

Press enter to exit...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
maui-check is constantly changing. I tried it this morning, on both Windows and a Mac and it ran successfully.
