### ISSUE TITLE
What about multiple entries?

### ISSUE THREAD

**Issue by mprogers** [dotnet/docs-maui#965]
What if I want to get more than one piece of information from a user? There must be someway to do that, obviously. Override a popup? Create a separate page and make it appear "like a popup"? Some guidance here, even just a sentence or two to send the developer to the right spot in the docs, would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 144c1b04-ddfc-e59b-773f-94124fbbce7a
* Version Independent ID: 144c1b04-ddfc-e59b-773f-94124fbbce7a
* Content: [Display pop-ups - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pop-ups?source=docs)
* Content Source: [docs/user-interface/pop-ups.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/pop-ups.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mprogers 

Good suggestion, and it'll make a good doc update. The solution is to create a new `ContentPage` containing your form, and push it onto the navigation stack as a modal page (see https://learn.microsoft.com/dotnet/maui/user-interface/pages/navigationpage#perform-modal-navigation).

**Comment by mprogers** [comment]
Thanks David, I appreciate that!

Related to this, how can I get multiple items up in the bar at the top of the page? Do I have to use Shell.TitleView and put a HorizontalStackLayout in it? I’m used to environments that give you access to a .Title, .Leading and .Trailing area, and I’m trying to position a + button so when I tap it, the aforementioned ContentPage will slide down modally.

I think if I knew Xamarin, this would be all be easier ...

Michael

**Comment by davidbritch** [comment]
@mprogers You can add a `ToolbarItems` collection to a `ContentPage`, that contains one or more `ToolbarItem` objects. See https://github.com/dotnet/maui-samples/blob/cd4cd91d9f31262c6bcafe9db3b87c860d502871/6.0/WebServices/TodoREST/TodoREST/Views/TodoListPage.xaml#L6

**Comment by mprogers** [comment]
Thank you so, so much!! This is extremely helpful.

Michael
