### ISSUE TITLE
.net 5 runtime not mentioned as required in your installation doc

### ISSUE THREAD

**Issue by iammephisto** [dotnet/docs-maui#97]
[Enter feedback here]
There is no mention that .net 5 runtime has to be installed before running maui-check in your installation guide.

Also, OpenJdk11 is not recognized and the tool always install Microsoft OpenJdk 11 either way, not sure if this is normal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7607155a-9a56-d752-c5ac-c3aeb6b128bc
* Version Independent ID: 9a62d421-d009-30b3-843e-a92bfc21c061
* Content: [.NET MAUI installation - .NET MAUI](https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation)
* Content Source: [docs/get-started/installation.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/installation.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by MuratTopcu** [comment]
> There is no mention that .net 5 runtime has to be installed before running maui-check in your installation guide.
> 
> Also, OpenJdk11 is not recognized and the tool always install Microsoft OpenJdk 11 either way, not sure if this is normal.

I'm having the same problems

**Comment by davidbritch** [comment]
Closing due to maui-check no longer being required.
