### ISSUE TITLE
difficult to understand how to add Entitlements.plist

### ISSUE THREAD

**Issue by AdamBebko** [dotnet/docs-maui#970]
Very difficult to understand how to add Entitlements.plist. and Visual studio for Mac 17.3 doesn't seem to have an entitlements editor. When I double click it opens Xcode.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f03ab28-e5c6-2176-1cfc-67ab6bf84b86
* Version Independent ID: 6f03ab28-e5c6-2176-1cfc-67ab6bf84b86
* Content: [Entitlements and capabilities - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/entitlements)
* Content Source: [docs/ios/deployment/entitlements.md](https://github.com/dotnet/docs-maui/blob/main/docs/ios/deployment/entitlements.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @AdamBebko for this issue there isn't much we can do in the documentation. You'll need to request that the product team prioritize getting an editor built. Sorry.

You can file an issue at https://github.com/dotnet/maui/issues

I did a quick search for you, to see if there were any existing issues that were reporting this same feature, but I didn't find any.
