### ISSUE TITLE
.net maiu execution on physical device with error

### ISSUE THREAD

**Issue by RafaelFernandesBR** [dotnet/docs-maui#974]
Hi, I'm not able to find any way to run my .net Maiu application on my physical device. I'm connected to it on the computer via cable, but I can't find it in visual studio to debug directly on it.
When I run an application in xamarin, I can run it smoothly, when I run the command 'dotnet build -t:Run -f net6.0-android', in the command line, I can run the application on my android tanbén.
In visual studio, I can only run on windows.
Does anyone know how I can solve this problem?
I'm using visual studio version 17.3.5

**Comment by adegeo** [comment]
Hi @RafaelFernandesBR sorry for the late reply. Did you find a solution to this problem? I was able to get it to appear in the debug target list by following the instructions to [Enable Physical Device Debugging](https://learn.microsoft.com/en-us/dotnet/maui/android/device/setup). The device automatically appeared in Visual Studio when I

1. Turned on developer mode on the device
2. Enabled USB debugging on the device
3. Plugged in the device to the computer via USB

![image](https://user-images.githubusercontent.com/67293991/195921306-c9b9e403-658a-427c-93fe-e941d24589d0.png)

I'm going to closet his as I believe this is the solution to your problem. If it isn't please feel free to reopen. Let me know either way!

**Comment by RafaelFernandesBR** [comment]
Hi, where do you click exactly to show this?
Here on mine it doesn't show up. At least not with screen readers.
I'm going to debug > other debug targets
