### ISSUE TITLE
Bottom Property for Tabbed Page Toolbar Placement overlaps with system bottom navigation

### ISSUE THREAD

**Issue by OmPals** [dotnet/docs-maui#985]
The Tabbed Page Toolbar Placement property to "bottom' makes the tabbar overlap with system bottom navigation for the Android.  Please refer to the image shown below. 

![image](https://user-images.githubusercontent.com/35599492/195141250-7d5bc7c4-6292-47ad-9a85-a074e052e9d8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 039cf416-fa7c-dca3-ef72-f9029c613ecd
* Version Independent ID: 039cf416-fa7c-dca3-ef72-f9029c613ecd
* Content: [TabbedPage toolbar placement on Android - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/android/platform-specifics/tabbedpage-toolbar-placement)
* Content Source: [docs/android/platform-specifics/tabbedpage-toolbar-placement.md](https://github.com/dotnet/docs-maui/blob/main/docs/android/platform-specifics/tabbedpage-toolbar-placement.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @OmPals you should probably file a bug in the [.NET MAUI issue repo](https://github.com/dotnet/maui) as it seems to be a bug in the product, not in the documentation.
