### ISSUE TITLE
Picker.Title 

### ISSUE THREAD

**Issue by githubgoucho** [dotnet/docs-maui#996]
not shown on Android 8.x and even there is no select sign which indicates a picker box
maui 6.x / vs 17.3.4

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 491d6466-047e-7219-a496-2d9bd59a3379
* Version Independent ID: 491d6466-047e-7219-a496-2d9bd59a3379
* Content: [Picker - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/picker)
* Content Source: [docs/user-interface/controls/picker.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/picker.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adegeo** [comment]
Hi @githubgoucho you should probably file a bug in the [.NET MAUI issue repo](https://github.com/dotnet/maui) to verify that there isn't a problem and it's operating as it should. Also, a screenshot helps to understand what you're seeing. I'll close this issue for now until we know there is or isn't a doc problem versus a .NET MAUI code problem.

Sorry.
