### ISSUE TITLE
Do you need a MAC PC to release an app for the iPhone.

### ISSUE THREAD

**Issue by John-Blair** [dotnet/docs-maui#999]
[Enter feedback here]
Do you need a MAC PC to release an app for the iPhone?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 779d2db3-3e9c-2692-57ff-787d9465a444
* Version Independent ID: e77ba6a7-e59d-1e1e-52e1-935f98a985cf
* Content: [Build your first .NET MAUI app - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/get-started/first-app?tabs=vswin)
* Content Source: [docs/get-started/first-app.md](https://github.com/dotnet/docs-maui/blob/main/docs/get-started/first-app.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @John-Blair 

Afraid so, yes. It's a licensing restriction from Apple - that the releasable app must be built on a Mac. Visual Studio (on Windows) has tooling that connects to a paired Mac to do the build, but you can still run it on a remote simulator in Windows.
